package q5

// GemvQ5PackedSelectedF32PTX is generated at development time and embedded.
const GemvQ5PackedSelectedF32PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemv_q5_packed_selected_f32

.visible .entry gemv_q5_packed_selected_f32(
	.param .u64 gemv_q5_packed_selected_f32_param_0,
	.param .u64 gemv_q5_packed_selected_f32_param_1,
	.param .u64 gemv_q5_packed_selected_f32_param_2,
	.param .u64 gemv_q5_packed_selected_f32_param_3,
	.param .u64 gemv_q5_packed_selected_f32_param_4,
	.param .u64 gemv_q5_packed_selected_f32_param_5,
	.param .u32 gemv_q5_packed_selected_f32_param_6,
	.param .u32 gemv_q5_packed_selected_f32_param_7
)
{
	.reg .pred 	%p<13>;
	.reg .b16 	%rs<6>;
	.reg .f32 	%f<60>;
	.reg .b32 	%r<74>;
	.reg .b64 	%rd<54>;


	ld.param.u64 	%rd20, [gemv_q5_packed_selected_f32_param_0];
	ld.param.u64 	%rd21, [gemv_q5_packed_selected_f32_param_1];
	ld.param.u64 	%rd22, [gemv_q5_packed_selected_f32_param_2];
	ld.param.u64 	%rd23, [gemv_q5_packed_selected_f32_param_3];
	ld.param.u64 	%rd18, [gemv_q5_packed_selected_f32_param_4];
	ld.param.u64 	%rd19, [gemv_q5_packed_selected_f32_param_5];
	ld.param.u32 	%r14, [gemv_q5_packed_selected_f32_param_6];
	ld.param.u32 	%r15, [gemv_q5_packed_selected_f32_param_7];
	cvta.to.global.u64 	%rd1, %rd23;
	cvta.to.global.u64 	%rd2, %rd21;
	cvta.to.global.u64 	%rd3, %rd22;
	cvta.to.global.u64 	%rd4, %rd20;
	mov.u32 	%r1, %ctaid.x;
	setp.ge.s32 	%p1, %r1, %r15;
	@%p1 bra 	$L__BB0_10;

	cvta.to.global.u64 	%rd24, %rd18;
	cvt.s64.s32 	%rd5, %r1;
	mul.wide.s32 	%rd25, %r1, 4;
	add.s64 	%rd26, %rd24, %rd25;
	ld.global.u32 	%r2, [%rd26];
	mov.u32 	%r3, %tid.x;
	setp.ge.s32 	%p2, %r3, %r14;
	mov.f32 	%f59, 0f00000000;
	@%p2 bra 	$L__BB0_8;

	shr.s32 	%r16, %r14, 31;
	shr.u32 	%r17, %r16, 27;
	add.s32 	%r18, %r14, %r17;
	shr.s32 	%r19, %r18, 5;
	mul.lo.s32 	%r4, %r2, %r19;
	not.b32 	%r20, %r3;
	add.s32 	%r5, %r20, %r14;
	shr.u32 	%r21, %r5, 5;
	add.s32 	%r22, %r21, 1;
	and.b32  	%r71, %r22, 3;
	setp.eq.s32 	%p3, %r71, 0;
	mov.f32 	%f59, 0f00000000;
	mov.u32 	%r72, %r3;
	@%p3 bra 	$L__BB0_5;

	mad.lo.s32 	%r23, %r2, %r14, %r3;
	cvt.s64.s32 	%rd27, %r23;
	add.s64 	%rd51, %rd2, %rd27;
	mul.wide.s32 	%rd28, %r3, 4;
	add.s64 	%rd50, %rd4, %rd28;
	mov.f32 	%f59, 0f00000000;
	mov.u32 	%r72, %r3;

$L__BB0_4:
	.pragma "nounroll";
	shr.s32 	%r24, %r72, 31;
	shr.u32 	%r25, %r24, 27;
	add.s32 	%r26, %r72, %r25;
	shr.s32 	%r27, %r26, 5;
	add.s32 	%r28, %r27, %r4;
	mul.wide.s32 	%rd29, %r28, 4;
	add.s64 	%rd30, %rd3, %rd29;
	ld.global.u8 	%rs1, [%rd51];
	cvt.rn.f32.u16 	%f13, %rs1;
	ld.global.f32 	%f14, [%rd30];
	mul.ftz.f32 	%f15, %f14, %f13;
	add.s64 	%rd31, %rd1, %rd29;
	ld.global.f32 	%f16, [%rd31];
	sub.ftz.f32 	%f17, %f15, %f16;
	ld.global.f32 	%f18, [%rd50];
	fma.rn.ftz.f32 	%f59, %f18, %f17, %f59;
	add.s32 	%r72, %r72, 32;
	add.s64 	%rd51, %rd51, 32;
	add.s64 	%rd50, %rd50, 128;
	add.s32 	%r71, %r71, -1;
	setp.ne.s32 	%p4, %r71, 0;
	@%p4 bra 	$L__BB0_4;

$L__BB0_5:
	setp.lt.u32 	%p5, %r5, 96;
	@%p5 bra 	$L__BB0_8;

	mad.lo.s32 	%r29, %r2, %r14, %r72;
	cvt.s64.s32 	%rd32, %r29;
	add.s64 	%rd53, %rd2, %rd32;
	mul.wide.s32 	%rd33, %r72, 4;
	add.s64 	%rd34, %rd4, %rd33;
	add.s64 	%rd52, %rd34, 256;

$L__BB0_7:
	shr.s32 	%r30, %r72, 31;
	shr.u32 	%r31, %r30, 27;
	add.s32 	%r32, %r72, %r31;
	shr.s32 	%r33, %r32, 5;
	add.s32 	%r34, %r33, %r4;
	mul.wide.s32 	%rd35, %r34, 4;
	add.s64 	%rd36, %rd3, %rd35;
	ld.global.u8 	%rs2, [%rd53];
	cvt.rn.f32.u16 	%f19, %rs2;
	ld.global.f32 	%f20, [%rd36];
	mul.ftz.f32 	%f21, %f20, %f19;
	add.s64 	%rd37, %rd1, %rd35;
	ld.global.f32 	%f22, [%rd37];
	sub.ftz.f32 	%f23, %f21, %f22;
	ld.global.f32 	%f24, [%rd52+-256];
	fma.rn.ftz.f32 	%f25, %f24, %f23, %f59;
	add.s32 	%r35, %r72, 32;
	shr.s32 	%r36, %r35, 31;
	shr.u32 	%r37, %r36, 27;
	add.s32 	%r38, %r35, %r37;
	shr.s32 	%r39, %r38, 5;
	add.s32 	%r40, %r39, %r4;
	mul.wide.s32 	%rd38, %r40, 4;
	add.s64 	%rd39, %rd3, %rd38;
	ld.global.u8 	%rs3, [%rd53+32];
	cvt.rn.f32.u16 	%f26, %rs3;
	ld.global.f32 	%f27, [%rd39];
	mul.ftz.f32 	%f28, %f27, %f26;
	add.s64 	%rd40, %rd1, %rd38;
	ld.global.f32 	%f29, [%rd40];
	sub.ftz.f32 	%f30, %f28, %f29;
	ld.global.f32 	%f31, [%rd52+-128];
	fma.rn.ftz.f32 	%f32, %f31, %f30, %f25;
	add.s32 	%r41, %r72, 64;
	shr.s32 	%r42, %r41, 31;
	shr.u32 	%r43, %r42, 27;
	add.s32 	%r44, %r41, %r43;
	shr.s32 	%r45, %r44, 5;
	add.s32 	%r46, %r45, %r4;
	mul.wide.s32 	%rd41, %r46, 4;
	add.s64 	%rd42, %rd3, %rd41;
	ld.global.u8 	%rs4, [%rd53+64];
	cvt.rn.f32.u16 	%f33, %rs4;
	ld.global.f32 	%f34, [%rd42];
	mul.ftz.f32 	%f35, %f34, %f33;
	add.s64 	%rd43, %rd1, %rd41;
	ld.global.f32 	%f36, [%rd43];
	sub.ftz.f32 	%f37, %f35, %f36;
	ld.global.f32 	%f38, [%rd52];
	fma.rn.ftz.f32 	%f39, %f38, %f37, %f32;
	add.s32 	%r47, %r72, 96;
	shr.s32 	%r48, %r47, 31;
	shr.u32 	%r49, %r48, 27;
	add.s32 	%r50, %r47, %r49;
	shr.s32 	%r51, %r50, 5;
	add.s32 	%r52, %r51, %r4;
	mul.wide.s32 	%rd44, %r52, 4;
	add.s64 	%rd45, %rd3, %rd44;
	ld.global.u8 	%rs5, [%rd53+96];
	cvt.rn.f32.u16 	%f40, %rs5;
	ld.global.f32 	%f41, [%rd45];
	mul.ftz.f32 	%f42, %f41, %f40;
	add.s64 	%rd46, %rd1, %rd44;
	ld.global.f32 	%f43, [%rd46];
	sub.ftz.f32 	%f44, %f42, %f43;
	ld.global.f32 	%f45, [%rd52+128];
	fma.rn.ftz.f32 	%f59, %f45, %f44, %f39;
	add.s64 	%rd53, %rd53, 128;
	add.s64 	%rd52, %rd52, 512;
	add.s32 	%r72, %r72, 128;
	setp.lt.s32 	%p6, %r72, %r14;
	@%p6 bra 	$L__BB0_7;

$L__BB0_8:
	mov.b32 	%r53, %f59;
	mov.u32 	%r54, 2;
	mov.u32 	%r55, 31;
	mov.u32 	%r56, 16;
	mov.u32 	%r57, -1;
	shfl.sync.down.b32 	%r58|%p7, %r53, %r56, %r55, %r57;
	mov.b32 	%f46, %r58;
	add.ftz.f32 	%f47, %f59, %f46;
	mov.b32 	%r59, %f47;
	mov.u32 	%r60, 8;
	shfl.sync.down.b32 	%r61|%p8, %r59, %r60, %r55, %r57;
	mov.b32 	%f48, %r61;
	add.ftz.f32 	%f49, %f47, %f48;
	mov.b32 	%r62, %f49;
	mov.u32 	%r63, 4;
	shfl.sync.down.b32 	%r64|%p9, %r62, %r63, %r55, %r57;
	mov.b32 	%f50, %r64;
	add.ftz.f32 	%f51, %f49, %f50;
	mov.b32 	%r65, %f51;
	shfl.sync.down.b32 	%r66|%p10, %r65, %r54, %r55, %r57;
	mov.b32 	%f52, %r66;
	add.ftz.f32 	%f53, %f51, %f52;
	mov.b32 	%r67, %f53;
	mov.u32 	%r68, 1;
	shfl.sync.down.b32 	%r69|%p11, %r67, %r68, %r55, %r57;
	mov.b32 	%f54, %r69;
	add.ftz.f32 	%f8, %f53, %f54;
	setp.ne.s32 	%p12, %r3, 0;
	@%p12 bra 	$L__BB0_10;

	cvta.to.global.u64 	%rd47, %rd19;
	shl.b64 	%rd48, %rd5, 2;
	add.s64 	%rd49, %rd47, %rd48;
	st.global.f32 	[%rd49], %f8;

$L__BB0_10:
	ret;

}

`
