package q4

// Coalesced Q4 kernels generated at development time and embedded.
const GemmQ4CoalescedQ8PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q4_coalesced_q8_batch16

.visible .entry gemm_q4_coalesced_q8_batch16(
	.param .u64 gemm_q4_coalesced_q8_batch16_param_0,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_1,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_2,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_3,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_4,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_5,
	.param .u64 gemm_q4_coalesced_q8_batch16_param_6,
	.param .u32 gemm_q4_coalesced_q8_batch16_param_7,
	.param .u32 gemm_q4_coalesced_q8_batch16_param_8,
	.param .u32 gemm_q4_coalesced_q8_batch16_param_9
)
{
	.reg .pred 	%p<147>;
	.reg .f32 	%f<401>;
	.reg .b32 	%r<987>;
	.reg .b64 	%rd<166>;


	ld.param.u64 	%rd52, [gemm_q4_coalesced_q8_batch16_param_0];
	ld.param.u64 	%rd53, [gemm_q4_coalesced_q8_batch16_param_1];
	ld.param.u64 	%rd54, [gemm_q4_coalesced_q8_batch16_param_2];
	ld.param.u64 	%rd55, [gemm_q4_coalesced_q8_batch16_param_3];
	ld.param.u64 	%rd56, [gemm_q4_coalesced_q8_batch16_param_4];
	ld.param.u64 	%rd57, [gemm_q4_coalesced_q8_batch16_param_5];
	ld.param.u64 	%rd58, [gemm_q4_coalesced_q8_batch16_param_6];
	ld.param.u32 	%r47, [gemm_q4_coalesced_q8_batch16_param_7];
	ld.param.u32 	%r48, [gemm_q4_coalesced_q8_batch16_param_8];
	ld.param.u32 	%r49, [gemm_q4_coalesced_q8_batch16_param_9];
	cvta.to.global.u64 	%rd1, %rd58;
	mov.u32 	%r1, %tid.x;
	shr.u32 	%r50, %r1, 5;
	and.b32  	%r986, %r1, 31;
	mov.u32 	%r51, %ctaid.x;
	shl.b32 	%r52, %r51, 2;
	add.s32 	%r3, %r52, %r50;
	mov.u32 	%r4, %ctaid.y;
	shl.b32 	%r5, %r4, 4;
	setp.ge.s32 	%p1, %r3, %r48;
	setp.ge.s32 	%p2, %r5, %r49;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_66;

	shr.s32 	%r53, %r47, 31;
	shr.u32 	%r54, %r53, 27;
	add.s32 	%r55, %r47, %r54;
	shr.s32 	%r6, %r55, 5;
	setp.ge.s32 	%p4, %r986, %r6;
	mov.f32 	%f376, 0f00000000;
	mov.f32 	%f375, %f376;
	mov.f32 	%f374, %f376;
	mov.f32 	%f373, %f376;
	mov.f32 	%f372, %f376;
	mov.f32 	%f371, %f376;
	mov.f32 	%f370, %f376;
	mov.f32 	%f392, %f376;
	mov.f32 	%f377, %f376;
	mov.f32 	%f378, %f376;
	mov.f32 	%f379, %f376;
	mov.f32 	%f380, %f376;
	mov.f32 	%f381, %f376;
	mov.f32 	%f382, %f376;
	mov.f32 	%f383, %f376;
	mov.f32 	%f384, %f376;
	@%p4 bra 	$L__BB0_34;

	mul.lo.s32 	%r56, %r5, %r47;
	cvt.s64.s32 	%rd59, %r56;
	add.s32 	%r57, %r56, %r47;
	cvt.s64.s32 	%rd60, %r57;
	add.s32 	%r58, %r57, %r47;
	cvt.s64.s32 	%rd61, %r58;
	add.s32 	%r59, %r58, %r47;
	cvt.s64.s32 	%rd62, %r59;
	add.s32 	%r60, %r59, %r47;
	cvt.s64.s32 	%rd63, %r60;
	add.s32 	%r61, %r60, %r47;
	cvt.s64.s32 	%rd64, %r61;
	add.s32 	%r62, %r61, %r47;
	cvt.s64.s32 	%rd65, %r62;
	add.s32 	%r63, %r62, %r47;
	cvt.s64.s32 	%rd66, %r63;
	add.s32 	%r64, %r63, %r47;
	cvt.s64.s32 	%rd67, %r64;
	add.s32 	%r65, %r64, %r47;
	cvt.s64.s32 	%rd68, %r65;
	add.s32 	%r66, %r65, %r47;
	cvt.s64.s32 	%rd69, %r66;
	add.s32 	%r67, %r66, %r47;
	cvt.s64.s32 	%rd70, %r67;
	add.s32 	%r68, %r67, %r47;
	cvt.s64.s32 	%rd71, %r68;
	add.s32 	%r69, %r68, %r47;
	cvt.s64.s32 	%rd2, %r69;
	add.s32 	%r70, %r69, %r47;
	cvt.s64.s32 	%rd3, %r70;
	add.s32 	%r71, %r70, %r47;
	cvt.s64.s32 	%rd4, %r71;
	add.s32 	%r7, %r5, 15;
	mad.lo.s32 	%r72, %r6, %r7, %r986;
	mul.wide.s32 	%rd5, %r72, 4;
	add.s32 	%r8, %r5, 14;
	mad.lo.s32 	%r73, %r6, %r8, %r986;
	mul.wide.s32 	%rd6, %r73, 4;
	add.s32 	%r9, %r5, 13;
	mad.lo.s32 	%r74, %r6, %r9, %r986;
	mul.wide.s32 	%rd7, %r74, 4;
	add.s32 	%r10, %r5, 12;
	mad.lo.s32 	%r75, %r6, %r10, %r986;
	mul.wide.s32 	%rd8, %r75, 4;
	add.s32 	%r11, %r5, 11;
	mad.lo.s32 	%r76, %r6, %r11, %r986;
	mul.wide.s32 	%rd9, %r76, 4;
	add.s32 	%r12, %r5, 10;
	mad.lo.s32 	%r77, %r6, %r12, %r986;
	mul.wide.s32 	%rd10, %r77, 4;
	add.s32 	%r13, %r5, 9;
	mad.lo.s32 	%r78, %r6, %r13, %r986;
	mul.wide.s32 	%rd11, %r78, 4;
	add.s32 	%r14, %r5, 8;
	mad.lo.s32 	%r79, %r6, %r14, %r986;
	mul.wide.s32 	%rd12, %r79, 4;
	add.s32 	%r15, %r5, 7;
	mad.lo.s32 	%r80, %r6, %r15, %r986;
	mul.wide.s32 	%rd13, %r80, 4;
	add.s32 	%r16, %r5, 6;
	mad.lo.s32 	%r81, %r6, %r16, %r986;
	mul.wide.s32 	%rd14, %r81, 4;
	add.s32 	%r17, %r5, 5;
	mad.lo.s32 	%r82, %r6, %r17, %r986;
	mul.wide.s32 	%rd15, %r82, 4;
	add.s32 	%r18, %r5, 4;
	mad.lo.s32 	%r83, %r6, %r18, %r986;
	mul.wide.s32 	%rd16, %r83, 4;
	add.s32 	%r19, %r5, 3;
	mad.lo.s32 	%r84, %r6, %r19, %r986;
	mul.wide.s32 	%rd17, %r84, 4;
	add.s32 	%r20, %r5, 2;
	mad.lo.s32 	%r85, %r6, %r20, %r986;
	mul.wide.s32 	%rd18, %r85, 4;
	add.s32 	%r21, %r5, 1;
	mad.lo.s32 	%r86, %r6, %r21, %r986;
	mul.wide.s32 	%rd19, %r86, 4;
	mul.lo.s32 	%r87, %r4, %r6;
	shl.b32 	%r88, %r87, 4;
	add.s32 	%r89, %r88, %r986;
	mul.wide.s32 	%rd20, %r89, 4;
	mul.lo.s32 	%r90, %r6, %r3;
	shl.b32 	%r91, %r90, 4;
	shl.b32 	%r92, %r986, 4;
	add.s32 	%r93, %r91, %r92;
	cvt.s64.s32 	%rd72, %r93;
	cvta.to.global.u64 	%rd73, %rd55;
	add.s64 	%rd74, %rd73, %rd72;
	add.s64 	%rd163, %rd74, 8;
	add.s32 	%r94, %r90, %r986;
	cvta.to.global.u64 	%rd75, %rd56;
	mul.wide.s32 	%rd76, %r94, 4;
	add.s64 	%rd162, %rd75, %rd76;
	cvta.to.global.u64 	%rd77, %rd57;
	add.s64 	%rd161, %rd77, %rd76;
	add.s64 	%rd24, %rd59, 28;
	mul.wide.u32 	%rd78, %r986, 32;
	cvta.to.global.u64 	%rd79, %rd52;
	add.s64 	%rd160, %rd79, %rd78;
	add.s64 	%rd26, %rd60, 28;
	add.s64 	%rd27, %rd61, 28;
	add.s64 	%rd28, %rd62, 28;
	add.s64 	%rd29, %rd63, 28;
	add.s64 	%rd30, %rd64, 28;
	add.s64 	%rd31, %rd65, 28;
	add.s64 	%rd32, %rd66, 28;
	add.s64 	%rd33, %rd67, 28;
	add.s64 	%rd34, %rd68, 28;
	add.s64 	%rd35, %rd69, 28;
	add.s64 	%rd36, %rd70, 28;
	add.s64 	%rd37, %rd71, 28;
	cvta.to.global.u64 	%rd165, %rd54;
	cvta.to.global.u64 	%rd164, %rd53;
	mov.f32 	%f376, 0f00000000;

$L__BB0_3:
	ld.global.f32 	%f17, [%rd162];
	ld.global.f32 	%f18, [%rd161];
	ld.global.u32 	%r128, [%rd163+-8];
	and.b32  	%r129, %r128, 15;
	and.b32  	%r130, %r128, 240;
	bfi.b32 	%r131, %r130, %r129, 4, 28;
	shl.b32 	%r132, %r128, 8;
	and.b32  	%r133, %r132, 983040;
	or.b32  	%r134, %r131, %r133;
	shl.b32 	%r135, %r128, 12;
	and.b32  	%r136, %r135, 251658240;
	or.b32  	%r97, %r134, %r136;
	shr.u32 	%r137, %r128, 16;
	and.b32  	%r138, %r137, 15;
	and.b32  	%r139, %r137, 240;
	bfi.b32 	%r140, %r139, %r138, 4, 28;
	shr.u32 	%r141, %r128, 8;
	and.b32  	%r142, %r141, 983040;
	or.b32  	%r143, %r140, %r142;
	shr.u32 	%r144, %r128, 4;
	and.b32  	%r145, %r144, 251658240;
	or.b32  	%r101, %r143, %r145;
	ld.global.u32 	%r146, [%rd163+-4];
	and.b32  	%r147, %r146, 15;
	and.b32  	%r148, %r146, 240;
	bfi.b32 	%r149, %r148, %r147, 4, 28;
	shl.b32 	%r150, %r146, 8;
	and.b32  	%r151, %r150, 983040;
	or.b32  	%r152, %r149, %r151;
	shl.b32 	%r153, %r146, 12;
	and.b32  	%r154, %r153, 251658240;
	or.b32  	%r105, %r152, %r154;
	shr.u32 	%r155, %r146, 16;
	and.b32  	%r156, %r155, 15;
	and.b32  	%r157, %r155, 240;
	bfi.b32 	%r158, %r157, %r156, 4, 28;
	shr.u32 	%r159, %r146, 8;
	and.b32  	%r160, %r159, 983040;
	or.b32  	%r161, %r158, %r160;
	shr.u32 	%r162, %r146, 4;
	and.b32  	%r163, %r162, 251658240;
	or.b32  	%r109, %r161, %r163;
	ld.global.u32 	%r164, [%rd163];
	and.b32  	%r165, %r164, 15;
	and.b32  	%r166, %r164, 240;
	bfi.b32 	%r167, %r166, %r165, 4, 28;
	shl.b32 	%r168, %r164, 8;
	and.b32  	%r169, %r168, 983040;
	or.b32  	%r170, %r167, %r169;
	shl.b32 	%r171, %r164, 12;
	and.b32  	%r172, %r171, 251658240;
	or.b32  	%r113, %r170, %r172;
	shr.u32 	%r173, %r164, 16;
	and.b32  	%r174, %r173, 15;
	and.b32  	%r175, %r173, 240;
	bfi.b32 	%r176, %r175, %r174, 4, 28;
	shr.u32 	%r177, %r164, 8;
	and.b32  	%r178, %r177, 983040;
	or.b32  	%r179, %r176, %r178;
	shr.u32 	%r180, %r164, 4;
	and.b32  	%r181, %r180, 251658240;
	or.b32  	%r117, %r179, %r181;
	ld.global.u32 	%r182, [%rd163+4];
	and.b32  	%r183, %r182, 15;
	and.b32  	%r184, %r182, 240;
	bfi.b32 	%r185, %r184, %r183, 4, 28;
	shl.b32 	%r186, %r182, 8;
	and.b32  	%r187, %r186, 983040;
	or.b32  	%r188, %r185, %r187;
	shl.b32 	%r189, %r182, 12;
	and.b32  	%r190, %r189, 251658240;
	or.b32  	%r121, %r188, %r190;
	shr.u32 	%r191, %r182, 16;
	and.b32  	%r192, %r191, 15;
	and.b32  	%r193, %r191, 240;
	bfi.b32 	%r194, %r193, %r192, 4, 28;
	shr.u32 	%r195, %r182, 8;
	and.b32  	%r196, %r195, 983040;
	or.b32  	%r197, %r194, %r196;
	shr.u32 	%r198, %r182, 4;
	and.b32  	%r199, %r198, 251658240;
	or.b32  	%r125, %r197, %r199;
	add.s64 	%rd80, %rd160, %rd24;
	ld.global.u32 	%r98, [%rd80+-28];
	mov.u32 	%r99, 0;
	// begin inline asm
	dp4a.s32.s32 %r96, %r97, %r98, %r99;
	// end inline asm
	ld.global.u32 	%r102, [%rd80+-24];
	// begin inline asm
	dp4a.s32.s32 %r100, %r101, %r102, %r96;
	// end inline asm
	ld.global.u32 	%r106, [%rd80+-20];
	// begin inline asm
	dp4a.s32.s32 %r104, %r105, %r106, %r100;
	// end inline asm
	ld.global.u32 	%r110, [%rd80+-16];
	// begin inline asm
	dp4a.s32.s32 %r108, %r109, %r110, %r104;
	// end inline asm
	ld.global.u32 	%r114, [%rd80+-12];
	// begin inline asm
	dp4a.s32.s32 %r112, %r113, %r114, %r108;
	// end inline asm
	ld.global.u32 	%r118, [%rd80+-8];
	// begin inline asm
	dp4a.s32.s32 %r116, %r117, %r118, %r112;
	// end inline asm
	ld.global.u32 	%r122, [%rd80+-4];
	// begin inline asm
	dp4a.s32.s32 %r120, %r121, %r122, %r116;
	// end inline asm
	ld.global.u32 	%r126, [%rd80];
	// begin inline asm
	dp4a.s32.s32 %r124, %r125, %r126, %r120;
	// end inline asm
	add.s64 	%rd81, %rd164, %rd20;
	cvt.rn.f32.s32 	%f114, %r124;
	mul.ftz.f32 	%f115, %f17, %f114;
	add.s64 	%rd82, %rd165, %rd20;
	ld.global.u32 	%r200, [%rd82];
	cvt.rn.f32.s32 	%f116, %r200;
	mul.ftz.f32 	%f117, %f18, %f116;
	sub.ftz.f32 	%f118, %f115, %f117;
	ld.global.f32 	%f119, [%rd81];
	fma.rn.ftz.f32 	%f392, %f119, %f118, %f392;
	setp.ge.s32 	%p5, %r21, %r49;
	@%p5 bra 	$L__BB0_5;

	add.s64 	%rd83, %rd160, %rd26;
	ld.global.u32 	%r203, [%rd83+-28];
	// begin inline asm
	dp4a.s32.s32 %r201, %r97, %r203, %r99;
	// end inline asm
	ld.global.u32 	%r207, [%rd83+-24];
	// begin inline asm
	dp4a.s32.s32 %r205, %r101, %r207, %r201;
	// end inline asm
	ld.global.u32 	%r211, [%rd83+-20];
	// begin inline asm
	dp4a.s32.s32 %r209, %r105, %r211, %r205;
	// end inline asm
	ld.global.u32 	%r215, [%rd83+-16];
	// begin inline asm
	dp4a.s32.s32 %r213, %r109, %r215, %r209;
	// end inline asm
	ld.global.u32 	%r219, [%rd83+-12];
	// begin inline asm
	dp4a.s32.s32 %r217, %r113, %r219, %r213;
	// end inline asm
	ld.global.u32 	%r223, [%rd83+-8];
	// begin inline asm
	dp4a.s32.s32 %r221, %r117, %r223, %r217;
	// end inline asm
	ld.global.u32 	%r227, [%rd83+-4];
	// begin inline asm
	dp4a.s32.s32 %r225, %r121, %r227, %r221;
	// end inline asm
	ld.global.u32 	%r231, [%rd83];
	// begin inline asm
	dp4a.s32.s32 %r229, %r125, %r231, %r225;
	// end inline asm
	add.s64 	%rd84, %rd164, %rd19;
	cvt.rn.f32.s32 	%f120, %r229;
	mul.ftz.f32 	%f121, %f17, %f120;
	add.s64 	%rd85, %rd165, %rd19;
	ld.global.u32 	%r233, [%rd85];
	cvt.rn.f32.s32 	%f122, %r233;
	mul.ftz.f32 	%f123, %f18, %f122;
	sub.ftz.f32 	%f124, %f121, %f123;
	ld.global.f32 	%f125, [%rd84];
	fma.rn.ftz.f32 	%f370, %f125, %f124, %f370;

$L__BB0_5:
	setp.ge.s32 	%p6, %r20, %r49;
	@%p6 bra 	$L__BB0_7;

	add.s64 	%rd86, %rd160, %rd27;
	ld.global.u32 	%r236, [%rd86+-28];
	mov.u32 	%r237, 0;
	// begin inline asm
	dp4a.s32.s32 %r234, %r97, %r236, %r237;
	// end inline asm
	ld.global.u32 	%r240, [%rd86+-24];
	// begin inline asm
	dp4a.s32.s32 %r238, %r101, %r240, %r234;
	// end inline asm
	ld.global.u32 	%r244, [%rd86+-20];
	// begin inline asm
	dp4a.s32.s32 %r242, %r105, %r244, %r238;
	// end inline asm
	ld.global.u32 	%r248, [%rd86+-16];
	// begin inline asm
	dp4a.s32.s32 %r246, %r109, %r248, %r242;
	// end inline asm
	ld.global.u32 	%r252, [%rd86+-12];
	// begin inline asm
	dp4a.s32.s32 %r250, %r113, %r252, %r246;
	// end inline asm
	ld.global.u32 	%r256, [%rd86+-8];
	// begin inline asm
	dp4a.s32.s32 %r254, %r117, %r256, %r250;
	// end inline asm
	ld.global.u32 	%r260, [%rd86+-4];
	// begin inline asm
	dp4a.s32.s32 %r258, %r121, %r260, %r254;
	// end inline asm
	ld.global.u32 	%r264, [%rd86];
	// begin inline asm
	dp4a.s32.s32 %r262, %r125, %r264, %r258;
	// end inline asm
	add.s64 	%rd87, %rd164, %rd18;
	cvt.rn.f32.s32 	%f126, %r262;
	mul.ftz.f32 	%f127, %f17, %f126;
	add.s64 	%rd88, %rd165, %rd18;
	ld.global.u32 	%r266, [%rd88];
	cvt.rn.f32.s32 	%f128, %r266;
	mul.ftz.f32 	%f129, %f18, %f128;
	sub.ftz.f32 	%f130, %f127, %f129;
	ld.global.f32 	%f131, [%rd87];
	fma.rn.ftz.f32 	%f371, %f131, %f130, %f371;

$L__BB0_7:
	setp.ge.s32 	%p7, %r19, %r49;
	@%p7 bra 	$L__BB0_9;

	add.s64 	%rd89, %rd160, %rd28;
	ld.global.u32 	%r269, [%rd89+-28];
	mov.u32 	%r270, 0;
	// begin inline asm
	dp4a.s32.s32 %r267, %r97, %r269, %r270;
	// end inline asm
	ld.global.u32 	%r273, [%rd89+-24];
	// begin inline asm
	dp4a.s32.s32 %r271, %r101, %r273, %r267;
	// end inline asm
	ld.global.u32 	%r277, [%rd89+-20];
	// begin inline asm
	dp4a.s32.s32 %r275, %r105, %r277, %r271;
	// end inline asm
	ld.global.u32 	%r281, [%rd89+-16];
	// begin inline asm
	dp4a.s32.s32 %r279, %r109, %r281, %r275;
	// end inline asm
	ld.global.u32 	%r285, [%rd89+-12];
	// begin inline asm
	dp4a.s32.s32 %r283, %r113, %r285, %r279;
	// end inline asm
	ld.global.u32 	%r289, [%rd89+-8];
	// begin inline asm
	dp4a.s32.s32 %r287, %r117, %r289, %r283;
	// end inline asm
	ld.global.u32 	%r293, [%rd89+-4];
	// begin inline asm
	dp4a.s32.s32 %r291, %r121, %r293, %r287;
	// end inline asm
	ld.global.u32 	%r297, [%rd89];
	// begin inline asm
	dp4a.s32.s32 %r295, %r125, %r297, %r291;
	// end inline asm
	add.s64 	%rd90, %rd164, %rd17;
	cvt.rn.f32.s32 	%f132, %r295;
	mul.ftz.f32 	%f133, %f17, %f132;
	add.s64 	%rd91, %rd165, %rd17;
	ld.global.u32 	%r299, [%rd91];
	cvt.rn.f32.s32 	%f134, %r299;
	mul.ftz.f32 	%f135, %f18, %f134;
	sub.ftz.f32 	%f136, %f133, %f135;
	ld.global.f32 	%f137, [%rd90];
	fma.rn.ftz.f32 	%f372, %f137, %f136, %f372;

$L__BB0_9:
	setp.ge.s32 	%p8, %r18, %r49;
	@%p8 bra 	$L__BB0_11;

	add.s64 	%rd92, %rd160, %rd29;
	ld.global.u32 	%r302, [%rd92+-28];
	mov.u32 	%r303, 0;
	// begin inline asm
	dp4a.s32.s32 %r300, %r97, %r302, %r303;
	// end inline asm
	ld.global.u32 	%r306, [%rd92+-24];
	// begin inline asm
	dp4a.s32.s32 %r304, %r101, %r306, %r300;
	// end inline asm
	ld.global.u32 	%r310, [%rd92+-20];
	// begin inline asm
	dp4a.s32.s32 %r308, %r105, %r310, %r304;
	// end inline asm
	ld.global.u32 	%r314, [%rd92+-16];
	// begin inline asm
	dp4a.s32.s32 %r312, %r109, %r314, %r308;
	// end inline asm
	ld.global.u32 	%r318, [%rd92+-12];
	// begin inline asm
	dp4a.s32.s32 %r316, %r113, %r318, %r312;
	// end inline asm
	ld.global.u32 	%r322, [%rd92+-8];
	// begin inline asm
	dp4a.s32.s32 %r320, %r117, %r322, %r316;
	// end inline asm
	ld.global.u32 	%r326, [%rd92+-4];
	// begin inline asm
	dp4a.s32.s32 %r324, %r121, %r326, %r320;
	// end inline asm
	ld.global.u32 	%r330, [%rd92];
	// begin inline asm
	dp4a.s32.s32 %r328, %r125, %r330, %r324;
	// end inline asm
	add.s64 	%rd93, %rd164, %rd16;
	cvt.rn.f32.s32 	%f138, %r328;
	mul.ftz.f32 	%f139, %f17, %f138;
	add.s64 	%rd94, %rd165, %rd16;
	ld.global.u32 	%r332, [%rd94];
	cvt.rn.f32.s32 	%f140, %r332;
	mul.ftz.f32 	%f141, %f18, %f140;
	sub.ftz.f32 	%f142, %f139, %f141;
	ld.global.f32 	%f143, [%rd93];
	fma.rn.ftz.f32 	%f373, %f143, %f142, %f373;

$L__BB0_11:
	setp.ge.s32 	%p9, %r17, %r49;
	@%p9 bra 	$L__BB0_13;

	add.s64 	%rd95, %rd160, %rd30;
	ld.global.u32 	%r335, [%rd95+-28];
	mov.u32 	%r336, 0;
	// begin inline asm
	dp4a.s32.s32 %r333, %r97, %r335, %r336;
	// end inline asm
	ld.global.u32 	%r339, [%rd95+-24];
	// begin inline asm
	dp4a.s32.s32 %r337, %r101, %r339, %r333;
	// end inline asm
	ld.global.u32 	%r343, [%rd95+-20];
	// begin inline asm
	dp4a.s32.s32 %r341, %r105, %r343, %r337;
	// end inline asm
	ld.global.u32 	%r347, [%rd95+-16];
	// begin inline asm
	dp4a.s32.s32 %r345, %r109, %r347, %r341;
	// end inline asm
	ld.global.u32 	%r351, [%rd95+-12];
	// begin inline asm
	dp4a.s32.s32 %r349, %r113, %r351, %r345;
	// end inline asm
	ld.global.u32 	%r355, [%rd95+-8];
	// begin inline asm
	dp4a.s32.s32 %r353, %r117, %r355, %r349;
	// end inline asm
	ld.global.u32 	%r359, [%rd95+-4];
	// begin inline asm
	dp4a.s32.s32 %r357, %r121, %r359, %r353;
	// end inline asm
	ld.global.u32 	%r363, [%rd95];
	// begin inline asm
	dp4a.s32.s32 %r361, %r125, %r363, %r357;
	// end inline asm
	add.s64 	%rd96, %rd164, %rd15;
	cvt.rn.f32.s32 	%f144, %r361;
	mul.ftz.f32 	%f145, %f17, %f144;
	add.s64 	%rd97, %rd165, %rd15;
	ld.global.u32 	%r365, [%rd97];
	cvt.rn.f32.s32 	%f146, %r365;
	mul.ftz.f32 	%f147, %f18, %f146;
	sub.ftz.f32 	%f148, %f145, %f147;
	ld.global.f32 	%f149, [%rd96];
	fma.rn.ftz.f32 	%f374, %f149, %f148, %f374;

$L__BB0_13:
	setp.ge.s32 	%p10, %r16, %r49;
	@%p10 bra 	$L__BB0_15;

	add.s64 	%rd98, %rd160, %rd31;
	ld.global.u32 	%r368, [%rd98+-28];
	mov.u32 	%r369, 0;
	// begin inline asm
	dp4a.s32.s32 %r366, %r97, %r368, %r369;
	// end inline asm
	ld.global.u32 	%r372, [%rd98+-24];
	// begin inline asm
	dp4a.s32.s32 %r370, %r101, %r372, %r366;
	// end inline asm
	ld.global.u32 	%r376, [%rd98+-20];
	// begin inline asm
	dp4a.s32.s32 %r374, %r105, %r376, %r370;
	// end inline asm
	ld.global.u32 	%r380, [%rd98+-16];
	// begin inline asm
	dp4a.s32.s32 %r378, %r109, %r380, %r374;
	// end inline asm
	ld.global.u32 	%r384, [%rd98+-12];
	// begin inline asm
	dp4a.s32.s32 %r382, %r113, %r384, %r378;
	// end inline asm
	ld.global.u32 	%r388, [%rd98+-8];
	// begin inline asm
	dp4a.s32.s32 %r386, %r117, %r388, %r382;
	// end inline asm
	ld.global.u32 	%r392, [%rd98+-4];
	// begin inline asm
	dp4a.s32.s32 %r390, %r121, %r392, %r386;
	// end inline asm
	ld.global.u32 	%r396, [%rd98];
	// begin inline asm
	dp4a.s32.s32 %r394, %r125, %r396, %r390;
	// end inline asm
	add.s64 	%rd99, %rd164, %rd14;
	cvt.rn.f32.s32 	%f150, %r394;
	mul.ftz.f32 	%f151, %f17, %f150;
	add.s64 	%rd100, %rd165, %rd14;
	ld.global.u32 	%r398, [%rd100];
	cvt.rn.f32.s32 	%f152, %r398;
	mul.ftz.f32 	%f153, %f18, %f152;
	sub.ftz.f32 	%f154, %f151, %f153;
	ld.global.f32 	%f155, [%rd99];
	fma.rn.ftz.f32 	%f375, %f155, %f154, %f375;

$L__BB0_15:
	setp.ge.s32 	%p11, %r15, %r49;
	@%p11 bra 	$L__BB0_17;

	add.s64 	%rd101, %rd160, %rd32;
	ld.global.u32 	%r401, [%rd101+-28];
	mov.u32 	%r402, 0;
	// begin inline asm
	dp4a.s32.s32 %r399, %r97, %r401, %r402;
	// end inline asm
	ld.global.u32 	%r405, [%rd101+-24];
	// begin inline asm
	dp4a.s32.s32 %r403, %r101, %r405, %r399;
	// end inline asm
	ld.global.u32 	%r409, [%rd101+-20];
	// begin inline asm
	dp4a.s32.s32 %r407, %r105, %r409, %r403;
	// end inline asm
	ld.global.u32 	%r413, [%rd101+-16];
	// begin inline asm
	dp4a.s32.s32 %r411, %r109, %r413, %r407;
	// end inline asm
	ld.global.u32 	%r417, [%rd101+-12];
	// begin inline asm
	dp4a.s32.s32 %r415, %r113, %r417, %r411;
	// end inline asm
	ld.global.u32 	%r421, [%rd101+-8];
	// begin inline asm
	dp4a.s32.s32 %r419, %r117, %r421, %r415;
	// end inline asm
	ld.global.u32 	%r425, [%rd101+-4];
	// begin inline asm
	dp4a.s32.s32 %r423, %r121, %r425, %r419;
	// end inline asm
	ld.global.u32 	%r429, [%rd101];
	// begin inline asm
	dp4a.s32.s32 %r427, %r125, %r429, %r423;
	// end inline asm
	add.s64 	%rd102, %rd164, %rd13;
	cvt.rn.f32.s32 	%f156, %r427;
	mul.ftz.f32 	%f157, %f17, %f156;
	add.s64 	%rd103, %rd165, %rd13;
	ld.global.u32 	%r431, [%rd103];
	cvt.rn.f32.s32 	%f158, %r431;
	mul.ftz.f32 	%f159, %f18, %f158;
	sub.ftz.f32 	%f160, %f157, %f159;
	ld.global.f32 	%f161, [%rd102];
	fma.rn.ftz.f32 	%f376, %f161, %f160, %f376;

$L__BB0_17:
	setp.ge.s32 	%p12, %r14, %r49;
	@%p12 bra 	$L__BB0_19;

	add.s64 	%rd104, %rd160, %rd33;
	ld.global.u32 	%r434, [%rd104+-28];
	mov.u32 	%r435, 0;
	// begin inline asm
	dp4a.s32.s32 %r432, %r97, %r434, %r435;
	// end inline asm
	ld.global.u32 	%r438, [%rd104+-24];
	// begin inline asm
	dp4a.s32.s32 %r436, %r101, %r438, %r432;
	// end inline asm
	ld.global.u32 	%r442, [%rd104+-20];
	// begin inline asm
	dp4a.s32.s32 %r440, %r105, %r442, %r436;
	// end inline asm
	ld.global.u32 	%r446, [%rd104+-16];
	// begin inline asm
	dp4a.s32.s32 %r444, %r109, %r446, %r440;
	// end inline asm
	ld.global.u32 	%r450, [%rd104+-12];
	// begin inline asm
	dp4a.s32.s32 %r448, %r113, %r450, %r444;
	// end inline asm
	ld.global.u32 	%r454, [%rd104+-8];
	// begin inline asm
	dp4a.s32.s32 %r452, %r117, %r454, %r448;
	// end inline asm
	ld.global.u32 	%r458, [%rd104+-4];
	// begin inline asm
	dp4a.s32.s32 %r456, %r121, %r458, %r452;
	// end inline asm
	ld.global.u32 	%r462, [%rd104];
	// begin inline asm
	dp4a.s32.s32 %r460, %r125, %r462, %r456;
	// end inline asm
	add.s64 	%rd105, %rd164, %rd12;
	cvt.rn.f32.s32 	%f162, %r460;
	mul.ftz.f32 	%f163, %f17, %f162;
	add.s64 	%rd106, %rd165, %rd12;
	ld.global.u32 	%r464, [%rd106];
	cvt.rn.f32.s32 	%f164, %r464;
	mul.ftz.f32 	%f165, %f18, %f164;
	sub.ftz.f32 	%f166, %f163, %f165;
	ld.global.f32 	%f167, [%rd105];
	fma.rn.ftz.f32 	%f377, %f167, %f166, %f377;

$L__BB0_19:
	setp.ge.s32 	%p13, %r13, %r49;
	@%p13 bra 	$L__BB0_21;

	add.s64 	%rd107, %rd160, %rd34;
	ld.global.u32 	%r467, [%rd107+-28];
	mov.u32 	%r468, 0;
	// begin inline asm
	dp4a.s32.s32 %r465, %r97, %r467, %r468;
	// end inline asm
	ld.global.u32 	%r471, [%rd107+-24];
	// begin inline asm
	dp4a.s32.s32 %r469, %r101, %r471, %r465;
	// end inline asm
	ld.global.u32 	%r475, [%rd107+-20];
	// begin inline asm
	dp4a.s32.s32 %r473, %r105, %r475, %r469;
	// end inline asm
	ld.global.u32 	%r479, [%rd107+-16];
	// begin inline asm
	dp4a.s32.s32 %r477, %r109, %r479, %r473;
	// end inline asm
	ld.global.u32 	%r483, [%rd107+-12];
	// begin inline asm
	dp4a.s32.s32 %r481, %r113, %r483, %r477;
	// end inline asm
	ld.global.u32 	%r487, [%rd107+-8];
	// begin inline asm
	dp4a.s32.s32 %r485, %r117, %r487, %r481;
	// end inline asm
	ld.global.u32 	%r491, [%rd107+-4];
	// begin inline asm
	dp4a.s32.s32 %r489, %r121, %r491, %r485;
	// end inline asm
	ld.global.u32 	%r495, [%rd107];
	// begin inline asm
	dp4a.s32.s32 %r493, %r125, %r495, %r489;
	// end inline asm
	add.s64 	%rd108, %rd164, %rd11;
	cvt.rn.f32.s32 	%f168, %r493;
	mul.ftz.f32 	%f169, %f17, %f168;
	add.s64 	%rd109, %rd165, %rd11;
	ld.global.u32 	%r497, [%rd109];
	cvt.rn.f32.s32 	%f170, %r497;
	mul.ftz.f32 	%f171, %f18, %f170;
	sub.ftz.f32 	%f172, %f169, %f171;
	ld.global.f32 	%f173, [%rd108];
	fma.rn.ftz.f32 	%f378, %f173, %f172, %f378;

$L__BB0_21:
	setp.ge.s32 	%p14, %r12, %r49;
	@%p14 bra 	$L__BB0_23;

	add.s64 	%rd110, %rd160, %rd35;
	ld.global.u32 	%r500, [%rd110+-28];
	mov.u32 	%r501, 0;
	// begin inline asm
	dp4a.s32.s32 %r498, %r97, %r500, %r501;
	// end inline asm
	ld.global.u32 	%r504, [%rd110+-24];
	// begin inline asm
	dp4a.s32.s32 %r502, %r101, %r504, %r498;
	// end inline asm
	ld.global.u32 	%r508, [%rd110+-20];
	// begin inline asm
	dp4a.s32.s32 %r506, %r105, %r508, %r502;
	// end inline asm
	ld.global.u32 	%r512, [%rd110+-16];
	// begin inline asm
	dp4a.s32.s32 %r510, %r109, %r512, %r506;
	// end inline asm
	ld.global.u32 	%r516, [%rd110+-12];
	// begin inline asm
	dp4a.s32.s32 %r514, %r113, %r516, %r510;
	// end inline asm
	ld.global.u32 	%r520, [%rd110+-8];
	// begin inline asm
	dp4a.s32.s32 %r518, %r117, %r520, %r514;
	// end inline asm
	ld.global.u32 	%r524, [%rd110+-4];
	// begin inline asm
	dp4a.s32.s32 %r522, %r121, %r524, %r518;
	// end inline asm
	ld.global.u32 	%r528, [%rd110];
	// begin inline asm
	dp4a.s32.s32 %r526, %r125, %r528, %r522;
	// end inline asm
	add.s64 	%rd111, %rd164, %rd10;
	cvt.rn.f32.s32 	%f174, %r526;
	mul.ftz.f32 	%f175, %f17, %f174;
	add.s64 	%rd112, %rd165, %rd10;
	ld.global.u32 	%r530, [%rd112];
	cvt.rn.f32.s32 	%f176, %r530;
	mul.ftz.f32 	%f177, %f18, %f176;
	sub.ftz.f32 	%f178, %f175, %f177;
	ld.global.f32 	%f179, [%rd111];
	fma.rn.ftz.f32 	%f379, %f179, %f178, %f379;

$L__BB0_23:
	setp.ge.s32 	%p15, %r11, %r49;
	@%p15 bra 	$L__BB0_25;

	add.s64 	%rd113, %rd160, %rd36;
	ld.global.u32 	%r533, [%rd113+-28];
	mov.u32 	%r534, 0;
	// begin inline asm
	dp4a.s32.s32 %r531, %r97, %r533, %r534;
	// end inline asm
	ld.global.u32 	%r537, [%rd113+-24];
	// begin inline asm
	dp4a.s32.s32 %r535, %r101, %r537, %r531;
	// end inline asm
	ld.global.u32 	%r541, [%rd113+-20];
	// begin inline asm
	dp4a.s32.s32 %r539, %r105, %r541, %r535;
	// end inline asm
	ld.global.u32 	%r545, [%rd113+-16];
	// begin inline asm
	dp4a.s32.s32 %r543, %r109, %r545, %r539;
	// end inline asm
	ld.global.u32 	%r549, [%rd113+-12];
	// begin inline asm
	dp4a.s32.s32 %r547, %r113, %r549, %r543;
	// end inline asm
	ld.global.u32 	%r553, [%rd113+-8];
	// begin inline asm
	dp4a.s32.s32 %r551, %r117, %r553, %r547;
	// end inline asm
	ld.global.u32 	%r557, [%rd113+-4];
	// begin inline asm
	dp4a.s32.s32 %r555, %r121, %r557, %r551;
	// end inline asm
	ld.global.u32 	%r561, [%rd113];
	// begin inline asm
	dp4a.s32.s32 %r559, %r125, %r561, %r555;
	// end inline asm
	add.s64 	%rd114, %rd164, %rd9;
	cvt.rn.f32.s32 	%f180, %r559;
	mul.ftz.f32 	%f181, %f17, %f180;
	add.s64 	%rd115, %rd165, %rd9;
	ld.global.u32 	%r563, [%rd115];
	cvt.rn.f32.s32 	%f182, %r563;
	mul.ftz.f32 	%f183, %f18, %f182;
	sub.ftz.f32 	%f184, %f181, %f183;
	ld.global.f32 	%f185, [%rd114];
	fma.rn.ftz.f32 	%f380, %f185, %f184, %f380;

$L__BB0_25:
	setp.ge.s32 	%p16, %r10, %r49;
	@%p16 bra 	$L__BB0_27;

	add.s64 	%rd116, %rd160, %rd37;
	ld.global.u32 	%r566, [%rd116+-28];
	mov.u32 	%r567, 0;
	// begin inline asm
	dp4a.s32.s32 %r564, %r97, %r566, %r567;
	// end inline asm
	ld.global.u32 	%r570, [%rd116+-24];
	// begin inline asm
	dp4a.s32.s32 %r568, %r101, %r570, %r564;
	// end inline asm
	ld.global.u32 	%r574, [%rd116+-20];
	// begin inline asm
	dp4a.s32.s32 %r572, %r105, %r574, %r568;
	// end inline asm
	ld.global.u32 	%r578, [%rd116+-16];
	// begin inline asm
	dp4a.s32.s32 %r576, %r109, %r578, %r572;
	// end inline asm
	ld.global.u32 	%r582, [%rd116+-12];
	// begin inline asm
	dp4a.s32.s32 %r580, %r113, %r582, %r576;
	// end inline asm
	ld.global.u32 	%r586, [%rd116+-8];
	// begin inline asm
	dp4a.s32.s32 %r584, %r117, %r586, %r580;
	// end inline asm
	ld.global.u32 	%r590, [%rd116+-4];
	// begin inline asm
	dp4a.s32.s32 %r588, %r121, %r590, %r584;
	// end inline asm
	ld.global.u32 	%r594, [%rd116];
	// begin inline asm
	dp4a.s32.s32 %r592, %r125, %r594, %r588;
	// end inline asm
	add.s64 	%rd117, %rd164, %rd8;
	cvt.rn.f32.s32 	%f186, %r592;
	mul.ftz.f32 	%f187, %f17, %f186;
	add.s64 	%rd118, %rd165, %rd8;
	ld.global.u32 	%r596, [%rd118];
	cvt.rn.f32.s32 	%f188, %r596;
	mul.ftz.f32 	%f189, %f18, %f188;
	sub.ftz.f32 	%f190, %f187, %f189;
	ld.global.f32 	%f191, [%rd117];
	fma.rn.ftz.f32 	%f381, %f191, %f190, %f381;

$L__BB0_27:
	setp.ge.s32 	%p17, %r9, %r49;
	@%p17 bra 	$L__BB0_29;

	add.s64 	%rd119, %rd160, %rd2;
	ld.global.u32 	%r599, [%rd119];
	mov.u32 	%r600, 0;
	// begin inline asm
	dp4a.s32.s32 %r597, %r97, %r599, %r600;
	// end inline asm
	ld.global.u32 	%r603, [%rd119+4];
	// begin inline asm
	dp4a.s32.s32 %r601, %r101, %r603, %r597;
	// end inline asm
	ld.global.u32 	%r607, [%rd119+8];
	// begin inline asm
	dp4a.s32.s32 %r605, %r105, %r607, %r601;
	// end inline asm
	ld.global.u32 	%r611, [%rd119+12];
	// begin inline asm
	dp4a.s32.s32 %r609, %r109, %r611, %r605;
	// end inline asm
	ld.global.u32 	%r615, [%rd119+16];
	// begin inline asm
	dp4a.s32.s32 %r613, %r113, %r615, %r609;
	// end inline asm
	ld.global.u32 	%r619, [%rd119+20];
	// begin inline asm
	dp4a.s32.s32 %r617, %r117, %r619, %r613;
	// end inline asm
	ld.global.u32 	%r623, [%rd119+24];
	// begin inline asm
	dp4a.s32.s32 %r621, %r121, %r623, %r617;
	// end inline asm
	ld.global.u32 	%r627, [%rd119+28];
	// begin inline asm
	dp4a.s32.s32 %r625, %r125, %r627, %r621;
	// end inline asm
	add.s64 	%rd120, %rd164, %rd7;
	cvt.rn.f32.s32 	%f192, %r625;
	mul.ftz.f32 	%f193, %f17, %f192;
	add.s64 	%rd121, %rd165, %rd7;
	ld.global.u32 	%r629, [%rd121];
	cvt.rn.f32.s32 	%f194, %r629;
	mul.ftz.f32 	%f195, %f18, %f194;
	sub.ftz.f32 	%f196, %f193, %f195;
	ld.global.f32 	%f197, [%rd120];
	fma.rn.ftz.f32 	%f382, %f197, %f196, %f382;

$L__BB0_29:
	setp.ge.s32 	%p18, %r8, %r49;
	@%p18 bra 	$L__BB0_31;

	add.s64 	%rd122, %rd160, %rd3;
	ld.global.u32 	%r632, [%rd122];
	mov.u32 	%r633, 0;
	// begin inline asm
	dp4a.s32.s32 %r630, %r97, %r632, %r633;
	// end inline asm
	ld.global.u32 	%r636, [%rd122+4];
	// begin inline asm
	dp4a.s32.s32 %r634, %r101, %r636, %r630;
	// end inline asm
	ld.global.u32 	%r640, [%rd122+8];
	// begin inline asm
	dp4a.s32.s32 %r638, %r105, %r640, %r634;
	// end inline asm
	ld.global.u32 	%r644, [%rd122+12];
	// begin inline asm
	dp4a.s32.s32 %r642, %r109, %r644, %r638;
	// end inline asm
	ld.global.u32 	%r648, [%rd122+16];
	// begin inline asm
	dp4a.s32.s32 %r646, %r113, %r648, %r642;
	// end inline asm
	ld.global.u32 	%r652, [%rd122+20];
	// begin inline asm
	dp4a.s32.s32 %r650, %r117, %r652, %r646;
	// end inline asm
	ld.global.u32 	%r656, [%rd122+24];
	// begin inline asm
	dp4a.s32.s32 %r654, %r121, %r656, %r650;
	// end inline asm
	ld.global.u32 	%r660, [%rd122+28];
	// begin inline asm
	dp4a.s32.s32 %r658, %r125, %r660, %r654;
	// end inline asm
	add.s64 	%rd123, %rd164, %rd6;
	cvt.rn.f32.s32 	%f198, %r658;
	mul.ftz.f32 	%f199, %f17, %f198;
	add.s64 	%rd124, %rd165, %rd6;
	ld.global.u32 	%r662, [%rd124];
	cvt.rn.f32.s32 	%f200, %r662;
	mul.ftz.f32 	%f201, %f18, %f200;
	sub.ftz.f32 	%f202, %f199, %f201;
	ld.global.f32 	%f203, [%rd123];
	fma.rn.ftz.f32 	%f383, %f203, %f202, %f383;

$L__BB0_31:
	setp.ge.s32 	%p19, %r7, %r49;
	@%p19 bra 	$L__BB0_33;

	add.s64 	%rd125, %rd160, %rd4;
	ld.global.u32 	%r665, [%rd125];
	mov.u32 	%r666, 0;
	// begin inline asm
	dp4a.s32.s32 %r663, %r97, %r665, %r666;
	// end inline asm
	ld.global.u32 	%r669, [%rd125+4];
	// begin inline asm
	dp4a.s32.s32 %r667, %r101, %r669, %r663;
	// end inline asm
	ld.global.u32 	%r673, [%rd125+8];
	// begin inline asm
	dp4a.s32.s32 %r671, %r105, %r673, %r667;
	// end inline asm
	ld.global.u32 	%r677, [%rd125+12];
	// begin inline asm
	dp4a.s32.s32 %r675, %r109, %r677, %r671;
	// end inline asm
	ld.global.u32 	%r681, [%rd125+16];
	// begin inline asm
	dp4a.s32.s32 %r679, %r113, %r681, %r675;
	// end inline asm
	ld.global.u32 	%r685, [%rd125+20];
	// begin inline asm
	dp4a.s32.s32 %r683, %r117, %r685, %r679;
	// end inline asm
	ld.global.u32 	%r689, [%rd125+24];
	// begin inline asm
	dp4a.s32.s32 %r687, %r121, %r689, %r683;
	// end inline asm
	ld.global.u32 	%r693, [%rd125+28];
	// begin inline asm
	dp4a.s32.s32 %r691, %r125, %r693, %r687;
	// end inline asm
	add.s64 	%rd126, %rd164, %rd5;
	cvt.rn.f32.s32 	%f204, %r691;
	mul.ftz.f32 	%f205, %f17, %f204;
	add.s64 	%rd127, %rd165, %rd5;
	ld.global.u32 	%r695, [%rd127];
	cvt.rn.f32.s32 	%f206, %r695;
	mul.ftz.f32 	%f207, %f18, %f206;
	sub.ftz.f32 	%f208, %f205, %f207;
	ld.global.f32 	%f209, [%rd126];
	fma.rn.ftz.f32 	%f384, %f209, %f208, %f384;

$L__BB0_33:
	add.s64 	%rd165, %rd165, 128;
	add.s64 	%rd164, %rd164, 128;
	add.s64 	%rd163, %rd163, 512;
	add.s64 	%rd162, %rd162, 128;
	add.s64 	%rd161, %rd161, 128;
	add.s64 	%rd160, %rd160, 1024;
	add.s32 	%r986, %r986, 32;
	setp.lt.s32 	%p20, %r986, %r6;
	@%p20 bra 	$L__BB0_3;

$L__BB0_34:
	mov.u32 	%r985, %tid.x;
	and.b32  	%r984, %r985, 31;
	mov.b32 	%r696, %f392;
	mov.u32 	%r697, 2;
	mov.u32 	%r698, 31;
	mov.u32 	%r699, 16;
	mov.u32 	%r700, -1;
	shfl.sync.down.b32 	%r701|%p21, %r696, %r699, %r698, %r700;
	mov.b32 	%f210, %r701;
	add.ftz.f32 	%f211, %f392, %f210;
	mov.b32 	%r702, %f211;
	mov.u32 	%r703, 8;
	shfl.sync.down.b32 	%r704|%p22, %r702, %r703, %r698, %r700;
	mov.b32 	%f212, %r704;
	add.ftz.f32 	%f213, %f211, %f212;
	mov.b32 	%r705, %f213;
	mov.u32 	%r706, 4;
	shfl.sync.down.b32 	%r707|%p23, %r705, %r706, %r698, %r700;
	mov.b32 	%f214, %r707;
	add.ftz.f32 	%f215, %f213, %f214;
	mov.b32 	%r708, %f215;
	shfl.sync.down.b32 	%r709|%p24, %r708, %r697, %r698, %r700;
	mov.b32 	%f216, %r709;
	add.ftz.f32 	%f217, %f215, %f216;
	mov.b32 	%r710, %f217;
	mov.u32 	%r711, 1;
	shfl.sync.down.b32 	%r712|%p25, %r710, %r711, %r698, %r700;
	mov.b32 	%f218, %r712;
	add.ftz.f32 	%f66, %f217, %f218;
	setp.ne.s32 	%p26, %r984, 0;
	@%p26 bra 	$L__BB0_36;

	mad.lo.s32 	%r713, %r5, %r48, %r3;
	mul.wide.s32 	%rd128, %r713, 4;
	add.s64 	%rd129, %rd1, %rd128;
	st.global.f32 	[%rd129], %f66;

$L__BB0_36:
	mov.b32 	%r714, %f370;
	shfl.sync.down.b32 	%r719|%p28, %r714, %r699, %r698, %r700;
	mov.b32 	%f219, %r719;
	add.ftz.f32 	%f220, %f370, %f219;
	mov.b32 	%r720, %f220;
	shfl.sync.down.b32 	%r722|%p29, %r720, %r703, %r698, %r700;
	mov.b32 	%f221, %r722;
	add.ftz.f32 	%f222, %f220, %f221;
	mov.b32 	%r723, %f222;
	shfl.sync.down.b32 	%r725|%p30, %r723, %r706, %r698, %r700;
	mov.b32 	%f223, %r725;
	add.ftz.f32 	%f224, %f222, %f223;
	mov.b32 	%r726, %f224;
	shfl.sync.down.b32 	%r727|%p31, %r726, %r697, %r698, %r700;
	mov.b32 	%f225, %r727;
	add.ftz.f32 	%f226, %f224, %f225;
	mov.b32 	%r728, %f226;
	shfl.sync.down.b32 	%r730|%p32, %r728, %r711, %r698, %r700;
	mov.b32 	%f227, %r730;
	add.ftz.f32 	%f67, %f226, %f227;
	add.s32 	%r32, %r5, 1;
	setp.ge.s32 	%p33, %r32, %r49;
	or.pred  	%p34, %p26, %p33;
	@%p34 bra 	$L__BB0_38;

	mad.lo.s32 	%r731, %r32, %r48, %r3;
	mul.wide.s32 	%rd130, %r731, 4;
	add.s64 	%rd131, %rd1, %rd130;
	st.global.f32 	[%rd131], %f67;

$L__BB0_38:
	mov.b32 	%r732, %f371;
	mov.u32 	%r733, 2;
	mov.u32 	%r734, 31;
	mov.u32 	%r735, 16;
	mov.u32 	%r736, -1;
	shfl.sync.down.b32 	%r737|%p36, %r732, %r735, %r734, %r736;
	mov.b32 	%f228, %r737;
	add.ftz.f32 	%f229, %f371, %f228;
	mov.b32 	%r738, %f229;
	mov.u32 	%r739, 8;
	shfl.sync.down.b32 	%r740|%p37, %r738, %r739, %r734, %r736;
	mov.b32 	%f230, %r740;
	add.ftz.f32 	%f231, %f229, %f230;
	mov.b32 	%r741, %f231;
	mov.u32 	%r742, 4;
	shfl.sync.down.b32 	%r743|%p38, %r741, %r742, %r734, %r736;
	mov.b32 	%f232, %r743;
	add.ftz.f32 	%f233, %f231, %f232;
	mov.b32 	%r744, %f233;
	shfl.sync.down.b32 	%r745|%p39, %r744, %r733, %r734, %r736;
	mov.b32 	%f234, %r745;
	add.ftz.f32 	%f235, %f233, %f234;
	mov.b32 	%r746, %f235;
	mov.u32 	%r747, 1;
	shfl.sync.down.b32 	%r748|%p40, %r746, %r747, %r734, %r736;
	mov.b32 	%f236, %r748;
	add.ftz.f32 	%f68, %f235, %f236;
	add.s32 	%r33, %r5, 2;
	setp.ge.s32 	%p41, %r33, %r49;
	or.pred  	%p42, %p26, %p41;
	@%p42 bra 	$L__BB0_40;

	mad.lo.s32 	%r749, %r33, %r48, %r3;
	mul.wide.s32 	%rd132, %r749, 4;
	add.s64 	%rd133, %rd1, %rd132;
	st.global.f32 	[%rd133], %f68;

$L__BB0_40:
	mov.b32 	%r750, %f372;
	shfl.sync.down.b32 	%r755|%p44, %r750, %r735, %r734, %r736;
	mov.b32 	%f237, %r755;
	add.ftz.f32 	%f238, %f372, %f237;
	mov.b32 	%r756, %f238;
	shfl.sync.down.b32 	%r758|%p45, %r756, %r739, %r734, %r736;
	mov.b32 	%f239, %r758;
	add.ftz.f32 	%f240, %f238, %f239;
	mov.b32 	%r759, %f240;
	shfl.sync.down.b32 	%r761|%p46, %r759, %r742, %r734, %r736;
	mov.b32 	%f241, %r761;
	add.ftz.f32 	%f242, %f240, %f241;
	mov.b32 	%r762, %f242;
	shfl.sync.down.b32 	%r763|%p47, %r762, %r733, %r734, %r736;
	mov.b32 	%f243, %r763;
	add.ftz.f32 	%f244, %f242, %f243;
	mov.b32 	%r764, %f244;
	shfl.sync.down.b32 	%r766|%p48, %r764, %r747, %r734, %r736;
	mov.b32 	%f245, %r766;
	add.ftz.f32 	%f69, %f244, %f245;
	add.s32 	%r34, %r5, 3;
	setp.ge.s32 	%p49, %r34, %r49;
	or.pred  	%p50, %p26, %p49;
	@%p50 bra 	$L__BB0_42;

	mad.lo.s32 	%r767, %r34, %r48, %r3;
	mul.wide.s32 	%rd134, %r767, 4;
	add.s64 	%rd135, %rd1, %rd134;
	st.global.f32 	[%rd135], %f69;

$L__BB0_42:
	mov.b32 	%r768, %f373;
	mov.u32 	%r769, 2;
	mov.u32 	%r770, 31;
	mov.u32 	%r771, 16;
	mov.u32 	%r772, -1;
	shfl.sync.down.b32 	%r773|%p52, %r768, %r771, %r770, %r772;
	mov.b32 	%f246, %r773;
	add.ftz.f32 	%f247, %f373, %f246;
	mov.b32 	%r774, %f247;
	mov.u32 	%r775, 8;
	shfl.sync.down.b32 	%r776|%p53, %r774, %r775, %r770, %r772;
	mov.b32 	%f248, %r776;
	add.ftz.f32 	%f249, %f247, %f248;
	mov.b32 	%r777, %f249;
	mov.u32 	%r778, 4;
	shfl.sync.down.b32 	%r779|%p54, %r777, %r778, %r770, %r772;
	mov.b32 	%f250, %r779;
	add.ftz.f32 	%f251, %f249, %f250;
	mov.b32 	%r780, %f251;
	shfl.sync.down.b32 	%r781|%p55, %r780, %r769, %r770, %r772;
	mov.b32 	%f252, %r781;
	add.ftz.f32 	%f253, %f251, %f252;
	mov.b32 	%r782, %f253;
	mov.u32 	%r783, 1;
	shfl.sync.down.b32 	%r784|%p56, %r782, %r783, %r770, %r772;
	mov.b32 	%f254, %r784;
	add.ftz.f32 	%f70, %f253, %f254;
	add.s32 	%r35, %r5, 4;
	setp.ge.s32 	%p57, %r35, %r49;
	or.pred  	%p58, %p26, %p57;
	@%p58 bra 	$L__BB0_44;

	mad.lo.s32 	%r785, %r35, %r48, %r3;
	mul.wide.s32 	%rd136, %r785, 4;
	add.s64 	%rd137, %rd1, %rd136;
	st.global.f32 	[%rd137], %f70;

$L__BB0_44:
	mov.b32 	%r786, %f374;
	shfl.sync.down.b32 	%r791|%p60, %r786, %r771, %r770, %r772;
	mov.b32 	%f255, %r791;
	add.ftz.f32 	%f256, %f374, %f255;
	mov.b32 	%r792, %f256;
	shfl.sync.down.b32 	%r794|%p61, %r792, %r775, %r770, %r772;
	mov.b32 	%f257, %r794;
	add.ftz.f32 	%f258, %f256, %f257;
	mov.b32 	%r795, %f258;
	shfl.sync.down.b32 	%r797|%p62, %r795, %r778, %r770, %r772;
	mov.b32 	%f259, %r797;
	add.ftz.f32 	%f260, %f258, %f259;
	mov.b32 	%r798, %f260;
	shfl.sync.down.b32 	%r799|%p63, %r798, %r769, %r770, %r772;
	mov.b32 	%f261, %r799;
	add.ftz.f32 	%f262, %f260, %f261;
	mov.b32 	%r800, %f262;
	shfl.sync.down.b32 	%r802|%p64, %r800, %r783, %r770, %r772;
	mov.b32 	%f263, %r802;
	add.ftz.f32 	%f71, %f262, %f263;
	add.s32 	%r36, %r5, 5;
	setp.ge.s32 	%p65, %r36, %r49;
	or.pred  	%p66, %p26, %p65;
	@%p66 bra 	$L__BB0_46;

	mad.lo.s32 	%r803, %r36, %r48, %r3;
	mul.wide.s32 	%rd138, %r803, 4;
	add.s64 	%rd139, %rd1, %rd138;
	st.global.f32 	[%rd139], %f71;

$L__BB0_46:
	mov.b32 	%r804, %f375;
	mov.u32 	%r805, 2;
	mov.u32 	%r806, 31;
	mov.u32 	%r807, 16;
	mov.u32 	%r808, -1;
	shfl.sync.down.b32 	%r809|%p68, %r804, %r807, %r806, %r808;
	mov.b32 	%f264, %r809;
	add.ftz.f32 	%f265, %f375, %f264;
	mov.b32 	%r810, %f265;
	mov.u32 	%r811, 8;
	shfl.sync.down.b32 	%r812|%p69, %r810, %r811, %r806, %r808;
	mov.b32 	%f266, %r812;
	add.ftz.f32 	%f267, %f265, %f266;
	mov.b32 	%r813, %f267;
	mov.u32 	%r814, 4;
	shfl.sync.down.b32 	%r815|%p70, %r813, %r814, %r806, %r808;
	mov.b32 	%f268, %r815;
	add.ftz.f32 	%f269, %f267, %f268;
	mov.b32 	%r816, %f269;
	shfl.sync.down.b32 	%r817|%p71, %r816, %r805, %r806, %r808;
	mov.b32 	%f270, %r817;
	add.ftz.f32 	%f271, %f269, %f270;
	mov.b32 	%r818, %f271;
	mov.u32 	%r819, 1;
	shfl.sync.down.b32 	%r820|%p72, %r818, %r819, %r806, %r808;
	mov.b32 	%f272, %r820;
	add.ftz.f32 	%f72, %f271, %f272;
	add.s32 	%r37, %r5, 6;
	setp.ge.s32 	%p73, %r37, %r49;
	or.pred  	%p74, %p26, %p73;
	@%p74 bra 	$L__BB0_48;

	mad.lo.s32 	%r821, %r37, %r48, %r3;
	mul.wide.s32 	%rd140, %r821, 4;
	add.s64 	%rd141, %rd1, %rd140;
	st.global.f32 	[%rd141], %f72;

$L__BB0_48:
	mov.b32 	%r822, %f376;
	shfl.sync.down.b32 	%r827|%p76, %r822, %r807, %r806, %r808;
	mov.b32 	%f273, %r827;
	add.ftz.f32 	%f274, %f376, %f273;
	mov.b32 	%r828, %f274;
	shfl.sync.down.b32 	%r830|%p77, %r828, %r811, %r806, %r808;
	mov.b32 	%f275, %r830;
	add.ftz.f32 	%f276, %f274, %f275;
	mov.b32 	%r831, %f276;
	shfl.sync.down.b32 	%r833|%p78, %r831, %r814, %r806, %r808;
	mov.b32 	%f277, %r833;
	add.ftz.f32 	%f278, %f276, %f277;
	mov.b32 	%r834, %f278;
	shfl.sync.down.b32 	%r835|%p79, %r834, %r805, %r806, %r808;
	mov.b32 	%f279, %r835;
	add.ftz.f32 	%f280, %f278, %f279;
	mov.b32 	%r836, %f280;
	shfl.sync.down.b32 	%r838|%p80, %r836, %r819, %r806, %r808;
	mov.b32 	%f281, %r838;
	add.ftz.f32 	%f73, %f280, %f281;
	add.s32 	%r38, %r5, 7;
	setp.ge.s32 	%p81, %r38, %r49;
	or.pred  	%p82, %p26, %p81;
	@%p82 bra 	$L__BB0_50;

	mad.lo.s32 	%r839, %r38, %r48, %r3;
	mul.wide.s32 	%rd142, %r839, 4;
	add.s64 	%rd143, %rd1, %rd142;
	st.global.f32 	[%rd143], %f73;

$L__BB0_50:
	mov.b32 	%r840, %f377;
	mov.u32 	%r841, 2;
	mov.u32 	%r842, 31;
	mov.u32 	%r843, 16;
	mov.u32 	%r844, -1;
	shfl.sync.down.b32 	%r845|%p84, %r840, %r843, %r842, %r844;
	mov.b32 	%f282, %r845;
	add.ftz.f32 	%f283, %f377, %f282;
	mov.b32 	%r846, %f283;
	mov.u32 	%r847, 8;
	shfl.sync.down.b32 	%r848|%p85, %r846, %r847, %r842, %r844;
	mov.b32 	%f284, %r848;
	add.ftz.f32 	%f285, %f283, %f284;
	mov.b32 	%r849, %f285;
	mov.u32 	%r850, 4;
	shfl.sync.down.b32 	%r851|%p86, %r849, %r850, %r842, %r844;
	mov.b32 	%f286, %r851;
	add.ftz.f32 	%f287, %f285, %f286;
	mov.b32 	%r852, %f287;
	shfl.sync.down.b32 	%r853|%p87, %r852, %r841, %r842, %r844;
	mov.b32 	%f288, %r853;
	add.ftz.f32 	%f289, %f287, %f288;
	mov.b32 	%r854, %f289;
	mov.u32 	%r855, 1;
	shfl.sync.down.b32 	%r856|%p88, %r854, %r855, %r842, %r844;
	mov.b32 	%f290, %r856;
	add.ftz.f32 	%f74, %f289, %f290;
	add.s32 	%r39, %r5, 8;
	setp.ge.s32 	%p89, %r39, %r49;
	or.pred  	%p90, %p26, %p89;
	@%p90 bra 	$L__BB0_52;

	mad.lo.s32 	%r857, %r39, %r48, %r3;
	mul.wide.s32 	%rd144, %r857, 4;
	add.s64 	%rd145, %rd1, %rd144;
	st.global.f32 	[%rd145], %f74;

$L__BB0_52:
	mov.b32 	%r858, %f378;
	shfl.sync.down.b32 	%r863|%p92, %r858, %r843, %r842, %r844;
	mov.b32 	%f291, %r863;
	add.ftz.f32 	%f292, %f378, %f291;
	mov.b32 	%r864, %f292;
	shfl.sync.down.b32 	%r866|%p93, %r864, %r847, %r842, %r844;
	mov.b32 	%f293, %r866;
	add.ftz.f32 	%f294, %f292, %f293;
	mov.b32 	%r867, %f294;
	shfl.sync.down.b32 	%r869|%p94, %r867, %r850, %r842, %r844;
	mov.b32 	%f295, %r869;
	add.ftz.f32 	%f296, %f294, %f295;
	mov.b32 	%r870, %f296;
	shfl.sync.down.b32 	%r871|%p95, %r870, %r841, %r842, %r844;
	mov.b32 	%f297, %r871;
	add.ftz.f32 	%f298, %f296, %f297;
	mov.b32 	%r872, %f298;
	shfl.sync.down.b32 	%r874|%p96, %r872, %r855, %r842, %r844;
	mov.b32 	%f299, %r874;
	add.ftz.f32 	%f75, %f298, %f299;
	add.s32 	%r40, %r5, 9;
	setp.ge.s32 	%p97, %r40, %r49;
	or.pred  	%p98, %p26, %p97;
	@%p98 bra 	$L__BB0_54;

	mad.lo.s32 	%r875, %r40, %r48, %r3;
	mul.wide.s32 	%rd146, %r875, 4;
	add.s64 	%rd147, %rd1, %rd146;
	st.global.f32 	[%rd147], %f75;

$L__BB0_54:
	mov.b32 	%r876, %f379;
	mov.u32 	%r877, 2;
	mov.u32 	%r878, 31;
	mov.u32 	%r879, 16;
	mov.u32 	%r880, -1;
	shfl.sync.down.b32 	%r881|%p100, %r876, %r879, %r878, %r880;
	mov.b32 	%f300, %r881;
	add.ftz.f32 	%f301, %f379, %f300;
	mov.b32 	%r882, %f301;
	mov.u32 	%r883, 8;
	shfl.sync.down.b32 	%r884|%p101, %r882, %r883, %r878, %r880;
	mov.b32 	%f302, %r884;
	add.ftz.f32 	%f303, %f301, %f302;
	mov.b32 	%r885, %f303;
	mov.u32 	%r886, 4;
	shfl.sync.down.b32 	%r887|%p102, %r885, %r886, %r878, %r880;
	mov.b32 	%f304, %r887;
	add.ftz.f32 	%f305, %f303, %f304;
	mov.b32 	%r888, %f305;
	shfl.sync.down.b32 	%r889|%p103, %r888, %r877, %r878, %r880;
	mov.b32 	%f306, %r889;
	add.ftz.f32 	%f307, %f305, %f306;
	mov.b32 	%r890, %f307;
	mov.u32 	%r891, 1;
	shfl.sync.down.b32 	%r892|%p104, %r890, %r891, %r878, %r880;
	mov.b32 	%f308, %r892;
	add.ftz.f32 	%f76, %f307, %f308;
	add.s32 	%r41, %r5, 10;
	setp.ge.s32 	%p105, %r41, %r49;
	or.pred  	%p106, %p26, %p105;
	@%p106 bra 	$L__BB0_56;

	mad.lo.s32 	%r893, %r41, %r48, %r3;
	mul.wide.s32 	%rd148, %r893, 4;
	add.s64 	%rd149, %rd1, %rd148;
	st.global.f32 	[%rd149], %f76;

$L__BB0_56:
	mov.b32 	%r894, %f380;
	shfl.sync.down.b32 	%r899|%p108, %r894, %r879, %r878, %r880;
	mov.b32 	%f309, %r899;
	add.ftz.f32 	%f310, %f380, %f309;
	mov.b32 	%r900, %f310;
	shfl.sync.down.b32 	%r902|%p109, %r900, %r883, %r878, %r880;
	mov.b32 	%f311, %r902;
	add.ftz.f32 	%f312, %f310, %f311;
	mov.b32 	%r903, %f312;
	shfl.sync.down.b32 	%r905|%p110, %r903, %r886, %r878, %r880;
	mov.b32 	%f313, %r905;
	add.ftz.f32 	%f314, %f312, %f313;
	mov.b32 	%r906, %f314;
	shfl.sync.down.b32 	%r907|%p111, %r906, %r877, %r878, %r880;
	mov.b32 	%f315, %r907;
	add.ftz.f32 	%f316, %f314, %f315;
	mov.b32 	%r908, %f316;
	shfl.sync.down.b32 	%r910|%p112, %r908, %r891, %r878, %r880;
	mov.b32 	%f317, %r910;
	add.ftz.f32 	%f77, %f316, %f317;
	add.s32 	%r42, %r5, 11;
	setp.ge.s32 	%p113, %r42, %r49;
	or.pred  	%p114, %p26, %p113;
	@%p114 bra 	$L__BB0_58;

	mad.lo.s32 	%r911, %r42, %r48, %r3;
	mul.wide.s32 	%rd150, %r911, 4;
	add.s64 	%rd151, %rd1, %rd150;
	st.global.f32 	[%rd151], %f77;

$L__BB0_58:
	mov.b32 	%r912, %f381;
	mov.u32 	%r913, 2;
	mov.u32 	%r914, 31;
	mov.u32 	%r915, 16;
	mov.u32 	%r916, -1;
	shfl.sync.down.b32 	%r917|%p116, %r912, %r915, %r914, %r916;
	mov.b32 	%f318, %r917;
	add.ftz.f32 	%f319, %f381, %f318;
	mov.b32 	%r918, %f319;
	mov.u32 	%r919, 8;
	shfl.sync.down.b32 	%r920|%p117, %r918, %r919, %r914, %r916;
	mov.b32 	%f320, %r920;
	add.ftz.f32 	%f321, %f319, %f320;
	mov.b32 	%r921, %f321;
	mov.u32 	%r922, 4;
	shfl.sync.down.b32 	%r923|%p118, %r921, %r922, %r914, %r916;
	mov.b32 	%f322, %r923;
	add.ftz.f32 	%f323, %f321, %f322;
	mov.b32 	%r924, %f323;
	shfl.sync.down.b32 	%r925|%p119, %r924, %r913, %r914, %r916;
	mov.b32 	%f324, %r925;
	add.ftz.f32 	%f325, %f323, %f324;
	mov.b32 	%r926, %f325;
	mov.u32 	%r927, 1;
	shfl.sync.down.b32 	%r928|%p120, %r926, %r927, %r914, %r916;
	mov.b32 	%f326, %r928;
	add.ftz.f32 	%f78, %f325, %f326;
	add.s32 	%r43, %r5, 12;
	setp.ge.s32 	%p121, %r43, %r49;
	or.pred  	%p122, %p26, %p121;
	@%p122 bra 	$L__BB0_60;

	mad.lo.s32 	%r929, %r43, %r48, %r3;
	mul.wide.s32 	%rd152, %r929, 4;
	add.s64 	%rd153, %rd1, %rd152;
	st.global.f32 	[%rd153], %f78;

$L__BB0_60:
	mov.b32 	%r930, %f382;
	shfl.sync.down.b32 	%r935|%p124, %r930, %r915, %r914, %r916;
	mov.b32 	%f327, %r935;
	add.ftz.f32 	%f328, %f382, %f327;
	mov.b32 	%r936, %f328;
	shfl.sync.down.b32 	%r938|%p125, %r936, %r919, %r914, %r916;
	mov.b32 	%f329, %r938;
	add.ftz.f32 	%f330, %f328, %f329;
	mov.b32 	%r939, %f330;
	shfl.sync.down.b32 	%r941|%p126, %r939, %r922, %r914, %r916;
	mov.b32 	%f331, %r941;
	add.ftz.f32 	%f332, %f330, %f331;
	mov.b32 	%r942, %f332;
	shfl.sync.down.b32 	%r943|%p127, %r942, %r913, %r914, %r916;
	mov.b32 	%f333, %r943;
	add.ftz.f32 	%f334, %f332, %f333;
	mov.b32 	%r944, %f334;
	shfl.sync.down.b32 	%r946|%p128, %r944, %r927, %r914, %r916;
	mov.b32 	%f335, %r946;
	add.ftz.f32 	%f79, %f334, %f335;
	add.s32 	%r44, %r5, 13;
	setp.ge.s32 	%p129, %r44, %r49;
	or.pred  	%p130, %p26, %p129;
	@%p130 bra 	$L__BB0_62;

	mad.lo.s32 	%r947, %r44, %r48, %r3;
	mul.wide.s32 	%rd154, %r947, 4;
	add.s64 	%rd155, %rd1, %rd154;
	st.global.f32 	[%rd155], %f79;

$L__BB0_62:
	mov.b32 	%r948, %f383;
	mov.u32 	%r949, 2;
	mov.u32 	%r950, 31;
	mov.u32 	%r951, 16;
	mov.u32 	%r952, -1;
	shfl.sync.down.b32 	%r953|%p132, %r948, %r951, %r950, %r952;
	mov.b32 	%f336, %r953;
	add.ftz.f32 	%f337, %f383, %f336;
	mov.b32 	%r954, %f337;
	mov.u32 	%r955, 8;
	shfl.sync.down.b32 	%r956|%p133, %r954, %r955, %r950, %r952;
	mov.b32 	%f338, %r956;
	add.ftz.f32 	%f339, %f337, %f338;
	mov.b32 	%r957, %f339;
	mov.u32 	%r958, 4;
	shfl.sync.down.b32 	%r959|%p134, %r957, %r958, %r950, %r952;
	mov.b32 	%f340, %r959;
	add.ftz.f32 	%f341, %f339, %f340;
	mov.b32 	%r960, %f341;
	shfl.sync.down.b32 	%r961|%p135, %r960, %r949, %r950, %r952;
	mov.b32 	%f342, %r961;
	add.ftz.f32 	%f343, %f341, %f342;
	mov.b32 	%r962, %f343;
	mov.u32 	%r963, 1;
	shfl.sync.down.b32 	%r964|%p136, %r962, %r963, %r950, %r952;
	mov.b32 	%f344, %r964;
	add.ftz.f32 	%f80, %f343, %f344;
	add.s32 	%r45, %r5, 14;
	setp.ge.s32 	%p137, %r45, %r49;
	or.pred  	%p138, %p26, %p137;
	@%p138 bra 	$L__BB0_64;

	mad.lo.s32 	%r965, %r45, %r48, %r3;
	mul.wide.s32 	%rd156, %r965, 4;
	add.s64 	%rd157, %rd1, %rd156;
	st.global.f32 	[%rd157], %f80;

$L__BB0_64:
	mov.b32 	%r966, %f384;
	shfl.sync.down.b32 	%r971|%p140, %r966, %r951, %r950, %r952;
	mov.b32 	%f345, %r971;
	add.ftz.f32 	%f346, %f384, %f345;
	mov.b32 	%r972, %f346;
	shfl.sync.down.b32 	%r974|%p141, %r972, %r955, %r950, %r952;
	mov.b32 	%f347, %r974;
	add.ftz.f32 	%f348, %f346, %f347;
	mov.b32 	%r975, %f348;
	shfl.sync.down.b32 	%r977|%p142, %r975, %r958, %r950, %r952;
	mov.b32 	%f349, %r977;
	add.ftz.f32 	%f350, %f348, %f349;
	mov.b32 	%r978, %f350;
	shfl.sync.down.b32 	%r979|%p143, %r978, %r949, %r950, %r952;
	mov.b32 	%f351, %r979;
	add.ftz.f32 	%f352, %f350, %f351;
	mov.b32 	%r980, %f352;
	shfl.sync.down.b32 	%r982|%p144, %r980, %r963, %r950, %r952;
	mov.b32 	%f353, %r982;
	add.ftz.f32 	%f81, %f352, %f353;
	add.s32 	%r46, %r5, 15;
	setp.ge.s32 	%p145, %r46, %r49;
	or.pred  	%p146, %p26, %p145;
	@%p146 bra 	$L__BB0_66;

	mad.lo.s32 	%r983, %r46, %r48, %r3;
	mul.wide.s32 	%rd158, %r983, 4;
	add.s64 	%rd159, %rd1, %rd158;
	st.global.f32 	[%rd159], %f81;

$L__BB0_66:
	ret;

}

`
const GemmQ4CoalescedF32PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q4_coalesced_f32

.visible .entry gemm_q4_coalesced_f32(
	.param .u64 gemm_q4_coalesced_f32_param_0,
	.param .u64 gemm_q4_coalesced_f32_param_1,
	.param .u64 gemm_q4_coalesced_f32_param_2,
	.param .u64 gemm_q4_coalesced_f32_param_3,
	.param .u64 gemm_q4_coalesced_f32_param_4,
	.param .u32 gemm_q4_coalesced_f32_param_5,
	.param .u32 gemm_q4_coalesced_f32_param_6,
	.param .u32 gemm_q4_coalesced_f32_param_7
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<49>;
	.reg .f32 	%f<179>;
	.reg .b32 	%r<43>;
	.reg .b64 	%rd<34>;


	ld.param.u64 	%rd13, [gemm_q4_coalesced_f32_param_0];
	ld.param.u64 	%rd14, [gemm_q4_coalesced_f32_param_1];
	ld.param.u64 	%rd15, [gemm_q4_coalesced_f32_param_2];
	ld.param.u64 	%rd16, [gemm_q4_coalesced_f32_param_3];
	ld.param.u64 	%rd17, [gemm_q4_coalesced_f32_param_4];
	ld.param.u32 	%r7, [gemm_q4_coalesced_f32_param_5];
	ld.param.u32 	%r8, [gemm_q4_coalesced_f32_param_6];
	ld.param.u32 	%r9, [gemm_q4_coalesced_f32_param_7];
	mov.u32 	%r10, %tid.x;
	shr.u32 	%r11, %r10, 5;
	and.b32  	%r1, %r10, 31;
	mov.u32 	%r12, %ctaid.x;
	shl.b32 	%r13, %r12, 2;
	add.s32 	%r2, %r13, %r11;
	setp.ge.s32 	%p1, %r2, %r8;
	mov.u32 	%r3, %ctaid.y;
	setp.ge.s32 	%p2, %r3, %r9;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_6;

	shr.s32 	%r14, %r7, 31;
	shr.u32 	%r15, %r14, 27;
	add.s32 	%r16, %r7, %r15;
	shr.s32 	%r4, %r16, 5;
	setp.ge.s32 	%p4, %r1, %r4;
	mov.f32 	%f178, 0f00000000;
	@%p4 bra 	$L__BB0_4;

	mul.lo.s32 	%r17, %r4, %r2;
	shl.b32 	%r18, %r17, 4;
	shl.b32 	%r19, %r1, 4;
	add.s32 	%r20, %r18, %r19;
	cvt.s64.s32 	%rd18, %r20;
	cvta.to.global.u64 	%rd19, %rd14;
	add.s64 	%rd20, %rd19, %rd18;
	add.s64 	%rd33, %rd20, 7;
	add.s32 	%r21, %r17, %r1;
	cvta.to.global.u64 	%rd21, %rd15;
	mul.wide.s32 	%rd22, %r21, 4;
	add.s64 	%rd32, %rd21, %rd22;
	cvta.to.global.u64 	%rd23, %rd16;
	add.s64 	%rd31, %rd23, %rd22;
	shl.b32 	%r22, %r1, 5;
	mad.lo.s32 	%r23, %r3, %r7, %r22;
	cvta.to.global.u64 	%rd24, %rd13;
	mul.wide.s32 	%rd25, %r23, 4;
	add.s64 	%rd26, %rd24, %rd25;
	add.s64 	%rd30, %rd26, 64;
	mov.f32 	%f178, 0f00000000;
	mov.u32 	%r42, %r1;

$L__BB0_3:
	ld.global.u8 	%rs1, [%rd33+-7];
	and.b16  	%rs2, %rs1, 15;
	cvt.rn.f32.u16 	%f7, %rs2;
	ld.global.f32 	%f8, [%rd32];
	mul.ftz.f32 	%f9, %f8, %f7;
	ld.global.f32 	%f10, [%rd31];
	sub.ftz.f32 	%f11, %f9, %f10;
	ld.global.f32 	%f12, [%rd30+-64];
	fma.rn.ftz.f32 	%f13, %f12, %f11, %f178;
	shr.u16 	%rs3, %rs1, 4;
	cvt.rn.f32.u16 	%f14, %rs3;
	mul.ftz.f32 	%f15, %f8, %f14;
	sub.ftz.f32 	%f16, %f15, %f10;
	ld.global.f32 	%f17, [%rd30+-60];
	fma.rn.ftz.f32 	%f18, %f17, %f16, %f13;
	ld.global.u8 	%rs4, [%rd33+-6];
	and.b16  	%rs5, %rs4, 15;
	cvt.rn.f32.u16 	%f19, %rs5;
	mul.ftz.f32 	%f20, %f8, %f19;
	sub.ftz.f32 	%f21, %f20, %f10;
	ld.global.f32 	%f22, [%rd30+-56];
	fma.rn.ftz.f32 	%f23, %f22, %f21, %f18;
	shr.u16 	%rs6, %rs4, 4;
	cvt.rn.f32.u16 	%f24, %rs6;
	mul.ftz.f32 	%f25, %f8, %f24;
	sub.ftz.f32 	%f26, %f25, %f10;
	ld.global.f32 	%f27, [%rd30+-52];
	fma.rn.ftz.f32 	%f28, %f27, %f26, %f23;
	ld.global.u8 	%rs7, [%rd33+-5];
	and.b16  	%rs8, %rs7, 15;
	cvt.rn.f32.u16 	%f29, %rs8;
	mul.ftz.f32 	%f30, %f8, %f29;
	sub.ftz.f32 	%f31, %f30, %f10;
	ld.global.f32 	%f32, [%rd30+-48];
	fma.rn.ftz.f32 	%f33, %f32, %f31, %f28;
	shr.u16 	%rs9, %rs7, 4;
	cvt.rn.f32.u16 	%f34, %rs9;
	mul.ftz.f32 	%f35, %f8, %f34;
	sub.ftz.f32 	%f36, %f35, %f10;
	ld.global.f32 	%f37, [%rd30+-44];
	fma.rn.ftz.f32 	%f38, %f37, %f36, %f33;
	ld.global.u8 	%rs10, [%rd33+-4];
	and.b16  	%rs11, %rs10, 15;
	cvt.rn.f32.u16 	%f39, %rs11;
	mul.ftz.f32 	%f40, %f8, %f39;
	sub.ftz.f32 	%f41, %f40, %f10;
	ld.global.f32 	%f42, [%rd30+-40];
	fma.rn.ftz.f32 	%f43, %f42, %f41, %f38;
	shr.u16 	%rs12, %rs10, 4;
	cvt.rn.f32.u16 	%f44, %rs12;
	mul.ftz.f32 	%f45, %f8, %f44;
	sub.ftz.f32 	%f46, %f45, %f10;
	ld.global.f32 	%f47, [%rd30+-36];
	fma.rn.ftz.f32 	%f48, %f47, %f46, %f43;
	ld.global.u8 	%rs13, [%rd33+-3];
	and.b16  	%rs14, %rs13, 15;
	cvt.rn.f32.u16 	%f49, %rs14;
	mul.ftz.f32 	%f50, %f8, %f49;
	sub.ftz.f32 	%f51, %f50, %f10;
	ld.global.f32 	%f52, [%rd30+-32];
	fma.rn.ftz.f32 	%f53, %f52, %f51, %f48;
	shr.u16 	%rs15, %rs13, 4;
	cvt.rn.f32.u16 	%f54, %rs15;
	mul.ftz.f32 	%f55, %f8, %f54;
	sub.ftz.f32 	%f56, %f55, %f10;
	ld.global.f32 	%f57, [%rd30+-28];
	fma.rn.ftz.f32 	%f58, %f57, %f56, %f53;
	ld.global.u8 	%rs16, [%rd33+-2];
	and.b16  	%rs17, %rs16, 15;
	cvt.rn.f32.u16 	%f59, %rs17;
	mul.ftz.f32 	%f60, %f8, %f59;
	sub.ftz.f32 	%f61, %f60, %f10;
	ld.global.f32 	%f62, [%rd30+-24];
	fma.rn.ftz.f32 	%f63, %f62, %f61, %f58;
	shr.u16 	%rs18, %rs16, 4;
	cvt.rn.f32.u16 	%f64, %rs18;
	mul.ftz.f32 	%f65, %f8, %f64;
	sub.ftz.f32 	%f66, %f65, %f10;
	ld.global.f32 	%f67, [%rd30+-20];
	fma.rn.ftz.f32 	%f68, %f67, %f66, %f63;
	ld.global.u8 	%rs19, [%rd33+-1];
	and.b16  	%rs20, %rs19, 15;
	cvt.rn.f32.u16 	%f69, %rs20;
	mul.ftz.f32 	%f70, %f8, %f69;
	sub.ftz.f32 	%f71, %f70, %f10;
	ld.global.f32 	%f72, [%rd30+-16];
	fma.rn.ftz.f32 	%f73, %f72, %f71, %f68;
	shr.u16 	%rs21, %rs19, 4;
	cvt.rn.f32.u16 	%f74, %rs21;
	mul.ftz.f32 	%f75, %f8, %f74;
	sub.ftz.f32 	%f76, %f75, %f10;
	ld.global.f32 	%f77, [%rd30+-12];
	fma.rn.ftz.f32 	%f78, %f77, %f76, %f73;
	ld.global.u8 	%rs22, [%rd33];
	and.b16  	%rs23, %rs22, 15;
	cvt.rn.f32.u16 	%f79, %rs23;
	mul.ftz.f32 	%f80, %f8, %f79;
	sub.ftz.f32 	%f81, %f80, %f10;
	ld.global.f32 	%f82, [%rd30+-8];
	fma.rn.ftz.f32 	%f83, %f82, %f81, %f78;
	shr.u16 	%rs24, %rs22, 4;
	cvt.rn.f32.u16 	%f84, %rs24;
	mul.ftz.f32 	%f85, %f8, %f84;
	sub.ftz.f32 	%f86, %f85, %f10;
	ld.global.f32 	%f87, [%rd30+-4];
	fma.rn.ftz.f32 	%f88, %f87, %f86, %f83;
	ld.global.u8 	%rs25, [%rd33+1];
	and.b16  	%rs26, %rs25, 15;
	cvt.rn.f32.u16 	%f89, %rs26;
	mul.ftz.f32 	%f90, %f8, %f89;
	sub.ftz.f32 	%f91, %f90, %f10;
	ld.global.f32 	%f92, [%rd30];
	fma.rn.ftz.f32 	%f93, %f92, %f91, %f88;
	shr.u16 	%rs27, %rs25, 4;
	cvt.rn.f32.u16 	%f94, %rs27;
	mul.ftz.f32 	%f95, %f8, %f94;
	sub.ftz.f32 	%f96, %f95, %f10;
	ld.global.f32 	%f97, [%rd30+4];
	fma.rn.ftz.f32 	%f98, %f97, %f96, %f93;
	ld.global.u8 	%rs28, [%rd33+2];
	and.b16  	%rs29, %rs28, 15;
	cvt.rn.f32.u16 	%f99, %rs29;
	mul.ftz.f32 	%f100, %f8, %f99;
	sub.ftz.f32 	%f101, %f100, %f10;
	ld.global.f32 	%f102, [%rd30+8];
	fma.rn.ftz.f32 	%f103, %f102, %f101, %f98;
	shr.u16 	%rs30, %rs28, 4;
	cvt.rn.f32.u16 	%f104, %rs30;
	mul.ftz.f32 	%f105, %f8, %f104;
	sub.ftz.f32 	%f106, %f105, %f10;
	ld.global.f32 	%f107, [%rd30+12];
	fma.rn.ftz.f32 	%f108, %f107, %f106, %f103;
	ld.global.u8 	%rs31, [%rd33+3];
	and.b16  	%rs32, %rs31, 15;
	cvt.rn.f32.u16 	%f109, %rs32;
	mul.ftz.f32 	%f110, %f8, %f109;
	sub.ftz.f32 	%f111, %f110, %f10;
	ld.global.f32 	%f112, [%rd30+16];
	fma.rn.ftz.f32 	%f113, %f112, %f111, %f108;
	shr.u16 	%rs33, %rs31, 4;
	cvt.rn.f32.u16 	%f114, %rs33;
	mul.ftz.f32 	%f115, %f8, %f114;
	sub.ftz.f32 	%f116, %f115, %f10;
	ld.global.f32 	%f117, [%rd30+20];
	fma.rn.ftz.f32 	%f118, %f117, %f116, %f113;
	ld.global.u8 	%rs34, [%rd33+4];
	and.b16  	%rs35, %rs34, 15;
	cvt.rn.f32.u16 	%f119, %rs35;
	mul.ftz.f32 	%f120, %f8, %f119;
	sub.ftz.f32 	%f121, %f120, %f10;
	ld.global.f32 	%f122, [%rd30+24];
	fma.rn.ftz.f32 	%f123, %f122, %f121, %f118;
	shr.u16 	%rs36, %rs34, 4;
	cvt.rn.f32.u16 	%f124, %rs36;
	mul.ftz.f32 	%f125, %f8, %f124;
	sub.ftz.f32 	%f126, %f125, %f10;
	ld.global.f32 	%f127, [%rd30+28];
	fma.rn.ftz.f32 	%f128, %f127, %f126, %f123;
	ld.global.u8 	%rs37, [%rd33+5];
	and.b16  	%rs38, %rs37, 15;
	cvt.rn.f32.u16 	%f129, %rs38;
	mul.ftz.f32 	%f130, %f8, %f129;
	sub.ftz.f32 	%f131, %f130, %f10;
	ld.global.f32 	%f132, [%rd30+32];
	fma.rn.ftz.f32 	%f133, %f132, %f131, %f128;
	shr.u16 	%rs39, %rs37, 4;
	cvt.rn.f32.u16 	%f134, %rs39;
	mul.ftz.f32 	%f135, %f8, %f134;
	sub.ftz.f32 	%f136, %f135, %f10;
	ld.global.f32 	%f137, [%rd30+36];
	fma.rn.ftz.f32 	%f138, %f137, %f136, %f133;
	ld.global.u8 	%rs40, [%rd33+6];
	and.b16  	%rs41, %rs40, 15;
	cvt.rn.f32.u16 	%f139, %rs41;
	mul.ftz.f32 	%f140, %f8, %f139;
	sub.ftz.f32 	%f141, %f140, %f10;
	ld.global.f32 	%f142, [%rd30+40];
	fma.rn.ftz.f32 	%f143, %f142, %f141, %f138;
	shr.u16 	%rs42, %rs40, 4;
	cvt.rn.f32.u16 	%f144, %rs42;
	mul.ftz.f32 	%f145, %f8, %f144;
	sub.ftz.f32 	%f146, %f145, %f10;
	ld.global.f32 	%f147, [%rd30+44];
	fma.rn.ftz.f32 	%f148, %f147, %f146, %f143;
	ld.global.u8 	%rs43, [%rd33+7];
	and.b16  	%rs44, %rs43, 15;
	cvt.rn.f32.u16 	%f149, %rs44;
	mul.ftz.f32 	%f150, %f8, %f149;
	sub.ftz.f32 	%f151, %f150, %f10;
	ld.global.f32 	%f152, [%rd30+48];
	fma.rn.ftz.f32 	%f153, %f152, %f151, %f148;
	shr.u16 	%rs45, %rs43, 4;
	cvt.rn.f32.u16 	%f154, %rs45;
	mul.ftz.f32 	%f155, %f8, %f154;
	sub.ftz.f32 	%f156, %f155, %f10;
	ld.global.f32 	%f157, [%rd30+52];
	fma.rn.ftz.f32 	%f158, %f157, %f156, %f153;
	ld.global.u8 	%rs46, [%rd33+8];
	and.b16  	%rs47, %rs46, 15;
	cvt.rn.f32.u16 	%f159, %rs47;
	mul.ftz.f32 	%f160, %f8, %f159;
	sub.ftz.f32 	%f161, %f160, %f10;
	ld.global.f32 	%f162, [%rd30+56];
	fma.rn.ftz.f32 	%f163, %f162, %f161, %f158;
	shr.u16 	%rs48, %rs46, 4;
	cvt.rn.f32.u16 	%f164, %rs48;
	mul.ftz.f32 	%f165, %f8, %f164;
	sub.ftz.f32 	%f166, %f165, %f10;
	ld.global.f32 	%f167, [%rd30+60];
	fma.rn.ftz.f32 	%f178, %f167, %f166, %f163;
	add.s64 	%rd33, %rd33, 512;
	add.s64 	%rd32, %rd32, 128;
	add.s64 	%rd31, %rd31, 128;
	add.s64 	%rd30, %rd30, 4096;
	add.s32 	%r42, %r42, 32;
	setp.lt.s32 	%p5, %r42, %r4;
	@%p5 bra 	$L__BB0_3;

$L__BB0_4:
	mov.b32 	%r24, %f178;
	mov.u32 	%r25, 2;
	mov.u32 	%r26, 31;
	mov.u32 	%r27, 16;
	mov.u32 	%r28, -1;
	shfl.sync.down.b32 	%r29|%p6, %r24, %r27, %r26, %r28;
	mov.b32 	%f168, %r29;
	add.ftz.f32 	%f169, %f178, %f168;
	mov.b32 	%r30, %f169;
	mov.u32 	%r31, 8;
	shfl.sync.down.b32 	%r32|%p7, %r30, %r31, %r26, %r28;
	mov.b32 	%f170, %r32;
	add.ftz.f32 	%f171, %f169, %f170;
	mov.b32 	%r33, %f171;
	mov.u32 	%r34, 4;
	shfl.sync.down.b32 	%r35|%p8, %r33, %r34, %r26, %r28;
	mov.b32 	%f172, %r35;
	add.ftz.f32 	%f173, %f171, %f172;
	mov.b32 	%r36, %f173;
	shfl.sync.down.b32 	%r37|%p9, %r36, %r25, %r26, %r28;
	mov.b32 	%f174, %r37;
	add.ftz.f32 	%f175, %f173, %f174;
	mov.b32 	%r38, %f175;
	mov.u32 	%r39, 1;
	shfl.sync.down.b32 	%r40|%p10, %r38, %r39, %r26, %r28;
	mov.b32 	%f176, %r40;
	add.ftz.f32 	%f4, %f175, %f176;
	setp.ne.s32 	%p11, %r1, 0;
	@%p11 bra 	$L__BB0_6;

	mad.lo.s32 	%r41, %r3, %r8, %r2;
	cvta.to.global.u64 	%rd27, %rd17;
	mul.wide.s32 	%rd28, %r41, 4;
	add.s64 	%rd29, %rd27, %rd28;
	st.global.f32 	[%rd29], %f4;

$L__BB0_6:
	ret;

}

`
