package q4

// GemmQ4PairMMQJ16PTX is generated at development time and embedded.
const GemmQ4PairMMQJ16PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q4_pair_mmq_j16
// _ZZ20gemm_q4_pair_mmq_j16E1X has been demoted

.visible .entry gemm_q4_pair_mmq_j16(
	.param .u64 gemm_q4_pair_mmq_j16_param_0,
	.param .u64 gemm_q4_pair_mmq_j16_param_1,
	.param .u64 gemm_q4_pair_mmq_j16_param_2,
	.param .u64 gemm_q4_pair_mmq_j16_param_3,
	.param .u64 gemm_q4_pair_mmq_j16_param_4,
	.param .u64 gemm_q4_pair_mmq_j16_param_5,
	.param .u64 gemm_q4_pair_mmq_j16_param_6,
	.param .u64 gemm_q4_pair_mmq_j16_param_7,
	.param .u64 gemm_q4_pair_mmq_j16_param_8,
	.param .u64 gemm_q4_pair_mmq_j16_param_9,
	.param .u64 gemm_q4_pair_mmq_j16_param_10,
	.param .u32 gemm_q4_pair_mmq_j16_param_11,
	.param .u32 gemm_q4_pair_mmq_j16_param_12,
	.param .u32 gemm_q4_pair_mmq_j16_param_13
)
{
	.reg .pred 	%p<196>;
	.reg .f32 	%f<705>;
	.reg .b32 	%r<1688>;
	.reg .b64 	%rd<141>;
	// demoted variable
	.shared .align 1 .b8 _ZZ20gemm_q4_pair_mmq_j16E1X[4096];

	ld.param.u64 	%rd12, [gemm_q4_pair_mmq_j16_param_0];
	ld.param.u64 	%rd13, [gemm_q4_pair_mmq_j16_param_1];
	ld.param.u64 	%rd14, [gemm_q4_pair_mmq_j16_param_2];
	ld.param.u64 	%rd6, [gemm_q4_pair_mmq_j16_param_3];
	ld.param.u64 	%rd7, [gemm_q4_pair_mmq_j16_param_4];
	ld.param.u64 	%rd8, [gemm_q4_pair_mmq_j16_param_5];
	ld.param.u64 	%rd9, [gemm_q4_pair_mmq_j16_param_6];
	ld.param.u64 	%rd10, [gemm_q4_pair_mmq_j16_param_7];
	ld.param.u64 	%rd11, [gemm_q4_pair_mmq_j16_param_8];
	ld.param.u64 	%rd15, [gemm_q4_pair_mmq_j16_param_9];
	ld.param.u64 	%rd16, [gemm_q4_pair_mmq_j16_param_10];
	ld.param.u32 	%r112, [gemm_q4_pair_mmq_j16_param_11];
	ld.param.u32 	%r113, [gemm_q4_pair_mmq_j16_param_12];
	ld.param.u32 	%r114, [gemm_q4_pair_mmq_j16_param_13];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd13;
	cvta.to.global.u64 	%rd3, %rd14;
	cvta.to.global.u64 	%rd4, %rd16;
	cvta.to.global.u64 	%rd5, %rd15;
	mov.u32 	%r1, %tid.x;
	shr.s32 	%r115, %r1, 5;
	and.b32  	%r116, %r1, 31;
	shr.u32 	%r117, %r116, 3;
	and.b32  	%r2, %r1, 7;
	mov.u32 	%r118, %ctaid.x;
	shl.b32 	%r119, %r118, 5;
	shl.b32 	%r120, %r115, 2;
	add.s32 	%r121, %r120, %r119;
	or.b32  	%r3, %r121, %r117;
	mov.u32 	%r122, %ctaid.y;
	shl.b32 	%r4, %r122, 4;
	shr.s32 	%r123, %r112, 31;
	shr.u32 	%r124, %r123, 27;
	add.s32 	%r125, %r112, %r124;
	shr.s32 	%r5, %r125, 5;
	setp.lt.s32 	%p2, %r112, 32;
	mov.f32 	%f579, 0f00000000;
	mov.f32 	%f642, %f579;
	mov.f32 	%f643, %f579;
	mov.f32 	%f644, %f579;
	mov.f32 	%f645, %f579;
	mov.f32 	%f646, %f579;
	mov.f32 	%f647, %f579;
	mov.f32 	%f648, %f579;
	mov.f32 	%f649, %f579;
	mov.f32 	%f650, %f579;
	mov.f32 	%f651, %f579;
	mov.f32 	%f652, %f579;
	mov.f32 	%f653, %f579;
	mov.f32 	%f654, %f579;
	mov.f32 	%f655, %f579;
	mov.f32 	%f656, %f579;
	mov.f32 	%f657, %f579;
	mov.f32 	%f658, %f579;
	mov.f32 	%f659, %f579;
	mov.f32 	%f660, %f579;
	mov.f32 	%f661, %f579;
	mov.f32 	%f662, %f579;
	mov.f32 	%f663, %f579;
	mov.f32 	%f664, %f579;
	mov.f32 	%f665, %f579;
	mov.f32 	%f666, %f579;
	mov.f32 	%f667, %f579;
	mov.f32 	%f668, %f579;
	mov.f32 	%f669, %f579;
	mov.f32 	%f670, %f579;
	mov.f32 	%f671, %f579;
	mov.f32 	%f610, %f579;
	@%p2 bra 	$L__BB0_58;

	mul.lo.s32 	%r6, %r5, %r3;
	max.s32 	%r127, %r1, 3840;
	add.s32 	%r128, %r127, 255;
	sub.s32 	%r7, %r128, %r1;
	shr.u32 	%r129, %r7, 8;
	add.s32 	%r130, %r129, 1;
	and.b32  	%r8, %r130, 3;
	shr.s32 	%r131, %r1, 8;
	add.s32 	%r9, %r131, %r4;
	mul.lo.s32 	%r10, %r9, %r112;
	and.b32  	%r11, %r1, 255;
	and.b32  	%r132, %r1, -256;
	mov.u32 	%r133, _ZZ20gemm_q4_pair_mmq_j16E1X;
	add.s32 	%r134, %r133, %r132;
	add.s32 	%r12, %r134, %r11;
	shl.b32 	%r135, %r2, 5;
	add.s32 	%r13, %r133, %r135;
	add.s32 	%r14, %r1, 256;
	shr.s32 	%r136, %r14, 8;
	and.b32  	%r137, %r14, 255;
	add.s32 	%r15, %r136, %r4;
	mad.lo.s32 	%r16, %r4, %r5, %r5;
	mul.lo.s32 	%r17, %r15, %r112;
	and.b32  	%r138, %r14, -256;
	add.s32 	%r139, %r133, %r138;
	add.s32 	%r18, %r139, %r137;
	add.s32 	%r19, %r16, %r5;
	add.s32 	%r20, %r1, 512;
	shr.s32 	%r140, %r20, 8;
	and.b32  	%r141, %r20, 255;
	add.s32 	%r21, %r140, %r4;
	add.s32 	%r22, %r19, %r5;
	mul.lo.s32 	%r23, %r21, %r112;
	and.b32  	%r142, %r20, -256;
	add.s32 	%r143, %r133, %r142;
	add.s32 	%r24, %r143, %r141;
	add.s32 	%r25, %r1, 768;
	add.s32 	%r26, %r22, %r5;
	add.s32 	%r27, %r26, %r5;
	add.s32 	%r28, %r27, %r5;
	add.s32 	%r29, %r4, 7;
	add.s32 	%r30, %r28, %r5;
	add.s32 	%r31, %r4, 8;
	add.s32 	%r32, %r30, %r5;
	add.s32 	%r33, %r4, 9;
	add.s32 	%r34, %r32, %r5;
	add.s32 	%r35, %r4, 10;
	add.s32 	%r36, %r34, %r5;
	add.s32 	%r37, %r4, 11;
	add.s32 	%r38, %r36, %r5;
	add.s32 	%r39, %r4, 12;
	add.s32 	%r40, %r38, %r5;
	add.s32 	%r41, %r4, 13;
	add.s32 	%r42, %r40, %r5;
	add.s32 	%r43, %r4, 14;
	add.s32 	%r44, %r42, %r5;
	add.s32 	%r45, %r4, 15;
	add.s32 	%r46, %r44, %r5;
	add.s32 	%r144, %r5, 7;
	shr.s32 	%r145, %r144, 31;
	shr.u32 	%r146, %r145, 29;
	add.s32 	%r147, %r144, %r146;
	shr.s32 	%r47, %r147, 3;
	mov.u32 	%r1678, 0;
	mov.f32 	%f579, 0f00000000;
	cvta.to.global.u64 	%rd32, %rd6;
	cvta.to.global.u64 	%rd34, %rd9;
	cvta.to.global.u64 	%rd36, %rd7;
	cvta.to.global.u64 	%rd39, %rd8;
	cvta.to.global.u64 	%rd41, %rd10;
	cvta.to.global.u64 	%rd43, %rd11;

$L__BB0_2:
	setp.gt.s32 	%p3, %r1, 4095;
	@%p3 bra 	$L__BB0_24;

	setp.eq.s32 	%p4, %r8, 0;
	shl.b32 	%r49, %r1678, 8;
	mov.u32 	%r1682, %r1;
	@%p4 bra 	$L__BB0_13;

	setp.ge.s32 	%p5, %r9, %r114;
	add.s32 	%r50, %r11, %r49;
	setp.ge.s32 	%p6, %r50, %r112;
	mov.u32 	%r1679, 0;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB0_6;

	add.s32 	%r149, %r50, %r10;
	cvt.s64.s32 	%rd17, %r149;
	add.s64 	%rd18, %rd1, %rd17;
	ld.global.s8 	%r1679, [%rd18];

$L__BB0_6:
	st.shared.u8 	[%r12], %r1679;
	setp.eq.s32 	%p8, %r8, 1;
	mov.u32 	%r1682, %r14;
	@%p8 bra 	$L__BB0_13;

	setp.ge.s32 	%p10, %r15, %r114;
	mov.u32 	%r1680, 0;
	or.pred  	%p11, %p10, %p6;
	@%p11 bra 	$L__BB0_9;

	add.s32 	%r151, %r50, %r17;
	cvt.s64.s32 	%rd19, %r151;
	add.s64 	%rd20, %rd1, %rd19;
	ld.global.s8 	%r1680, [%rd20];

$L__BB0_9:
	st.shared.u8 	[%r18], %r1680;
	setp.eq.s32 	%p12, %r8, 2;
	mov.u32 	%r1682, %r20;
	@%p12 bra 	$L__BB0_13;

	setp.ge.s32 	%p14, %r21, %r114;
	mov.u32 	%r1681, 0;
	or.pred  	%p15, %p14, %p6;
	@%p15 bra 	$L__BB0_12;

	add.s32 	%r153, %r50, %r23;
	cvt.s64.s32 	%rd21, %r153;
	add.s64 	%rd22, %rd1, %rd21;
	ld.global.s8 	%r1681, [%rd22];

$L__BB0_12:
	st.shared.u8 	[%r24], %r1681;
	mov.u32 	%r1682, %r25;

$L__BB0_13:
	setp.lt.u32 	%p16, %r7, 768;
	@%p16 bra 	$L__BB0_24;

	and.b32  	%r58, %r1682, 255;
	add.s32 	%r59, %r58, %r49;

$L__BB0_15:
	shr.s32 	%r61, %r1682, 8;
	add.s32 	%r62, %r61, %r4;
	setp.ge.s32 	%p17, %r62, %r114;
	setp.ge.s32 	%p18, %r59, %r112;
	mov.u32 	%r1685, 0;
	or.pred  	%p19, %p17, %p18;
	mov.u32 	%r1684, %r1685;
	@%p19 bra 	$L__BB0_17;

	mad.lo.s32 	%r155, %r62, %r112, %r59;
	cvt.s64.s32 	%rd23, %r155;
	add.s64 	%rd24, %rd1, %rd23;
	ld.global.s8 	%r1684, [%rd24];

$L__BB0_17:
	shl.b32 	%r157, %r61, 8;
	add.s32 	%r159, %r133, %r157;
	add.s32 	%r160, %r159, %r58;
	st.shared.u8 	[%r160], %r1684;
	add.s32 	%r161, %r1682, 256;
	shr.s32 	%r65, %r161, 8;
	add.s32 	%r66, %r65, %r4;
	setp.ge.s32 	%p20, %r66, %r114;
	or.pred  	%p22, %p20, %p18;
	@%p22 bra 	$L__BB0_19;

	mad.lo.s32 	%r162, %r66, %r112, %r59;
	cvt.s64.s32 	%rd25, %r162;
	add.s64 	%rd26, %rd1, %rd25;
	ld.global.s8 	%r1685, [%rd26];

$L__BB0_19:
	shl.b32 	%r164, %r65, 8;
	add.s32 	%r166, %r133, %r164;
	add.s32 	%r167, %r166, %r58;
	mov.u32 	%r1687, 0;
	st.shared.u8 	[%r167], %r1685;
	add.s32 	%r168, %r1682, 512;
	shr.s32 	%r69, %r168, 8;
	add.s32 	%r70, %r69, %r4;
	setp.ge.s32 	%p23, %r70, %r114;
	or.pred  	%p25, %p23, %p18;
	mov.u32 	%r1686, %r1687;
	@%p25 bra 	$L__BB0_21;

	mad.lo.s32 	%r169, %r70, %r112, %r59;
	cvt.s64.s32 	%rd27, %r169;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.s8 	%r1686, [%rd28];

$L__BB0_21:
	shl.b32 	%r171, %r69, 8;
	add.s32 	%r173, %r133, %r171;
	add.s32 	%r174, %r173, %r58;
	st.shared.u8 	[%r174], %r1686;
	add.s32 	%r175, %r1682, 768;
	shr.s32 	%r73, %r175, 8;
	add.s32 	%r74, %r73, %r4;
	setp.ge.s32 	%p26, %r74, %r114;
	or.pred  	%p28, %p26, %p18;
	@%p28 bra 	$L__BB0_23;

	mad.lo.s32 	%r176, %r74, %r112, %r59;
	cvt.s64.s32 	%rd29, %r176;
	add.s64 	%rd30, %rd1, %rd29;
	ld.global.s8 	%r1687, [%rd30];

$L__BB0_23:
	shl.b32 	%r177, %r73, 8;
	add.s32 	%r179, %r133, %r177;
	add.s32 	%r180, %r179, %r58;
	st.shared.u8 	[%r180], %r1687;
	add.s32 	%r77, %r1682, 1024;
	setp.lt.s32 	%p29, %r1682, 3072;
	mov.u32 	%r1682, %r77;
	@%p29 bra 	$L__BB0_15;

$L__BB0_24:
	setp.ge.s32 	%p30, %r3, %r113;
	bar.sync 	0;
	shl.b32 	%r181, %r1678, 3;
	or.b32  	%r78, %r181, %r2;
	setp.ge.s32 	%p31, %r78, %r5;
	or.pred  	%p32, %p30, %p31;
	@%p32 bra 	$L__BB0_57;

	setp.ge.s32 	%p33, %r4, %r114;
	add.s32 	%r182, %r78, %r6;
	shl.b32 	%r183, %r182, 4;
	cvt.s64.s32 	%rd31, %r183;
	add.s64 	%rd33, %rd32, %rd31;
	add.s64 	%rd35, %rd34, %rd31;
	ld.global.u32 	%r184, [%rd33];
	and.b32  	%r185, %r184, 15;
	and.b32  	%r186, %r184, 240;
	bfi.b32 	%r187, %r186, %r185, 4, 28;
	shl.b32 	%r188, %r184, 8;
	and.b32  	%r189, %r188, 983040;
	or.b32  	%r190, %r187, %r189;
	shl.b32 	%r191, %r184, 12;
	and.b32  	%r192, %r191, 251658240;
	or.b32  	%r79, %r190, %r192;
	shr.u32 	%r193, %r184, 16;
	and.b32  	%r194, %r193, 15;
	and.b32  	%r195, %r193, 240;
	bfi.b32 	%r196, %r195, %r194, 4, 28;
	shr.u32 	%r197, %r184, 8;
	and.b32  	%r198, %r197, 983040;
	or.b32  	%r199, %r196, %r198;
	shr.u32 	%r200, %r184, 4;
	and.b32  	%r201, %r200, 251658240;
	or.b32  	%r80, %r199, %r201;
	ld.global.u32 	%r202, [%rd33+4];
	and.b32  	%r203, %r202, 15;
	and.b32  	%r204, %r202, 240;
	bfi.b32 	%r205, %r204, %r203, 4, 28;
	shl.b32 	%r206, %r202, 8;
	and.b32  	%r207, %r206, 983040;
	or.b32  	%r208, %r205, %r207;
	shl.b32 	%r209, %r202, 12;
	and.b32  	%r210, %r209, 251658240;
	or.b32  	%r81, %r208, %r210;
	shr.u32 	%r211, %r202, 16;
	and.b32  	%r212, %r211, 15;
	and.b32  	%r213, %r211, 240;
	bfi.b32 	%r214, %r213, %r212, 4, 28;
	shr.u32 	%r215, %r202, 8;
	and.b32  	%r216, %r215, 983040;
	or.b32  	%r217, %r214, %r216;
	shr.u32 	%r218, %r202, 4;
	and.b32  	%r219, %r218, 251658240;
	or.b32  	%r82, %r217, %r219;
	ld.global.u32 	%r220, [%rd33+8];
	and.b32  	%r221, %r220, 15;
	and.b32  	%r222, %r220, 240;
	bfi.b32 	%r223, %r222, %r221, 4, 28;
	shl.b32 	%r224, %r220, 8;
	and.b32  	%r225, %r224, 983040;
	or.b32  	%r226, %r223, %r225;
	shl.b32 	%r227, %r220, 12;
	and.b32  	%r228, %r227, 251658240;
	or.b32  	%r83, %r226, %r228;
	shr.u32 	%r229, %r220, 16;
	and.b32  	%r230, %r229, 15;
	and.b32  	%r231, %r229, 240;
	bfi.b32 	%r232, %r231, %r230, 4, 28;
	shr.u32 	%r233, %r220, 8;
	and.b32  	%r234, %r233, 983040;
	or.b32  	%r235, %r232, %r234;
	shr.u32 	%r236, %r220, 4;
	and.b32  	%r237, %r236, 251658240;
	or.b32  	%r84, %r235, %r237;
	ld.global.u32 	%r238, [%rd33+12];
	and.b32  	%r239, %r238, 15;
	and.b32  	%r240, %r238, 240;
	bfi.b32 	%r241, %r240, %r239, 4, 28;
	shl.b32 	%r242, %r238, 8;
	and.b32  	%r243, %r242, 983040;
	or.b32  	%r244, %r241, %r243;
	shl.b32 	%r245, %r238, 12;
	and.b32  	%r246, %r245, 251658240;
	or.b32  	%r85, %r244, %r246;
	shr.u32 	%r247, %r238, 16;
	and.b32  	%r248, %r247, 15;
	and.b32  	%r249, %r247, 240;
	bfi.b32 	%r250, %r249, %r248, 4, 28;
	shr.u32 	%r251, %r238, 8;
	and.b32  	%r252, %r251, 983040;
	or.b32  	%r253, %r250, %r252;
	shr.u32 	%r254, %r238, 4;
	and.b32  	%r255, %r254, 251658240;
	or.b32  	%r86, %r253, %r255;
	ld.global.u32 	%r256, [%rd35];
	and.b32  	%r257, %r256, 15;
	and.b32  	%r258, %r256, 240;
	bfi.b32 	%r259, %r258, %r257, 4, 28;
	shl.b32 	%r260, %r256, 8;
	and.b32  	%r261, %r260, 983040;
	or.b32  	%r262, %r259, %r261;
	shl.b32 	%r263, %r256, 12;
	and.b32  	%r264, %r263, 251658240;
	or.b32  	%r87, %r262, %r264;
	shr.u32 	%r265, %r256, 16;
	and.b32  	%r266, %r265, 15;
	and.b32  	%r267, %r265, 240;
	bfi.b32 	%r268, %r267, %r266, 4, 28;
	shr.u32 	%r269, %r256, 8;
	and.b32  	%r270, %r269, 983040;
	or.b32  	%r271, %r268, %r270;
	shr.u32 	%r272, %r256, 4;
	and.b32  	%r273, %r272, 251658240;
	or.b32  	%r88, %r271, %r273;
	ld.global.u32 	%r274, [%rd35+4];
	and.b32  	%r275, %r274, 15;
	and.b32  	%r276, %r274, 240;
	bfi.b32 	%r277, %r276, %r275, 4, 28;
	shl.b32 	%r278, %r274, 8;
	and.b32  	%r279, %r278, 983040;
	or.b32  	%r280, %r277, %r279;
	shl.b32 	%r281, %r274, 12;
	and.b32  	%r282, %r281, 251658240;
	or.b32  	%r89, %r280, %r282;
	shr.u32 	%r283, %r274, 16;
	and.b32  	%r284, %r283, 15;
	and.b32  	%r285, %r283, 240;
	bfi.b32 	%r286, %r285, %r284, 4, 28;
	shr.u32 	%r287, %r274, 8;
	and.b32  	%r288, %r287, 983040;
	or.b32  	%r289, %r286, %r288;
	shr.u32 	%r290, %r274, 4;
	and.b32  	%r291, %r290, 251658240;
	or.b32  	%r90, %r289, %r291;
	ld.global.u32 	%r292, [%rd35+8];
	and.b32  	%r293, %r292, 15;
	and.b32  	%r294, %r292, 240;
	bfi.b32 	%r295, %r294, %r293, 4, 28;
	shl.b32 	%r296, %r292, 8;
	and.b32  	%r297, %r296, 983040;
	or.b32  	%r298, %r295, %r297;
	shl.b32 	%r299, %r292, 12;
	and.b32  	%r300, %r299, 251658240;
	or.b32  	%r91, %r298, %r300;
	shr.u32 	%r301, %r292, 16;
	and.b32  	%r302, %r301, 15;
	and.b32  	%r303, %r301, 240;
	bfi.b32 	%r304, %r303, %r302, 4, 28;
	shr.u32 	%r305, %r292, 8;
	and.b32  	%r306, %r305, 983040;
	or.b32  	%r307, %r304, %r306;
	shr.u32 	%r308, %r292, 4;
	and.b32  	%r309, %r308, 251658240;
	or.b32  	%r92, %r307, %r309;
	ld.global.u32 	%r310, [%rd35+12];
	and.b32  	%r311, %r310, 15;
	and.b32  	%r312, %r310, 240;
	bfi.b32 	%r313, %r312, %r311, 4, 28;
	shl.b32 	%r314, %r310, 8;
	and.b32  	%r315, %r314, 983040;
	or.b32  	%r316, %r313, %r315;
	shl.b32 	%r317, %r310, 12;
	and.b32  	%r318, %r317, 251658240;
	or.b32  	%r93, %r316, %r318;
	shr.u32 	%r319, %r310, 16;
	and.b32  	%r320, %r319, 15;
	and.b32  	%r321, %r319, 240;
	bfi.b32 	%r322, %r321, %r320, 4, 28;
	shr.u32 	%r323, %r310, 8;
	and.b32  	%r324, %r323, 983040;
	or.b32  	%r325, %r322, %r324;
	shr.u32 	%r326, %r310, 4;
	and.b32  	%r327, %r326, 251658240;
	or.b32  	%r94, %r325, %r327;
	mul.wide.s32 	%rd37, %r182, 4;
	add.s64 	%rd38, %rd36, %rd37;
	ld.global.f32 	%f33, [%rd38];
	add.s64 	%rd40, %rd39, %rd37;
	ld.global.f32 	%f34, [%rd40];
	add.s64 	%rd42, %rd41, %rd37;
	ld.global.f32 	%f35, [%rd42];
	add.s64 	%rd44, %rd43, %rd37;
	ld.global.f32 	%f36, [%rd44];
	@%p33 bra 	$L__BB0_27;

	ld.shared.u32 	%r330, [%r13];
	mov.u32 	%r335, 0;
	// begin inline asm
	dp4a.s32.s32 %r328, %r79, %r330, %r335;
	// end inline asm
	ld.shared.u32 	%r334, [%r13];
	// begin inline asm
	dp4a.s32.s32 %r332, %r87, %r334, %r335;
	// end inline asm
	ld.shared.u32 	%r338, [%r13+4];
	// begin inline asm
	dp4a.s32.s32 %r336, %r80, %r338, %r328;
	// end inline asm
	ld.shared.u32 	%r342, [%r13+4];
	// begin inline asm
	dp4a.s32.s32 %r340, %r88, %r342, %r332;
	// end inline asm
	ld.shared.u32 	%r346, [%r13+8];
	// begin inline asm
	dp4a.s32.s32 %r344, %r81, %r346, %r336;
	// end inline asm
	ld.shared.u32 	%r350, [%r13+8];
	// begin inline asm
	dp4a.s32.s32 %r348, %r89, %r350, %r340;
	// end inline asm
	ld.shared.u32 	%r354, [%r13+12];
	// begin inline asm
	dp4a.s32.s32 %r352, %r82, %r354, %r344;
	// end inline asm
	ld.shared.u32 	%r358, [%r13+12];
	// begin inline asm
	dp4a.s32.s32 %r356, %r90, %r358, %r348;
	// end inline asm
	ld.shared.u32 	%r362, [%r13+16];
	// begin inline asm
	dp4a.s32.s32 %r360, %r83, %r362, %r352;
	// end inline asm
	ld.shared.u32 	%r366, [%r13+16];
	// begin inline asm
	dp4a.s32.s32 %r364, %r91, %r366, %r356;
	// end inline asm
	ld.shared.u32 	%r370, [%r13+20];
	// begin inline asm
	dp4a.s32.s32 %r368, %r84, %r370, %r360;
	// end inline asm
	ld.shared.u32 	%r374, [%r13+20];
	// begin inline asm
	dp4a.s32.s32 %r372, %r92, %r374, %r364;
	// end inline asm
	ld.shared.u32 	%r378, [%r13+24];
	// begin inline asm
	dp4a.s32.s32 %r376, %r85, %r378, %r368;
	// end inline asm
	ld.shared.u32 	%r382, [%r13+24];
	// begin inline asm
	dp4a.s32.s32 %r380, %r93, %r382, %r372;
	// end inline asm
	ld.shared.u32 	%r386, [%r13+28];
	// begin inline asm
	dp4a.s32.s32 %r384, %r86, %r386, %r376;
	// end inline asm
	ld.shared.u32 	%r390, [%r13+28];
	// begin inline asm
	dp4a.s32.s32 %r388, %r94, %r390, %r380;
	// end inline asm
	mad.lo.s32 	%r392, %r4, %r5, %r78;
	mul.wide.s32 	%rd45, %r392, 4;
	add.s64 	%rd46, %rd3, %rd45;
	add.s64 	%rd47, %rd2, %rd45;
	cvt.rn.f32.s32 	%f259, %r384;
	mul.ftz.f32 	%f260, %f33, %f259;
	ld.global.u32 	%r393, [%rd46];
	cvt.rn.f32.s32 	%f261, %r393;
	mul.ftz.f32 	%f262, %f34, %f261;
	sub.ftz.f32 	%f263, %f260, %f262;
	ld.global.f32 	%f264, [%rd47];
	fma.rn.ftz.f32 	%f657, %f264, %f263, %f657;
	cvt.rn.f32.s32 	%f265, %r388;
	mul.ftz.f32 	%f266, %f35, %f265;
	mul.ftz.f32 	%f267, %f36, %f261;
	sub.ftz.f32 	%f268, %f266, %f267;
	fma.rn.ftz.f32 	%f656, %f264, %f268, %f656;

$L__BB0_27:
	add.s32 	%r394, %r4, 1;
	setp.ge.s32 	%p34, %r394, %r114;
	@%p34 bra 	$L__BB0_29;

	ld.shared.u32 	%r397, [%r13+256];
	mov.u32 	%r402, 0;
	// begin inline asm
	dp4a.s32.s32 %r395, %r79, %r397, %r402;
	// end inline asm
	ld.shared.u32 	%r401, [%r13+256];
	// begin inline asm
	dp4a.s32.s32 %r399, %r87, %r401, %r402;
	// end inline asm
	ld.shared.u32 	%r405, [%r13+260];
	// begin inline asm
	dp4a.s32.s32 %r403, %r80, %r405, %r395;
	// end inline asm
	ld.shared.u32 	%r409, [%r13+260];
	// begin inline asm
	dp4a.s32.s32 %r407, %r88, %r409, %r399;
	// end inline asm
	ld.shared.u32 	%r413, [%r13+264];
	// begin inline asm
	dp4a.s32.s32 %r411, %r81, %r413, %r403;
	// end inline asm
	ld.shared.u32 	%r417, [%r13+264];
	// begin inline asm
	dp4a.s32.s32 %r415, %r89, %r417, %r407;
	// end inline asm
	ld.shared.u32 	%r421, [%r13+268];
	// begin inline asm
	dp4a.s32.s32 %r419, %r82, %r421, %r411;
	// end inline asm
	ld.shared.u32 	%r425, [%r13+268];
	// begin inline asm
	dp4a.s32.s32 %r423, %r90, %r425, %r415;
	// end inline asm
	ld.shared.u32 	%r429, [%r13+272];
	// begin inline asm
	dp4a.s32.s32 %r427, %r83, %r429, %r419;
	// end inline asm
	ld.shared.u32 	%r433, [%r13+272];
	// begin inline asm
	dp4a.s32.s32 %r431, %r91, %r433, %r423;
	// end inline asm
	ld.shared.u32 	%r437, [%r13+276];
	// begin inline asm
	dp4a.s32.s32 %r435, %r84, %r437, %r427;
	// end inline asm
	ld.shared.u32 	%r441, [%r13+276];
	// begin inline asm
	dp4a.s32.s32 %r439, %r92, %r441, %r431;
	// end inline asm
	ld.shared.u32 	%r445, [%r13+280];
	// begin inline asm
	dp4a.s32.s32 %r443, %r85, %r445, %r435;
	// end inline asm
	ld.shared.u32 	%r449, [%r13+280];
	// begin inline asm
	dp4a.s32.s32 %r447, %r93, %r449, %r439;
	// end inline asm
	ld.shared.u32 	%r453, [%r13+284];
	// begin inline asm
	dp4a.s32.s32 %r451, %r86, %r453, %r443;
	// end inline asm
	ld.shared.u32 	%r457, [%r13+284];
	// begin inline asm
	dp4a.s32.s32 %r455, %r94, %r457, %r447;
	// end inline asm
	add.s32 	%r459, %r16, %r78;
	mul.wide.s32 	%rd48, %r459, 4;
	add.s64 	%rd49, %rd3, %rd48;
	add.s64 	%rd50, %rd2, %rd48;
	cvt.rn.f32.s32 	%f269, %r451;
	mul.ftz.f32 	%f270, %f33, %f269;
	ld.global.u32 	%r460, [%rd49];
	cvt.rn.f32.s32 	%f271, %r460;
	mul.ftz.f32 	%f272, %f34, %f271;
	sub.ftz.f32 	%f273, %f270, %f272;
	ld.global.f32 	%f274, [%rd50];
	fma.rn.ftz.f32 	%f658, %f274, %f273, %f658;
	cvt.rn.f32.s32 	%f275, %r455;
	mul.ftz.f32 	%f276, %f35, %f275;
	mul.ftz.f32 	%f277, %f36, %f271;
	sub.ftz.f32 	%f278, %f276, %f277;
	fma.rn.ftz.f32 	%f655, %f274, %f278, %f655;

$L__BB0_29:
	add.s32 	%r461, %r4, 2;
	setp.ge.s32 	%p35, %r461, %r114;
	@%p35 bra 	$L__BB0_31;

	ld.shared.u32 	%r464, [%r13+512];
	mov.u32 	%r469, 0;
	// begin inline asm
	dp4a.s32.s32 %r462, %r79, %r464, %r469;
	// end inline asm
	ld.shared.u32 	%r468, [%r13+512];
	// begin inline asm
	dp4a.s32.s32 %r466, %r87, %r468, %r469;
	// end inline asm
	ld.shared.u32 	%r472, [%r13+516];
	// begin inline asm
	dp4a.s32.s32 %r470, %r80, %r472, %r462;
	// end inline asm
	ld.shared.u32 	%r476, [%r13+516];
	// begin inline asm
	dp4a.s32.s32 %r474, %r88, %r476, %r466;
	// end inline asm
	ld.shared.u32 	%r480, [%r13+520];
	// begin inline asm
	dp4a.s32.s32 %r478, %r81, %r480, %r470;
	// end inline asm
	ld.shared.u32 	%r484, [%r13+520];
	// begin inline asm
	dp4a.s32.s32 %r482, %r89, %r484, %r474;
	// end inline asm
	ld.shared.u32 	%r488, [%r13+524];
	// begin inline asm
	dp4a.s32.s32 %r486, %r82, %r488, %r478;
	// end inline asm
	ld.shared.u32 	%r492, [%r13+524];
	// begin inline asm
	dp4a.s32.s32 %r490, %r90, %r492, %r482;
	// end inline asm
	ld.shared.u32 	%r496, [%r13+528];
	// begin inline asm
	dp4a.s32.s32 %r494, %r83, %r496, %r486;
	// end inline asm
	ld.shared.u32 	%r500, [%r13+528];
	// begin inline asm
	dp4a.s32.s32 %r498, %r91, %r500, %r490;
	// end inline asm
	ld.shared.u32 	%r504, [%r13+532];
	// begin inline asm
	dp4a.s32.s32 %r502, %r84, %r504, %r494;
	// end inline asm
	ld.shared.u32 	%r508, [%r13+532];
	// begin inline asm
	dp4a.s32.s32 %r506, %r92, %r508, %r498;
	// end inline asm
	ld.shared.u32 	%r512, [%r13+536];
	// begin inline asm
	dp4a.s32.s32 %r510, %r85, %r512, %r502;
	// end inline asm
	ld.shared.u32 	%r516, [%r13+536];
	// begin inline asm
	dp4a.s32.s32 %r514, %r93, %r516, %r506;
	// end inline asm
	ld.shared.u32 	%r520, [%r13+540];
	// begin inline asm
	dp4a.s32.s32 %r518, %r86, %r520, %r510;
	// end inline asm
	ld.shared.u32 	%r524, [%r13+540];
	// begin inline asm
	dp4a.s32.s32 %r522, %r94, %r524, %r514;
	// end inline asm
	add.s32 	%r526, %r19, %r78;
	mul.wide.s32 	%rd51, %r526, 4;
	add.s64 	%rd52, %rd3, %rd51;
	add.s64 	%rd53, %rd2, %rd51;
	cvt.rn.f32.s32 	%f279, %r518;
	mul.ftz.f32 	%f280, %f33, %f279;
	ld.global.u32 	%r527, [%rd52];
	cvt.rn.f32.s32 	%f281, %r527;
	mul.ftz.f32 	%f282, %f34, %f281;
	sub.ftz.f32 	%f283, %f280, %f282;
	ld.global.f32 	%f284, [%rd53];
	fma.rn.ftz.f32 	%f659, %f284, %f283, %f659;
	cvt.rn.f32.s32 	%f285, %r522;
	mul.ftz.f32 	%f286, %f35, %f285;
	mul.ftz.f32 	%f287, %f36, %f281;
	sub.ftz.f32 	%f288, %f286, %f287;
	fma.rn.ftz.f32 	%f654, %f284, %f288, %f654;

$L__BB0_31:
	add.s32 	%r528, %r4, 3;
	setp.ge.s32 	%p36, %r528, %r114;
	@%p36 bra 	$L__BB0_33;

	ld.shared.u32 	%r531, [%r13+768];
	mov.u32 	%r536, 0;
	// begin inline asm
	dp4a.s32.s32 %r529, %r79, %r531, %r536;
	// end inline asm
	ld.shared.u32 	%r535, [%r13+768];
	// begin inline asm
	dp4a.s32.s32 %r533, %r87, %r535, %r536;
	// end inline asm
	ld.shared.u32 	%r539, [%r13+772];
	// begin inline asm
	dp4a.s32.s32 %r537, %r80, %r539, %r529;
	// end inline asm
	ld.shared.u32 	%r543, [%r13+772];
	// begin inline asm
	dp4a.s32.s32 %r541, %r88, %r543, %r533;
	// end inline asm
	ld.shared.u32 	%r547, [%r13+776];
	// begin inline asm
	dp4a.s32.s32 %r545, %r81, %r547, %r537;
	// end inline asm
	ld.shared.u32 	%r551, [%r13+776];
	// begin inline asm
	dp4a.s32.s32 %r549, %r89, %r551, %r541;
	// end inline asm
	ld.shared.u32 	%r555, [%r13+780];
	// begin inline asm
	dp4a.s32.s32 %r553, %r82, %r555, %r545;
	// end inline asm
	ld.shared.u32 	%r559, [%r13+780];
	// begin inline asm
	dp4a.s32.s32 %r557, %r90, %r559, %r549;
	// end inline asm
	ld.shared.u32 	%r563, [%r13+784];
	// begin inline asm
	dp4a.s32.s32 %r561, %r83, %r563, %r553;
	// end inline asm
	ld.shared.u32 	%r567, [%r13+784];
	// begin inline asm
	dp4a.s32.s32 %r565, %r91, %r567, %r557;
	// end inline asm
	ld.shared.u32 	%r571, [%r13+788];
	// begin inline asm
	dp4a.s32.s32 %r569, %r84, %r571, %r561;
	// end inline asm
	ld.shared.u32 	%r575, [%r13+788];
	// begin inline asm
	dp4a.s32.s32 %r573, %r92, %r575, %r565;
	// end inline asm
	ld.shared.u32 	%r579, [%r13+792];
	// begin inline asm
	dp4a.s32.s32 %r577, %r85, %r579, %r569;
	// end inline asm
	ld.shared.u32 	%r583, [%r13+792];
	// begin inline asm
	dp4a.s32.s32 %r581, %r93, %r583, %r573;
	// end inline asm
	ld.shared.u32 	%r587, [%r13+796];
	// begin inline asm
	dp4a.s32.s32 %r585, %r86, %r587, %r577;
	// end inline asm
	ld.shared.u32 	%r591, [%r13+796];
	// begin inline asm
	dp4a.s32.s32 %r589, %r94, %r591, %r581;
	// end inline asm
	add.s32 	%r593, %r22, %r78;
	mul.wide.s32 	%rd54, %r593, 4;
	add.s64 	%rd55, %rd3, %rd54;
	add.s64 	%rd56, %rd2, %rd54;
	cvt.rn.f32.s32 	%f289, %r585;
	mul.ftz.f32 	%f290, %f33, %f289;
	ld.global.u32 	%r594, [%rd55];
	cvt.rn.f32.s32 	%f291, %r594;
	mul.ftz.f32 	%f292, %f34, %f291;
	sub.ftz.f32 	%f293, %f290, %f292;
	ld.global.f32 	%f294, [%rd56];
	fma.rn.ftz.f32 	%f660, %f294, %f293, %f660;
	cvt.rn.f32.s32 	%f295, %r589;
	mul.ftz.f32 	%f296, %f35, %f295;
	mul.ftz.f32 	%f297, %f36, %f291;
	sub.ftz.f32 	%f298, %f296, %f297;
	fma.rn.ftz.f32 	%f653, %f294, %f298, %f653;

$L__BB0_33:
	add.s32 	%r595, %r4, 4;
	setp.ge.s32 	%p37, %r595, %r114;
	@%p37 bra 	$L__BB0_35;

	ld.shared.u32 	%r598, [%r13+1024];
	mov.u32 	%r603, 0;
	// begin inline asm
	dp4a.s32.s32 %r596, %r79, %r598, %r603;
	// end inline asm
	ld.shared.u32 	%r602, [%r13+1024];
	// begin inline asm
	dp4a.s32.s32 %r600, %r87, %r602, %r603;
	// end inline asm
	ld.shared.u32 	%r606, [%r13+1028];
	// begin inline asm
	dp4a.s32.s32 %r604, %r80, %r606, %r596;
	// end inline asm
	ld.shared.u32 	%r610, [%r13+1028];
	// begin inline asm
	dp4a.s32.s32 %r608, %r88, %r610, %r600;
	// end inline asm
	ld.shared.u32 	%r614, [%r13+1032];
	// begin inline asm
	dp4a.s32.s32 %r612, %r81, %r614, %r604;
	// end inline asm
	ld.shared.u32 	%r618, [%r13+1032];
	// begin inline asm
	dp4a.s32.s32 %r616, %r89, %r618, %r608;
	// end inline asm
	ld.shared.u32 	%r622, [%r13+1036];
	// begin inline asm
	dp4a.s32.s32 %r620, %r82, %r622, %r612;
	// end inline asm
	ld.shared.u32 	%r626, [%r13+1036];
	// begin inline asm
	dp4a.s32.s32 %r624, %r90, %r626, %r616;
	// end inline asm
	ld.shared.u32 	%r630, [%r13+1040];
	// begin inline asm
	dp4a.s32.s32 %r628, %r83, %r630, %r620;
	// end inline asm
	ld.shared.u32 	%r634, [%r13+1040];
	// begin inline asm
	dp4a.s32.s32 %r632, %r91, %r634, %r624;
	// end inline asm
	ld.shared.u32 	%r638, [%r13+1044];
	// begin inline asm
	dp4a.s32.s32 %r636, %r84, %r638, %r628;
	// end inline asm
	ld.shared.u32 	%r642, [%r13+1044];
	// begin inline asm
	dp4a.s32.s32 %r640, %r92, %r642, %r632;
	// end inline asm
	ld.shared.u32 	%r646, [%r13+1048];
	// begin inline asm
	dp4a.s32.s32 %r644, %r85, %r646, %r636;
	// end inline asm
	ld.shared.u32 	%r650, [%r13+1048];
	// begin inline asm
	dp4a.s32.s32 %r648, %r93, %r650, %r640;
	// end inline asm
	ld.shared.u32 	%r654, [%r13+1052];
	// begin inline asm
	dp4a.s32.s32 %r652, %r86, %r654, %r644;
	// end inline asm
	ld.shared.u32 	%r658, [%r13+1052];
	// begin inline asm
	dp4a.s32.s32 %r656, %r94, %r658, %r648;
	// end inline asm
	add.s32 	%r660, %r26, %r78;
	mul.wide.s32 	%rd57, %r660, 4;
	add.s64 	%rd58, %rd3, %rd57;
	add.s64 	%rd59, %rd2, %rd57;
	cvt.rn.f32.s32 	%f299, %r652;
	mul.ftz.f32 	%f300, %f33, %f299;
	ld.global.u32 	%r661, [%rd58];
	cvt.rn.f32.s32 	%f301, %r661;
	mul.ftz.f32 	%f302, %f34, %f301;
	sub.ftz.f32 	%f303, %f300, %f302;
	ld.global.f32 	%f304, [%rd59];
	fma.rn.ftz.f32 	%f661, %f304, %f303, %f661;
	cvt.rn.f32.s32 	%f305, %r656;
	mul.ftz.f32 	%f306, %f35, %f305;
	mul.ftz.f32 	%f307, %f36, %f301;
	sub.ftz.f32 	%f308, %f306, %f307;
	fma.rn.ftz.f32 	%f652, %f304, %f308, %f652;

$L__BB0_35:
	add.s32 	%r662, %r4, 5;
	setp.ge.s32 	%p38, %r662, %r114;
	@%p38 bra 	$L__BB0_37;

	ld.shared.u32 	%r665, [%r13+1280];
	mov.u32 	%r670, 0;
	// begin inline asm
	dp4a.s32.s32 %r663, %r79, %r665, %r670;
	// end inline asm
	ld.shared.u32 	%r669, [%r13+1280];
	// begin inline asm
	dp4a.s32.s32 %r667, %r87, %r669, %r670;
	// end inline asm
	ld.shared.u32 	%r673, [%r13+1284];
	// begin inline asm
	dp4a.s32.s32 %r671, %r80, %r673, %r663;
	// end inline asm
	ld.shared.u32 	%r677, [%r13+1284];
	// begin inline asm
	dp4a.s32.s32 %r675, %r88, %r677, %r667;
	// end inline asm
	ld.shared.u32 	%r681, [%r13+1288];
	// begin inline asm
	dp4a.s32.s32 %r679, %r81, %r681, %r671;
	// end inline asm
	ld.shared.u32 	%r685, [%r13+1288];
	// begin inline asm
	dp4a.s32.s32 %r683, %r89, %r685, %r675;
	// end inline asm
	ld.shared.u32 	%r689, [%r13+1292];
	// begin inline asm
	dp4a.s32.s32 %r687, %r82, %r689, %r679;
	// end inline asm
	ld.shared.u32 	%r693, [%r13+1292];
	// begin inline asm
	dp4a.s32.s32 %r691, %r90, %r693, %r683;
	// end inline asm
	ld.shared.u32 	%r697, [%r13+1296];
	// begin inline asm
	dp4a.s32.s32 %r695, %r83, %r697, %r687;
	// end inline asm
	ld.shared.u32 	%r701, [%r13+1296];
	// begin inline asm
	dp4a.s32.s32 %r699, %r91, %r701, %r691;
	// end inline asm
	ld.shared.u32 	%r705, [%r13+1300];
	// begin inline asm
	dp4a.s32.s32 %r703, %r84, %r705, %r695;
	// end inline asm
	ld.shared.u32 	%r709, [%r13+1300];
	// begin inline asm
	dp4a.s32.s32 %r707, %r92, %r709, %r699;
	// end inline asm
	ld.shared.u32 	%r713, [%r13+1304];
	// begin inline asm
	dp4a.s32.s32 %r711, %r85, %r713, %r703;
	// end inline asm
	ld.shared.u32 	%r717, [%r13+1304];
	// begin inline asm
	dp4a.s32.s32 %r715, %r93, %r717, %r707;
	// end inline asm
	ld.shared.u32 	%r721, [%r13+1308];
	// begin inline asm
	dp4a.s32.s32 %r719, %r86, %r721, %r711;
	// end inline asm
	ld.shared.u32 	%r725, [%r13+1308];
	// begin inline asm
	dp4a.s32.s32 %r723, %r94, %r725, %r715;
	// end inline asm
	add.s32 	%r727, %r27, %r78;
	mul.wide.s32 	%rd60, %r727, 4;
	add.s64 	%rd61, %rd3, %rd60;
	add.s64 	%rd62, %rd2, %rd60;
	cvt.rn.f32.s32 	%f309, %r719;
	mul.ftz.f32 	%f310, %f33, %f309;
	ld.global.u32 	%r728, [%rd61];
	cvt.rn.f32.s32 	%f311, %r728;
	mul.ftz.f32 	%f312, %f34, %f311;
	sub.ftz.f32 	%f313, %f310, %f312;
	ld.global.f32 	%f314, [%rd62];
	fma.rn.ftz.f32 	%f662, %f314, %f313, %f662;
	cvt.rn.f32.s32 	%f315, %r723;
	mul.ftz.f32 	%f316, %f35, %f315;
	mul.ftz.f32 	%f317, %f36, %f311;
	sub.ftz.f32 	%f318, %f316, %f317;
	fma.rn.ftz.f32 	%f651, %f314, %f318, %f651;

$L__BB0_37:
	add.s32 	%r729, %r4, 6;
	setp.ge.s32 	%p39, %r729, %r114;
	@%p39 bra 	$L__BB0_39;

	ld.shared.u32 	%r732, [%r13+1536];
	mov.u32 	%r737, 0;
	// begin inline asm
	dp4a.s32.s32 %r730, %r79, %r732, %r737;
	// end inline asm
	ld.shared.u32 	%r736, [%r13+1536];
	// begin inline asm
	dp4a.s32.s32 %r734, %r87, %r736, %r737;
	// end inline asm
	ld.shared.u32 	%r740, [%r13+1540];
	// begin inline asm
	dp4a.s32.s32 %r738, %r80, %r740, %r730;
	// end inline asm
	ld.shared.u32 	%r744, [%r13+1540];
	// begin inline asm
	dp4a.s32.s32 %r742, %r88, %r744, %r734;
	// end inline asm
	ld.shared.u32 	%r748, [%r13+1544];
	// begin inline asm
	dp4a.s32.s32 %r746, %r81, %r748, %r738;
	// end inline asm
	ld.shared.u32 	%r752, [%r13+1544];
	// begin inline asm
	dp4a.s32.s32 %r750, %r89, %r752, %r742;
	// end inline asm
	ld.shared.u32 	%r756, [%r13+1548];
	// begin inline asm
	dp4a.s32.s32 %r754, %r82, %r756, %r746;
	// end inline asm
	ld.shared.u32 	%r760, [%r13+1548];
	// begin inline asm
	dp4a.s32.s32 %r758, %r90, %r760, %r750;
	// end inline asm
	ld.shared.u32 	%r764, [%r13+1552];
	// begin inline asm
	dp4a.s32.s32 %r762, %r83, %r764, %r754;
	// end inline asm
	ld.shared.u32 	%r768, [%r13+1552];
	// begin inline asm
	dp4a.s32.s32 %r766, %r91, %r768, %r758;
	// end inline asm
	ld.shared.u32 	%r772, [%r13+1556];
	// begin inline asm
	dp4a.s32.s32 %r770, %r84, %r772, %r762;
	// end inline asm
	ld.shared.u32 	%r776, [%r13+1556];
	// begin inline asm
	dp4a.s32.s32 %r774, %r92, %r776, %r766;
	// end inline asm
	ld.shared.u32 	%r780, [%r13+1560];
	// begin inline asm
	dp4a.s32.s32 %r778, %r85, %r780, %r770;
	// end inline asm
	ld.shared.u32 	%r784, [%r13+1560];
	// begin inline asm
	dp4a.s32.s32 %r782, %r93, %r784, %r774;
	// end inline asm
	ld.shared.u32 	%r788, [%r13+1564];
	// begin inline asm
	dp4a.s32.s32 %r786, %r86, %r788, %r778;
	// end inline asm
	ld.shared.u32 	%r792, [%r13+1564];
	// begin inline asm
	dp4a.s32.s32 %r790, %r94, %r792, %r782;
	// end inline asm
	add.s32 	%r794, %r28, %r78;
	mul.wide.s32 	%rd63, %r794, 4;
	add.s64 	%rd64, %rd3, %rd63;
	add.s64 	%rd65, %rd2, %rd63;
	cvt.rn.f32.s32 	%f319, %r786;
	mul.ftz.f32 	%f320, %f33, %f319;
	ld.global.u32 	%r795, [%rd64];
	cvt.rn.f32.s32 	%f321, %r795;
	mul.ftz.f32 	%f322, %f34, %f321;
	sub.ftz.f32 	%f323, %f320, %f322;
	ld.global.f32 	%f324, [%rd65];
	fma.rn.ftz.f32 	%f663, %f324, %f323, %f663;
	cvt.rn.f32.s32 	%f325, %r790;
	mul.ftz.f32 	%f326, %f35, %f325;
	mul.ftz.f32 	%f327, %f36, %f321;
	sub.ftz.f32 	%f328, %f326, %f327;
	fma.rn.ftz.f32 	%f650, %f324, %f328, %f650;

$L__BB0_39:
	setp.ge.s32 	%p40, %r29, %r114;
	@%p40 bra 	$L__BB0_41;

	ld.shared.u32 	%r798, [%r13+1792];
	mov.u32 	%r803, 0;
	// begin inline asm
	dp4a.s32.s32 %r796, %r79, %r798, %r803;
	// end inline asm
	ld.shared.u32 	%r802, [%r13+1792];
	// begin inline asm
	dp4a.s32.s32 %r800, %r87, %r802, %r803;
	// end inline asm
	ld.shared.u32 	%r806, [%r13+1796];
	// begin inline asm
	dp4a.s32.s32 %r804, %r80, %r806, %r796;
	// end inline asm
	ld.shared.u32 	%r810, [%r13+1796];
	// begin inline asm
	dp4a.s32.s32 %r808, %r88, %r810, %r800;
	// end inline asm
	ld.shared.u32 	%r814, [%r13+1800];
	// begin inline asm
	dp4a.s32.s32 %r812, %r81, %r814, %r804;
	// end inline asm
	ld.shared.u32 	%r818, [%r13+1800];
	// begin inline asm
	dp4a.s32.s32 %r816, %r89, %r818, %r808;
	// end inline asm
	ld.shared.u32 	%r822, [%r13+1804];
	// begin inline asm
	dp4a.s32.s32 %r820, %r82, %r822, %r812;
	// end inline asm
	ld.shared.u32 	%r826, [%r13+1804];
	// begin inline asm
	dp4a.s32.s32 %r824, %r90, %r826, %r816;
	// end inline asm
	ld.shared.u32 	%r830, [%r13+1808];
	// begin inline asm
	dp4a.s32.s32 %r828, %r83, %r830, %r820;
	// end inline asm
	ld.shared.u32 	%r834, [%r13+1808];
	// begin inline asm
	dp4a.s32.s32 %r832, %r91, %r834, %r824;
	// end inline asm
	ld.shared.u32 	%r838, [%r13+1812];
	// begin inline asm
	dp4a.s32.s32 %r836, %r84, %r838, %r828;
	// end inline asm
	ld.shared.u32 	%r842, [%r13+1812];
	// begin inline asm
	dp4a.s32.s32 %r840, %r92, %r842, %r832;
	// end inline asm
	ld.shared.u32 	%r846, [%r13+1816];
	// begin inline asm
	dp4a.s32.s32 %r844, %r85, %r846, %r836;
	// end inline asm
	ld.shared.u32 	%r850, [%r13+1816];
	// begin inline asm
	dp4a.s32.s32 %r848, %r93, %r850, %r840;
	// end inline asm
	ld.shared.u32 	%r854, [%r13+1820];
	// begin inline asm
	dp4a.s32.s32 %r852, %r86, %r854, %r844;
	// end inline asm
	ld.shared.u32 	%r858, [%r13+1820];
	// begin inline asm
	dp4a.s32.s32 %r856, %r94, %r858, %r848;
	// end inline asm
	add.s32 	%r860, %r30, %r78;
	mul.wide.s32 	%rd66, %r860, 4;
	add.s64 	%rd67, %rd3, %rd66;
	add.s64 	%rd68, %rd2, %rd66;
	cvt.rn.f32.s32 	%f329, %r852;
	mul.ftz.f32 	%f330, %f33, %f329;
	ld.global.u32 	%r861, [%rd67];
	cvt.rn.f32.s32 	%f331, %r861;
	mul.ftz.f32 	%f332, %f34, %f331;
	sub.ftz.f32 	%f333, %f330, %f332;
	ld.global.f32 	%f334, [%rd68];
	fma.rn.ftz.f32 	%f664, %f334, %f333, %f664;
	cvt.rn.f32.s32 	%f335, %r856;
	mul.ftz.f32 	%f336, %f35, %f335;
	mul.ftz.f32 	%f337, %f36, %f331;
	sub.ftz.f32 	%f338, %f336, %f337;
	fma.rn.ftz.f32 	%f649, %f334, %f338, %f649;

$L__BB0_41:
	setp.ge.s32 	%p41, %r31, %r114;
	@%p41 bra 	$L__BB0_43;

	ld.shared.u32 	%r864, [%r13+2048];
	mov.u32 	%r869, 0;
	// begin inline asm
	dp4a.s32.s32 %r862, %r79, %r864, %r869;
	// end inline asm
	ld.shared.u32 	%r868, [%r13+2048];
	// begin inline asm
	dp4a.s32.s32 %r866, %r87, %r868, %r869;
	// end inline asm
	ld.shared.u32 	%r872, [%r13+2052];
	// begin inline asm
	dp4a.s32.s32 %r870, %r80, %r872, %r862;
	// end inline asm
	ld.shared.u32 	%r876, [%r13+2052];
	// begin inline asm
	dp4a.s32.s32 %r874, %r88, %r876, %r866;
	// end inline asm
	ld.shared.u32 	%r880, [%r13+2056];
	// begin inline asm
	dp4a.s32.s32 %r878, %r81, %r880, %r870;
	// end inline asm
	ld.shared.u32 	%r884, [%r13+2056];
	// begin inline asm
	dp4a.s32.s32 %r882, %r89, %r884, %r874;
	// end inline asm
	ld.shared.u32 	%r888, [%r13+2060];
	// begin inline asm
	dp4a.s32.s32 %r886, %r82, %r888, %r878;
	// end inline asm
	ld.shared.u32 	%r892, [%r13+2060];
	// begin inline asm
	dp4a.s32.s32 %r890, %r90, %r892, %r882;
	// end inline asm
	ld.shared.u32 	%r896, [%r13+2064];
	// begin inline asm
	dp4a.s32.s32 %r894, %r83, %r896, %r886;
	// end inline asm
	ld.shared.u32 	%r900, [%r13+2064];
	// begin inline asm
	dp4a.s32.s32 %r898, %r91, %r900, %r890;
	// end inline asm
	ld.shared.u32 	%r904, [%r13+2068];
	// begin inline asm
	dp4a.s32.s32 %r902, %r84, %r904, %r894;
	// end inline asm
	ld.shared.u32 	%r908, [%r13+2068];
	// begin inline asm
	dp4a.s32.s32 %r906, %r92, %r908, %r898;
	// end inline asm
	ld.shared.u32 	%r912, [%r13+2072];
	// begin inline asm
	dp4a.s32.s32 %r910, %r85, %r912, %r902;
	// end inline asm
	ld.shared.u32 	%r916, [%r13+2072];
	// begin inline asm
	dp4a.s32.s32 %r914, %r93, %r916, %r906;
	// end inline asm
	ld.shared.u32 	%r920, [%r13+2076];
	// begin inline asm
	dp4a.s32.s32 %r918, %r86, %r920, %r910;
	// end inline asm
	ld.shared.u32 	%r924, [%r13+2076];
	// begin inline asm
	dp4a.s32.s32 %r922, %r94, %r924, %r914;
	// end inline asm
	add.s32 	%r926, %r32, %r78;
	mul.wide.s32 	%rd69, %r926, 4;
	add.s64 	%rd70, %rd3, %rd69;
	add.s64 	%rd71, %rd2, %rd69;
	cvt.rn.f32.s32 	%f339, %r918;
	mul.ftz.f32 	%f340, %f33, %f339;
	ld.global.u32 	%r927, [%rd70];
	cvt.rn.f32.s32 	%f341, %r927;
	mul.ftz.f32 	%f342, %f34, %f341;
	sub.ftz.f32 	%f343, %f340, %f342;
	ld.global.f32 	%f344, [%rd71];
	fma.rn.ftz.f32 	%f665, %f344, %f343, %f665;
	cvt.rn.f32.s32 	%f345, %r922;
	mul.ftz.f32 	%f346, %f35, %f345;
	mul.ftz.f32 	%f347, %f36, %f341;
	sub.ftz.f32 	%f348, %f346, %f347;
	fma.rn.ftz.f32 	%f648, %f344, %f348, %f648;

$L__BB0_43:
	setp.ge.s32 	%p42, %r33, %r114;
	@%p42 bra 	$L__BB0_45;

	ld.shared.u32 	%r930, [%r13+2304];
	mov.u32 	%r935, 0;
	// begin inline asm
	dp4a.s32.s32 %r928, %r79, %r930, %r935;
	// end inline asm
	ld.shared.u32 	%r934, [%r13+2304];
	// begin inline asm
	dp4a.s32.s32 %r932, %r87, %r934, %r935;
	// end inline asm
	ld.shared.u32 	%r938, [%r13+2308];
	// begin inline asm
	dp4a.s32.s32 %r936, %r80, %r938, %r928;
	// end inline asm
	ld.shared.u32 	%r942, [%r13+2308];
	// begin inline asm
	dp4a.s32.s32 %r940, %r88, %r942, %r932;
	// end inline asm
	ld.shared.u32 	%r946, [%r13+2312];
	// begin inline asm
	dp4a.s32.s32 %r944, %r81, %r946, %r936;
	// end inline asm
	ld.shared.u32 	%r950, [%r13+2312];
	// begin inline asm
	dp4a.s32.s32 %r948, %r89, %r950, %r940;
	// end inline asm
	ld.shared.u32 	%r954, [%r13+2316];
	// begin inline asm
	dp4a.s32.s32 %r952, %r82, %r954, %r944;
	// end inline asm
	ld.shared.u32 	%r958, [%r13+2316];
	// begin inline asm
	dp4a.s32.s32 %r956, %r90, %r958, %r948;
	// end inline asm
	ld.shared.u32 	%r962, [%r13+2320];
	// begin inline asm
	dp4a.s32.s32 %r960, %r83, %r962, %r952;
	// end inline asm
	ld.shared.u32 	%r966, [%r13+2320];
	// begin inline asm
	dp4a.s32.s32 %r964, %r91, %r966, %r956;
	// end inline asm
	ld.shared.u32 	%r970, [%r13+2324];
	// begin inline asm
	dp4a.s32.s32 %r968, %r84, %r970, %r960;
	// end inline asm
	ld.shared.u32 	%r974, [%r13+2324];
	// begin inline asm
	dp4a.s32.s32 %r972, %r92, %r974, %r964;
	// end inline asm
	ld.shared.u32 	%r978, [%r13+2328];
	// begin inline asm
	dp4a.s32.s32 %r976, %r85, %r978, %r968;
	// end inline asm
	ld.shared.u32 	%r982, [%r13+2328];
	// begin inline asm
	dp4a.s32.s32 %r980, %r93, %r982, %r972;
	// end inline asm
	ld.shared.u32 	%r986, [%r13+2332];
	// begin inline asm
	dp4a.s32.s32 %r984, %r86, %r986, %r976;
	// end inline asm
	ld.shared.u32 	%r990, [%r13+2332];
	// begin inline asm
	dp4a.s32.s32 %r988, %r94, %r990, %r980;
	// end inline asm
	add.s32 	%r992, %r34, %r78;
	mul.wide.s32 	%rd72, %r992, 4;
	add.s64 	%rd73, %rd3, %rd72;
	add.s64 	%rd74, %rd2, %rd72;
	cvt.rn.f32.s32 	%f349, %r984;
	mul.ftz.f32 	%f350, %f33, %f349;
	ld.global.u32 	%r993, [%rd73];
	cvt.rn.f32.s32 	%f351, %r993;
	mul.ftz.f32 	%f352, %f34, %f351;
	sub.ftz.f32 	%f353, %f350, %f352;
	ld.global.f32 	%f354, [%rd74];
	fma.rn.ftz.f32 	%f666, %f354, %f353, %f666;
	cvt.rn.f32.s32 	%f355, %r988;
	mul.ftz.f32 	%f356, %f35, %f355;
	mul.ftz.f32 	%f357, %f36, %f351;
	sub.ftz.f32 	%f358, %f356, %f357;
	fma.rn.ftz.f32 	%f647, %f354, %f358, %f647;

$L__BB0_45:
	setp.ge.s32 	%p43, %r35, %r114;
	@%p43 bra 	$L__BB0_47;

	ld.shared.u32 	%r996, [%r13+2560];
	mov.u32 	%r1001, 0;
	// begin inline asm
	dp4a.s32.s32 %r994, %r79, %r996, %r1001;
	// end inline asm
	ld.shared.u32 	%r1000, [%r13+2560];
	// begin inline asm
	dp4a.s32.s32 %r998, %r87, %r1000, %r1001;
	// end inline asm
	ld.shared.u32 	%r1004, [%r13+2564];
	// begin inline asm
	dp4a.s32.s32 %r1002, %r80, %r1004, %r994;
	// end inline asm
	ld.shared.u32 	%r1008, [%r13+2564];
	// begin inline asm
	dp4a.s32.s32 %r1006, %r88, %r1008, %r998;
	// end inline asm
	ld.shared.u32 	%r1012, [%r13+2568];
	// begin inline asm
	dp4a.s32.s32 %r1010, %r81, %r1012, %r1002;
	// end inline asm
	ld.shared.u32 	%r1016, [%r13+2568];
	// begin inline asm
	dp4a.s32.s32 %r1014, %r89, %r1016, %r1006;
	// end inline asm
	ld.shared.u32 	%r1020, [%r13+2572];
	// begin inline asm
	dp4a.s32.s32 %r1018, %r82, %r1020, %r1010;
	// end inline asm
	ld.shared.u32 	%r1024, [%r13+2572];
	// begin inline asm
	dp4a.s32.s32 %r1022, %r90, %r1024, %r1014;
	// end inline asm
	ld.shared.u32 	%r1028, [%r13+2576];
	// begin inline asm
	dp4a.s32.s32 %r1026, %r83, %r1028, %r1018;
	// end inline asm
	ld.shared.u32 	%r1032, [%r13+2576];
	// begin inline asm
	dp4a.s32.s32 %r1030, %r91, %r1032, %r1022;
	// end inline asm
	ld.shared.u32 	%r1036, [%r13+2580];
	// begin inline asm
	dp4a.s32.s32 %r1034, %r84, %r1036, %r1026;
	// end inline asm
	ld.shared.u32 	%r1040, [%r13+2580];
	// begin inline asm
	dp4a.s32.s32 %r1038, %r92, %r1040, %r1030;
	// end inline asm
	ld.shared.u32 	%r1044, [%r13+2584];
	// begin inline asm
	dp4a.s32.s32 %r1042, %r85, %r1044, %r1034;
	// end inline asm
	ld.shared.u32 	%r1048, [%r13+2584];
	// begin inline asm
	dp4a.s32.s32 %r1046, %r93, %r1048, %r1038;
	// end inline asm
	ld.shared.u32 	%r1052, [%r13+2588];
	// begin inline asm
	dp4a.s32.s32 %r1050, %r86, %r1052, %r1042;
	// end inline asm
	ld.shared.u32 	%r1056, [%r13+2588];
	// begin inline asm
	dp4a.s32.s32 %r1054, %r94, %r1056, %r1046;
	// end inline asm
	add.s32 	%r1058, %r36, %r78;
	mul.wide.s32 	%rd75, %r1058, 4;
	add.s64 	%rd76, %rd3, %rd75;
	add.s64 	%rd77, %rd2, %rd75;
	cvt.rn.f32.s32 	%f359, %r1050;
	mul.ftz.f32 	%f360, %f33, %f359;
	ld.global.u32 	%r1059, [%rd76];
	cvt.rn.f32.s32 	%f361, %r1059;
	mul.ftz.f32 	%f362, %f34, %f361;
	sub.ftz.f32 	%f363, %f360, %f362;
	ld.global.f32 	%f364, [%rd77];
	fma.rn.ftz.f32 	%f667, %f364, %f363, %f667;
	cvt.rn.f32.s32 	%f365, %r1054;
	mul.ftz.f32 	%f366, %f35, %f365;
	mul.ftz.f32 	%f367, %f36, %f361;
	sub.ftz.f32 	%f368, %f366, %f367;
	fma.rn.ftz.f32 	%f646, %f364, %f368, %f646;

$L__BB0_47:
	setp.ge.s32 	%p44, %r37, %r114;
	@%p44 bra 	$L__BB0_49;

	ld.shared.u32 	%r1062, [%r13+2816];
	mov.u32 	%r1067, 0;
	// begin inline asm
	dp4a.s32.s32 %r1060, %r79, %r1062, %r1067;
	// end inline asm
	ld.shared.u32 	%r1066, [%r13+2816];
	// begin inline asm
	dp4a.s32.s32 %r1064, %r87, %r1066, %r1067;
	// end inline asm
	ld.shared.u32 	%r1070, [%r13+2820];
	// begin inline asm
	dp4a.s32.s32 %r1068, %r80, %r1070, %r1060;
	// end inline asm
	ld.shared.u32 	%r1074, [%r13+2820];
	// begin inline asm
	dp4a.s32.s32 %r1072, %r88, %r1074, %r1064;
	// end inline asm
	ld.shared.u32 	%r1078, [%r13+2824];
	// begin inline asm
	dp4a.s32.s32 %r1076, %r81, %r1078, %r1068;
	// end inline asm
	ld.shared.u32 	%r1082, [%r13+2824];
	// begin inline asm
	dp4a.s32.s32 %r1080, %r89, %r1082, %r1072;
	// end inline asm
	ld.shared.u32 	%r1086, [%r13+2828];
	// begin inline asm
	dp4a.s32.s32 %r1084, %r82, %r1086, %r1076;
	// end inline asm
	ld.shared.u32 	%r1090, [%r13+2828];
	// begin inline asm
	dp4a.s32.s32 %r1088, %r90, %r1090, %r1080;
	// end inline asm
	ld.shared.u32 	%r1094, [%r13+2832];
	// begin inline asm
	dp4a.s32.s32 %r1092, %r83, %r1094, %r1084;
	// end inline asm
	ld.shared.u32 	%r1098, [%r13+2832];
	// begin inline asm
	dp4a.s32.s32 %r1096, %r91, %r1098, %r1088;
	// end inline asm
	ld.shared.u32 	%r1102, [%r13+2836];
	// begin inline asm
	dp4a.s32.s32 %r1100, %r84, %r1102, %r1092;
	// end inline asm
	ld.shared.u32 	%r1106, [%r13+2836];
	// begin inline asm
	dp4a.s32.s32 %r1104, %r92, %r1106, %r1096;
	// end inline asm
	ld.shared.u32 	%r1110, [%r13+2840];
	// begin inline asm
	dp4a.s32.s32 %r1108, %r85, %r1110, %r1100;
	// end inline asm
	ld.shared.u32 	%r1114, [%r13+2840];
	// begin inline asm
	dp4a.s32.s32 %r1112, %r93, %r1114, %r1104;
	// end inline asm
	ld.shared.u32 	%r1118, [%r13+2844];
	// begin inline asm
	dp4a.s32.s32 %r1116, %r86, %r1118, %r1108;
	// end inline asm
	ld.shared.u32 	%r1122, [%r13+2844];
	// begin inline asm
	dp4a.s32.s32 %r1120, %r94, %r1122, %r1112;
	// end inline asm
	add.s32 	%r1124, %r38, %r78;
	mul.wide.s32 	%rd78, %r1124, 4;
	add.s64 	%rd79, %rd3, %rd78;
	add.s64 	%rd80, %rd2, %rd78;
	cvt.rn.f32.s32 	%f369, %r1116;
	mul.ftz.f32 	%f370, %f33, %f369;
	ld.global.u32 	%r1125, [%rd79];
	cvt.rn.f32.s32 	%f371, %r1125;
	mul.ftz.f32 	%f372, %f34, %f371;
	sub.ftz.f32 	%f373, %f370, %f372;
	ld.global.f32 	%f374, [%rd80];
	fma.rn.ftz.f32 	%f668, %f374, %f373, %f668;
	cvt.rn.f32.s32 	%f375, %r1120;
	mul.ftz.f32 	%f376, %f35, %f375;
	mul.ftz.f32 	%f377, %f36, %f371;
	sub.ftz.f32 	%f378, %f376, %f377;
	fma.rn.ftz.f32 	%f645, %f374, %f378, %f645;

$L__BB0_49:
	setp.ge.s32 	%p45, %r39, %r114;
	@%p45 bra 	$L__BB0_51;

	ld.shared.u32 	%r1128, [%r13+3072];
	mov.u32 	%r1133, 0;
	// begin inline asm
	dp4a.s32.s32 %r1126, %r79, %r1128, %r1133;
	// end inline asm
	ld.shared.u32 	%r1132, [%r13+3072];
	// begin inline asm
	dp4a.s32.s32 %r1130, %r87, %r1132, %r1133;
	// end inline asm
	ld.shared.u32 	%r1136, [%r13+3076];
	// begin inline asm
	dp4a.s32.s32 %r1134, %r80, %r1136, %r1126;
	// end inline asm
	ld.shared.u32 	%r1140, [%r13+3076];
	// begin inline asm
	dp4a.s32.s32 %r1138, %r88, %r1140, %r1130;
	// end inline asm
	ld.shared.u32 	%r1144, [%r13+3080];
	// begin inline asm
	dp4a.s32.s32 %r1142, %r81, %r1144, %r1134;
	// end inline asm
	ld.shared.u32 	%r1148, [%r13+3080];
	// begin inline asm
	dp4a.s32.s32 %r1146, %r89, %r1148, %r1138;
	// end inline asm
	ld.shared.u32 	%r1152, [%r13+3084];
	// begin inline asm
	dp4a.s32.s32 %r1150, %r82, %r1152, %r1142;
	// end inline asm
	ld.shared.u32 	%r1156, [%r13+3084];
	// begin inline asm
	dp4a.s32.s32 %r1154, %r90, %r1156, %r1146;
	// end inline asm
	ld.shared.u32 	%r1160, [%r13+3088];
	// begin inline asm
	dp4a.s32.s32 %r1158, %r83, %r1160, %r1150;
	// end inline asm
	ld.shared.u32 	%r1164, [%r13+3088];
	// begin inline asm
	dp4a.s32.s32 %r1162, %r91, %r1164, %r1154;
	// end inline asm
	ld.shared.u32 	%r1168, [%r13+3092];
	// begin inline asm
	dp4a.s32.s32 %r1166, %r84, %r1168, %r1158;
	// end inline asm
	ld.shared.u32 	%r1172, [%r13+3092];
	// begin inline asm
	dp4a.s32.s32 %r1170, %r92, %r1172, %r1162;
	// end inline asm
	ld.shared.u32 	%r1176, [%r13+3096];
	// begin inline asm
	dp4a.s32.s32 %r1174, %r85, %r1176, %r1166;
	// end inline asm
	ld.shared.u32 	%r1180, [%r13+3096];
	// begin inline asm
	dp4a.s32.s32 %r1178, %r93, %r1180, %r1170;
	// end inline asm
	ld.shared.u32 	%r1184, [%r13+3100];
	// begin inline asm
	dp4a.s32.s32 %r1182, %r86, %r1184, %r1174;
	// end inline asm
	ld.shared.u32 	%r1188, [%r13+3100];
	// begin inline asm
	dp4a.s32.s32 %r1186, %r94, %r1188, %r1178;
	// end inline asm
	add.s32 	%r1190, %r40, %r78;
	mul.wide.s32 	%rd81, %r1190, 4;
	add.s64 	%rd82, %rd3, %rd81;
	add.s64 	%rd83, %rd2, %rd81;
	cvt.rn.f32.s32 	%f379, %r1182;
	mul.ftz.f32 	%f380, %f33, %f379;
	ld.global.u32 	%r1191, [%rd82];
	cvt.rn.f32.s32 	%f381, %r1191;
	mul.ftz.f32 	%f382, %f34, %f381;
	sub.ftz.f32 	%f383, %f380, %f382;
	ld.global.f32 	%f384, [%rd83];
	fma.rn.ftz.f32 	%f669, %f384, %f383, %f669;
	cvt.rn.f32.s32 	%f385, %r1186;
	mul.ftz.f32 	%f386, %f35, %f385;
	mul.ftz.f32 	%f387, %f36, %f381;
	sub.ftz.f32 	%f388, %f386, %f387;
	fma.rn.ftz.f32 	%f644, %f384, %f388, %f644;

$L__BB0_51:
	setp.ge.s32 	%p46, %r41, %r114;
	@%p46 bra 	$L__BB0_53;

	ld.shared.u32 	%r1194, [%r13+3328];
	mov.u32 	%r1199, 0;
	// begin inline asm
	dp4a.s32.s32 %r1192, %r79, %r1194, %r1199;
	// end inline asm
	ld.shared.u32 	%r1198, [%r13+3328];
	// begin inline asm
	dp4a.s32.s32 %r1196, %r87, %r1198, %r1199;
	// end inline asm
	ld.shared.u32 	%r1202, [%r13+3332];
	// begin inline asm
	dp4a.s32.s32 %r1200, %r80, %r1202, %r1192;
	// end inline asm
	ld.shared.u32 	%r1206, [%r13+3332];
	// begin inline asm
	dp4a.s32.s32 %r1204, %r88, %r1206, %r1196;
	// end inline asm
	ld.shared.u32 	%r1210, [%r13+3336];
	// begin inline asm
	dp4a.s32.s32 %r1208, %r81, %r1210, %r1200;
	// end inline asm
	ld.shared.u32 	%r1214, [%r13+3336];
	// begin inline asm
	dp4a.s32.s32 %r1212, %r89, %r1214, %r1204;
	// end inline asm
	ld.shared.u32 	%r1218, [%r13+3340];
	// begin inline asm
	dp4a.s32.s32 %r1216, %r82, %r1218, %r1208;
	// end inline asm
	ld.shared.u32 	%r1222, [%r13+3340];
	// begin inline asm
	dp4a.s32.s32 %r1220, %r90, %r1222, %r1212;
	// end inline asm
	ld.shared.u32 	%r1226, [%r13+3344];
	// begin inline asm
	dp4a.s32.s32 %r1224, %r83, %r1226, %r1216;
	// end inline asm
	ld.shared.u32 	%r1230, [%r13+3344];
	// begin inline asm
	dp4a.s32.s32 %r1228, %r91, %r1230, %r1220;
	// end inline asm
	ld.shared.u32 	%r1234, [%r13+3348];
	// begin inline asm
	dp4a.s32.s32 %r1232, %r84, %r1234, %r1224;
	// end inline asm
	ld.shared.u32 	%r1238, [%r13+3348];
	// begin inline asm
	dp4a.s32.s32 %r1236, %r92, %r1238, %r1228;
	// end inline asm
	ld.shared.u32 	%r1242, [%r13+3352];
	// begin inline asm
	dp4a.s32.s32 %r1240, %r85, %r1242, %r1232;
	// end inline asm
	ld.shared.u32 	%r1246, [%r13+3352];
	// begin inline asm
	dp4a.s32.s32 %r1244, %r93, %r1246, %r1236;
	// end inline asm
	ld.shared.u32 	%r1250, [%r13+3356];
	// begin inline asm
	dp4a.s32.s32 %r1248, %r86, %r1250, %r1240;
	// end inline asm
	ld.shared.u32 	%r1254, [%r13+3356];
	// begin inline asm
	dp4a.s32.s32 %r1252, %r94, %r1254, %r1244;
	// end inline asm
	add.s32 	%r1256, %r42, %r78;
	mul.wide.s32 	%rd84, %r1256, 4;
	add.s64 	%rd85, %rd3, %rd84;
	add.s64 	%rd86, %rd2, %rd84;
	cvt.rn.f32.s32 	%f389, %r1248;
	mul.ftz.f32 	%f390, %f33, %f389;
	ld.global.u32 	%r1257, [%rd85];
	cvt.rn.f32.s32 	%f391, %r1257;
	mul.ftz.f32 	%f392, %f34, %f391;
	sub.ftz.f32 	%f393, %f390, %f392;
	ld.global.f32 	%f394, [%rd86];
	fma.rn.ftz.f32 	%f670, %f394, %f393, %f670;
	cvt.rn.f32.s32 	%f395, %r1252;
	mul.ftz.f32 	%f396, %f35, %f395;
	mul.ftz.f32 	%f397, %f36, %f391;
	sub.ftz.f32 	%f398, %f396, %f397;
	fma.rn.ftz.f32 	%f643, %f394, %f398, %f643;

$L__BB0_53:
	setp.ge.s32 	%p47, %r43, %r114;
	@%p47 bra 	$L__BB0_55;

	ld.shared.u32 	%r1260, [%r13+3584];
	mov.u32 	%r1265, 0;
	// begin inline asm
	dp4a.s32.s32 %r1258, %r79, %r1260, %r1265;
	// end inline asm
	ld.shared.u32 	%r1264, [%r13+3584];
	// begin inline asm
	dp4a.s32.s32 %r1262, %r87, %r1264, %r1265;
	// end inline asm
	ld.shared.u32 	%r1268, [%r13+3588];
	// begin inline asm
	dp4a.s32.s32 %r1266, %r80, %r1268, %r1258;
	// end inline asm
	ld.shared.u32 	%r1272, [%r13+3588];
	// begin inline asm
	dp4a.s32.s32 %r1270, %r88, %r1272, %r1262;
	// end inline asm
	ld.shared.u32 	%r1276, [%r13+3592];
	// begin inline asm
	dp4a.s32.s32 %r1274, %r81, %r1276, %r1266;
	// end inline asm
	ld.shared.u32 	%r1280, [%r13+3592];
	// begin inline asm
	dp4a.s32.s32 %r1278, %r89, %r1280, %r1270;
	// end inline asm
	ld.shared.u32 	%r1284, [%r13+3596];
	// begin inline asm
	dp4a.s32.s32 %r1282, %r82, %r1284, %r1274;
	// end inline asm
	ld.shared.u32 	%r1288, [%r13+3596];
	// begin inline asm
	dp4a.s32.s32 %r1286, %r90, %r1288, %r1278;
	// end inline asm
	ld.shared.u32 	%r1292, [%r13+3600];
	// begin inline asm
	dp4a.s32.s32 %r1290, %r83, %r1292, %r1282;
	// end inline asm
	ld.shared.u32 	%r1296, [%r13+3600];
	// begin inline asm
	dp4a.s32.s32 %r1294, %r91, %r1296, %r1286;
	// end inline asm
	ld.shared.u32 	%r1300, [%r13+3604];
	// begin inline asm
	dp4a.s32.s32 %r1298, %r84, %r1300, %r1290;
	// end inline asm
	ld.shared.u32 	%r1304, [%r13+3604];
	// begin inline asm
	dp4a.s32.s32 %r1302, %r92, %r1304, %r1294;
	// end inline asm
	ld.shared.u32 	%r1308, [%r13+3608];
	// begin inline asm
	dp4a.s32.s32 %r1306, %r85, %r1308, %r1298;
	// end inline asm
	ld.shared.u32 	%r1312, [%r13+3608];
	// begin inline asm
	dp4a.s32.s32 %r1310, %r93, %r1312, %r1302;
	// end inline asm
	ld.shared.u32 	%r1316, [%r13+3612];
	// begin inline asm
	dp4a.s32.s32 %r1314, %r86, %r1316, %r1306;
	// end inline asm
	ld.shared.u32 	%r1320, [%r13+3612];
	// begin inline asm
	dp4a.s32.s32 %r1318, %r94, %r1320, %r1310;
	// end inline asm
	add.s32 	%r1322, %r44, %r78;
	mul.wide.s32 	%rd87, %r1322, 4;
	add.s64 	%rd88, %rd3, %rd87;
	add.s64 	%rd89, %rd2, %rd87;
	cvt.rn.f32.s32 	%f399, %r1314;
	mul.ftz.f32 	%f400, %f33, %f399;
	ld.global.u32 	%r1323, [%rd88];
	cvt.rn.f32.s32 	%f401, %r1323;
	mul.ftz.f32 	%f402, %f34, %f401;
	sub.ftz.f32 	%f403, %f400, %f402;
	ld.global.f32 	%f404, [%rd89];
	fma.rn.ftz.f32 	%f671, %f404, %f403, %f671;
	cvt.rn.f32.s32 	%f405, %r1318;
	mul.ftz.f32 	%f406, %f35, %f405;
	mul.ftz.f32 	%f407, %f36, %f401;
	sub.ftz.f32 	%f408, %f406, %f407;
	fma.rn.ftz.f32 	%f642, %f404, %f408, %f642;

$L__BB0_55:
	setp.ge.s32 	%p48, %r45, %r114;
	@%p48 bra 	$L__BB0_57;

	ld.shared.u32 	%r1326, [%r13+3840];
	mov.u32 	%r1331, 0;
	// begin inline asm
	dp4a.s32.s32 %r1324, %r79, %r1326, %r1331;
	// end inline asm
	ld.shared.u32 	%r1330, [%r13+3840];
	// begin inline asm
	dp4a.s32.s32 %r1328, %r87, %r1330, %r1331;
	// end inline asm
	ld.shared.u32 	%r1334, [%r13+3844];
	// begin inline asm
	dp4a.s32.s32 %r1332, %r80, %r1334, %r1324;
	// end inline asm
	ld.shared.u32 	%r1338, [%r13+3844];
	// begin inline asm
	dp4a.s32.s32 %r1336, %r88, %r1338, %r1328;
	// end inline asm
	ld.shared.u32 	%r1342, [%r13+3848];
	// begin inline asm
	dp4a.s32.s32 %r1340, %r81, %r1342, %r1332;
	// end inline asm
	ld.shared.u32 	%r1346, [%r13+3848];
	// begin inline asm
	dp4a.s32.s32 %r1344, %r89, %r1346, %r1336;
	// end inline asm
	ld.shared.u32 	%r1350, [%r13+3852];
	// begin inline asm
	dp4a.s32.s32 %r1348, %r82, %r1350, %r1340;
	// end inline asm
	ld.shared.u32 	%r1354, [%r13+3852];
	// begin inline asm
	dp4a.s32.s32 %r1352, %r90, %r1354, %r1344;
	// end inline asm
	ld.shared.u32 	%r1358, [%r13+3856];
	// begin inline asm
	dp4a.s32.s32 %r1356, %r83, %r1358, %r1348;
	// end inline asm
	ld.shared.u32 	%r1362, [%r13+3856];
	// begin inline asm
	dp4a.s32.s32 %r1360, %r91, %r1362, %r1352;
	// end inline asm
	ld.shared.u32 	%r1366, [%r13+3860];
	// begin inline asm
	dp4a.s32.s32 %r1364, %r84, %r1366, %r1356;
	// end inline asm
	ld.shared.u32 	%r1370, [%r13+3860];
	// begin inline asm
	dp4a.s32.s32 %r1368, %r92, %r1370, %r1360;
	// end inline asm
	ld.shared.u32 	%r1374, [%r13+3864];
	// begin inline asm
	dp4a.s32.s32 %r1372, %r85, %r1374, %r1364;
	// end inline asm
	ld.shared.u32 	%r1378, [%r13+3864];
	// begin inline asm
	dp4a.s32.s32 %r1376, %r93, %r1378, %r1368;
	// end inline asm
	ld.shared.u32 	%r1382, [%r13+3868];
	// begin inline asm
	dp4a.s32.s32 %r1380, %r86, %r1382, %r1372;
	// end inline asm
	ld.shared.u32 	%r1386, [%r13+3868];
	// begin inline asm
	dp4a.s32.s32 %r1384, %r94, %r1386, %r1376;
	// end inline asm
	add.s32 	%r1388, %r46, %r78;
	mul.wide.s32 	%rd90, %r1388, 4;
	add.s64 	%rd91, %rd3, %rd90;
	add.s64 	%rd92, %rd2, %rd90;
	cvt.rn.f32.s32 	%f409, %r1380;
	mul.ftz.f32 	%f410, %f33, %f409;
	ld.global.u32 	%r1389, [%rd91];
	cvt.rn.f32.s32 	%f411, %r1389;
	mul.ftz.f32 	%f412, %f34, %f411;
	sub.ftz.f32 	%f413, %f410, %f412;
	ld.global.f32 	%f414, [%rd92];
	fma.rn.ftz.f32 	%f610, %f414, %f413, %f610;
	cvt.rn.f32.s32 	%f415, %r1384;
	mul.ftz.f32 	%f416, %f35, %f415;
	mul.ftz.f32 	%f417, %f36, %f411;
	sub.ftz.f32 	%f418, %f416, %f417;
	fma.rn.ftz.f32 	%f579, %f414, %f418, %f579;

$L__BB0_57:
	bar.sync 	0;
	add.s32 	%r1678, %r1678, 1;
	setp.lt.s32 	%p49, %r1678, %r47;
	@%p49 bra 	$L__BB0_2;

$L__BB0_58:
	setp.lt.s32 	%p50, %r3, %r113;
	setp.eq.s32 	%p51, %r2, 0;
	and.pred  	%p1, %p51, %p50;
	not.pred 	%p52, %p1;
	mov.b32 	%r1390, %f657;
	mov.u32 	%r1391, 2;
	mov.u32 	%r1392, 6175;
	mov.u32 	%r1393, 4;
	mov.u32 	%r1394, -1;
	shfl.sync.down.b32 	%r1395|%p53, %r1390, %r1393, %r1392, %r1394;
	mov.b32 	%f419, %r1395;
	add.ftz.f32 	%f420, %f657, %f419;
	mov.b32 	%r1396, %f420;
	shfl.sync.down.b32 	%r1397|%p54, %r1396, %r1391, %r1392, %r1394;
	mov.b32 	%f421, %r1397;
	add.ftz.f32 	%f422, %f420, %f421;
	mov.b32 	%r1398, %f422;
	mov.u32 	%r1399, 1;
	shfl.sync.down.b32 	%r1400|%p55, %r1398, %r1399, %r1392, %r1394;
	mov.b32 	%f423, %r1400;
	add.ftz.f32 	%f163, %f422, %f423;
	mov.b32 	%r1401, %f656;
	shfl.sync.down.b32 	%r1402|%p56, %r1401, %r1393, %r1392, %r1394;
	mov.b32 	%f424, %r1402;
	add.ftz.f32 	%f425, %f656, %f424;
	mov.b32 	%r1403, %f425;
	shfl.sync.down.b32 	%r1404|%p57, %r1403, %r1391, %r1392, %r1394;
	mov.b32 	%f426, %r1404;
	add.ftz.f32 	%f427, %f425, %f426;
	mov.b32 	%r1405, %f427;
	shfl.sync.down.b32 	%r1406|%p58, %r1405, %r1399, %r1392, %r1394;
	mov.b32 	%f428, %r1406;
	add.ftz.f32 	%f164, %f427, %f428;
	setp.ge.s32 	%p59, %r4, %r114;
	or.pred  	%p60, %p52, %p59;
	@%p60 bra 	$L__BB0_60;

	mad.lo.s32 	%r1407, %r4, %r113, %r3;
	mul.wide.s32 	%rd93, %r1407, 4;
	add.s64 	%rd94, %rd5, %rd93;
	st.global.f32 	[%rd94], %f163;
	add.s64 	%rd95, %rd4, %rd93;
	st.global.f32 	[%rd95], %f164;

$L__BB0_60:
	mov.b32 	%r1408, %f658;
	shfl.sync.down.b32 	%r1413|%p61, %r1408, %r1393, %r1392, %r1394;
	mov.b32 	%f429, %r1413;
	add.ftz.f32 	%f430, %f658, %f429;
	mov.b32 	%r1414, %f430;
	shfl.sync.down.b32 	%r1415|%p62, %r1414, %r1391, %r1392, %r1394;
	mov.b32 	%f431, %r1415;
	add.ftz.f32 	%f432, %f430, %f431;
	mov.b32 	%r1416, %f432;
	shfl.sync.down.b32 	%r1418|%p63, %r1416, %r1399, %r1392, %r1394;
	mov.b32 	%f433, %r1418;
	add.ftz.f32 	%f165, %f432, %f433;
	mov.b32 	%r1419, %f655;
	shfl.sync.down.b32 	%r1420|%p64, %r1419, %r1393, %r1392, %r1394;
	mov.b32 	%f434, %r1420;
	add.ftz.f32 	%f435, %f655, %f434;
	mov.b32 	%r1421, %f435;
	shfl.sync.down.b32 	%r1422|%p65, %r1421, %r1391, %r1392, %r1394;
	mov.b32 	%f436, %r1422;
	add.ftz.f32 	%f437, %f435, %f436;
	mov.b32 	%r1423, %f437;
	shfl.sync.down.b32 	%r1424|%p66, %r1423, %r1399, %r1392, %r1394;
	mov.b32 	%f438, %r1424;
	add.ftz.f32 	%f166, %f437, %f438;
	add.s32 	%r97, %r4, 1;
	setp.ge.s32 	%p67, %r97, %r114;
	or.pred  	%p69, %p52, %p67;
	@%p69 bra 	$L__BB0_62;

	mad.lo.s32 	%r1425, %r97, %r113, %r3;
	mul.wide.s32 	%rd96, %r1425, 4;
	add.s64 	%rd97, %rd5, %rd96;
	st.global.f32 	[%rd97], %f165;
	add.s64 	%rd98, %rd4, %rd96;
	st.global.f32 	[%rd98], %f166;

$L__BB0_62:
	mov.b32 	%r1426, %f659;
	mov.u32 	%r1427, 2;
	mov.u32 	%r1428, 6175;
	mov.u32 	%r1429, 4;
	mov.u32 	%r1430, -1;
	shfl.sync.down.b32 	%r1431|%p70, %r1426, %r1429, %r1428, %r1430;
	mov.b32 	%f439, %r1431;
	add.ftz.f32 	%f440, %f659, %f439;
	mov.b32 	%r1432, %f440;
	shfl.sync.down.b32 	%r1433|%p71, %r1432, %r1427, %r1428, %r1430;
	mov.b32 	%f441, %r1433;
	add.ftz.f32 	%f442, %f440, %f441;
	mov.b32 	%r1434, %f442;
	mov.u32 	%r1435, 1;
	shfl.sync.down.b32 	%r1436|%p72, %r1434, %r1435, %r1428, %r1430;
	mov.b32 	%f443, %r1436;
	add.ftz.f32 	%f167, %f442, %f443;
	mov.b32 	%r1437, %f654;
	shfl.sync.down.b32 	%r1438|%p73, %r1437, %r1429, %r1428, %r1430;
	mov.b32 	%f444, %r1438;
	add.ftz.f32 	%f445, %f654, %f444;
	mov.b32 	%r1439, %f445;
	shfl.sync.down.b32 	%r1440|%p74, %r1439, %r1427, %r1428, %r1430;
	mov.b32 	%f446, %r1440;
	add.ftz.f32 	%f447, %f445, %f446;
	mov.b32 	%r1441, %f447;
	shfl.sync.down.b32 	%r1442|%p75, %r1441, %r1435, %r1428, %r1430;
	mov.b32 	%f448, %r1442;
	add.ftz.f32 	%f168, %f447, %f448;
	add.s32 	%r98, %r4, 2;
	setp.ge.s32 	%p76, %r98, %r114;
	or.pred  	%p78, %p52, %p76;
	@%p78 bra 	$L__BB0_64;

	mad.lo.s32 	%r1443, %r98, %r113, %r3;
	mul.wide.s32 	%rd99, %r1443, 4;
	add.s64 	%rd100, %rd5, %rd99;
	st.global.f32 	[%rd100], %f167;
	add.s64 	%rd101, %rd4, %rd99;
	st.global.f32 	[%rd101], %f168;

$L__BB0_64:
	mov.b32 	%r1444, %f660;
	shfl.sync.down.b32 	%r1449|%p79, %r1444, %r1429, %r1428, %r1430;
	mov.b32 	%f449, %r1449;
	add.ftz.f32 	%f450, %f660, %f449;
	mov.b32 	%r1450, %f450;
	shfl.sync.down.b32 	%r1451|%p80, %r1450, %r1427, %r1428, %r1430;
	mov.b32 	%f451, %r1451;
	add.ftz.f32 	%f452, %f450, %f451;
	mov.b32 	%r1452, %f452;
	shfl.sync.down.b32 	%r1454|%p81, %r1452, %r1435, %r1428, %r1430;
	mov.b32 	%f453, %r1454;
	add.ftz.f32 	%f169, %f452, %f453;
	mov.b32 	%r1455, %f653;
	shfl.sync.down.b32 	%r1456|%p82, %r1455, %r1429, %r1428, %r1430;
	mov.b32 	%f454, %r1456;
	add.ftz.f32 	%f455, %f653, %f454;
	mov.b32 	%r1457, %f455;
	shfl.sync.down.b32 	%r1458|%p83, %r1457, %r1427, %r1428, %r1430;
	mov.b32 	%f456, %r1458;
	add.ftz.f32 	%f457, %f455, %f456;
	mov.b32 	%r1459, %f457;
	shfl.sync.down.b32 	%r1460|%p84, %r1459, %r1435, %r1428, %r1430;
	mov.b32 	%f458, %r1460;
	add.ftz.f32 	%f170, %f457, %f458;
	add.s32 	%r99, %r4, 3;
	setp.ge.s32 	%p85, %r99, %r114;
	or.pred  	%p87, %p52, %p85;
	@%p87 bra 	$L__BB0_66;

	mad.lo.s32 	%r1461, %r99, %r113, %r3;
	mul.wide.s32 	%rd102, %r1461, 4;
	add.s64 	%rd103, %rd5, %rd102;
	st.global.f32 	[%rd103], %f169;
	add.s64 	%rd104, %rd4, %rd102;
	st.global.f32 	[%rd104], %f170;

$L__BB0_66:
	mov.b32 	%r1462, %f661;
	mov.u32 	%r1463, 2;
	mov.u32 	%r1464, 6175;
	mov.u32 	%r1465, 4;
	mov.u32 	%r1466, -1;
	shfl.sync.down.b32 	%r1467|%p88, %r1462, %r1465, %r1464, %r1466;
	mov.b32 	%f459, %r1467;
	add.ftz.f32 	%f460, %f661, %f459;
	mov.b32 	%r1468, %f460;
	shfl.sync.down.b32 	%r1469|%p89, %r1468, %r1463, %r1464, %r1466;
	mov.b32 	%f461, %r1469;
	add.ftz.f32 	%f462, %f460, %f461;
	mov.b32 	%r1470, %f462;
	mov.u32 	%r1471, 1;
	shfl.sync.down.b32 	%r1472|%p90, %r1470, %r1471, %r1464, %r1466;
	mov.b32 	%f463, %r1472;
	add.ftz.f32 	%f171, %f462, %f463;
	mov.b32 	%r1473, %f652;
	shfl.sync.down.b32 	%r1474|%p91, %r1473, %r1465, %r1464, %r1466;
	mov.b32 	%f464, %r1474;
	add.ftz.f32 	%f465, %f652, %f464;
	mov.b32 	%r1475, %f465;
	shfl.sync.down.b32 	%r1476|%p92, %r1475, %r1463, %r1464, %r1466;
	mov.b32 	%f466, %r1476;
	add.ftz.f32 	%f467, %f465, %f466;
	mov.b32 	%r1477, %f467;
	shfl.sync.down.b32 	%r1478|%p93, %r1477, %r1471, %r1464, %r1466;
	mov.b32 	%f468, %r1478;
	add.ftz.f32 	%f172, %f467, %f468;
	add.s32 	%r100, %r4, 4;
	setp.ge.s32 	%p94, %r100, %r114;
	or.pred  	%p96, %p52, %p94;
	@%p96 bra 	$L__BB0_68;

	mad.lo.s32 	%r1479, %r100, %r113, %r3;
	mul.wide.s32 	%rd105, %r1479, 4;
	add.s64 	%rd106, %rd5, %rd105;
	st.global.f32 	[%rd106], %f171;
	add.s64 	%rd107, %rd4, %rd105;
	st.global.f32 	[%rd107], %f172;

$L__BB0_68:
	mov.b32 	%r1480, %f662;
	shfl.sync.down.b32 	%r1485|%p97, %r1480, %r1465, %r1464, %r1466;
	mov.b32 	%f469, %r1485;
	add.ftz.f32 	%f470, %f662, %f469;
	mov.b32 	%r1486, %f470;
	shfl.sync.down.b32 	%r1487|%p98, %r1486, %r1463, %r1464, %r1466;
	mov.b32 	%f471, %r1487;
	add.ftz.f32 	%f472, %f470, %f471;
	mov.b32 	%r1488, %f472;
	shfl.sync.down.b32 	%r1490|%p99, %r1488, %r1471, %r1464, %r1466;
	mov.b32 	%f473, %r1490;
	add.ftz.f32 	%f173, %f472, %f473;
	mov.b32 	%r1491, %f651;
	shfl.sync.down.b32 	%r1492|%p100, %r1491, %r1465, %r1464, %r1466;
	mov.b32 	%f474, %r1492;
	add.ftz.f32 	%f475, %f651, %f474;
	mov.b32 	%r1493, %f475;
	shfl.sync.down.b32 	%r1494|%p101, %r1493, %r1463, %r1464, %r1466;
	mov.b32 	%f476, %r1494;
	add.ftz.f32 	%f477, %f475, %f476;
	mov.b32 	%r1495, %f477;
	shfl.sync.down.b32 	%r1496|%p102, %r1495, %r1471, %r1464, %r1466;
	mov.b32 	%f478, %r1496;
	add.ftz.f32 	%f174, %f477, %f478;
	add.s32 	%r101, %r4, 5;
	setp.ge.s32 	%p103, %r101, %r114;
	or.pred  	%p105, %p52, %p103;
	@%p105 bra 	$L__BB0_70;

	mad.lo.s32 	%r1497, %r101, %r113, %r3;
	mul.wide.s32 	%rd108, %r1497, 4;
	add.s64 	%rd109, %rd5, %rd108;
	st.global.f32 	[%rd109], %f173;
	add.s64 	%rd110, %rd4, %rd108;
	st.global.f32 	[%rd110], %f174;

$L__BB0_70:
	mov.b32 	%r1498, %f663;
	mov.u32 	%r1499, 2;
	mov.u32 	%r1500, 6175;
	mov.u32 	%r1501, 4;
	mov.u32 	%r1502, -1;
	shfl.sync.down.b32 	%r1503|%p106, %r1498, %r1501, %r1500, %r1502;
	mov.b32 	%f479, %r1503;
	add.ftz.f32 	%f480, %f663, %f479;
	mov.b32 	%r1504, %f480;
	shfl.sync.down.b32 	%r1505|%p107, %r1504, %r1499, %r1500, %r1502;
	mov.b32 	%f481, %r1505;
	add.ftz.f32 	%f482, %f480, %f481;
	mov.b32 	%r1506, %f482;
	mov.u32 	%r1507, 1;
	shfl.sync.down.b32 	%r1508|%p108, %r1506, %r1507, %r1500, %r1502;
	mov.b32 	%f483, %r1508;
	add.ftz.f32 	%f175, %f482, %f483;
	mov.b32 	%r1509, %f650;
	shfl.sync.down.b32 	%r1510|%p109, %r1509, %r1501, %r1500, %r1502;
	mov.b32 	%f484, %r1510;
	add.ftz.f32 	%f485, %f650, %f484;
	mov.b32 	%r1511, %f485;
	shfl.sync.down.b32 	%r1512|%p110, %r1511, %r1499, %r1500, %r1502;
	mov.b32 	%f486, %r1512;
	add.ftz.f32 	%f487, %f485, %f486;
	mov.b32 	%r1513, %f487;
	shfl.sync.down.b32 	%r1514|%p111, %r1513, %r1507, %r1500, %r1502;
	mov.b32 	%f488, %r1514;
	add.ftz.f32 	%f176, %f487, %f488;
	add.s32 	%r102, %r4, 6;
	setp.ge.s32 	%p112, %r102, %r114;
	or.pred  	%p114, %p52, %p112;
	@%p114 bra 	$L__BB0_72;

	mad.lo.s32 	%r1515, %r102, %r113, %r3;
	mul.wide.s32 	%rd111, %r1515, 4;
	add.s64 	%rd112, %rd5, %rd111;
	st.global.f32 	[%rd112], %f175;
	add.s64 	%rd113, %rd4, %rd111;
	st.global.f32 	[%rd113], %f176;

$L__BB0_72:
	mov.b32 	%r1516, %f664;
	shfl.sync.down.b32 	%r1521|%p115, %r1516, %r1501, %r1500, %r1502;
	mov.b32 	%f489, %r1521;
	add.ftz.f32 	%f490, %f664, %f489;
	mov.b32 	%r1522, %f490;
	shfl.sync.down.b32 	%r1523|%p116, %r1522, %r1499, %r1500, %r1502;
	mov.b32 	%f491, %r1523;
	add.ftz.f32 	%f492, %f490, %f491;
	mov.b32 	%r1524, %f492;
	shfl.sync.down.b32 	%r1526|%p117, %r1524, %r1507, %r1500, %r1502;
	mov.b32 	%f493, %r1526;
	add.ftz.f32 	%f177, %f492, %f493;
	mov.b32 	%r1527, %f649;
	shfl.sync.down.b32 	%r1528|%p118, %r1527, %r1501, %r1500, %r1502;
	mov.b32 	%f494, %r1528;
	add.ftz.f32 	%f495, %f649, %f494;
	mov.b32 	%r1529, %f495;
	shfl.sync.down.b32 	%r1530|%p119, %r1529, %r1499, %r1500, %r1502;
	mov.b32 	%f496, %r1530;
	add.ftz.f32 	%f497, %f495, %f496;
	mov.b32 	%r1531, %f497;
	shfl.sync.down.b32 	%r1532|%p120, %r1531, %r1507, %r1500, %r1502;
	mov.b32 	%f498, %r1532;
	add.ftz.f32 	%f178, %f497, %f498;
	add.s32 	%r103, %r4, 7;
	setp.ge.s32 	%p121, %r103, %r114;
	or.pred  	%p123, %p52, %p121;
	@%p123 bra 	$L__BB0_74;

	mad.lo.s32 	%r1533, %r103, %r113, %r3;
	mul.wide.s32 	%rd114, %r1533, 4;
	add.s64 	%rd115, %rd5, %rd114;
	st.global.f32 	[%rd115], %f177;
	add.s64 	%rd116, %rd4, %rd114;
	st.global.f32 	[%rd116], %f178;

$L__BB0_74:
	mov.b32 	%r1534, %f665;
	mov.u32 	%r1535, 2;
	mov.u32 	%r1536, 6175;
	mov.u32 	%r1537, 4;
	mov.u32 	%r1538, -1;
	shfl.sync.down.b32 	%r1539|%p124, %r1534, %r1537, %r1536, %r1538;
	mov.b32 	%f499, %r1539;
	add.ftz.f32 	%f500, %f665, %f499;
	mov.b32 	%r1540, %f500;
	shfl.sync.down.b32 	%r1541|%p125, %r1540, %r1535, %r1536, %r1538;
	mov.b32 	%f501, %r1541;
	add.ftz.f32 	%f502, %f500, %f501;
	mov.b32 	%r1542, %f502;
	mov.u32 	%r1543, 1;
	shfl.sync.down.b32 	%r1544|%p126, %r1542, %r1543, %r1536, %r1538;
	mov.b32 	%f503, %r1544;
	add.ftz.f32 	%f179, %f502, %f503;
	mov.b32 	%r1545, %f648;
	shfl.sync.down.b32 	%r1546|%p127, %r1545, %r1537, %r1536, %r1538;
	mov.b32 	%f504, %r1546;
	add.ftz.f32 	%f505, %f648, %f504;
	mov.b32 	%r1547, %f505;
	shfl.sync.down.b32 	%r1548|%p128, %r1547, %r1535, %r1536, %r1538;
	mov.b32 	%f506, %r1548;
	add.ftz.f32 	%f507, %f505, %f506;
	mov.b32 	%r1549, %f507;
	shfl.sync.down.b32 	%r1550|%p129, %r1549, %r1543, %r1536, %r1538;
	mov.b32 	%f508, %r1550;
	add.ftz.f32 	%f180, %f507, %f508;
	add.s32 	%r104, %r4, 8;
	setp.ge.s32 	%p130, %r104, %r114;
	or.pred  	%p132, %p52, %p130;
	@%p132 bra 	$L__BB0_76;

	mad.lo.s32 	%r1551, %r104, %r113, %r3;
	mul.wide.s32 	%rd117, %r1551, 4;
	add.s64 	%rd118, %rd5, %rd117;
	st.global.f32 	[%rd118], %f179;
	add.s64 	%rd119, %rd4, %rd117;
	st.global.f32 	[%rd119], %f180;

$L__BB0_76:
	mov.b32 	%r1552, %f666;
	shfl.sync.down.b32 	%r1557|%p133, %r1552, %r1537, %r1536, %r1538;
	mov.b32 	%f509, %r1557;
	add.ftz.f32 	%f510, %f666, %f509;
	mov.b32 	%r1558, %f510;
	shfl.sync.down.b32 	%r1559|%p134, %r1558, %r1535, %r1536, %r1538;
	mov.b32 	%f511, %r1559;
	add.ftz.f32 	%f512, %f510, %f511;
	mov.b32 	%r1560, %f512;
	shfl.sync.down.b32 	%r1562|%p135, %r1560, %r1543, %r1536, %r1538;
	mov.b32 	%f513, %r1562;
	add.ftz.f32 	%f181, %f512, %f513;
	mov.b32 	%r1563, %f647;
	shfl.sync.down.b32 	%r1564|%p136, %r1563, %r1537, %r1536, %r1538;
	mov.b32 	%f514, %r1564;
	add.ftz.f32 	%f515, %f647, %f514;
	mov.b32 	%r1565, %f515;
	shfl.sync.down.b32 	%r1566|%p137, %r1565, %r1535, %r1536, %r1538;
	mov.b32 	%f516, %r1566;
	add.ftz.f32 	%f517, %f515, %f516;
	mov.b32 	%r1567, %f517;
	shfl.sync.down.b32 	%r1568|%p138, %r1567, %r1543, %r1536, %r1538;
	mov.b32 	%f518, %r1568;
	add.ftz.f32 	%f182, %f517, %f518;
	add.s32 	%r105, %r4, 9;
	setp.ge.s32 	%p139, %r105, %r114;
	or.pred  	%p141, %p52, %p139;
	@%p141 bra 	$L__BB0_78;

	mad.lo.s32 	%r1569, %r105, %r113, %r3;
	mul.wide.s32 	%rd120, %r1569, 4;
	add.s64 	%rd121, %rd5, %rd120;
	st.global.f32 	[%rd121], %f181;
	add.s64 	%rd122, %rd4, %rd120;
	st.global.f32 	[%rd122], %f182;

$L__BB0_78:
	mov.b32 	%r1570, %f667;
	mov.u32 	%r1571, 2;
	mov.u32 	%r1572, 6175;
	mov.u32 	%r1573, 4;
	mov.u32 	%r1574, -1;
	shfl.sync.down.b32 	%r1575|%p142, %r1570, %r1573, %r1572, %r1574;
	mov.b32 	%f519, %r1575;
	add.ftz.f32 	%f520, %f667, %f519;
	mov.b32 	%r1576, %f520;
	shfl.sync.down.b32 	%r1577|%p143, %r1576, %r1571, %r1572, %r1574;
	mov.b32 	%f521, %r1577;
	add.ftz.f32 	%f522, %f520, %f521;
	mov.b32 	%r1578, %f522;
	mov.u32 	%r1579, 1;
	shfl.sync.down.b32 	%r1580|%p144, %r1578, %r1579, %r1572, %r1574;
	mov.b32 	%f523, %r1580;
	add.ftz.f32 	%f183, %f522, %f523;
	mov.b32 	%r1581, %f646;
	shfl.sync.down.b32 	%r1582|%p145, %r1581, %r1573, %r1572, %r1574;
	mov.b32 	%f524, %r1582;
	add.ftz.f32 	%f525, %f646, %f524;
	mov.b32 	%r1583, %f525;
	shfl.sync.down.b32 	%r1584|%p146, %r1583, %r1571, %r1572, %r1574;
	mov.b32 	%f526, %r1584;
	add.ftz.f32 	%f527, %f525, %f526;
	mov.b32 	%r1585, %f527;
	shfl.sync.down.b32 	%r1586|%p147, %r1585, %r1579, %r1572, %r1574;
	mov.b32 	%f528, %r1586;
	add.ftz.f32 	%f184, %f527, %f528;
	add.s32 	%r106, %r4, 10;
	setp.ge.s32 	%p148, %r106, %r114;
	or.pred  	%p150, %p52, %p148;
	@%p150 bra 	$L__BB0_80;

	mad.lo.s32 	%r1587, %r106, %r113, %r3;
	mul.wide.s32 	%rd123, %r1587, 4;
	add.s64 	%rd124, %rd5, %rd123;
	st.global.f32 	[%rd124], %f183;
	add.s64 	%rd125, %rd4, %rd123;
	st.global.f32 	[%rd125], %f184;

$L__BB0_80:
	mov.b32 	%r1588, %f668;
	shfl.sync.down.b32 	%r1593|%p151, %r1588, %r1573, %r1572, %r1574;
	mov.b32 	%f529, %r1593;
	add.ftz.f32 	%f530, %f668, %f529;
	mov.b32 	%r1594, %f530;
	shfl.sync.down.b32 	%r1595|%p152, %r1594, %r1571, %r1572, %r1574;
	mov.b32 	%f531, %r1595;
	add.ftz.f32 	%f532, %f530, %f531;
	mov.b32 	%r1596, %f532;
	shfl.sync.down.b32 	%r1598|%p153, %r1596, %r1579, %r1572, %r1574;
	mov.b32 	%f533, %r1598;
	add.ftz.f32 	%f185, %f532, %f533;
	mov.b32 	%r1599, %f645;
	shfl.sync.down.b32 	%r1600|%p154, %r1599, %r1573, %r1572, %r1574;
	mov.b32 	%f534, %r1600;
	add.ftz.f32 	%f535, %f645, %f534;
	mov.b32 	%r1601, %f535;
	shfl.sync.down.b32 	%r1602|%p155, %r1601, %r1571, %r1572, %r1574;
	mov.b32 	%f536, %r1602;
	add.ftz.f32 	%f537, %f535, %f536;
	mov.b32 	%r1603, %f537;
	shfl.sync.down.b32 	%r1604|%p156, %r1603, %r1579, %r1572, %r1574;
	mov.b32 	%f538, %r1604;
	add.ftz.f32 	%f186, %f537, %f538;
	add.s32 	%r107, %r4, 11;
	setp.ge.s32 	%p157, %r107, %r114;
	or.pred  	%p159, %p52, %p157;
	@%p159 bra 	$L__BB0_82;

	mad.lo.s32 	%r1605, %r107, %r113, %r3;
	mul.wide.s32 	%rd126, %r1605, 4;
	add.s64 	%rd127, %rd5, %rd126;
	st.global.f32 	[%rd127], %f185;
	add.s64 	%rd128, %rd4, %rd126;
	st.global.f32 	[%rd128], %f186;

$L__BB0_82:
	mov.b32 	%r1606, %f669;
	mov.u32 	%r1607, 2;
	mov.u32 	%r1608, 6175;
	mov.u32 	%r1609, 4;
	mov.u32 	%r1610, -1;
	shfl.sync.down.b32 	%r1611|%p160, %r1606, %r1609, %r1608, %r1610;
	mov.b32 	%f539, %r1611;
	add.ftz.f32 	%f540, %f669, %f539;
	mov.b32 	%r1612, %f540;
	shfl.sync.down.b32 	%r1613|%p161, %r1612, %r1607, %r1608, %r1610;
	mov.b32 	%f541, %r1613;
	add.ftz.f32 	%f542, %f540, %f541;
	mov.b32 	%r1614, %f542;
	mov.u32 	%r1615, 1;
	shfl.sync.down.b32 	%r1616|%p162, %r1614, %r1615, %r1608, %r1610;
	mov.b32 	%f543, %r1616;
	add.ftz.f32 	%f187, %f542, %f543;
	mov.b32 	%r1617, %f644;
	shfl.sync.down.b32 	%r1618|%p163, %r1617, %r1609, %r1608, %r1610;
	mov.b32 	%f544, %r1618;
	add.ftz.f32 	%f545, %f644, %f544;
	mov.b32 	%r1619, %f545;
	shfl.sync.down.b32 	%r1620|%p164, %r1619, %r1607, %r1608, %r1610;
	mov.b32 	%f546, %r1620;
	add.ftz.f32 	%f547, %f545, %f546;
	mov.b32 	%r1621, %f547;
	shfl.sync.down.b32 	%r1622|%p165, %r1621, %r1615, %r1608, %r1610;
	mov.b32 	%f548, %r1622;
	add.ftz.f32 	%f188, %f547, %f548;
	add.s32 	%r108, %r4, 12;
	setp.ge.s32 	%p166, %r108, %r114;
	or.pred  	%p168, %p52, %p166;
	@%p168 bra 	$L__BB0_84;

	mad.lo.s32 	%r1623, %r108, %r113, %r3;
	mul.wide.s32 	%rd129, %r1623, 4;
	add.s64 	%rd130, %rd5, %rd129;
	st.global.f32 	[%rd130], %f187;
	add.s64 	%rd131, %rd4, %rd129;
	st.global.f32 	[%rd131], %f188;

$L__BB0_84:
	mov.b32 	%r1624, %f670;
	shfl.sync.down.b32 	%r1629|%p169, %r1624, %r1609, %r1608, %r1610;
	mov.b32 	%f549, %r1629;
	add.ftz.f32 	%f550, %f670, %f549;
	mov.b32 	%r1630, %f550;
	shfl.sync.down.b32 	%r1631|%p170, %r1630, %r1607, %r1608, %r1610;
	mov.b32 	%f551, %r1631;
	add.ftz.f32 	%f552, %f550, %f551;
	mov.b32 	%r1632, %f552;
	shfl.sync.down.b32 	%r1634|%p171, %r1632, %r1615, %r1608, %r1610;
	mov.b32 	%f553, %r1634;
	add.ftz.f32 	%f189, %f552, %f553;
	mov.b32 	%r1635, %f643;
	shfl.sync.down.b32 	%r1636|%p172, %r1635, %r1609, %r1608, %r1610;
	mov.b32 	%f554, %r1636;
	add.ftz.f32 	%f555, %f643, %f554;
	mov.b32 	%r1637, %f555;
	shfl.sync.down.b32 	%r1638|%p173, %r1637, %r1607, %r1608, %r1610;
	mov.b32 	%f556, %r1638;
	add.ftz.f32 	%f557, %f555, %f556;
	mov.b32 	%r1639, %f557;
	shfl.sync.down.b32 	%r1640|%p174, %r1639, %r1615, %r1608, %r1610;
	mov.b32 	%f558, %r1640;
	add.ftz.f32 	%f190, %f557, %f558;
	add.s32 	%r109, %r4, 13;
	setp.ge.s32 	%p175, %r109, %r114;
	or.pred  	%p177, %p52, %p175;
	@%p177 bra 	$L__BB0_86;

	mad.lo.s32 	%r1641, %r109, %r113, %r3;
	mul.wide.s32 	%rd132, %r1641, 4;
	add.s64 	%rd133, %rd5, %rd132;
	st.global.f32 	[%rd133], %f189;
	add.s64 	%rd134, %rd4, %rd132;
	st.global.f32 	[%rd134], %f190;

$L__BB0_86:
	mov.b32 	%r1642, %f671;
	mov.u32 	%r1643, 2;
	mov.u32 	%r1644, 6175;
	mov.u32 	%r1645, 4;
	mov.u32 	%r1646, -1;
	shfl.sync.down.b32 	%r1647|%p178, %r1642, %r1645, %r1644, %r1646;
	mov.b32 	%f559, %r1647;
	add.ftz.f32 	%f560, %f671, %f559;
	mov.b32 	%r1648, %f560;
	shfl.sync.down.b32 	%r1649|%p179, %r1648, %r1643, %r1644, %r1646;
	mov.b32 	%f561, %r1649;
	add.ftz.f32 	%f562, %f560, %f561;
	mov.b32 	%r1650, %f562;
	mov.u32 	%r1651, 1;
	shfl.sync.down.b32 	%r1652|%p180, %r1650, %r1651, %r1644, %r1646;
	mov.b32 	%f563, %r1652;
	add.ftz.f32 	%f191, %f562, %f563;
	mov.b32 	%r1653, %f642;
	shfl.sync.down.b32 	%r1654|%p181, %r1653, %r1645, %r1644, %r1646;
	mov.b32 	%f564, %r1654;
	add.ftz.f32 	%f565, %f642, %f564;
	mov.b32 	%r1655, %f565;
	shfl.sync.down.b32 	%r1656|%p182, %r1655, %r1643, %r1644, %r1646;
	mov.b32 	%f566, %r1656;
	add.ftz.f32 	%f567, %f565, %f566;
	mov.b32 	%r1657, %f567;
	shfl.sync.down.b32 	%r1658|%p183, %r1657, %r1651, %r1644, %r1646;
	mov.b32 	%f568, %r1658;
	add.ftz.f32 	%f192, %f567, %f568;
	add.s32 	%r110, %r4, 14;
	setp.ge.s32 	%p184, %r110, %r114;
	or.pred  	%p186, %p52, %p184;
	@%p186 bra 	$L__BB0_88;

	mad.lo.s32 	%r1659, %r110, %r113, %r3;
	mul.wide.s32 	%rd135, %r1659, 4;
	add.s64 	%rd136, %rd5, %rd135;
	st.global.f32 	[%rd136], %f191;
	add.s64 	%rd137, %rd4, %rd135;
	st.global.f32 	[%rd137], %f192;

$L__BB0_88:
	mov.b32 	%r1660, %f610;
	shfl.sync.down.b32 	%r1665|%p187, %r1660, %r1645, %r1644, %r1646;
	mov.b32 	%f569, %r1665;
	add.ftz.f32 	%f570, %f610, %f569;
	mov.b32 	%r1666, %f570;
	shfl.sync.down.b32 	%r1667|%p188, %r1666, %r1643, %r1644, %r1646;
	mov.b32 	%f571, %r1667;
	add.ftz.f32 	%f572, %f570, %f571;
	mov.b32 	%r1668, %f572;
	shfl.sync.down.b32 	%r1670|%p189, %r1668, %r1651, %r1644, %r1646;
	mov.b32 	%f573, %r1670;
	add.ftz.f32 	%f193, %f572, %f573;
	mov.b32 	%r1671, %f579;
	shfl.sync.down.b32 	%r1672|%p190, %r1671, %r1645, %r1644, %r1646;
	mov.b32 	%f574, %r1672;
	add.ftz.f32 	%f575, %f579, %f574;
	mov.b32 	%r1673, %f575;
	shfl.sync.down.b32 	%r1674|%p191, %r1673, %r1643, %r1644, %r1646;
	mov.b32 	%f576, %r1674;
	add.ftz.f32 	%f577, %f575, %f576;
	mov.b32 	%r1675, %f577;
	shfl.sync.down.b32 	%r1676|%p192, %r1675, %r1651, %r1644, %r1646;
	mov.b32 	%f578, %r1676;
	add.ftz.f32 	%f194, %f577, %f578;
	add.s32 	%r111, %r4, 15;
	setp.ge.s32 	%p193, %r111, %r114;
	or.pred  	%p195, %p52, %p193;
	@%p195 bra 	$L__BB0_90;

	mad.lo.s32 	%r1677, %r111, %r113, %r3;
	mul.wide.s32 	%rd138, %r1677, 4;
	add.s64 	%rd139, %rd5, %rd138;
	st.global.f32 	[%rd139], %f193;
	add.s64 	%rd140, %rd4, %rd138;
	st.global.f32 	[%rd140], %f194;

$L__BB0_90:
	ret;

}

`
