package q4

// QuantizeQ81MMQ2DPTX is generated at development time from the byte-exact 2D Q8_1 packer source.
const QuantizeQ81MMQ2DPTX = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	quantize_q8_1_mmq_ds4

.visible .entry quantize_q8_1_mmq_ds4(
	.param .u64 quantize_q8_1_mmq_ds4_param_0,
	.param .u64 quantize_q8_1_mmq_ds4_param_1,
	.param .u32 quantize_q8_1_mmq_ds4_param_2,
	.param .u32 quantize_q8_1_mmq_ds4_param_3,
	.param .u32 quantize_q8_1_mmq_ds4_param_4
)
.maxntid 32, 1, 1
.minnctapersm 16
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<41>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd2, [quantize_q8_1_mmq_ds4_param_0];
	ld.param.u64 	%rd3, [quantize_q8_1_mmq_ds4_param_1];
	ld.param.u32 	%r5, [quantize_q8_1_mmq_ds4_param_2];
	ld.param.u32 	%r7, [quantize_q8_1_mmq_ds4_param_3];
	ld.param.u32 	%r6, [quantize_q8_1_mmq_ds4_param_4];
	cvta.to.global.u64 	%rd1, %rd3;
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r2, %ctaid.y;
	setp.ge.s32 	%p1, %r2, %r7;
	shr.s32 	%r8, %r5, 31;
	shr.u32 	%r9, %r8, 25;
	add.s32 	%r10, %r5, %r9;
	shr.s32 	%r11, %r10, 7;
	mov.u32 	%r3, %ctaid.x;
	setp.ge.s32 	%p2, %r3, %r11;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_6;

	shl.b32 	%r12, %r3, 7;
	shl.b32 	%r4, %r1, 2;
	mov.u32 	%r13, 2;
	add.s32 	%r14, %r12, %r4;
	mad.lo.s32 	%r15, %r2, %r5, %r14;
	cvta.to.global.u64 	%rd4, %rd2;
	mul.wide.s32 	%rd5, %r15, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.f32 	%f1, [%rd6];
	abs.ftz.f32 	%f10, %f1;
	mov.f32 	%f40, 0f00000000;
	max.ftz.f32 	%f11, %f40, %f10;
	add.ftz.f32 	%f12, %f1, 0f00000000;
	ld.global.f32 	%f2, [%rd6+4];
	abs.ftz.f32 	%f13, %f2;
	max.ftz.f32 	%f14, %f11, %f13;
	add.ftz.f32 	%f15, %f12, %f2;
	ld.global.f32 	%f3, [%rd6+8];
	abs.ftz.f32 	%f16, %f3;
	max.ftz.f32 	%f17, %f14, %f16;
	add.ftz.f32 	%f18, %f15, %f3;
	ld.global.f32 	%f4, [%rd6+12];
	abs.ftz.f32 	%f19, %f4;
	max.ftz.f32 	%f20, %f17, %f19;
	add.ftz.f32 	%f21, %f18, %f4;
	mov.b32 	%r16, %f20;
	mov.u32 	%r17, 31;
	mov.u32 	%r18, 4;
	mov.u32 	%r19, -1;
	shfl.sync.bfly.b32 	%r20|%p4, %r16, %r18, %r17, %r19;
	mov.b32 	%f22, %r20;
	max.ftz.f32 	%f23, %f20, %f22;
	mov.b32 	%r21, %f21;
	shfl.sync.bfly.b32 	%r22|%p5, %r21, %r18, %r17, %r19;
	mov.b32 	%f24, %r22;
	add.ftz.f32 	%f25, %f21, %f24;
	mov.b32 	%r23, %f23;
	shfl.sync.bfly.b32 	%r24|%p6, %r23, %r13, %r17, %r19;
	mov.b32 	%f26, %r24;
	max.ftz.f32 	%f27, %f23, %f26;
	mov.b32 	%r25, %f25;
	shfl.sync.bfly.b32 	%r26|%p7, %r25, %r13, %r17, %r19;
	mov.b32 	%f28, %r26;
	add.ftz.f32 	%f29, %f25, %f28;
	mov.b32 	%r27, %f27;
	mov.u32 	%r28, 1;
	shfl.sync.bfly.b32 	%r29|%p8, %r27, %r28, %r17, %r19;
	mov.b32 	%f30, %r29;
	max.ftz.f32 	%f31, %f27, %f30;
	mov.b32 	%r30, %f29;
	shfl.sync.bfly.b32 	%r31|%p9, %r30, %r28, %r17, %r19;
	mov.b32 	%f32, %r31;
	add.ftz.f32 	%f5, %f29, %f32;
	mov.f32 	%f33, 0f42FE0000;
	div.approx.ftz.f32 	%f6, %f31, %f33;
	setp.eq.ftz.f32 	%p10, %f6, 0f00000000;
	@%p10 bra 	$L__BB0_3;

	rcp.approx.ftz.f32 	%f40, %f6;

$L__BB0_3:
	and.b32  	%r32, %r1, 7;
	setp.eq.s32 	%p11, %r32, 0;
	@%p11 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_5;

$L__BB0_4:
	// begin inline asm
	{ cvt.rn.f16x2.f32 %r33, %f5, %f6; }

	// end inline asm
	mad.lo.s32 	%r34, %r3, %r6, %r2;
	shr.s32 	%r35, %r1, 3;
	mul.wide.s32 	%rd7, %r34, 144;
	add.s64 	%rd8, %rd1, %rd7;
	mul.wide.s32 	%rd9, %r35, 4;
	add.s64 	%rd10, %rd8, %rd9;
	st.global.u32 	[%rd10], %r33;

$L__BB0_5:
	mad.lo.s32 	%r36, %r3, %r6, %r2;
	mul.ftz.f32 	%f36, %f40, %f1;
	cvt.rni.ftz.s32.f32 	%r37, %f36;
	cvt.s64.s32 	%rd11, %r4;
	mul.wide.s32 	%rd12, %r36, 144;
	add.s64 	%rd13, %rd1, %rd12;
	add.s64 	%rd14, %rd13, %rd11;
	st.global.u8 	[%rd14+16], %r37;
	mul.ftz.f32 	%f37, %f40, %f2;
	cvt.rni.ftz.s32.f32 	%r38, %f37;
	st.global.u8 	[%rd14+17], %r38;
	mul.ftz.f32 	%f38, %f40, %f3;
	cvt.rni.ftz.s32.f32 	%r39, %f38;
	st.global.u8 	[%rd14+18], %r39;
	mul.ftz.f32 	%f39, %f40, %f4;
	cvt.rni.ftz.s32.f32 	%r40, %f39;
	st.global.u8 	[%rd14+19], %r40;

$L__BB0_6:
	ret;

}

`
