package q6

// GemmQ6PackedMMQ8PTX is generated at development time and embedded.
const GemmQ6PackedMMQ8PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q6_packed_mmq8
// _ZZ19gemm_q6_packed_mmq8E1X has been demoted

.visible .entry gemm_q6_packed_mmq8(
	.param .u64 gemm_q6_packed_mmq8_param_0,
	.param .u64 gemm_q6_packed_mmq8_param_1,
	.param .u64 gemm_q6_packed_mmq8_param_2,
	.param .u64 gemm_q6_packed_mmq8_param_3,
	.param .u64 gemm_q6_packed_mmq8_param_4,
	.param .u32 gemm_q6_packed_mmq8_param_5,
	.param .u32 gemm_q6_packed_mmq8_param_6,
	.param .u32 gemm_q6_packed_mmq8_param_7
)
{
	.reg .pred 	%p<103>;
	.reg .f32 	%f<223>;
	.reg .b32 	%r<549>;
	.reg .b64 	%rd<84>;
	// demoted variable
	.shared .align 1 .b8 _ZZ19gemm_q6_packed_mmq8E1X[2048];

	ld.param.u64 	%rd7, [gemm_q6_packed_mmq8_param_0];
	ld.param.u64 	%rd8, [gemm_q6_packed_mmq8_param_1];
	ld.param.u64 	%rd9, [gemm_q6_packed_mmq8_param_2];
	ld.param.u64 	%rd10, [gemm_q6_packed_mmq8_param_3];
	ld.param.u64 	%rd11, [gemm_q6_packed_mmq8_param_4];
	ld.param.u32 	%r87, [gemm_q6_packed_mmq8_param_5];
	ld.param.u32 	%r88, [gemm_q6_packed_mmq8_param_6];
	ld.param.u32 	%r89, [gemm_q6_packed_mmq8_param_7];
	cvta.to.global.u64 	%rd1, %rd7;
	cvta.to.global.u64 	%rd2, %rd8;
	cvta.to.global.u64 	%rd3, %rd10;
	cvta.to.global.u64 	%rd4, %rd9;
	cvta.to.global.u64 	%rd5, %rd11;
	mov.u32 	%r1, %tid.x;
	shr.s32 	%r90, %r1, 5;
	and.b32  	%r91, %r1, 31;
	shr.u32 	%r92, %r91, 3;
	and.b32  	%r2, %r1, 7;
	mov.u32 	%r93, %ctaid.x;
	shl.b32 	%r94, %r93, 5;
	shl.b32 	%r95, %r90, 2;
	add.s32 	%r96, %r95, %r94;
	or.b32  	%r3, %r96, %r92;
	mov.u32 	%r97, %ctaid.y;
	shl.b32 	%r4, %r97, 3;
	shr.s32 	%r98, %r87, 31;
	shr.u32 	%r99, %r98, 28;
	add.s32 	%r100, %r87, %r99;
	shr.s32 	%r5, %r100, 4;
	setp.lt.s32 	%p2, %r87, 16;
	mov.f32 	%f207, 0f00000000;
	mov.f32 	%f208, %f207;
	mov.f32 	%f209, %f207;
	mov.f32 	%f210, %f207;
	mov.f32 	%f211, %f207;
	mov.f32 	%f212, %f207;
	mov.f32 	%f213, %f207;
	mov.f32 	%f214, %f207;
	@%p2 bra 	$L__BB0_59;

	mul.lo.s32 	%r102, %r3, %r87;
	cvt.s64.s32 	%rd6, %r102;
	mul.lo.s32 	%r6, %r5, %r3;
	max.s32 	%r103, %r1, 1792;
	add.s32 	%r104, %r103, 255;
	sub.s32 	%r7, %r104, %r1;
	shr.u32 	%r105, %r7, 8;
	add.s32 	%r106, %r105, 1;
	and.b32  	%r8, %r106, 3;
	shr.s32 	%r107, %r1, 8;
	add.s32 	%r9, %r107, %r4;
	mul.lo.s32 	%r10, %r9, %r87;
	and.b32  	%r11, %r1, 255;
	and.b32  	%r108, %r1, -256;
	mov.u32 	%r109, _ZZ19gemm_q6_packed_mmq8E1X;
	add.s32 	%r110, %r109, %r108;
	add.s32 	%r12, %r110, %r11;
	shl.b32 	%r111, %r2, 4;
	add.s32 	%r13, %r109, %r111;
	add.s32 	%r14, %r4, 1;
	add.s32 	%r15, %r1, 256;
	shr.s32 	%r112, %r15, 8;
	and.b32  	%r113, %r15, 255;
	add.s32 	%r16, %r112, %r4;
	mul.lo.s32 	%r17, %r4, %r5;
	add.s32 	%r18, %r17, %r5;
	add.s32 	%r19, %r4, 2;
	mul.lo.s32 	%r20, %r16, %r87;
	and.b32  	%r114, %r15, -256;
	add.s32 	%r115, %r109, %r114;
	add.s32 	%r21, %r115, %r113;
	shl.b32 	%r116, %r5, 1;
	add.s32 	%r22, %r17, %r116;
	add.s32 	%r23, %r4, 3;
	add.s32 	%r24, %r1, 512;
	shr.s32 	%r117, %r24, 8;
	and.b32  	%r118, %r24, 255;
	add.s32 	%r25, %r117, %r4;
	add.s32 	%r26, %r18, %r116;
	add.s32 	%r27, %r4, 4;
	mul.lo.s32 	%r28, %r25, %r87;
	and.b32  	%r119, %r24, -256;
	add.s32 	%r120, %r109, %r119;
	add.s32 	%r29, %r120, %r118;
	add.s32 	%r31, %r22, %r116;
	add.s32 	%r32, %r4, 5;
	add.s32 	%r33, %r26, %r116;
	add.s32 	%r34, %r4, 6;
	add.s32 	%r35, %r31, %r116;
	add.s32 	%r36, %r4, 7;
	add.s32 	%r37, %r33, %r116;
	add.s32 	%r121, %r5, 15;
	shr.s32 	%r122, %r121, 31;
	shr.u32 	%r123, %r122, 28;
	add.s32 	%r124, %r121, %r123;
	shr.s32 	%r38, %r124, 4;
	mov.u32 	%r539, 0;
	mov.f32 	%f207, 0f00000000;

$L__BB0_2:
	setp.gt.s32 	%p3, %r1, 2047;
	@%p3 bra 	$L__BB0_24;

	setp.eq.s32 	%p4, %r8, 0;
	mov.u32 	%r543, %r1;
	@%p4 bra 	$L__BB0_13;

	shl.b32 	%r537, %r539, 8;
	and.b32  	%r533, %r1, 255;
	shr.s32 	%r532, %r1, 8;
	add.s32 	%r531, %r532, %r4;
	setp.ge.s32 	%p5, %r531, %r89;
	add.s32 	%r41, %r533, %r537;
	setp.ge.s32 	%p6, %r41, %r87;
	mov.u32 	%r540, 0;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB0_6;

	add.s32 	%r126, %r41, %r10;
	cvt.s64.s32 	%rd12, %r126;
	add.s64 	%rd13, %rd1, %rd12;
	ld.global.s8 	%r540, [%rd13];

$L__BB0_6:
	add.s32 	%r543, %r1, 256;
	st.shared.u8 	[%r12], %r540;
	setp.eq.s32 	%p8, %r8, 1;
	@%p8 bra 	$L__BB0_13;

	setp.ge.s32 	%p10, %r16, %r89;
	mov.u32 	%r541, 0;
	or.pred  	%p11, %p10, %p6;
	@%p11 bra 	$L__BB0_9;

	add.s32 	%r128, %r41, %r20;
	cvt.s64.s32 	%rd14, %r128;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.s8 	%r541, [%rd15];

$L__BB0_9:
	add.s32 	%r543, %r1, 512;
	st.shared.u8 	[%r21], %r541;
	setp.eq.s32 	%p12, %r8, 2;
	@%p12 bra 	$L__BB0_13;

	setp.ge.s32 	%p14, %r25, %r89;
	mov.u32 	%r542, 0;
	or.pred  	%p15, %p14, %p6;
	@%p15 bra 	$L__BB0_12;

	add.s32 	%r130, %r41, %r28;
	cvt.s64.s32 	%rd16, %r130;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.s8 	%r542, [%rd17];

$L__BB0_12:
	add.s32 	%r543, %r1, 768;
	st.shared.u8 	[%r29], %r542;

$L__BB0_13:
	setp.lt.u32 	%p16, %r7, 768;
	@%p16 bra 	$L__BB0_24;

	shl.b32 	%r538, %r539, 8;
	and.b32  	%r49, %r543, 255;
	add.s32 	%r50, %r49, %r538;

$L__BB0_15:
	shr.s32 	%r52, %r543, 8;
	add.s32 	%r53, %r52, %r4;
	setp.ge.s32 	%p17, %r53, %r89;
	setp.ge.s32 	%p18, %r50, %r87;
	mov.u32 	%r546, 0;
	or.pred  	%p19, %p17, %p18;
	mov.u32 	%r545, %r546;
	@%p19 bra 	$L__BB0_17;

	mad.lo.s32 	%r132, %r53, %r87, %r50;
	cvt.s64.s32 	%rd18, %r132;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.s8 	%r545, [%rd19];

$L__BB0_17:
	shl.b32 	%r134, %r52, 8;
	add.s32 	%r136, %r109, %r134;
	add.s32 	%r137, %r136, %r49;
	st.shared.u8 	[%r137], %r545;
	add.s32 	%r138, %r543, 256;
	shr.s32 	%r56, %r138, 8;
	add.s32 	%r57, %r56, %r4;
	setp.ge.s32 	%p20, %r57, %r89;
	or.pred  	%p22, %p20, %p18;
	@%p22 bra 	$L__BB0_19;

	mad.lo.s32 	%r139, %r57, %r87, %r50;
	cvt.s64.s32 	%rd20, %r139;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.s8 	%r546, [%rd21];

$L__BB0_19:
	shl.b32 	%r141, %r56, 8;
	add.s32 	%r143, %r109, %r141;
	add.s32 	%r144, %r143, %r49;
	mov.u32 	%r548, 0;
	st.shared.u8 	[%r144], %r546;
	add.s32 	%r145, %r543, 512;
	shr.s32 	%r60, %r145, 8;
	add.s32 	%r61, %r60, %r4;
	setp.ge.s32 	%p23, %r61, %r89;
	or.pred  	%p25, %p23, %p18;
	mov.u32 	%r547, %r548;
	@%p25 bra 	$L__BB0_21;

	mad.lo.s32 	%r146, %r61, %r87, %r50;
	cvt.s64.s32 	%rd22, %r146;
	add.s64 	%rd23, %rd1, %rd22;
	ld.global.s8 	%r547, [%rd23];

$L__BB0_21:
	shl.b32 	%r148, %r60, 8;
	add.s32 	%r150, %r109, %r148;
	add.s32 	%r151, %r150, %r49;
	st.shared.u8 	[%r151], %r547;
	add.s32 	%r152, %r543, 768;
	shr.s32 	%r64, %r152, 8;
	add.s32 	%r65, %r64, %r4;
	setp.ge.s32 	%p26, %r65, %r89;
	or.pred  	%p28, %p26, %p18;
	@%p28 bra 	$L__BB0_23;

	mad.lo.s32 	%r153, %r65, %r87, %r50;
	cvt.s64.s32 	%rd24, %r153;
	add.s64 	%rd25, %rd1, %rd24;
	ld.global.s8 	%r548, [%rd25];

$L__BB0_23:
	shl.b32 	%r154, %r64, 8;
	add.s32 	%r156, %r109, %r154;
	add.s32 	%r157, %r156, %r49;
	st.shared.u8 	[%r157], %r548;
	add.s32 	%r68, %r543, 1024;
	setp.lt.s32 	%p29, %r543, 1024;
	mov.u32 	%r543, %r68;
	@%p29 bra 	$L__BB0_15;

$L__BB0_24:
	setp.ge.s32 	%p30, %r3, %r88;
	bar.sync 	0;
	shl.b32 	%r158, %r539, 4;
	or.b32  	%r69, %r158, %r2;
	setp.ge.s32 	%p31, %r69, %r5;
	or.pred  	%p32, %p30, %p31;
	@%p32 bra 	$L__BB0_41;

	setp.ge.s32 	%p33, %r4, %r89;
	shl.b32 	%r159, %r69, 4;
	cvt.s64.s32 	%rd26, %r159;
	add.s64 	%rd27, %rd26, %rd6;
	add.s64 	%rd28, %rd4, %rd27;
	ld.global.u32 	%r70, [%rd28];
	ld.global.u32 	%r71, [%rd28+4];
	ld.global.u32 	%r72, [%rd28+8];
	ld.global.u32 	%r73, [%rd28+12];
	add.s32 	%r160, %r69, %r6;
	mul.wide.s32 	%rd29, %r160, 4;
	add.s64 	%rd30, %rd3, %rd29;
	ld.global.f32 	%f9, [%rd30];
	@%p33 bra 	$L__BB0_27;

	ld.shared.u32 	%r163, [%r13];
	mov.u32 	%r164, 0;
	// begin inline asm
	dp4a.s32.s32 %r161, %r70, %r163, %r164;
	// end inline asm
	ld.shared.u32 	%r167, [%r13+4];
	// begin inline asm
	dp4a.s32.s32 %r165, %r71, %r167, %r161;
	// end inline asm
	ld.shared.u32 	%r171, [%r13+8];
	// begin inline asm
	dp4a.s32.s32 %r169, %r72, %r171, %r165;
	// end inline asm
	ld.shared.u32 	%r175, [%r13+12];
	// begin inline asm
	dp4a.s32.s32 %r173, %r73, %r175, %r169;
	// end inline asm
	cvt.rn.f32.s32 	%f89, %r173;
	mul.ftz.f32 	%f90, %f9, %f89;
	add.s32 	%r177, %r17, %r69;
	mul.wide.s32 	%rd31, %r177, 4;
	add.s64 	%rd32, %rd2, %rd31;
	ld.global.f32 	%f91, [%rd32];
	fma.rn.ftz.f32 	%f214, %f91, %f90, %f214;

$L__BB0_27:
	setp.ge.s32 	%p34, %r14, %r89;
	@%p34 bra 	$L__BB0_29;

	ld.shared.u32 	%r180, [%r13+256];
	mov.u32 	%r181, 0;
	// begin inline asm
	dp4a.s32.s32 %r178, %r70, %r180, %r181;
	// end inline asm
	ld.shared.u32 	%r184, [%r13+260];
	// begin inline asm
	dp4a.s32.s32 %r182, %r71, %r184, %r178;
	// end inline asm
	ld.shared.u32 	%r188, [%r13+264];
	// begin inline asm
	dp4a.s32.s32 %r186, %r72, %r188, %r182;
	// end inline asm
	ld.shared.u32 	%r192, [%r13+268];
	// begin inline asm
	dp4a.s32.s32 %r190, %r73, %r192, %r186;
	// end inline asm
	cvt.rn.f32.s32 	%f92, %r190;
	mul.ftz.f32 	%f93, %f9, %f92;
	add.s32 	%r194, %r18, %r69;
	mul.wide.s32 	%rd33, %r194, 4;
	add.s64 	%rd34, %rd2, %rd33;
	ld.global.f32 	%f94, [%rd34];
	fma.rn.ftz.f32 	%f213, %f94, %f93, %f213;

$L__BB0_29:
	setp.ge.s32 	%p35, %r19, %r89;
	@%p35 bra 	$L__BB0_31;

	ld.shared.u32 	%r197, [%r13+512];
	mov.u32 	%r198, 0;
	// begin inline asm
	dp4a.s32.s32 %r195, %r70, %r197, %r198;
	// end inline asm
	ld.shared.u32 	%r201, [%r13+516];
	// begin inline asm
	dp4a.s32.s32 %r199, %r71, %r201, %r195;
	// end inline asm
	ld.shared.u32 	%r205, [%r13+520];
	// begin inline asm
	dp4a.s32.s32 %r203, %r72, %r205, %r199;
	// end inline asm
	ld.shared.u32 	%r209, [%r13+524];
	// begin inline asm
	dp4a.s32.s32 %r207, %r73, %r209, %r203;
	// end inline asm
	cvt.rn.f32.s32 	%f95, %r207;
	mul.ftz.f32 	%f96, %f9, %f95;
	add.s32 	%r211, %r22, %r69;
	mul.wide.s32 	%rd35, %r211, 4;
	add.s64 	%rd36, %rd2, %rd35;
	ld.global.f32 	%f97, [%rd36];
	fma.rn.ftz.f32 	%f212, %f97, %f96, %f212;

$L__BB0_31:
	setp.ge.s32 	%p36, %r23, %r89;
	@%p36 bra 	$L__BB0_33;

	ld.shared.u32 	%r214, [%r13+768];
	mov.u32 	%r215, 0;
	// begin inline asm
	dp4a.s32.s32 %r212, %r70, %r214, %r215;
	// end inline asm
	ld.shared.u32 	%r218, [%r13+772];
	// begin inline asm
	dp4a.s32.s32 %r216, %r71, %r218, %r212;
	// end inline asm
	ld.shared.u32 	%r222, [%r13+776];
	// begin inline asm
	dp4a.s32.s32 %r220, %r72, %r222, %r216;
	// end inline asm
	ld.shared.u32 	%r226, [%r13+780];
	// begin inline asm
	dp4a.s32.s32 %r224, %r73, %r226, %r220;
	// end inline asm
	cvt.rn.f32.s32 	%f98, %r224;
	mul.ftz.f32 	%f99, %f9, %f98;
	add.s32 	%r228, %r26, %r69;
	mul.wide.s32 	%rd37, %r228, 4;
	add.s64 	%rd38, %rd2, %rd37;
	ld.global.f32 	%f100, [%rd38];
	fma.rn.ftz.f32 	%f211, %f100, %f99, %f211;

$L__BB0_33:
	setp.ge.s32 	%p37, %r27, %r89;
	@%p37 bra 	$L__BB0_35;

	ld.shared.u32 	%r231, [%r13+1024];
	mov.u32 	%r232, 0;
	// begin inline asm
	dp4a.s32.s32 %r229, %r70, %r231, %r232;
	// end inline asm
	ld.shared.u32 	%r235, [%r13+1028];
	// begin inline asm
	dp4a.s32.s32 %r233, %r71, %r235, %r229;
	// end inline asm
	ld.shared.u32 	%r239, [%r13+1032];
	// begin inline asm
	dp4a.s32.s32 %r237, %r72, %r239, %r233;
	// end inline asm
	ld.shared.u32 	%r243, [%r13+1036];
	// begin inline asm
	dp4a.s32.s32 %r241, %r73, %r243, %r237;
	// end inline asm
	cvt.rn.f32.s32 	%f101, %r241;
	mul.ftz.f32 	%f102, %f9, %f101;
	add.s32 	%r245, %r31, %r69;
	mul.wide.s32 	%rd39, %r245, 4;
	add.s64 	%rd40, %rd2, %rd39;
	ld.global.f32 	%f103, [%rd40];
	fma.rn.ftz.f32 	%f210, %f103, %f102, %f210;

$L__BB0_35:
	setp.ge.s32 	%p38, %r32, %r89;
	@%p38 bra 	$L__BB0_37;

	ld.shared.u32 	%r248, [%r13+1280];
	mov.u32 	%r249, 0;
	// begin inline asm
	dp4a.s32.s32 %r246, %r70, %r248, %r249;
	// end inline asm
	ld.shared.u32 	%r252, [%r13+1284];
	// begin inline asm
	dp4a.s32.s32 %r250, %r71, %r252, %r246;
	// end inline asm
	ld.shared.u32 	%r256, [%r13+1288];
	// begin inline asm
	dp4a.s32.s32 %r254, %r72, %r256, %r250;
	// end inline asm
	ld.shared.u32 	%r260, [%r13+1292];
	// begin inline asm
	dp4a.s32.s32 %r258, %r73, %r260, %r254;
	// end inline asm
	cvt.rn.f32.s32 	%f104, %r258;
	mul.ftz.f32 	%f105, %f9, %f104;
	add.s32 	%r262, %r33, %r69;
	mul.wide.s32 	%rd41, %r262, 4;
	add.s64 	%rd42, %rd2, %rd41;
	ld.global.f32 	%f106, [%rd42];
	fma.rn.ftz.f32 	%f209, %f106, %f105, %f209;

$L__BB0_37:
	setp.ge.s32 	%p39, %r34, %r89;
	@%p39 bra 	$L__BB0_39;

	ld.shared.u32 	%r265, [%r13+1536];
	mov.u32 	%r266, 0;
	// begin inline asm
	dp4a.s32.s32 %r263, %r70, %r265, %r266;
	// end inline asm
	ld.shared.u32 	%r269, [%r13+1540];
	// begin inline asm
	dp4a.s32.s32 %r267, %r71, %r269, %r263;
	// end inline asm
	ld.shared.u32 	%r273, [%r13+1544];
	// begin inline asm
	dp4a.s32.s32 %r271, %r72, %r273, %r267;
	// end inline asm
	ld.shared.u32 	%r277, [%r13+1548];
	// begin inline asm
	dp4a.s32.s32 %r275, %r73, %r277, %r271;
	// end inline asm
	cvt.rn.f32.s32 	%f107, %r275;
	mul.ftz.f32 	%f108, %f9, %f107;
	add.s32 	%r279, %r35, %r69;
	mul.wide.s32 	%rd43, %r279, 4;
	add.s64 	%rd44, %rd2, %rd43;
	ld.global.f32 	%f109, [%rd44];
	fma.rn.ftz.f32 	%f208, %f109, %f108, %f208;

$L__BB0_39:
	setp.ge.s32 	%p40, %r36, %r89;
	@%p40 bra 	$L__BB0_41;

	ld.shared.u32 	%r282, [%r13+1792];
	mov.u32 	%r283, 0;
	// begin inline asm
	dp4a.s32.s32 %r280, %r70, %r282, %r283;
	// end inline asm
	ld.shared.u32 	%r286, [%r13+1796];
	// begin inline asm
	dp4a.s32.s32 %r284, %r71, %r286, %r280;
	// end inline asm
	ld.shared.u32 	%r290, [%r13+1800];
	// begin inline asm
	dp4a.s32.s32 %r288, %r72, %r290, %r284;
	// end inline asm
	ld.shared.u32 	%r294, [%r13+1804];
	// begin inline asm
	dp4a.s32.s32 %r292, %r73, %r294, %r288;
	// end inline asm
	cvt.rn.f32.s32 	%f110, %r292;
	mul.ftz.f32 	%f111, %f9, %f110;
	add.s32 	%r296, %r37, %r69;
	mul.wide.s32 	%rd45, %r296, 4;
	add.s64 	%rd46, %rd2, %rd45;
	ld.global.f32 	%f112, [%rd46];
	fma.rn.ftz.f32 	%f207, %f112, %f111, %f207;

$L__BB0_41:
	add.s32 	%r74, %r69, 8;
	setp.ge.s32 	%p41, %r74, %r5;
	or.pred  	%p43, %p30, %p41;
	@%p43 bra 	$L__BB0_58;

	setp.ge.s32 	%p44, %r4, %r89;
	shl.b32 	%r297, %r74, 4;
	cvt.s64.s32 	%rd47, %r297;
	add.s64 	%rd48, %rd47, %rd6;
	add.s64 	%rd49, %rd4, %rd48;
	ld.global.u32 	%r75, [%rd49];
	ld.global.u32 	%r76, [%rd49+4];
	ld.global.u32 	%r77, [%rd49+8];
	ld.global.u32 	%r78, [%rd49+12];
	add.s32 	%r298, %r74, %r6;
	mul.wide.s32 	%rd50, %r298, 4;
	add.s64 	%rd51, %rd3, %rd50;
	ld.global.f32 	%f33, [%rd51];
	@%p44 bra 	$L__BB0_44;

	ld.shared.u32 	%r301, [%r13+128];
	mov.u32 	%r302, 0;
	// begin inline asm
	dp4a.s32.s32 %r299, %r75, %r301, %r302;
	// end inline asm
	ld.shared.u32 	%r305, [%r13+132];
	// begin inline asm
	dp4a.s32.s32 %r303, %r76, %r305, %r299;
	// end inline asm
	ld.shared.u32 	%r309, [%r13+136];
	// begin inline asm
	dp4a.s32.s32 %r307, %r77, %r309, %r303;
	// end inline asm
	ld.shared.u32 	%r313, [%r13+140];
	// begin inline asm
	dp4a.s32.s32 %r311, %r78, %r313, %r307;
	// end inline asm
	cvt.rn.f32.s32 	%f113, %r311;
	mul.ftz.f32 	%f114, %f33, %f113;
	add.s32 	%r315, %r17, %r74;
	mul.wide.s32 	%rd52, %r315, 4;
	add.s64 	%rd53, %rd2, %rd52;
	ld.global.f32 	%f115, [%rd53];
	fma.rn.ftz.f32 	%f214, %f115, %f114, %f214;

$L__BB0_44:
	setp.ge.s32 	%p45, %r14, %r89;
	@%p45 bra 	$L__BB0_46;

	ld.shared.u32 	%r318, [%r13+384];
	mov.u32 	%r319, 0;
	// begin inline asm
	dp4a.s32.s32 %r316, %r75, %r318, %r319;
	// end inline asm
	ld.shared.u32 	%r322, [%r13+388];
	// begin inline asm
	dp4a.s32.s32 %r320, %r76, %r322, %r316;
	// end inline asm
	ld.shared.u32 	%r326, [%r13+392];
	// begin inline asm
	dp4a.s32.s32 %r324, %r77, %r326, %r320;
	// end inline asm
	ld.shared.u32 	%r330, [%r13+396];
	// begin inline asm
	dp4a.s32.s32 %r328, %r78, %r330, %r324;
	// end inline asm
	cvt.rn.f32.s32 	%f116, %r328;
	mul.ftz.f32 	%f117, %f33, %f116;
	add.s32 	%r332, %r18, %r74;
	mul.wide.s32 	%rd54, %r332, 4;
	add.s64 	%rd55, %rd2, %rd54;
	ld.global.f32 	%f118, [%rd55];
	fma.rn.ftz.f32 	%f213, %f118, %f117, %f213;

$L__BB0_46:
	setp.ge.s32 	%p46, %r19, %r89;
	@%p46 bra 	$L__BB0_48;

	ld.shared.u32 	%r335, [%r13+640];
	mov.u32 	%r336, 0;
	// begin inline asm
	dp4a.s32.s32 %r333, %r75, %r335, %r336;
	// end inline asm
	ld.shared.u32 	%r339, [%r13+644];
	// begin inline asm
	dp4a.s32.s32 %r337, %r76, %r339, %r333;
	// end inline asm
	ld.shared.u32 	%r343, [%r13+648];
	// begin inline asm
	dp4a.s32.s32 %r341, %r77, %r343, %r337;
	// end inline asm
	ld.shared.u32 	%r347, [%r13+652];
	// begin inline asm
	dp4a.s32.s32 %r345, %r78, %r347, %r341;
	// end inline asm
	cvt.rn.f32.s32 	%f119, %r345;
	mul.ftz.f32 	%f120, %f33, %f119;
	add.s32 	%r349, %r22, %r74;
	mul.wide.s32 	%rd56, %r349, 4;
	add.s64 	%rd57, %rd2, %rd56;
	ld.global.f32 	%f121, [%rd57];
	fma.rn.ftz.f32 	%f212, %f121, %f120, %f212;

$L__BB0_48:
	setp.ge.s32 	%p47, %r23, %r89;
	@%p47 bra 	$L__BB0_50;

	ld.shared.u32 	%r352, [%r13+896];
	mov.u32 	%r353, 0;
	// begin inline asm
	dp4a.s32.s32 %r350, %r75, %r352, %r353;
	// end inline asm
	ld.shared.u32 	%r356, [%r13+900];
	// begin inline asm
	dp4a.s32.s32 %r354, %r76, %r356, %r350;
	// end inline asm
	ld.shared.u32 	%r360, [%r13+904];
	// begin inline asm
	dp4a.s32.s32 %r358, %r77, %r360, %r354;
	// end inline asm
	ld.shared.u32 	%r364, [%r13+908];
	// begin inline asm
	dp4a.s32.s32 %r362, %r78, %r364, %r358;
	// end inline asm
	cvt.rn.f32.s32 	%f122, %r362;
	mul.ftz.f32 	%f123, %f33, %f122;
	add.s32 	%r366, %r26, %r74;
	mul.wide.s32 	%rd58, %r366, 4;
	add.s64 	%rd59, %rd2, %rd58;
	ld.global.f32 	%f124, [%rd59];
	fma.rn.ftz.f32 	%f211, %f124, %f123, %f211;

$L__BB0_50:
	setp.ge.s32 	%p48, %r27, %r89;
	@%p48 bra 	$L__BB0_52;

	ld.shared.u32 	%r369, [%r13+1152];
	mov.u32 	%r370, 0;
	// begin inline asm
	dp4a.s32.s32 %r367, %r75, %r369, %r370;
	// end inline asm
	ld.shared.u32 	%r373, [%r13+1156];
	// begin inline asm
	dp4a.s32.s32 %r371, %r76, %r373, %r367;
	// end inline asm
	ld.shared.u32 	%r377, [%r13+1160];
	// begin inline asm
	dp4a.s32.s32 %r375, %r77, %r377, %r371;
	// end inline asm
	ld.shared.u32 	%r381, [%r13+1164];
	// begin inline asm
	dp4a.s32.s32 %r379, %r78, %r381, %r375;
	// end inline asm
	cvt.rn.f32.s32 	%f125, %r379;
	mul.ftz.f32 	%f126, %f33, %f125;
	add.s32 	%r383, %r31, %r74;
	mul.wide.s32 	%rd60, %r383, 4;
	add.s64 	%rd61, %rd2, %rd60;
	ld.global.f32 	%f127, [%rd61];
	fma.rn.ftz.f32 	%f210, %f127, %f126, %f210;

$L__BB0_52:
	setp.ge.s32 	%p49, %r32, %r89;
	@%p49 bra 	$L__BB0_54;

	ld.shared.u32 	%r386, [%r13+1408];
	mov.u32 	%r387, 0;
	// begin inline asm
	dp4a.s32.s32 %r384, %r75, %r386, %r387;
	// end inline asm
	ld.shared.u32 	%r390, [%r13+1412];
	// begin inline asm
	dp4a.s32.s32 %r388, %r76, %r390, %r384;
	// end inline asm
	ld.shared.u32 	%r394, [%r13+1416];
	// begin inline asm
	dp4a.s32.s32 %r392, %r77, %r394, %r388;
	// end inline asm
	ld.shared.u32 	%r398, [%r13+1420];
	// begin inline asm
	dp4a.s32.s32 %r396, %r78, %r398, %r392;
	// end inline asm
	cvt.rn.f32.s32 	%f128, %r396;
	mul.ftz.f32 	%f129, %f33, %f128;
	add.s32 	%r400, %r33, %r74;
	mul.wide.s32 	%rd62, %r400, 4;
	add.s64 	%rd63, %rd2, %rd62;
	ld.global.f32 	%f130, [%rd63];
	fma.rn.ftz.f32 	%f209, %f130, %f129, %f209;

$L__BB0_54:
	setp.ge.s32 	%p50, %r34, %r89;
	@%p50 bra 	$L__BB0_56;

	ld.shared.u32 	%r403, [%r13+1664];
	mov.u32 	%r404, 0;
	// begin inline asm
	dp4a.s32.s32 %r401, %r75, %r403, %r404;
	// end inline asm
	ld.shared.u32 	%r407, [%r13+1668];
	// begin inline asm
	dp4a.s32.s32 %r405, %r76, %r407, %r401;
	// end inline asm
	ld.shared.u32 	%r411, [%r13+1672];
	// begin inline asm
	dp4a.s32.s32 %r409, %r77, %r411, %r405;
	// end inline asm
	ld.shared.u32 	%r415, [%r13+1676];
	// begin inline asm
	dp4a.s32.s32 %r413, %r78, %r415, %r409;
	// end inline asm
	cvt.rn.f32.s32 	%f131, %r413;
	mul.ftz.f32 	%f132, %f33, %f131;
	add.s32 	%r417, %r35, %r74;
	mul.wide.s32 	%rd64, %r417, 4;
	add.s64 	%rd65, %rd2, %rd64;
	ld.global.f32 	%f133, [%rd65];
	fma.rn.ftz.f32 	%f208, %f133, %f132, %f208;

$L__BB0_56:
	setp.ge.s32 	%p51, %r36, %r89;
	@%p51 bra 	$L__BB0_58;

	ld.shared.u32 	%r420, [%r13+1920];
	mov.u32 	%r421, 0;
	// begin inline asm
	dp4a.s32.s32 %r418, %r75, %r420, %r421;
	// end inline asm
	ld.shared.u32 	%r424, [%r13+1924];
	// begin inline asm
	dp4a.s32.s32 %r422, %r76, %r424, %r418;
	// end inline asm
	ld.shared.u32 	%r428, [%r13+1928];
	// begin inline asm
	dp4a.s32.s32 %r426, %r77, %r428, %r422;
	// end inline asm
	ld.shared.u32 	%r432, [%r13+1932];
	// begin inline asm
	dp4a.s32.s32 %r430, %r78, %r432, %r426;
	// end inline asm
	cvt.rn.f32.s32 	%f134, %r430;
	mul.ftz.f32 	%f135, %f33, %f134;
	add.s32 	%r434, %r37, %r74;
	mul.wide.s32 	%rd66, %r434, 4;
	add.s64 	%rd67, %rd2, %rd66;
	ld.global.f32 	%f136, [%rd67];
	fma.rn.ftz.f32 	%f207, %f136, %f135, %f207;

$L__BB0_58:
	bar.sync 	0;
	add.s32 	%r539, %r539, 1;
	setp.lt.s32 	%p52, %r539, %r38;
	@%p52 bra 	$L__BB0_2;

$L__BB0_59:
	setp.lt.s32 	%p53, %r3, %r88;
	setp.eq.s32 	%p54, %r2, 0;
	and.pred  	%p1, %p54, %p53;
	not.pred 	%p55, %p1;
	mov.b32 	%r435, %f214;
	mov.u32 	%r436, 2;
	mov.u32 	%r437, 6175;
	mov.u32 	%r438, 4;
	mov.u32 	%r439, -1;
	shfl.sync.down.b32 	%r440|%p56, %r435, %r438, %r437, %r439;
	mov.b32 	%f137, %r440;
	add.ftz.f32 	%f138, %f214, %f137;
	mov.b32 	%r441, %f138;
	shfl.sync.down.b32 	%r442|%p57, %r441, %r436, %r437, %r439;
	mov.b32 	%f139, %r442;
	add.ftz.f32 	%f140, %f138, %f139;
	mov.b32 	%r443, %f140;
	mov.u32 	%r444, 1;
	shfl.sync.down.b32 	%r445|%p58, %r443, %r444, %r437, %r439;
	mov.b32 	%f141, %r445;
	add.ftz.f32 	%f65, %f140, %f141;
	setp.ge.s32 	%p59, %r4, %r89;
	or.pred  	%p60, %p55, %p59;
	@%p60 bra 	$L__BB0_61;

	mad.lo.s32 	%r446, %r4, %r88, %r3;
	mul.wide.s32 	%rd68, %r446, 4;
	add.s64 	%rd69, %rd5, %rd68;
	st.global.f32 	[%rd69], %f65;

$L__BB0_61:
	mov.b32 	%r447, %f213;
	shfl.sync.down.b32 	%r452|%p61, %r447, %r438, %r437, %r439;
	mov.b32 	%f142, %r452;
	add.ftz.f32 	%f143, %f213, %f142;
	mov.b32 	%r453, %f143;
	shfl.sync.down.b32 	%r454|%p62, %r453, %r436, %r437, %r439;
	mov.b32 	%f144, %r454;
	add.ftz.f32 	%f145, %f143, %f144;
	mov.b32 	%r455, %f145;
	shfl.sync.down.b32 	%r457|%p63, %r455, %r444, %r437, %r439;
	mov.b32 	%f146, %r457;
	add.ftz.f32 	%f66, %f145, %f146;
	add.s32 	%r80, %r4, 1;
	setp.ge.s32 	%p64, %r80, %r89;
	or.pred  	%p66, %p55, %p64;
	@%p66 bra 	$L__BB0_63;

	mad.lo.s32 	%r458, %r80, %r88, %r3;
	mul.wide.s32 	%rd70, %r458, 4;
	add.s64 	%rd71, %rd5, %rd70;
	st.global.f32 	[%rd71], %f66;

$L__BB0_63:
	mov.b32 	%r459, %f212;
	mov.u32 	%r460, 2;
	mov.u32 	%r461, 6175;
	mov.u32 	%r462, 4;
	mov.u32 	%r463, -1;
	shfl.sync.down.b32 	%r464|%p67, %r459, %r462, %r461, %r463;
	mov.b32 	%f147, %r464;
	add.ftz.f32 	%f148, %f212, %f147;
	mov.b32 	%r465, %f148;
	shfl.sync.down.b32 	%r466|%p68, %r465, %r460, %r461, %r463;
	mov.b32 	%f149, %r466;
	add.ftz.f32 	%f150, %f148, %f149;
	mov.b32 	%r467, %f150;
	mov.u32 	%r468, 1;
	shfl.sync.down.b32 	%r469|%p69, %r467, %r468, %r461, %r463;
	mov.b32 	%f151, %r469;
	add.ftz.f32 	%f67, %f150, %f151;
	add.s32 	%r81, %r4, 2;
	setp.ge.s32 	%p70, %r81, %r89;
	or.pred  	%p72, %p55, %p70;
	@%p72 bra 	$L__BB0_65;

	mad.lo.s32 	%r470, %r81, %r88, %r3;
	mul.wide.s32 	%rd72, %r470, 4;
	add.s64 	%rd73, %rd5, %rd72;
	st.global.f32 	[%rd73], %f67;

$L__BB0_65:
	mov.b32 	%r471, %f211;
	shfl.sync.down.b32 	%r476|%p73, %r471, %r462, %r461, %r463;
	mov.b32 	%f152, %r476;
	add.ftz.f32 	%f153, %f211, %f152;
	mov.b32 	%r477, %f153;
	shfl.sync.down.b32 	%r478|%p74, %r477, %r460, %r461, %r463;
	mov.b32 	%f154, %r478;
	add.ftz.f32 	%f155, %f153, %f154;
	mov.b32 	%r479, %f155;
	shfl.sync.down.b32 	%r481|%p75, %r479, %r468, %r461, %r463;
	mov.b32 	%f156, %r481;
	add.ftz.f32 	%f68, %f155, %f156;
	add.s32 	%r82, %r4, 3;
	setp.ge.s32 	%p76, %r82, %r89;
	or.pred  	%p78, %p55, %p76;
	@%p78 bra 	$L__BB0_67;

	mad.lo.s32 	%r482, %r82, %r88, %r3;
	mul.wide.s32 	%rd74, %r482, 4;
	add.s64 	%rd75, %rd5, %rd74;
	st.global.f32 	[%rd75], %f68;

$L__BB0_67:
	mov.b32 	%r483, %f210;
	mov.u32 	%r484, 2;
	mov.u32 	%r485, 6175;
	mov.u32 	%r486, 4;
	mov.u32 	%r487, -1;
	shfl.sync.down.b32 	%r488|%p79, %r483, %r486, %r485, %r487;
	mov.b32 	%f157, %r488;
	add.ftz.f32 	%f158, %f210, %f157;
	mov.b32 	%r489, %f158;
	shfl.sync.down.b32 	%r490|%p80, %r489, %r484, %r485, %r487;
	mov.b32 	%f159, %r490;
	add.ftz.f32 	%f160, %f158, %f159;
	mov.b32 	%r491, %f160;
	mov.u32 	%r492, 1;
	shfl.sync.down.b32 	%r493|%p81, %r491, %r492, %r485, %r487;
	mov.b32 	%f161, %r493;
	add.ftz.f32 	%f69, %f160, %f161;
	add.s32 	%r83, %r4, 4;
	setp.ge.s32 	%p82, %r83, %r89;
	or.pred  	%p84, %p55, %p82;
	@%p84 bra 	$L__BB0_69;

	mad.lo.s32 	%r494, %r83, %r88, %r3;
	mul.wide.s32 	%rd76, %r494, 4;
	add.s64 	%rd77, %rd5, %rd76;
	st.global.f32 	[%rd77], %f69;

$L__BB0_69:
	mov.b32 	%r495, %f209;
	shfl.sync.down.b32 	%r500|%p85, %r495, %r486, %r485, %r487;
	mov.b32 	%f162, %r500;
	add.ftz.f32 	%f163, %f209, %f162;
	mov.b32 	%r501, %f163;
	shfl.sync.down.b32 	%r502|%p86, %r501, %r484, %r485, %r487;
	mov.b32 	%f164, %r502;
	add.ftz.f32 	%f165, %f163, %f164;
	mov.b32 	%r503, %f165;
	shfl.sync.down.b32 	%r505|%p87, %r503, %r492, %r485, %r487;
	mov.b32 	%f166, %r505;
	add.ftz.f32 	%f70, %f165, %f166;
	add.s32 	%r84, %r4, 5;
	setp.ge.s32 	%p88, %r84, %r89;
	or.pred  	%p90, %p55, %p88;
	@%p90 bra 	$L__BB0_71;

	mad.lo.s32 	%r506, %r84, %r88, %r3;
	mul.wide.s32 	%rd78, %r506, 4;
	add.s64 	%rd79, %rd5, %rd78;
	st.global.f32 	[%rd79], %f70;

$L__BB0_71:
	mov.b32 	%r507, %f208;
	mov.u32 	%r508, 2;
	mov.u32 	%r509, 6175;
	mov.u32 	%r510, 4;
	mov.u32 	%r511, -1;
	shfl.sync.down.b32 	%r512|%p91, %r507, %r510, %r509, %r511;
	mov.b32 	%f167, %r512;
	add.ftz.f32 	%f168, %f208, %f167;
	mov.b32 	%r513, %f168;
	shfl.sync.down.b32 	%r514|%p92, %r513, %r508, %r509, %r511;
	mov.b32 	%f169, %r514;
	add.ftz.f32 	%f170, %f168, %f169;
	mov.b32 	%r515, %f170;
	mov.u32 	%r516, 1;
	shfl.sync.down.b32 	%r517|%p93, %r515, %r516, %r509, %r511;
	mov.b32 	%f171, %r517;
	add.ftz.f32 	%f71, %f170, %f171;
	add.s32 	%r85, %r4, 6;
	setp.ge.s32 	%p94, %r85, %r89;
	or.pred  	%p96, %p55, %p94;
	@%p96 bra 	$L__BB0_73;

	mad.lo.s32 	%r518, %r85, %r88, %r3;
	mul.wide.s32 	%rd80, %r518, 4;
	add.s64 	%rd81, %rd5, %rd80;
	st.global.f32 	[%rd81], %f71;

$L__BB0_73:
	mov.b32 	%r519, %f207;
	shfl.sync.down.b32 	%r524|%p97, %r519, %r510, %r509, %r511;
	mov.b32 	%f172, %r524;
	add.ftz.f32 	%f173, %f207, %f172;
	mov.b32 	%r525, %f173;
	shfl.sync.down.b32 	%r526|%p98, %r525, %r508, %r509, %r511;
	mov.b32 	%f174, %r526;
	add.ftz.f32 	%f175, %f173, %f174;
	mov.b32 	%r527, %f175;
	shfl.sync.down.b32 	%r529|%p99, %r527, %r516, %r509, %r511;
	mov.b32 	%f176, %r529;
	add.ftz.f32 	%f72, %f175, %f176;
	add.s32 	%r86, %r4, 7;
	setp.ge.s32 	%p100, %r86, %r89;
	or.pred  	%p102, %p55, %p100;
	@%p102 bra 	$L__BB0_75;

	mad.lo.s32 	%r530, %r86, %r88, %r3;
	mul.wide.s32 	%rd82, %r530, 4;
	add.s64 	%rd83, %rd5, %rd82;
	st.global.f32 	[%rd83], %f72;

$L__BB0_75:
	ret;

}

`
