package q6

// Packed Q6/Q8 PTX is generated at development time and embedded.
const QuantizeQ8Rows16PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	quantize_q8_rows16
// _ZZ18quantize_q8_rows16E1m has been demoted

.visible .entry quantize_q8_rows16(
	.param .u64 quantize_q8_rows16_param_0,
	.param .u64 quantize_q8_rows16_param_1,
	.param .u64 quantize_q8_rows16_param_2,
	.param .u32 quantize_q8_rows16_param_3,
	.param .u32 quantize_q8_rows16_param_4
)
{
	.reg .pred 	%p<10>;
	.reg .f32 	%f<25>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<13>;
	// demoted variable
	.shared .align 4 .b8 _ZZ18quantize_q8_rows16E1m[64];

	ld.param.u64 	%rd1, [quantize_q8_rows16_param_0];
	ld.param.u64 	%rd2, [quantize_q8_rows16_param_1];
	ld.param.u64 	%rd3, [quantize_q8_rows16_param_2];
	ld.param.u32 	%r8, [quantize_q8_rows16_param_4];
	mov.u32 	%r1, %ctaid.y;
	mov.u32 	%r2, %ctaid.x;
	shl.b32 	%r9, %r2, 4;
	mov.u32 	%r3, %tid.x;
	add.s32 	%r4, %r9, %r3;
	setp.ge.s32 	%p1, %r4, %r8;
	mov.f32 	%f23, 0f00000000;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd1;
	mad.lo.s32 	%r10, %r1, %r8, %r4;
	mul.wide.s32 	%rd5, %r10, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.f32 	%f23, [%rd6];

$L__BB0_2:
	shl.b32 	%r11, %r3, 2;
	mov.u32 	%r12, _ZZ18quantize_q8_rows16E1m;
	add.s32 	%r5, %r12, %r11;
	abs.ftz.f32 	%f7, %f23;
	st.shared.f32 	[%r5], %f7;
	bar.sync 	0;
	setp.gt.s32 	%p2, %r3, 7;
	@%p2 bra 	$L__BB0_4;

	ld.shared.f32 	%f8, [%r5];
	ld.shared.f32 	%f9, [%r5+32];
	max.ftz.f32 	%f10, %f8, %f9;
	st.shared.f32 	[%r5], %f10;

$L__BB0_4:
	bar.sync 	0;
	setp.gt.s32 	%p3, %r3, 3;
	@%p3 bra 	$L__BB0_6;

	ld.shared.f32 	%f11, [%r5];
	ld.shared.f32 	%f12, [%r5+16];
	max.ftz.f32 	%f13, %f11, %f12;
	st.shared.f32 	[%r5], %f13;

$L__BB0_6:
	bar.sync 	0;
	setp.gt.s32 	%p4, %r3, 1;
	@%p4 bra 	$L__BB0_8;

	ld.shared.f32 	%f14, [%r5];
	ld.shared.f32 	%f15, [%r5+8];
	max.ftz.f32 	%f16, %f14, %f15;
	st.shared.f32 	[%r5], %f16;

$L__BB0_8:
	bar.sync 	0;
	setp.gt.s32 	%p5, %r3, 0;
	@%p5 bra 	$L__BB0_10;

	ld.shared.f32 	%f17, [%r5];
	ld.shared.f32 	%f18, [%r5+4];
	max.ftz.f32 	%f19, %f17, %f18;
	st.shared.f32 	[%r5], %f19;

$L__BB0_10:
	bar.sync 	0;
	ld.shared.f32 	%f3, [_ZZ18quantize_q8_rows16E1m];
	setp.leu.ftz.f32 	%p6, %f3, 0f00000000;
	mov.f32 	%f24, 0f00000000;
	@%p6 bra 	$L__BB0_12;

	mov.f32 	%f21, 0f42FE0000;
	div.approx.ftz.f32 	%f24, %f3, %f21;

$L__BB0_12:
	setp.ne.s32 	%p7, %r3, 0;
	@%p7 bra 	$L__BB0_14;

	add.s32 	%r13, %r8, 15;
	shr.s32 	%r14, %r13, 31;
	shr.u32 	%r15, %r14, 28;
	add.s32 	%r16, %r13, %r15;
	shr.s32 	%r17, %r16, 4;
	mad.lo.s32 	%r18, %r17, %r1, %r2;
	cvta.to.global.u64 	%rd7, %rd3;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f24;

$L__BB0_14:
	@%p1 bra 	$L__BB0_18;

	setp.leu.ftz.f32 	%p9, %f24, 0f00000000;
	mov.u32 	%r23, 0;
	@%p9 bra 	$L__BB0_17;

	div.approx.ftz.f32 	%f22, %f23, %f24;
	cvt.rni.ftz.s32.f32 	%r23, %f22;

$L__BB0_17:
	min.s32 	%r20, %r23, 127;
	max.s32 	%r21, %r20, -127;
	mad.lo.s32 	%r22, %r1, %r8, %r4;
	cvt.s64.s32 	%rd10, %r22;
	cvta.to.global.u64 	%rd11, %rd2;
	add.s64 	%rd12, %rd11, %rd10;
	st.global.u8 	[%rd12], %r21;

$L__BB0_18:
	ret;

}

`
const GemmQ6PackedQ8PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q6_packed_q8_batch4

.visible .entry gemm_q6_packed_q8_batch4(
	.param .u64 gemm_q6_packed_q8_batch4_param_0,
	.param .u64 gemm_q6_packed_q8_batch4_param_1,
	.param .u64 gemm_q6_packed_q8_batch4_param_2,
	.param .u64 gemm_q6_packed_q8_batch4_param_3,
	.param .u64 gemm_q6_packed_q8_batch4_param_4,
	.param .u32 gemm_q6_packed_q8_batch4_param_5,
	.param .u32 gemm_q6_packed_q8_batch4_param_6,
	.param .u32 gemm_q6_packed_q8_batch4_param_7
)
{
	.reg .pred 	%p<39>;
	.reg .f32 	%f<88>;
	.reg .b32 	%r<174>;
	.reg .b64 	%rd<67>;


	ld.param.u64 	%rd26, [gemm_q6_packed_q8_batch4_param_0];
	ld.param.u64 	%rd27, [gemm_q6_packed_q8_batch4_param_1];
	ld.param.u64 	%rd28, [gemm_q6_packed_q8_batch4_param_2];
	ld.param.u64 	%rd29, [gemm_q6_packed_q8_batch4_param_3];
	ld.param.u64 	%rd30, [gemm_q6_packed_q8_batch4_param_4];
	ld.param.u32 	%r15, [gemm_q6_packed_q8_batch4_param_5];
	ld.param.u32 	%r16, [gemm_q6_packed_q8_batch4_param_6];
	ld.param.u32 	%r17, [gemm_q6_packed_q8_batch4_param_7];
	cvta.to.global.u64 	%rd1, %rd30;
	mov.u32 	%r1, %tid.x;
	shr.u32 	%r18, %r1, 5;
	and.b32  	%r2, %r1, 31;
	mov.u32 	%r19, %ctaid.x;
	shl.b32 	%r20, %r19, 2;
	add.s32 	%r3, %r20, %r18;
	mov.u32 	%r4, %ctaid.y;
	shl.b32 	%r5, %r4, 2;
	setp.ge.s32 	%p1, %r3, %r16;
	setp.ge.s32 	%p2, %r5, %r17;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_18;

	shr.s32 	%r21, %r15, 31;
	shr.u32 	%r22, %r21, 28;
	add.s32 	%r23, %r15, %r22;
	shr.s32 	%r6, %r23, 4;
	setp.ge.s32 	%p4, %r2, %r6;
	mov.f32 	%f83, 0f00000000;
	mov.f32 	%f82, %f83;
	mov.f32 	%f81, %f83;
	mov.f32 	%f87, %f83;
	@%p4 bra 	$L__BB0_10;

	cvta.to.global.u64 	%rd31, %rd27;
	cvta.to.global.u64 	%rd32, %rd26;
	mul.lo.s32 	%r24, %r3, %r15;
	cvt.s64.s32 	%rd33, %r24;
	mul.lo.s32 	%r25, %r5, %r15;
	cvt.s64.s32 	%rd34, %r25;
	add.s32 	%r26, %r25, %r15;
	cvt.s64.s32 	%rd35, %r26;
	add.s32 	%r27, %r26, %r15;
	cvt.s64.s32 	%rd36, %r27;
	add.s32 	%r28, %r27, %r15;
	cvt.s64.s32 	%rd37, %r28;
	add.s32 	%r7, %r5, 3;
	mad.lo.s32 	%r29, %r6, %r7, %r2;
	mul.wide.s32 	%rd38, %r29, 4;
	add.s64 	%rd66, %rd31, %rd38;
	add.s32 	%r8, %r5, 2;
	mad.lo.s32 	%r30, %r6, %r8, %r2;
	mul.wide.s32 	%rd39, %r30, 4;
	add.s64 	%rd65, %rd31, %rd39;
	add.s32 	%r9, %r5, 1;
	mad.lo.s32 	%r31, %r6, %r9, %r2;
	mul.wide.s32 	%rd40, %r31, 4;
	add.s64 	%rd64, %rd31, %rd40;
	mul.lo.s32 	%r32, %r4, %r6;
	shl.b32 	%r33, %r32, 2;
	add.s32 	%r34, %r33, %r2;
	mul.wide.s32 	%rd41, %r34, 4;
	add.s64 	%rd63, %rd31, %rd41;
	mad.lo.s32 	%r35, %r6, %r3, %r2;
	cvta.to.global.u64 	%rd42, %rd29;
	mul.wide.s32 	%rd43, %r35, 4;
	add.s64 	%rd62, %rd42, %rd43;
	cvta.to.global.u64 	%rd44, %rd28;
	add.s64 	%rd45, %rd44, %rd33;
	add.s64 	%rd7, %rd45, 12;
	mul.wide.u32 	%rd61, %r2, 16;
	add.s64 	%rd9, %rd32, %rd37;
	add.s64 	%rd46, %rd32, %rd34;
	add.s64 	%rd10, %rd46, 12;
	add.s64 	%rd47, %rd32, %rd35;
	add.s64 	%rd11, %rd47, 12;
	add.s64 	%rd12, %rd32, %rd36;
	mov.f32 	%f83, 0f00000000;
	mov.u32 	%r173, %r2;

$L__BB0_3:
	add.s64 	%rd48, %rd7, %rd61;
	add.s64 	%rd19, %rd48, -12;
	ld.global.f32 	%f5, [%rd62];
	ld.global.u32 	%r38, [%rd48+-12];
	add.s64 	%rd49, %rd10, %rd61;
	ld.global.u32 	%r39, [%rd49+-12];
	mov.u32 	%r40, 0;
	// begin inline asm
	dp4a.s32.s32 %r37, %r38, %r39, %r40;
	// end inline asm
	ld.global.u32 	%r42, [%rd48+-8];
	ld.global.u32 	%r43, [%rd49+-8];
	// begin inline asm
	dp4a.s32.s32 %r41, %r42, %r43, %r37;
	// end inline asm
	ld.global.u32 	%r46, [%rd48+-4];
	ld.global.u32 	%r47, [%rd49+-4];
	// begin inline asm
	dp4a.s32.s32 %r45, %r46, %r47, %r41;
	// end inline asm
	ld.global.u32 	%r50, [%rd48];
	ld.global.u32 	%r51, [%rd49];
	// begin inline asm
	dp4a.s32.s32 %r49, %r50, %r51, %r45;
	// end inline asm
	cvt.rn.f32.s32 	%f29, %r49;
	mul.ftz.f32 	%f30, %f5, %f29;
	ld.global.f32 	%f31, [%rd63];
	fma.rn.ftz.f32 	%f87, %f31, %f30, %f87;
	setp.ge.s32 	%p5, %r9, %r17;
	@%p5 bra 	$L__BB0_5;

	ld.global.u32 	%r54, [%rd19];
	add.s64 	%rd50, %rd11, %rd61;
	ld.global.u32 	%r55, [%rd50+-12];
	// begin inline asm
	dp4a.s32.s32 %r53, %r54, %r55, %r40;
	// end inline asm
	ld.global.u32 	%r58, [%rd19+4];
	ld.global.u32 	%r59, [%rd50+-8];
	// begin inline asm
	dp4a.s32.s32 %r57, %r58, %r59, %r53;
	// end inline asm
	ld.global.u32 	%r62, [%rd19+8];
	ld.global.u32 	%r63, [%rd50+-4];
	// begin inline asm
	dp4a.s32.s32 %r61, %r62, %r63, %r57;
	// end inline asm
	ld.global.u32 	%r66, [%rd19+12];
	ld.global.u32 	%r67, [%rd50];
	// begin inline asm
	dp4a.s32.s32 %r65, %r66, %r67, %r61;
	// end inline asm
	cvt.rn.f32.s32 	%f32, %r65;
	mul.ftz.f32 	%f33, %f5, %f32;
	ld.global.f32 	%f34, [%rd64];
	fma.rn.ftz.f32 	%f81, %f34, %f33, %f81;

$L__BB0_5:
	setp.ge.s32 	%p6, %r8, %r17;
	@%p6 bra 	$L__BB0_7;

	add.s64 	%rd51, %rd12, %rd61;
	ld.global.u32 	%r70, [%rd19];
	ld.global.u32 	%r71, [%rd51];
	mov.u32 	%r72, 0;
	// begin inline asm
	dp4a.s32.s32 %r69, %r70, %r71, %r72;
	// end inline asm
	ld.global.u32 	%r74, [%rd19+4];
	ld.global.u32 	%r75, [%rd51+4];
	// begin inline asm
	dp4a.s32.s32 %r73, %r74, %r75, %r69;
	// end inline asm
	ld.global.u32 	%r78, [%rd19+8];
	ld.global.u32 	%r79, [%rd51+8];
	// begin inline asm
	dp4a.s32.s32 %r77, %r78, %r79, %r73;
	// end inline asm
	ld.global.u32 	%r82, [%rd19+12];
	ld.global.u32 	%r83, [%rd51+12];
	// begin inline asm
	dp4a.s32.s32 %r81, %r82, %r83, %r77;
	// end inline asm
	cvt.rn.f32.s32 	%f35, %r81;
	mul.ftz.f32 	%f36, %f5, %f35;
	ld.global.f32 	%f37, [%rd65];
	fma.rn.ftz.f32 	%f82, %f37, %f36, %f82;

$L__BB0_7:
	setp.ge.s32 	%p7, %r7, %r17;
	@%p7 bra 	$L__BB0_9;

	add.s64 	%rd52, %rd9, %rd61;
	ld.global.u32 	%r86, [%rd19];
	ld.global.u32 	%r87, [%rd52];
	mov.u32 	%r88, 0;
	// begin inline asm
	dp4a.s32.s32 %r85, %r86, %r87, %r88;
	// end inline asm
	ld.global.u32 	%r90, [%rd19+4];
	ld.global.u32 	%r91, [%rd52+4];
	// begin inline asm
	dp4a.s32.s32 %r89, %r90, %r91, %r85;
	// end inline asm
	ld.global.u32 	%r94, [%rd19+8];
	ld.global.u32 	%r95, [%rd52+8];
	// begin inline asm
	dp4a.s32.s32 %r93, %r94, %r95, %r89;
	// end inline asm
	ld.global.u32 	%r98, [%rd19+12];
	ld.global.u32 	%r99, [%rd52+12];
	// begin inline asm
	dp4a.s32.s32 %r97, %r98, %r99, %r93;
	// end inline asm
	cvt.rn.f32.s32 	%f38, %r97;
	mul.ftz.f32 	%f39, %f5, %f38;
	ld.global.f32 	%f40, [%rd66];
	fma.rn.ftz.f32 	%f83, %f40, %f39, %f83;

$L__BB0_9:
	add.s64 	%rd66, %rd66, 128;
	add.s64 	%rd65, %rd65, 128;
	add.s64 	%rd64, %rd64, 128;
	add.s64 	%rd63, %rd63, 128;
	add.s64 	%rd62, %rd62, 128;
	add.s64 	%rd61, %rd61, 512;
	add.s32 	%r173, %r173, 32;
	setp.lt.s32 	%p8, %r173, %r6;
	@%p8 bra 	$L__BB0_3;

$L__BB0_10:
	mov.b32 	%r101, %f87;
	mov.u32 	%r102, 2;
	mov.u32 	%r103, 31;
	mov.u32 	%r104, 16;
	mov.u32 	%r105, -1;
	shfl.sync.down.b32 	%r106|%p9, %r101, %r104, %r103, %r105;
	mov.b32 	%f41, %r106;
	add.ftz.f32 	%f42, %f87, %f41;
	mov.b32 	%r107, %f42;
	mov.u32 	%r108, 8;
	shfl.sync.down.b32 	%r109|%p10, %r107, %r108, %r103, %r105;
	mov.b32 	%f43, %r109;
	add.ftz.f32 	%f44, %f42, %f43;
	mov.b32 	%r110, %f44;
	mov.u32 	%r111, 4;
	shfl.sync.down.b32 	%r112|%p11, %r110, %r111, %r103, %r105;
	mov.b32 	%f45, %r112;
	add.ftz.f32 	%f46, %f44, %f45;
	mov.b32 	%r113, %f46;
	shfl.sync.down.b32 	%r114|%p12, %r113, %r102, %r103, %r105;
	mov.b32 	%f47, %r114;
	add.ftz.f32 	%f48, %f46, %f47;
	mov.b32 	%r115, %f48;
	mov.u32 	%r116, 1;
	shfl.sync.down.b32 	%r117|%p13, %r115, %r116, %r103, %r105;
	mov.b32 	%f49, %r117;
	add.ftz.f32 	%f17, %f48, %f49;
	setp.ne.s32 	%p14, %r2, 0;
	@%p14 bra 	$L__BB0_12;

	mad.lo.s32 	%r118, %r5, %r16, %r3;
	mul.wide.s32 	%rd53, %r118, 4;
	add.s64 	%rd54, %rd1, %rd53;
	st.global.f32 	[%rd54], %f17;

$L__BB0_12:
	mov.b32 	%r119, %f81;
	shfl.sync.down.b32 	%r124|%p16, %r119, %r104, %r103, %r105;
	mov.b32 	%f50, %r124;
	add.ftz.f32 	%f51, %f81, %f50;
	mov.b32 	%r125, %f51;
	shfl.sync.down.b32 	%r127|%p17, %r125, %r108, %r103, %r105;
	mov.b32 	%f52, %r127;
	add.ftz.f32 	%f53, %f51, %f52;
	mov.b32 	%r128, %f53;
	shfl.sync.down.b32 	%r130|%p18, %r128, %r111, %r103, %r105;
	mov.b32 	%f54, %r130;
	add.ftz.f32 	%f55, %f53, %f54;
	mov.b32 	%r131, %f55;
	shfl.sync.down.b32 	%r132|%p19, %r131, %r102, %r103, %r105;
	mov.b32 	%f56, %r132;
	add.ftz.f32 	%f57, %f55, %f56;
	mov.b32 	%r133, %f57;
	shfl.sync.down.b32 	%r135|%p20, %r133, %r116, %r103, %r105;
	mov.b32 	%f58, %r135;
	add.ftz.f32 	%f18, %f57, %f58;
	add.s32 	%r12, %r5, 1;
	setp.ge.s32 	%p21, %r12, %r17;
	or.pred  	%p22, %p14, %p21;
	@%p22 bra 	$L__BB0_14;

	mad.lo.s32 	%r136, %r12, %r16, %r3;
	mul.wide.s32 	%rd55, %r136, 4;
	add.s64 	%rd56, %rd1, %rd55;
	st.global.f32 	[%rd56], %f18;

$L__BB0_14:
	mov.b32 	%r137, %f82;
	mov.u32 	%r138, 2;
	mov.u32 	%r139, 31;
	mov.u32 	%r140, 16;
	mov.u32 	%r141, -1;
	shfl.sync.down.b32 	%r142|%p24, %r137, %r140, %r139, %r141;
	mov.b32 	%f59, %r142;
	add.ftz.f32 	%f60, %f82, %f59;
	mov.b32 	%r143, %f60;
	mov.u32 	%r144, 8;
	shfl.sync.down.b32 	%r145|%p25, %r143, %r144, %r139, %r141;
	mov.b32 	%f61, %r145;
	add.ftz.f32 	%f62, %f60, %f61;
	mov.b32 	%r146, %f62;
	mov.u32 	%r147, 4;
	shfl.sync.down.b32 	%r148|%p26, %r146, %r147, %r139, %r141;
	mov.b32 	%f63, %r148;
	add.ftz.f32 	%f64, %f62, %f63;
	mov.b32 	%r149, %f64;
	shfl.sync.down.b32 	%r150|%p27, %r149, %r138, %r139, %r141;
	mov.b32 	%f65, %r150;
	add.ftz.f32 	%f66, %f64, %f65;
	mov.b32 	%r151, %f66;
	mov.u32 	%r152, 1;
	shfl.sync.down.b32 	%r153|%p28, %r151, %r152, %r139, %r141;
	mov.b32 	%f67, %r153;
	add.ftz.f32 	%f19, %f66, %f67;
	add.s32 	%r13, %r5, 2;
	setp.ge.s32 	%p29, %r13, %r17;
	or.pred  	%p30, %p14, %p29;
	@%p30 bra 	$L__BB0_16;

	mad.lo.s32 	%r154, %r13, %r16, %r3;
	mul.wide.s32 	%rd57, %r154, 4;
	add.s64 	%rd58, %rd1, %rd57;
	st.global.f32 	[%rd58], %f19;

$L__BB0_16:
	mov.b32 	%r155, %f83;
	shfl.sync.down.b32 	%r160|%p32, %r155, %r140, %r139, %r141;
	mov.b32 	%f68, %r160;
	add.ftz.f32 	%f69, %f83, %f68;
	mov.b32 	%r161, %f69;
	shfl.sync.down.b32 	%r163|%p33, %r161, %r144, %r139, %r141;
	mov.b32 	%f70, %r163;
	add.ftz.f32 	%f71, %f69, %f70;
	mov.b32 	%r164, %f71;
	shfl.sync.down.b32 	%r166|%p34, %r164, %r147, %r139, %r141;
	mov.b32 	%f72, %r166;
	add.ftz.f32 	%f73, %f71, %f72;
	mov.b32 	%r167, %f73;
	shfl.sync.down.b32 	%r168|%p35, %r167, %r138, %r139, %r141;
	mov.b32 	%f74, %r168;
	add.ftz.f32 	%f75, %f73, %f74;
	mov.b32 	%r169, %f75;
	shfl.sync.down.b32 	%r171|%p36, %r169, %r152, %r139, %r141;
	mov.b32 	%f76, %r171;
	add.ftz.f32 	%f20, %f75, %f76;
	add.s32 	%r14, %r5, 3;
	setp.ge.s32 	%p37, %r14, %r17;
	or.pred  	%p38, %p14, %p37;
	@%p38 bra 	$L__BB0_18;

	mad.lo.s32 	%r172, %r14, %r16, %r3;
	mul.wide.s32 	%rd59, %r172, 4;
	add.s64 	%rd60, %rd1, %rd59;
	st.global.f32 	[%rd60], %f20;

$L__BB0_18:
	ret;

}

`
