package q6

// QuantizeQ8PTX is generated at development time and embedded for driver JIT.
const QuantizeQ8PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	quantize_q8_rows
// _ZZ16quantize_q8_rowsE1m has been demoted

.visible .entry quantize_q8_rows(
	.param .u64 quantize_q8_rows_param_0,
	.param .u64 quantize_q8_rows_param_1,
	.param .u64 quantize_q8_rows_param_2,
	.param .u32 quantize_q8_rows_param_3,
	.param .u32 quantize_q8_rows_param_4
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<28>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<13>;
	// demoted variable
	.shared .align 4 .b8 _ZZ16quantize_q8_rowsE1m[128];

	ld.param.u64 	%rd1, [quantize_q8_rows_param_0];
	ld.param.u64 	%rd2, [quantize_q8_rows_param_1];
	ld.param.u64 	%rd3, [quantize_q8_rows_param_2];
	ld.param.u32 	%r8, [quantize_q8_rows_param_4];
	mov.u32 	%r1, %ctaid.y;
	mov.u32 	%r2, %ctaid.x;
	shl.b32 	%r9, %r2, 5;
	mov.u32 	%r3, %tid.x;
	add.s32 	%r4, %r9, %r3;
	setp.ge.s32 	%p1, %r4, %r8;
	mov.f32 	%f26, 0f00000000;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd1;
	mad.lo.s32 	%r10, %r1, %r8, %r4;
	mul.wide.s32 	%rd5, %r10, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.f32 	%f26, [%rd6];

$L__BB0_2:
	shl.b32 	%r11, %r3, 2;
	mov.u32 	%r12, _ZZ16quantize_q8_rowsE1m;
	add.s32 	%r5, %r12, %r11;
	abs.ftz.f32 	%f7, %f26;
	st.shared.f32 	[%r5], %f7;
	bar.sync 	0;
	setp.gt.s32 	%p2, %r3, 15;
	@%p2 bra 	$L__BB0_4;

	ld.shared.f32 	%f8, [%r5];
	ld.shared.f32 	%f9, [%r5+64];
	max.ftz.f32 	%f10, %f8, %f9;
	st.shared.f32 	[%r5], %f10;

$L__BB0_4:
	bar.sync 	0;
	setp.gt.s32 	%p3, %r3, 7;
	@%p3 bra 	$L__BB0_6;

	ld.shared.f32 	%f11, [%r5];
	ld.shared.f32 	%f12, [%r5+32];
	max.ftz.f32 	%f13, %f11, %f12;
	st.shared.f32 	[%r5], %f13;

$L__BB0_6:
	bar.sync 	0;
	setp.gt.s32 	%p4, %r3, 3;
	@%p4 bra 	$L__BB0_8;

	ld.shared.f32 	%f14, [%r5];
	ld.shared.f32 	%f15, [%r5+16];
	max.ftz.f32 	%f16, %f14, %f15;
	st.shared.f32 	[%r5], %f16;

$L__BB0_8:
	bar.sync 	0;
	setp.gt.s32 	%p5, %r3, 1;
	@%p5 bra 	$L__BB0_10;

	ld.shared.f32 	%f17, [%r5];
	ld.shared.f32 	%f18, [%r5+8];
	max.ftz.f32 	%f19, %f17, %f18;
	st.shared.f32 	[%r5], %f19;

$L__BB0_10:
	bar.sync 	0;
	setp.gt.s32 	%p6, %r3, 0;
	@%p6 bra 	$L__BB0_12;

	ld.shared.f32 	%f20, [%r5];
	ld.shared.f32 	%f21, [%r5+4];
	max.ftz.f32 	%f22, %f20, %f21;
	st.shared.f32 	[%r5], %f22;

$L__BB0_12:
	bar.sync 	0;
	ld.shared.f32 	%f3, [_ZZ16quantize_q8_rowsE1m];
	setp.leu.ftz.f32 	%p7, %f3, 0f00000000;
	mov.f32 	%f27, 0f00000000;
	@%p7 bra 	$L__BB0_14;

	mov.f32 	%f24, 0f42FE0000;
	div.approx.ftz.f32 	%f27, %f3, %f24;

$L__BB0_14:
	setp.ne.s32 	%p8, %r3, 0;
	@%p8 bra 	$L__BB0_16;

	add.s32 	%r13, %r8, 31;
	shr.s32 	%r14, %r13, 31;
	shr.u32 	%r15, %r14, 27;
	add.s32 	%r16, %r13, %r15;
	shr.s32 	%r17, %r16, 5;
	mad.lo.s32 	%r18, %r17, %r1, %r2;
	cvta.to.global.u64 	%rd7, %rd3;
	mul.wide.s32 	%rd8, %r18, 4;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f27;

$L__BB0_16:
	@%p1 bra 	$L__BB0_20;

	setp.leu.ftz.f32 	%p10, %f27, 0f00000000;
	mov.u32 	%r23, 0;
	@%p10 bra 	$L__BB0_19;

	div.approx.ftz.f32 	%f25, %f26, %f27;
	cvt.rni.ftz.s32.f32 	%r23, %f25;

$L__BB0_19:
	min.s32 	%r20, %r23, 127;
	max.s32 	%r21, %r20, -127;
	mad.lo.s32 	%r22, %r1, %r8, %r4;
	cvt.s64.s32 	%rd10, %r22;
	cvta.to.global.u64 	%rd11, %rd2;
	add.s64 	%rd12, %rd11, %rd10;
	st.global.u8 	[%rd12], %r21;

$L__BB0_20:
	ret;

}

`

// GemmQ6Q8PTX is generated at development time and embedded for driver JIT.
const GemmQ6Q8PTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gemm_q6_k_q8_batch4

.visible .entry gemm_q6_k_q8_batch4(
	.param .u64 gemm_q6_k_q8_batch4_param_0,
	.param .u64 gemm_q6_k_q8_batch4_param_1,
	.param .u64 gemm_q6_k_q8_batch4_param_2,
	.param .u64 gemm_q6_k_q8_batch4_param_3,
	.param .u32 gemm_q6_k_q8_batch4_param_4,
	.param .u32 gemm_q6_k_q8_batch4_param_5,
	.param .u32 gemm_q6_k_q8_batch4_param_6
)
{
	.reg .pred 	%p<49>;
	.reg .b16 	%rs<6>;
	.reg .f32 	%f<124>;
	.reg .b32 	%r<250>;
	.reg .b64 	%rd<73>;


	ld.param.u64 	%rd29, [gemm_q6_k_q8_batch4_param_0];
	ld.param.u64 	%rd30, [gemm_q6_k_q8_batch4_param_1];
	ld.param.u64 	%rd31, [gemm_q6_k_q8_batch4_param_2];
	ld.param.u64 	%rd32, [gemm_q6_k_q8_batch4_param_3];
	ld.param.u32 	%r34, [gemm_q6_k_q8_batch4_param_4];
	ld.param.u32 	%r35, [gemm_q6_k_q8_batch4_param_5];
	ld.param.u32 	%r36, [gemm_q6_k_q8_batch4_param_6];
	cvta.to.global.u64 	%rd1, %rd31;
	cvta.to.global.u64 	%rd2, %rd32;
	mov.u32 	%r37, %tid.x;
	shr.u32 	%r38, %r37, 5;
	and.b32  	%r239, %r37, 31;
	mov.u32 	%r39, %ctaid.x;
	shl.b32 	%r40, %r39, 2;
	add.s32 	%r2, %r40, %r38;
	mov.u32 	%r41, %ctaid.y;
	shl.b32 	%r3, %r41, 2;
	setp.ge.s32 	%p1, %r2, %r35;
	setp.ge.s32 	%p2, %r3, %r36;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_33;

	shr.s32 	%r42, %r34, 31;
	shr.u32 	%r43, %r42, 27;
	add.s32 	%r44, %r34, %r43;
	shr.s32 	%r4, %r44, 5;
	shr.u32 	%r45, %r42, 24;
	add.s32 	%r46, %r34, %r45;
	shr.s32 	%r47, %r46, 8;
	mul.lo.s32 	%r48, %r2, %r47;
	mul.lo.s32 	%r49, %r48, 210;
	cvt.s64.s32 	%rd3, %r49;
	setp.ge.s32 	%p4, %r239, %r4;
	mov.f32 	%f119, 0f00000000;
	mov.f32 	%f118, %f119;
	mov.f32 	%f117, %f119;
	mov.f32 	%f116, %f119;
	@%p4 bra 	$L__BB0_25;

	cvta.to.global.u64 	%rd4, %rd30;
	mul.lo.s32 	%r50, %r3, %r34;
	cvt.s64.s32 	%rd5, %r50;
	add.s32 	%r5, %r3, 1;
	mul.lo.s32 	%r6, %r3, %r4;
	add.s32 	%r51, %r50, %r34;
	cvt.s64.s32 	%rd6, %r51;
	add.s32 	%r7, %r3, 2;
	add.s32 	%r52, %r51, %r34;
	cvt.s64.s32 	%rd7, %r52;
	add.s32 	%r8, %r3, 3;
	add.s32 	%r53, %r52, %r34;
	cvt.s64.s32 	%rd8, %r53;
	add.s64 	%rd33, %rd1, %rd3;
	add.s64 	%rd9, %rd33, 3;
	add.s64 	%rd10, %rd33, 131;
	cvta.to.global.u64 	%rd11, %rd29;
	mov.f32 	%f119, 0f00000000;

$L__BB0_3:
	shr.u32 	%r60, %r239, 3;
	mul.lo.s32 	%r61, %r60, 210;
	cvt.s64.s32 	%rd34, %r61;
	add.s64 	%rd12, %rd34, %rd3;
	add.s64 	%rd35, %rd1, %rd12;
	ld.global.u16 	%rs1, [%rd35+208];
	// begin inline asm
	{  cvt.f32.f16 %f39, %rs1;}

	// end inline asm
	shl.b32 	%r62, %r239, 5;
	and.b32  	%r63, %r62, 32;
	shl.b32 	%r64, %r239, 3;
	and.b32  	%r65, %r64, 32;
	add.s32 	%r68, %r6, %r239;
	mul.wide.s32 	%rd37, %r68, 4;
	add.s64 	%rd13, %rd4, %rd37;
	add.s32 	%r69, %r68, %r4;
	mul.wide.s32 	%rd38, %r69, 4;
	add.s64 	%rd14, %rd4, %rd38;
	add.s32 	%r70, %r69, %r4;
	mul.wide.s32 	%rd39, %r70, 4;
	add.s64 	%rd15, %rd4, %rd39;
	add.s32 	%r71, %r70, %r4;
	mul.wide.s32 	%rd40, %r71, 4;
	add.s64 	%rd16, %rd4, %rd40;
	cvt.u16.u32 	%rs2, %r239;
	shr.u16 	%rs3, %rs2, 2;
	and.b16  	%rs4, %rs3, 1;
	mul.wide.u16 	%r72, %rs4, 64;
	or.b32  	%r73, %r63, %r72;
	cvt.u64.u32 	%rd41, %r73;
	add.s64 	%rd42, %rd34, %rd41;
	add.s64 	%rd71, %rd9, %rd42;
	cvt.u64.u32 	%rd43, %r65;
	add.s64 	%rd44, %rd34, %rd43;
	add.s64 	%rd70, %rd10, %rd44;
	mov.u32 	%r249, 0;
	mov.u32 	%r241, -8;
	mov.u32 	%r240, 28;
	mov.u64 	%rd72, %rd11;
	mov.u32 	%r248, %r249;
	mov.u32 	%r247, %r249;
	mov.u32 	%r246, %r249;

$L__BB0_4:
	shl.b32 	%r221, %r239, 1;
	shl.b32 	%r220, %r239, 5;
	cvt.s64.s32 	%rd63, %r220;
	add.s64 	%rd62, %rd5, %rd63;
	shr.u32 	%r219, %r239, 3;
	mul.lo.s32 	%r218, %r219, 210;
	cvt.s64.s32 	%rd61, %r218;
	add.s64 	%rd60, %rd61, %rd3;
	and.b32  	%r217, %r221, 14;
	or.b32  	%r216, %r217, 192;
	and.b32  	%r215, %r221, 6;
	and.b32  	%r214, %r239, 3;
	ld.global.u8 	%r78, [%rd71+-3];
	and.b32  	%r79, %r78, 15;
	shr.u32 	%r80, %r78, 4;
	setp.lt.u32 	%p5, %r214, 2;
	selp.b32 	%r81, %r79, %r80, %p5;
	ld.global.u8 	%r82, [%rd70+-3];
	shr.u32 	%r83, %r82, %r215;
	shl.b32 	%r84, %r83, 4;
	and.b32  	%r85, %r84, 48;
	or.b32  	%r86, %r85, %r81;
	add.s32 	%r87, %r86, 224;
	ld.global.u8 	%r88, [%rd71+-2];
	and.b32  	%r89, %r88, 15;
	shr.u32 	%r90, %r88, 4;
	selp.b32 	%r91, %r89, %r90, %p5;
	ld.global.u8 	%r92, [%rd70+-2];
	shr.u32 	%r93, %r92, %r215;
	shl.b32 	%r94, %r93, 4;
	and.b32  	%r95, %r94, 48;
	or.b32  	%r96, %r95, %r91;
	add.s32 	%r97, %r96, 224;
	ld.global.u8 	%r98, [%rd71+-1];
	and.b32  	%r99, %r98, 15;
	shr.u32 	%r100, %r98, 4;
	selp.b32 	%r101, %r99, %r100, %p5;
	ld.global.u8 	%r102, [%rd70+-1];
	shr.u32 	%r103, %r102, %r215;
	shl.b32 	%r104, %r103, 4;
	and.b32  	%r105, %r104, 48;
	or.b32  	%r106, %r105, %r101;
	add.s32 	%r107, %r106, 224;
	ld.global.u8 	%r108, [%rd71];
	and.b32  	%r109, %r108, 15;
	shr.u32 	%r110, %r108, 4;
	selp.b32 	%r111, %r109, %r110, %p5;
	ld.global.u8 	%r112, [%rd70];
	shr.u32 	%r113, %r112, %r215;
	shl.b32 	%r114, %r113, 4;
	and.b32  	%r115, %r114, 48;
	or.b32  	%r116, %r115, %r111;
	add.s32 	%r117, %r116, 224;
	mov.u32 	%r118, 64;
	prmt.b32 	%r119, %r87, %r97, %r118;
	mov.u32 	%r120, 1040;
	prmt.b32 	%r121, %r119, %r107, %r120;
	mov.u32 	%r122, 16912;
	prmt.b32 	%r75, %r121, %r117, %r122;
	add.s32 	%r123, %r241, 8;
	shr.u32 	%r124, %r123, 2;
	add.s32 	%r125, %r216, %r124;
	cvt.u64.u32 	%rd45, %r125;
	add.s64 	%rd46, %rd60, %rd45;
	add.s64 	%rd47, %rd1, %rd46;
	ld.global.s8 	%rs5, [%rd47];
	cvt.rn.f32.s16 	%f10, %rs5;
	add.s64 	%rd48, %rd72, %rd62;
	ld.global.u32 	%r76, [%rd48];
	// begin inline asm
	dp4a.s32.s32 %r246, %r75, %r76, %r246;
	// end inline asm
	setp.eq.s32 	%p6, %r241, -5;
	@%p6 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	cvt.rn.f32.s32 	%f44, %r246;
	mul.ftz.f32 	%f45, %f39, %f44;
	mul.ftz.f32 	%f46, %f45, %f10;
	ld.global.f32 	%f47, [%rd13];
	fma.rn.ftz.f32 	%f116, %f47, %f46, %f116;
	mov.u32 	%r246, 0;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	setp.ne.s32 	%p7, %r241, -1;
	@%p7 bra 	$L__BB0_8;

	cvt.rn.f32.s32 	%f40, %r246;
	mul.ftz.f32 	%f41, %f39, %f40;
	mul.ftz.f32 	%f42, %f41, %f10;
	ld.global.f32 	%f43, [%rd13];
	fma.rn.ftz.f32 	%f116, %f43, %f42, %f116;

$L__BB0_8:
	setp.ge.s32 	%p8, %r5, %r36;
	@%p8 bra 	$L__BB0_13;

	shl.b32 	%r238, %r239, 5;
	cvt.s64.s32 	%rd69, %r238;
	add.s64 	%rd68, %rd6, %rd69;
	add.s64 	%rd49, %rd72, %rd68;
	ld.global.u32 	%r129, [%rd49];
	// begin inline asm
	dp4a.s32.s32 %r247, %r75, %r129, %r247;
	// end inline asm
	@%p6 bra 	$L__BB0_12;
	bra.uni 	$L__BB0_10;

$L__BB0_12:
	cvt.rn.f32.s32 	%f52, %r247;
	mul.ftz.f32 	%f53, %f39, %f52;
	mul.ftz.f32 	%f54, %f53, %f10;
	ld.global.f32 	%f55, [%rd14];
	fma.rn.ftz.f32 	%f117, %f55, %f54, %f117;
	mov.u32 	%r247, 0;
	bra.uni 	$L__BB0_13;

$L__BB0_10:
	setp.ne.s32 	%p10, %r241, -1;
	@%p10 bra 	$L__BB0_13;

	cvt.rn.f32.s32 	%f48, %r247;
	mul.ftz.f32 	%f49, %f39, %f48;
	mul.ftz.f32 	%f50, %f49, %f10;
	ld.global.f32 	%f51, [%rd14];
	fma.rn.ftz.f32 	%f117, %f51, %f50, %f117;

$L__BB0_13:
	setp.ge.s32 	%p11, %r7, %r36;
	@%p11 bra 	$L__BB0_18;

	shl.b32 	%r237, %r239, 5;
	cvt.s64.s32 	%rd67, %r237;
	add.s64 	%rd66, %rd7, %rd67;
	add.s64 	%rd50, %rd72, %rd66;
	ld.global.u32 	%r134, [%rd50];
	// begin inline asm
	dp4a.s32.s32 %r248, %r75, %r134, %r248;
	// end inline asm
	@%p6 bra 	$L__BB0_17;
	bra.uni 	$L__BB0_15;

$L__BB0_17:
	cvt.rn.f32.s32 	%f60, %r248;
	mul.ftz.f32 	%f61, %f39, %f60;
	mul.ftz.f32 	%f62, %f61, %f10;
	ld.global.f32 	%f63, [%rd15];
	fma.rn.ftz.f32 	%f118, %f63, %f62, %f118;
	mov.u32 	%r248, 0;
	bra.uni 	$L__BB0_18;

$L__BB0_15:
	setp.ne.s32 	%p13, %r241, -1;
	@%p13 bra 	$L__BB0_18;

	cvt.rn.f32.s32 	%f56, %r248;
	mul.ftz.f32 	%f57, %f39, %f56;
	mul.ftz.f32 	%f58, %f57, %f10;
	ld.global.f32 	%f59, [%rd15];
	fma.rn.ftz.f32 	%f118, %f59, %f58, %f118;

$L__BB0_18:
	setp.ge.s32 	%p14, %r8, %r36;
	@%p14 bra 	$L__BB0_23;

	shl.b32 	%r236, %r239, 5;
	cvt.s64.s32 	%rd65, %r236;
	add.s64 	%rd64, %rd8, %rd65;
	add.s64 	%rd51, %rd72, %rd64;
	ld.global.u32 	%r139, [%rd51];
	// begin inline asm
	dp4a.s32.s32 %r249, %r75, %r139, %r249;
	// end inline asm
	@%p6 bra 	$L__BB0_22;
	bra.uni 	$L__BB0_20;

$L__BB0_22:
	cvt.rn.f32.s32 	%f68, %r249;
	mul.ftz.f32 	%f69, %f39, %f68;
	mul.ftz.f32 	%f70, %f69, %f10;
	ld.global.f32 	%f71, [%rd16];
	fma.rn.ftz.f32 	%f119, %f71, %f70, %f119;
	mov.u32 	%r249, 0;
	bra.uni 	$L__BB0_23;

$L__BB0_20:
	setp.ne.s32 	%p16, %r241, -1;
	@%p16 bra 	$L__BB0_23;

	cvt.rn.f32.s32 	%f64, %r249;
	mul.ftz.f32 	%f65, %f39, %f64;
	mul.ftz.f32 	%f66, %f65, %f10;
	ld.global.f32 	%f67, [%rd16];
	fma.rn.ftz.f32 	%f119, %f67, %f66, %f119;

$L__BB0_23:
	add.s32 	%r241, %r241, 1;
	add.s64 	%rd72, %rd72, 4;
	add.s64 	%rd71, %rd71, 4;
	add.s64 	%rd70, %rd70, 4;
	add.s32 	%r240, %r240, -4;
	setp.ne.s32 	%p17, %r240, -4;
	@%p17 bra 	$L__BB0_4;

	add.s32 	%r239, %r239, 32;
	setp.lt.s32 	%p18, %r239, %r4;
	@%p18 bra 	$L__BB0_3;

$L__BB0_25:
	mov.u32 	%r223, %tid.x;
	and.b32  	%r222, %r223, 31;
	mov.b32 	%r142, %f116;
	mov.u32 	%r143, 2;
	mov.u32 	%r144, 31;
	mov.u32 	%r145, 16;
	mov.u32 	%r146, -1;
	shfl.sync.down.b32 	%r147|%p19, %r142, %r145, %r144, %r146;
	mov.b32 	%f72, %r147;
	add.ftz.f32 	%f73, %f116, %f72;
	mov.b32 	%r148, %f73;
	mov.u32 	%r149, 8;
	shfl.sync.down.b32 	%r150|%p20, %r148, %r149, %r144, %r146;
	mov.b32 	%f74, %r150;
	add.ftz.f32 	%f75, %f73, %f74;
	mov.b32 	%r151, %f75;
	mov.u32 	%r152, 4;
	shfl.sync.down.b32 	%r153|%p21, %r151, %r152, %r144, %r146;
	mov.b32 	%f76, %r153;
	add.ftz.f32 	%f77, %f75, %f76;
	mov.b32 	%r154, %f77;
	shfl.sync.down.b32 	%r155|%p22, %r154, %r143, %r144, %r146;
	mov.b32 	%f78, %r155;
	add.ftz.f32 	%f79, %f77, %f78;
	mov.b32 	%r156, %f79;
	mov.u32 	%r157, 1;
	shfl.sync.down.b32 	%r158|%p23, %r156, %r157, %r144, %r146;
	mov.b32 	%f80, %r158;
	add.ftz.f32 	%f27, %f79, %f80;
	setp.ne.s32 	%p24, %r222, 0;
	@%p24 bra 	$L__BB0_27;

	ld.param.u32 	%r235, [gemm_q6_k_q8_batch4_param_5];
	mov.u32 	%r234, %ctaid.y;
	shl.b32 	%r233, %r234, 2;
	mad.lo.s32 	%r159, %r233, %r235, %r2;
	mul.wide.s32 	%rd52, %r159, 4;
	add.s64 	%rd53, %rd2, %rd52;
	st.global.f32 	[%rd53], %f27;

$L__BB0_27:
	mov.u32 	%r225, %ctaid.y;
	shl.b32 	%r224, %r225, 2;
	mov.b32 	%r160, %f117;
	shfl.sync.down.b32 	%r165|%p26, %r160, %r145, %r144, %r146;
	mov.b32 	%f81, %r165;
	add.ftz.f32 	%f82, %f117, %f81;
	mov.b32 	%r166, %f82;
	shfl.sync.down.b32 	%r168|%p27, %r166, %r149, %r144, %r146;
	mov.b32 	%f83, %r168;
	add.ftz.f32 	%f84, %f82, %f83;
	mov.b32 	%r169, %f84;
	shfl.sync.down.b32 	%r171|%p28, %r169, %r152, %r144, %r146;
	mov.b32 	%f85, %r171;
	add.ftz.f32 	%f86, %f84, %f85;
	mov.b32 	%r172, %f86;
	shfl.sync.down.b32 	%r173|%p29, %r172, %r143, %r144, %r146;
	mov.b32 	%f87, %r173;
	add.ftz.f32 	%f88, %f86, %f87;
	mov.b32 	%r174, %f88;
	shfl.sync.down.b32 	%r176|%p30, %r174, %r157, %r144, %r146;
	mov.b32 	%f89, %r176;
	add.ftz.f32 	%f28, %f88, %f89;
	add.s32 	%r31, %r224, 1;
	setp.ge.s32 	%p31, %r31, %r36;
	or.pred  	%p32, %p24, %p31;
	@%p32 bra 	$L__BB0_29;

	ld.param.u32 	%r232, [gemm_q6_k_q8_batch4_param_5];
	mad.lo.s32 	%r177, %r31, %r232, %r2;
	mul.wide.s32 	%rd54, %r177, 4;
	add.s64 	%rd55, %rd2, %rd54;
	st.global.f32 	[%rd55], %f28;

$L__BB0_29:
	mov.u32 	%r227, %ctaid.y;
	shl.b32 	%r226, %r227, 2;
	mov.b32 	%r178, %f118;
	mov.u32 	%r179, 2;
	mov.u32 	%r180, 31;
	mov.u32 	%r181, 16;
	mov.u32 	%r182, -1;
	shfl.sync.down.b32 	%r183|%p34, %r178, %r181, %r180, %r182;
	mov.b32 	%f90, %r183;
	add.ftz.f32 	%f91, %f118, %f90;
	mov.b32 	%r184, %f91;
	mov.u32 	%r185, 8;
	shfl.sync.down.b32 	%r186|%p35, %r184, %r185, %r180, %r182;
	mov.b32 	%f92, %r186;
	add.ftz.f32 	%f93, %f91, %f92;
	mov.b32 	%r187, %f93;
	mov.u32 	%r188, 4;
	shfl.sync.down.b32 	%r189|%p36, %r187, %r188, %r180, %r182;
	mov.b32 	%f94, %r189;
	add.ftz.f32 	%f95, %f93, %f94;
	mov.b32 	%r190, %f95;
	shfl.sync.down.b32 	%r191|%p37, %r190, %r179, %r180, %r182;
	mov.b32 	%f96, %r191;
	add.ftz.f32 	%f97, %f95, %f96;
	mov.b32 	%r192, %f97;
	mov.u32 	%r193, 1;
	shfl.sync.down.b32 	%r194|%p38, %r192, %r193, %r180, %r182;
	mov.b32 	%f98, %r194;
	add.ftz.f32 	%f29, %f97, %f98;
	add.s32 	%r32, %r226, 2;
	setp.ge.s32 	%p39, %r32, %r36;
	or.pred  	%p40, %p24, %p39;
	@%p40 bra 	$L__BB0_31;

	ld.param.u32 	%r231, [gemm_q6_k_q8_batch4_param_5];
	mad.lo.s32 	%r195, %r32, %r231, %r2;
	mul.wide.s32 	%rd56, %r195, 4;
	add.s64 	%rd57, %rd2, %rd56;
	st.global.f32 	[%rd57], %f29;

$L__BB0_31:
	mov.u32 	%r229, %ctaid.y;
	shl.b32 	%r228, %r229, 2;
	mov.b32 	%r196, %f119;
	shfl.sync.down.b32 	%r201|%p42, %r196, %r181, %r180, %r182;
	mov.b32 	%f99, %r201;
	add.ftz.f32 	%f100, %f119, %f99;
	mov.b32 	%r202, %f100;
	shfl.sync.down.b32 	%r204|%p43, %r202, %r185, %r180, %r182;
	mov.b32 	%f101, %r204;
	add.ftz.f32 	%f102, %f100, %f101;
	mov.b32 	%r205, %f102;
	shfl.sync.down.b32 	%r207|%p44, %r205, %r188, %r180, %r182;
	mov.b32 	%f103, %r207;
	add.ftz.f32 	%f104, %f102, %f103;
	mov.b32 	%r208, %f104;
	shfl.sync.down.b32 	%r209|%p45, %r208, %r179, %r180, %r182;
	mov.b32 	%f105, %r209;
	add.ftz.f32 	%f106, %f104, %f105;
	mov.b32 	%r210, %f106;
	shfl.sync.down.b32 	%r212|%p46, %r210, %r193, %r180, %r182;
	mov.b32 	%f107, %r212;
	add.ftz.f32 	%f30, %f106, %f107;
	add.s32 	%r33, %r228, 3;
	setp.ge.s32 	%p47, %r33, %r36;
	or.pred  	%p48, %p24, %p47;
	@%p48 bra 	$L__BB0_33;

	ld.param.u32 	%r230, [gemm_q6_k_q8_batch4_param_5];
	mad.lo.s32 	%r213, %r33, %r230, %r2;
	mul.wide.s32 	%rd58, %r213, 4;
	add.s64 	%rd59, %rd2, %rd58;
	st.global.f32 	[%rd59], %f30;

$L__BB0_33:
	ret;

}

`
