package q6

// QuantizeQ8Rows16GroupedPTX is generated at development time from the byte-exact grouped Q6 activation packer.
const QuantizeQ8Rows16GroupedPTX = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	quantize_q8_rows16

.visible .entry quantize_q8_rows16(
	.param .u64 quantize_q8_rows16_param_0,
	.param .u64 quantize_q8_rows16_param_1,
	.param .u64 quantize_q8_rows16_param_2,
	.param .u32 quantize_q8_rows16_param_3,
	.param .u32 quantize_q8_rows16_param_4
)
.maxntid 128, 1, 1
.minnctapersm 4
{
	.reg .pred 	%p<14>;
	.reg .f32 	%f<21>;
	.reg .b32 	%r<42>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [quantize_q8_rows16_param_0];
	ld.param.u64 	%rd2, [quantize_q8_rows16_param_1];
	ld.param.u64 	%rd3, [quantize_q8_rows16_param_2];
	ld.param.u32 	%r9, [quantize_q8_rows16_param_3];
	ld.param.u32 	%r8, [quantize_q8_rows16_param_4];
	mov.u32 	%r10, %ctaid.x;
	shl.b32 	%r11, %r10, 3;
	mov.u32 	%r12, %tid.x;
	shr.u32 	%r13, %r12, 4;
	add.s32 	%r1, %r11, %r13;
	and.b32  	%r2, %r12, 15;
	bfi.b32 	%r3, %r1, %r2, 4, 28;
	add.s32 	%r14, %r8, 15;
	shr.s32 	%r15, %r14, 31;
	shr.u32 	%r16, %r15, 28;
	add.s32 	%r17, %r14, %r16;
	shr.s32 	%r4, %r17, 4;
	mov.u32 	%r5, %ctaid.y;
	setp.ge.s32 	%p1, %r5, %r9;
	setp.ge.s32 	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_11;

	setp.ge.s32 	%p4, %r3, %r8;
	mov.f32 	%f20, 0f00000000;
	mov.f32 	%f19, %f20;
	@%p4 bra 	$L__BB0_3;

	mad.lo.s32 	%r18, %r5, %r8, %r3;
	cvta.to.global.u64 	%rd4, %rd1;
	mul.wide.s32 	%rd5, %r18, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.f32 	%f19, [%rd6];

$L__BB0_3:
	abs.ftz.f32 	%f8, %f19;
	mov.b32 	%r19, %f8;
	mov.u32 	%r20, 2;
	mov.u32 	%r21, 4127;
	mov.u32 	%r22, 8;
	mov.u32 	%r23, -1;
	shfl.sync.down.b32 	%r24|%p5, %r19, %r22, %r21, %r23;
	mov.b32 	%f9, %r24;
	max.ftz.f32 	%f10, %f8, %f9;
	mov.b32 	%r25, %f10;
	mov.u32 	%r26, 4;
	shfl.sync.down.b32 	%r27|%p6, %r25, %r26, %r21, %r23;
	mov.b32 	%f11, %r27;
	max.ftz.f32 	%f12, %f10, %f11;
	mov.b32 	%r28, %f12;
	shfl.sync.down.b32 	%r29|%p7, %r28, %r20, %r21, %r23;
	mov.b32 	%f13, %r29;
	max.ftz.f32 	%f14, %f12, %f13;
	mov.b32 	%r30, %f14;
	mov.u32 	%r31, 1;
	shfl.sync.down.b32 	%r32|%p8, %r30, %r31, %r21, %r23;
	mov.b32 	%f15, %r32;
	max.ftz.f32 	%f16, %f14, %f15;
	mov.b32 	%r33, %f16;
	mov.u32 	%r34, 0;
	shfl.sync.idx.b32 	%r35|%p9, %r33, %r34, %r21, %r23;
	mov.b32 	%f3, %r35;
	setp.leu.ftz.f32 	%p10, %f3, 0f00000000;
	@%p10 bra 	$L__BB0_5;

	mov.f32 	%f17, 0f42FE0000;
	div.approx.ftz.f32 	%f20, %f3, %f17;

$L__BB0_5:
	setp.ne.s32 	%p11, %r2, 0;
	@%p11 bra 	$L__BB0_7;

	mad.lo.s32 	%r36, %r4, %r5, %r1;
	cvta.to.global.u64 	%rd7, %rd3;
	mul.wide.s32 	%rd8, %r36, 4;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f20;

$L__BB0_7:
	@%p4 bra 	$L__BB0_11;

	setp.leu.ftz.f32 	%p13, %f20, 0f00000000;
	mov.u32 	%r41, 0;
	@%p13 bra 	$L__BB0_10;

	div.approx.ftz.f32 	%f18, %f19, %f20;
	cvt.rni.ftz.s32.f32 	%r41, %f18;

$L__BB0_10:
	min.s32 	%r38, %r41, 127;
	max.s32 	%r39, %r38, -127;
	mad.lo.s32 	%r40, %r5, %r8, %r3;
	cvt.s64.s32 	%rd10, %r40;
	cvta.to.global.u64 	%rd11, %rd2;
	add.s64 	%rd12, %rd11, %rd10;
	st.global.u8 	[%rd12], %r39;

$L__BB0_11:
	ret;

}

`
