package tensor

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// Reference values generated by numpy (see testdata/reference.json).
// This test ensures bit-exact reproducibility against the Python reference.

func loadRefs(t *testing.T) map[string][]float64 {
	t.Helper()
	data, err := os.ReadFile("testdata/reference.json")
	if err != nil {
		t.Fatalf("load reference.json: %v", err)
	}
	var refs map[string][]float64
	if err := json.Unmarshal(data, &refs); err != nil {
		t.Fatalf("parse reference.json: %v", err)
	}
	return refs
}

func f64to32(d []float64) []float32 {
	out := make([]float32, len(d))
	for i, v := range d {
		out[i] = float32(v)
	}
	return out
}

func assertClose(t *testing.T, name string, got, want []float32, atol float32) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch: got %d, want %d", name, len(got), len(want))
	}
	for i := range got {
		diff := float32(math.Abs(float64(got[i] - want[i])))
		if diff > atol {
			t.Errorf("%s[%d]: got %v, want %v (diff=%v, atol=%v)", name, i, got[i], want[i], diff, atol)
		}
	}
}

func TestReferenceAdd(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	b := FromFloat32(f64to32(r["binary_b"]), []int{6})
	assertClose(t, "add", a.Add(b).Data(), f64to32(r["add"]), 1e-6)
}

func TestReferenceSub(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	b := FromFloat32(f64to32(r["binary_b"]), []int{6})
	assertClose(t, "sub", a.Sub(b).Data(), f64to32(r["sub"]), 1e-6)
}

func TestReferenceMul(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	b := FromFloat32(f64to32(r["binary_b"]), []int{6})
	assertClose(t, "mul", a.Mul(b).Data(), f64to32(r["mul"]), 1e-6)
}

func TestReferenceDiv(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	b := FromFloat32(f64to32(r["binary_b"]), []int{6})
	assertClose(t, "div", a.Div(b).Data(), f64to32(r["div"]), 1e-5)
}

func TestReferenceNeg(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	assertClose(t, "neg", a.Neg().Data(), f64to32(r["neg"]), 1e-6)
}

func TestReferenceSqrt(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["sqrt_input"]), []int{6})
	assertClose(t, "sqrt", a.Sqrt().Data(), f64to32(r["sqrt"]), 1e-6)
}

func TestReferenceExp2(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	assertClose(t, "exp2", a.Exp2().Data(), f64to32(r["exp2"]), 1e-3)
}

func TestReferenceLog2(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["log2_input"]), []int{6})
	assertClose(t, "log2", a.Log2().Data(), f64to32(r["log2"]), 1e-5)
}

func TestReferenceRecip(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["binary_a"]), []int{6})
	assertClose(t, "recip", a.Recip().Data(), f64to32(r["recip"]), 1e-5)
}

func TestReferenceReduceSumAxis1(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["reduce_input"]), []int{2, 3})
	assertClose(t, "sum_axis1", a.Sum(1).Data(), f64to32(r["reduce_sum_axis1"]), 1e-5)
}

func TestReferenceReduceSumAxis0(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["reduce_input"]), []int{2, 3})
	assertClose(t, "sum_axis0", a.Sum(0).Data(), f64to32(r["reduce_sum_axis0"]), 1e-5)
}

func TestReferenceReduceMaxAxis1(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["reduce_input"]), []int{2, 3})
	assertClose(t, "max_axis1", a.ReduceMax(1).Data(), f64to32(r["reduce_max_axis1"]), 1e-6)
}

func TestReferenceMatMul(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["matmul_a"]), []int{2, 3})
	b := FromFloat32(f64to32(r["matmul_b"]), []int{3, 2})
	assertClose(t, "matmul", a.MatMul(b).Data(), f64to32(r["matmul_result"]), 1e-5)
}

func TestReferenceMatMulTransposed(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["matmul_a"]), []int{2, 3})
	w := FromFloat32(f64to32(r["matmul_t_w"]), []int{4, 3})
	assertClose(t, "matmul_t", a.MatMulTransposed(w).Data(), f64to32(r["matmul_t_result"]), 1e-5)
}

func TestReferencePermute(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["permute_input"]), []int{2, 3})
	assertClose(t, "permute", a.Permute([]int{1, 0}).Data(), f64to32(r["permute_result"]), 1e-6)
}

func TestReferenceBroadcastAdd(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["broadcast_a"]), []int{2, 3})
	b := FromFloat32(f64to32(r["broadcast_b"]), []int{3})
	assertClose(t, "broadcast_add", a.Add(b).Data(), f64to32(r["broadcast_add"]), 1e-6)
}

func TestReferenceSoftmax(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["softmax_input"]), []int{1, 4})
	assertClose(t, "softmax", a.Softmax().Data(), f64to32(r["softmax_result"]), 1e-6)
}

func TestReferenceLayerNorm(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["layernorm_input"]), []int{2, 3})
	gamma := Ones([]int{3})
	beta := Zeros([]int{3})
	assertClose(t, "layernorm", a.LayerNorm(gamma, beta, 1e-5).Data(), f64to32(r["layernorm_result"]), 1e-4)
}

func TestReferenceGELU(t *testing.T) {
	r := loadRefs(t)
	a := FromFloat32(f64to32(r["gelu_input"]), []int{5})
	assertClose(t, "gelu", a.GELU().Data(), f64to32(r["gelu_result"]), 1e-5)
}

func TestReferenceLinear(t *testing.T) {
	r := loadRefs(t)
	x := FromFloat32(f64to32(r["linear_x"]), []int{2, 3})
	w := FromFloat32(f64to32(r["linear_w"]), []int{2, 3})
	bias := FromFloat32(f64to32(r["linear_bias"]), []int{2})
	assertClose(t, "linear", x.Linear(w, bias).Data(), f64to32(r["linear_result"]), 1e-5)
}
