#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
nvcc=${NVCC:-/usr/local/cuda/bin/nvcc}
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
"$nvcc" -ptx -arch=sm_86 -O3 --use_fast_math "$root/scripts/kernels/qk_staged.cu" -o "$tmp/staged.ptx"
{
  printf 'package ptx\n\n// Generated by scripts/generate-qk-staged-ptx.sh; CUDA 12.8, sm_86.\nconst QKStagedPTX = `\n'
  cat "$tmp/staged.ptx"
  printf '`\n'
} > "$root/backends/nvidia/ptx/qk_staged_generated.go"
gofmt -w "$root/backends/nvidia/ptx/qk_staged_generated.go"
