package ptx

// CausalBatchAttentionWarpPTX computes causal grouped-query attention for packed
// query rows over one shared physical KV sequence.
//
// Each CUDA block owns one (query head, query row) pair. Its eight warps compute
// different Q·K scores in parallel; the 32 lanes reduce one head-dimension dot
// product with warp shuffles. The block then reduces the softmax maximum and sum
// across 256 threads, keeps up to 2,048 probabilities in shared memory, and
// assigns output dimensions across the block for the probability·V reduction.
// Causal and sliding-window bounds are derived from POS0, the row index, KV_LEN,
// and WINDOW before either reduction.
//
// The generated sm_86 image uses 61 registers per thread and 9,216 bytes of
// static shared memory. It has no stack frame or local-memory spills. Production
// loads the embedded PTX through the NVIDIA Driver API; nvcc is required only to
// regenerate it. The source was compiled with CUDA 12.8, -O3, and
// --use_fast_math.
//
// The numerical contract is the existing F32 causal-GQA result. Synthetic full
// and windowed CPU differentials use a 2e-5 absolute/relative limit. A direct
// comparison with the previous serial-dot PTX measured a 3.0e-8 maximum absolute
// difference. The pinned Gemma 4 12B released-model parity gate must pass before
// this kernel is accepted.
const CausalBatchAttentionWarpPTX = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gqa_attention_causal_batch
// _ZZ26gqa_attention_causal_batchE6scores has been demoted
// _ZZ26gqa_attention_causal_batchE6reduce has been demoted

.visible .entry gqa_attention_causal_batch(
	.param .u64 gqa_attention_causal_batch_param_0,
	.param .u64 gqa_attention_causal_batch_param_1,
	.param .u64 gqa_attention_causal_batch_param_2,
	.param .u64 gqa_attention_causal_batch_param_3,
	.param .u32 gqa_attention_causal_batch_param_4,
	.param .u32 gqa_attention_causal_batch_param_5,
	.param .u32 gqa_attention_causal_batch_param_6,
	.param .u32 gqa_attention_causal_batch_param_7,
	.param .u32 gqa_attention_causal_batch_param_8,
	.param .u32 gqa_attention_causal_batch_param_9,
	.param .u32 gqa_attention_causal_batch_param_10,
	.param .f32 gqa_attention_causal_batch_param_11
)
.maxntid 256, 1, 1
.minnctapersm 1
{
	.reg .pred 	%p<64>;
	.reg .f32 	%f<202>;
	.reg .b32 	%r<255>;
	.reg .b64 	%rd<56>;
	// demoted variable
	.shared .align 4 .b8 _ZZ26gqa_attention_causal_batchE6scores[8192];
	// demoted variable
	.shared .align 4 .b8 _ZZ26gqa_attention_causal_batchE6reduce[1024];

	ld.param.u64 	%rd19, [gqa_attention_causal_batch_param_0];
	ld.param.u64 	%rd20, [gqa_attention_causal_batch_param_1];
	ld.param.u64 	%rd21, [gqa_attention_causal_batch_param_2];
	ld.param.u64 	%rd22, [gqa_attention_causal_batch_param_3];
	ld.param.u32 	%r99, [gqa_attention_causal_batch_param_4];
	ld.param.u32 	%r93, [gqa_attention_causal_batch_param_5];
	ld.param.u32 	%r94, [gqa_attention_causal_batch_param_6];
	ld.param.u32 	%r95, [gqa_attention_causal_batch_param_7];
	ld.param.u32 	%r96, [gqa_attention_causal_batch_param_8];
	ld.param.u32 	%r97, [gqa_attention_causal_batch_param_9];
	ld.param.u32 	%r98, [gqa_attention_causal_batch_param_10];
	ld.param.f32 	%f34, [gqa_attention_causal_batch_param_11];
	cvta.to.global.u64 	%rd1, %rd21;
	cvta.to.global.u64 	%rd2, %rd22;
	mov.u32 	%r249, %tid.x;
	and.b32  	%r2, %r249, 31;
	mov.u32 	%r3, %ctaid.x;
	setp.ge.s32 	%p1, %r3, %r96;
	mov.u32 	%r4, %ctaid.y;
	setp.ge.s32 	%p2, %r4, %r99;
	or.pred  	%p3, %p2, %p1;
	@%p3 bra 	$L__BB0_84;

	shr.s32 	%r226, %r249, 5;
	div.s32 	%r100, %r96, %r97;
	div.s32 	%r6, %r3, %r100;
	mad.lo.s32 	%r101, %r4, %r96, %r3;
	mul.lo.s32 	%r7, %r101, %r98;
	mul.lo.s32 	%r8, %r98, %r97;
	add.s32 	%r102, %r4, %r93;
	add.s32 	%r103, %r102, 1;
	min.s32 	%r104, %r103, %r94;
	setp.gt.s32 	%p4, %r104, %r95;
	setp.gt.s32 	%p5, %r95, 0;
	and.pred  	%p6, %p5, %p4;
	sub.s32 	%r105, %r104, %r95;
	selp.b32 	%r9, %r105, 0, %p6;
	sub.s32 	%r10, %r104, %r9;
	setp.ge.s32 	%p7, %r226, %r10;
	@%p7 bra 	$L__BB0_14;

	not.b32 	%r106, %r2;
	add.s32 	%r11, %r106, %r98;
	shr.u32 	%r107, %r11, 5;
	add.s32 	%r108, %r107, 1;
	and.b32  	%r12, %r108, 3;
	add.s32 	%r109, %r2, %r7;
	cvta.to.global.u64 	%rd23, %rd19;
	mul.wide.s32 	%rd24, %r109, 4;
	add.s64 	%rd3, %rd23, %rd24;
	or.b32  	%r13, %r2, 32;
	or.b32  	%r14, %r2, 64;
	or.b32  	%r15, %r2, 96;
	cvta.to.global.u64 	%rd25, %rd20;

$L__BB0_3:
	add.s32 	%r17, %r226, %r9;
	setp.ge.s32 	%p8, %r2, %r98;
	mov.f32 	%f187, 0f00000000;
	@%p8 bra 	$L__BB0_11;

	setp.eq.s32 	%p9, %r12, 0;
	mov.f32 	%f187, 0f00000000;
	mov.u32 	%r227, %r2;
	@%p9 bra 	$L__BB0_8;

	setp.eq.s32 	%p10, %r12, 1;
	mul.lo.s32 	%r111, %r6, %r98;
	mad.lo.s32 	%r18, %r17, %r8, %r111;
	mov.u32 	%r112, %tid.x;
	and.b32  	%r113, %r112, 31;
	add.s32 	%r114, %r18, %r113;
	mul.wide.s32 	%rd26, %r114, 4;
	add.s64 	%rd27, %rd25, %rd26;
	ld.global.f32 	%f38, [%rd27];
	ld.global.f32 	%f39, [%rd3];
	mov.f32 	%f40, 0f00000000;
	fma.rn.ftz.f32 	%f187, %f39, %f38, %f40;
	mov.u32 	%r227, %r13;
	@%p10 bra 	$L__BB0_8;

	setp.eq.s32 	%p11, %r12, 2;
	ld.global.f32 	%f41, [%rd27+128];
	ld.global.f32 	%f42, [%rd3+128];
	fma.rn.ftz.f32 	%f187, %f42, %f41, %f187;
	mov.u32 	%r227, %r14;
	@%p11 bra 	$L__BB0_8;

	ld.global.f32 	%f43, [%rd27+256];
	ld.global.f32 	%f44, [%rd3+256];
	fma.rn.ftz.f32 	%f187, %f44, %f43, %f187;
	mov.u32 	%r227, %r15;

$L__BB0_8:
	setp.lt.u32 	%p12, %r11, 96;
	@%p12 bra 	$L__BB0_11;

	mad.lo.s32 	%r124, %r97, %r17, %r6;
	mad.lo.s32 	%r125, %r98, %r124, %r227;
	mul.wide.s32 	%rd5, %r125, 4;
	add.s32 	%r126, %r7, %r227;
	mul.wide.s32 	%rd35, %r126, 4;
	add.s64 	%rd52, %rd23, %rd35;
	mov.u64 	%rd53, %rd25;

$L__BB0_10:
	add.s64 	%rd36, %rd53, %rd5;
	ld.global.f32 	%f45, [%rd36];
	ld.global.f32 	%f46, [%rd52];
	fma.rn.ftz.f32 	%f47, %f46, %f45, %f187;
	ld.global.f32 	%f48, [%rd36+128];
	ld.global.f32 	%f49, [%rd52+128];
	fma.rn.ftz.f32 	%f50, %f49, %f48, %f47;
	ld.global.f32 	%f51, [%rd36+256];
	ld.global.f32 	%f52, [%rd52+256];
	fma.rn.ftz.f32 	%f53, %f52, %f51, %f50;
	ld.global.f32 	%f54, [%rd36+384];
	ld.global.f32 	%f55, [%rd52+384];
	fma.rn.ftz.f32 	%f187, %f55, %f54, %f53;
	add.s64 	%rd53, %rd53, 512;
	add.s64 	%rd52, %rd52, 512;
	add.s32 	%r227, %r227, 128;
	setp.lt.s32 	%p13, %r227, %r98;
	@%p13 bra 	$L__BB0_10;

$L__BB0_11:
	mov.b32 	%r127, %f187;
	mov.u32 	%r128, 2;
	mov.u32 	%r129, 31;
	mov.u32 	%r130, 16;
	mov.u32 	%r131, -1;
	shfl.sync.down.b32 	%r132|%p14, %r127, %r130, %r129, %r131;
	mov.b32 	%f56, %r132;
	add.ftz.f32 	%f57, %f187, %f56;
	mov.b32 	%r133, %f57;
	mov.u32 	%r134, 8;
	shfl.sync.down.b32 	%r135|%p15, %r133, %r134, %r129, %r131;
	mov.b32 	%f58, %r135;
	add.ftz.f32 	%f59, %f57, %f58;
	mov.b32 	%r136, %f59;
	mov.u32 	%r137, 4;
	shfl.sync.down.b32 	%r138|%p16, %r136, %r137, %r129, %r131;
	mov.b32 	%f60, %r138;
	add.ftz.f32 	%f61, %f59, %f60;
	mov.b32 	%r139, %f61;
	shfl.sync.down.b32 	%r140|%p17, %r139, %r128, %r129, %r131;
	mov.b32 	%f62, %r140;
	add.ftz.f32 	%f63, %f61, %f62;
	mov.b32 	%r141, %f63;
	mov.u32 	%r142, 1;
	shfl.sync.down.b32 	%r143|%p18, %r141, %r142, %r129, %r131;
	mov.b32 	%f64, %r143;
	add.ftz.f32 	%f9, %f63, %f64;
	setp.ne.s32 	%p19, %r2, 0;
	@%p19 bra 	$L__BB0_13;

	mul.ftz.f32 	%f65, %f9, %f34;
	shl.b32 	%r144, %r226, 2;
	mov.u32 	%r145, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r146, %r145, %r144;
	st.shared.f32 	[%r146], %f65;

$L__BB0_13:
	add.s32 	%r226, %r226, 8;
	setp.lt.s32 	%p20, %r226, %r10;
	@%p20 bra 	$L__BB0_3;

$L__BB0_14:
	bar.sync 	0;
	setp.ge.s32 	%p21, %r249, %r10;
	mov.f32 	%f192, 0fFF7FFFFF;
	@%p21 bra 	$L__BB0_21;

	mov.u32 	%r147, -2;
	sub.s32 	%r148, %r147, %r9;
	sub.s32 	%r149, %r148, %r249;
	sub.s32 	%r151, %r147, %r4;
	sub.s32 	%r152, %r151, %r93;
	not.b32 	%r153, %r94;
	max.s32 	%r154, %r152, %r153;
	sub.s32 	%r23, %r149, %r154;
	shr.u32 	%r155, %r23, 8;
	add.s32 	%r156, %r155, 1;
	and.b32  	%r231, %r156, 3;
	setp.eq.s32 	%p22, %r231, 0;
	mov.f32 	%f192, 0fFF7FFFFF;
	mov.u32 	%r232, %r249;
	@%p22 bra 	$L__BB0_18;

	shl.b32 	%r157, %r249, 2;
	mov.u32 	%r158, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r229, %r158, %r157;
	mov.f32 	%f192, 0fFF7FFFFF;
	mov.u32 	%r232, %r249;

$L__BB0_17:
	.pragma "nounroll";
	ld.shared.f32 	%f70, [%r229];
	max.ftz.f32 	%f192, %f192, %f70;
	add.s32 	%r232, %r232, 256;
	add.s32 	%r229, %r229, 1024;
	add.s32 	%r231, %r231, -1;
	setp.ne.s32 	%p23, %r231, 0;
	@%p23 bra 	$L__BB0_17;

$L__BB0_18:
	setp.lt.u32 	%p24, %r23, 768;
	@%p24 bra 	$L__BB0_21;

	shl.b32 	%r159, %r232, 2;
	mov.u32 	%r160, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r161, %r160, %r159;
	add.s32 	%r233, %r161, 2048;

$L__BB0_20:
	ld.shared.f32 	%f71, [%r233+-2048];
	max.ftz.f32 	%f72, %f192, %f71;
	ld.shared.f32 	%f73, [%r233+-1024];
	max.ftz.f32 	%f74, %f72, %f73;
	ld.shared.f32 	%f75, [%r233];
	max.ftz.f32 	%f76, %f74, %f75;
	ld.shared.f32 	%f77, [%r233+1024];
	max.ftz.f32 	%f192, %f76, %f77;
	add.s32 	%r233, %r233, 4096;
	add.s32 	%r232, %r232, 1024;
	setp.lt.s32 	%p25, %r232, %r10;
	@%p25 bra 	$L__BB0_20;

$L__BB0_21:
	shl.b32 	%r162, %r249, 2;
	mov.u32 	%r163, _ZZ26gqa_attention_causal_batchE6reduce;
	add.s32 	%r38, %r163, %r162;
	st.shared.f32 	[%r38], %f192;
	bar.sync 	0;
	setp.gt.s32 	%p26, %r249, 127;
	@%p26 bra 	$L__BB0_23;

	ld.shared.f32 	%f78, [%r38];
	ld.shared.f32 	%f79, [%r38+512];
	max.ftz.f32 	%f80, %f78, %f79;
	st.shared.f32 	[%r38], %f80;

$L__BB0_23:
	bar.sync 	0;
	setp.gt.s32 	%p27, %r249, 63;
	@%p27 bra 	$L__BB0_25;

	ld.shared.f32 	%f81, [%r38];
	ld.shared.f32 	%f82, [%r38+256];
	max.ftz.f32 	%f83, %f81, %f82;
	st.shared.f32 	[%r38], %f83;

$L__BB0_25:
	bar.sync 	0;
	setp.gt.s32 	%p28, %r249, 31;
	@%p28 bra 	$L__BB0_27;

	ld.shared.f32 	%f84, [%r38];
	ld.shared.f32 	%f85, [%r38+128];
	max.ftz.f32 	%f86, %f84, %f85;
	st.shared.f32 	[%r38], %f86;

$L__BB0_27:
	bar.sync 	0;
	setp.gt.s32 	%p29, %r249, 15;
	@%p29 bra 	$L__BB0_29;

	ld.shared.f32 	%f87, [%r38];
	ld.shared.f32 	%f88, [%r38+64];
	max.ftz.f32 	%f89, %f87, %f88;
	st.shared.f32 	[%r38], %f89;

$L__BB0_29:
	bar.sync 	0;
	setp.gt.s32 	%p30, %r249, 7;
	@%p30 bra 	$L__BB0_31;

	ld.shared.f32 	%f90, [%r38];
	ld.shared.f32 	%f91, [%r38+32];
	max.ftz.f32 	%f92, %f90, %f91;
	st.shared.f32 	[%r38], %f92;

$L__BB0_31:
	bar.sync 	0;
	setp.gt.s32 	%p31, %r249, 3;
	@%p31 bra 	$L__BB0_33;

	ld.shared.f32 	%f93, [%r38];
	ld.shared.f32 	%f94, [%r38+16];
	max.ftz.f32 	%f95, %f93, %f94;
	st.shared.f32 	[%r38], %f95;

$L__BB0_33:
	bar.sync 	0;
	setp.gt.s32 	%p32, %r249, 1;
	@%p32 bra 	$L__BB0_35;

	ld.shared.f32 	%f96, [%r38];
	ld.shared.f32 	%f97, [%r38+8];
	max.ftz.f32 	%f98, %f96, %f97;
	st.shared.f32 	[%r38], %f98;

$L__BB0_35:
	bar.sync 	0;
	setp.gt.s32 	%p33, %r249, 0;
	@%p33 bra 	$L__BB0_37;

	ld.shared.f32 	%f99, [%r38];
	ld.shared.f32 	%f100, [%r38+4];
	max.ftz.f32 	%f101, %f99, %f100;
	st.shared.f32 	[%r38], %f101;

$L__BB0_37:
	bar.sync 	0;
	mov.f32 	%f197, 0f00000000;
	ld.shared.f32 	%f17, [_ZZ26gqa_attention_causal_batchE6reduce];
	// All warps must read the shared maximum before any warp overwrites
	// the reduction workspace with its exponential sum.
	bar.sync 	0;
	@%p21 bra 	$L__BB0_44;

	mov.u32 	%r164, -2;
	sub.s32 	%r165, %r164, %r9;
	sub.s32 	%r166, %r165, %r249;
	sub.s32 	%r168, %r164, %r4;
	sub.s32 	%r169, %r168, %r93;
	not.b32 	%r170, %r94;
	max.s32 	%r171, %r169, %r170;
	sub.s32 	%r39, %r166, %r171;
	shr.u32 	%r172, %r39, 8;
	add.s32 	%r173, %r172, 1;
	and.b32  	%r237, %r173, 3;
	setp.eq.s32 	%p35, %r237, 0;
	mov.f32 	%f197, 0f00000000;
	mov.u32 	%r238, %r249;
	@%p35 bra 	$L__BB0_41;

	mov.u32 	%r175, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r235, %r175, %r162;
	mov.f32 	%f197, 0f00000000;
	mov.u32 	%r238, %r249;

$L__BB0_40:
	.pragma "nounroll";
	ld.shared.f32 	%f106, [%r235];
	sub.ftz.f32 	%f107, %f106, %f17;
	mul.ftz.f32 	%f108, %f107, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f109, %f108;
	st.shared.f32 	[%r235], %f109;
	add.ftz.f32 	%f197, %f197, %f109;
	add.s32 	%r238, %r238, 256;
	add.s32 	%r235, %r235, 1024;
	add.s32 	%r237, %r237, -1;
	setp.ne.s32 	%p36, %r237, 0;
	@%p36 bra 	$L__BB0_40;

$L__BB0_41:
	setp.lt.u32 	%p37, %r39, 768;
	@%p37 bra 	$L__BB0_44;

	shl.b32 	%r176, %r238, 2;
	mov.u32 	%r177, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r178, %r177, %r176;
	add.s32 	%r239, %r178, 2048;

$L__BB0_43:
	ld.shared.f32 	%f110, [%r239+-2048];
	sub.ftz.f32 	%f111, %f110, %f17;
	mul.ftz.f32 	%f112, %f111, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f113, %f112;
	st.shared.f32 	[%r239+-2048], %f113;
	add.ftz.f32 	%f114, %f197, %f113;
	ld.shared.f32 	%f115, [%r239+-1024];
	sub.ftz.f32 	%f116, %f115, %f17;
	mul.ftz.f32 	%f117, %f116, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f118, %f117;
	st.shared.f32 	[%r239+-1024], %f118;
	add.ftz.f32 	%f119, %f114, %f118;
	ld.shared.f32 	%f120, [%r239];
	sub.ftz.f32 	%f121, %f120, %f17;
	mul.ftz.f32 	%f122, %f121, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f123, %f122;
	st.shared.f32 	[%r239], %f123;
	add.ftz.f32 	%f124, %f119, %f123;
	ld.shared.f32 	%f125, [%r239+1024];
	sub.ftz.f32 	%f126, %f125, %f17;
	mul.ftz.f32 	%f127, %f126, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f128, %f127;
	st.shared.f32 	[%r239+1024], %f128;
	add.ftz.f32 	%f197, %f124, %f128;
	add.s32 	%r239, %r239, 4096;
	add.s32 	%r238, %r238, 1024;
	setp.lt.s32 	%p38, %r238, %r10;
	@%p38 bra 	$L__BB0_43;

$L__BB0_44:
	st.shared.f32 	[%r38], %f197;
	bar.sync 	0;
	@%p26 bra 	$L__BB0_46;

	ld.shared.f32 	%f129, [%r38];
	ld.shared.f32 	%f130, [%r38+512];
	add.ftz.f32 	%f131, %f130, %f129;
	st.shared.f32 	[%r38], %f131;

$L__BB0_46:
	bar.sync 	0;
	@%p27 bra 	$L__BB0_48;

	ld.shared.f32 	%f132, [%r38];
	ld.shared.f32 	%f133, [%r38+256];
	add.ftz.f32 	%f134, %f133, %f132;
	st.shared.f32 	[%r38], %f134;

$L__BB0_48:
	bar.sync 	0;
	@%p28 bra 	$L__BB0_50;

	ld.shared.f32 	%f135, [%r38];
	ld.shared.f32 	%f136, [%r38+128];
	add.ftz.f32 	%f137, %f136, %f135;
	st.shared.f32 	[%r38], %f137;

$L__BB0_50:
	bar.sync 	0;
	@%p29 bra 	$L__BB0_52;

	ld.shared.f32 	%f138, [%r38];
	ld.shared.f32 	%f139, [%r38+64];
	add.ftz.f32 	%f140, %f139, %f138;
	st.shared.f32 	[%r38], %f140;

$L__BB0_52:
	bar.sync 	0;
	@%p30 bra 	$L__BB0_54;

	ld.shared.f32 	%f141, [%r38];
	ld.shared.f32 	%f142, [%r38+32];
	add.ftz.f32 	%f143, %f142, %f141;
	st.shared.f32 	[%r38], %f143;

$L__BB0_54:
	bar.sync 	0;
	@%p31 bra 	$L__BB0_56;

	ld.shared.f32 	%f144, [%r38];
	ld.shared.f32 	%f145, [%r38+16];
	add.ftz.f32 	%f146, %f145, %f144;
	st.shared.f32 	[%r38], %f146;

$L__BB0_56:
	bar.sync 	0;
	@%p32 bra 	$L__BB0_58;

	ld.shared.f32 	%f147, [%r38];
	ld.shared.f32 	%f148, [%r38+8];
	add.ftz.f32 	%f149, %f148, %f147;
	st.shared.f32 	[%r38], %f149;

$L__BB0_58:
	bar.sync 	0;
	@%p33 bra 	$L__BB0_60;

	ld.shared.f32 	%f150, [%r38];
	ld.shared.f32 	%f151, [%r38+4];
	add.ftz.f32 	%f152, %f151, %f150;
	st.shared.f32 	[%r38], %f152;

$L__BB0_60:
	bar.sync 	0;
	ld.shared.f32 	%f153, [_ZZ26gqa_attention_causal_batchE6reduce];
	rcp.approx.ftz.f32 	%f25, %f153;
	@%p21 bra 	$L__BB0_67;

	mov.u32 	%r179, -2;
	sub.s32 	%r180, %r179, %r9;
	sub.s32 	%r181, %r180, %r249;
	sub.s32 	%r183, %r179, %r4;
	sub.s32 	%r184, %r183, %r93;
	not.b32 	%r185, %r94;
	max.s32 	%r186, %r184, %r185;
	sub.s32 	%r54, %r181, %r186;
	shr.u32 	%r187, %r54, 8;
	add.s32 	%r188, %r187, 1;
	and.b32  	%r243, %r188, 3;
	setp.eq.s32 	%p48, %r243, 0;
	mov.u32 	%r244, %r249;
	@%p48 bra 	$L__BB0_64;

	mov.u32 	%r190, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r241, %r190, %r162;
	mov.u32 	%r244, %r249;

$L__BB0_63:
	.pragma "nounroll";
	ld.shared.f32 	%f154, [%r241];
	mul.ftz.f32 	%f155, %f25, %f154;
	st.shared.f32 	[%r241], %f155;
	add.s32 	%r244, %r244, 256;
	add.s32 	%r241, %r241, 1024;
	add.s32 	%r243, %r243, -1;
	setp.ne.s32 	%p49, %r243, 0;
	@%p49 bra 	$L__BB0_63;

$L__BB0_64:
	setp.lt.u32 	%p50, %r54, 768;
	@%p50 bra 	$L__BB0_67;

	shl.b32 	%r191, %r244, 2;
	mov.u32 	%r192, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r193, %r192, %r191;
	add.s32 	%r245, %r193, 2048;

$L__BB0_66:
	ld.shared.f32 	%f156, [%r245+-2048];
	mul.ftz.f32 	%f157, %f25, %f156;
	st.shared.f32 	[%r245+-2048], %f157;
	ld.shared.f32 	%f158, [%r245+-1024];
	mul.ftz.f32 	%f159, %f25, %f158;
	st.shared.f32 	[%r245+-1024], %f159;
	ld.shared.f32 	%f160, [%r245];
	mul.ftz.f32 	%f161, %f25, %f160;
	st.shared.f32 	[%r245], %f161;
	ld.shared.f32 	%f162, [%r245+1024];
	mul.ftz.f32 	%f163, %f25, %f162;
	st.shared.f32 	[%r245+1024], %f163;
	add.s32 	%r245, %r245, 4096;
	add.s32 	%r244, %r244, 1024;
	setp.lt.s32 	%p51, %r244, %r10;
	@%p51 bra 	$L__BB0_66;

$L__BB0_67:
	bar.sync 	0;
	setp.ge.s32 	%p52, %r249, %r98;
	@%p52 bra 	$L__BB0_84;

	setp.gt.s32 	%p53, %r10, 0;
	@%p53 bra 	$L__BB0_75;
	bra.uni 	$L__BB0_69;

$L__BB0_75:
	not.b32 	%r201, %r9;
	mov.u32 	%r203, -2;
	sub.s32 	%r204, %r203, %r4;
	sub.s32 	%r205, %r204, %r93;
	not.b32 	%r206, %r94;
	max.s32 	%r207, %r205, %r206;
	sub.s32 	%r208, %r201, %r207;
	sub.s32 	%r209, %r203, %r9;
	sub.s32 	%r78, %r209, %r207;
	and.b32  	%r79, %r208, 3;
	sub.s32 	%r80, %r208, %r79;
	mul.wide.s32 	%rd18, %r8, 4;
	mul.lo.s32 	%r81, %r6, %r98;

$L__BB0_76:
	add.s32 	%r83, %r249, %r81;
	setp.lt.u32 	%p58, %r78, 3;
	mov.f32 	%f201, 0f00000000;
	mov.u32 	%r254, 0;
	@%p58 bra 	$L__BB0_79;

	mov.f32 	%f201, 0f00000000;
	mov.u32 	%r254, 0;
	mov.u32 	%r253, %r80;

$L__BB0_78:
	add.s32 	%r213, %r254, %r9;
	mad.lo.s32 	%r214, %r213, %r8, %r83;
	mul.wide.s32 	%rd39, %r214, 4;
	add.s64 	%rd40, %rd1, %rd39;
	ld.global.f32 	%f167, [%rd40];
	shl.b32 	%r215, %r254, 2;
	mov.u32 	%r216, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r217, %r216, %r215;
	ld.shared.f32 	%f168, [%r217];
	fma.rn.ftz.f32 	%f169, %f168, %f167, %f201;
	add.s64 	%rd41, %rd40, %rd18;
	ld.global.f32 	%f170, [%rd41];
	ld.shared.f32 	%f171, [%r217+4];
	fma.rn.ftz.f32 	%f172, %f171, %f170, %f169;
	add.s64 	%rd42, %rd41, %rd18;
	ld.global.f32 	%f173, [%rd42];
	ld.shared.f32 	%f174, [%r217+8];
	fma.rn.ftz.f32 	%f175, %f174, %f173, %f172;
	add.s64 	%rd43, %rd42, %rd18;
	ld.global.f32 	%f176, [%rd43];
	ld.shared.f32 	%f177, [%r217+12];
	fma.rn.ftz.f32 	%f201, %f177, %f176, %f175;
	add.s32 	%r254, %r254, 4;
	add.s32 	%r253, %r253, -4;
	setp.ne.s32 	%p59, %r253, 0;
	@%p59 bra 	$L__BB0_78;

$L__BB0_79:
	setp.eq.s32 	%p60, %r79, 0;
	@%p60 bra 	$L__BB0_83;

	setp.eq.s32 	%p61, %r79, 1;
	add.s32 	%r89, %r254, %r9;
	mul.lo.s32 	%r90, %r89, %r8;
	add.s32 	%r218, %r83, %r90;
	mul.wide.s32 	%rd44, %r218, 4;
	add.s64 	%rd45, %rd1, %rd44;
	ld.global.f32 	%f178, [%rd45];
	shl.b32 	%r219, %r254, 2;
	mov.u32 	%r220, _ZZ26gqa_attention_causal_batchE6scores;
	add.s32 	%r91, %r220, %r219;
	ld.shared.f32 	%f179, [%r91];
	fma.rn.ftz.f32 	%f201, %f179, %f178, %f201;
	@%p61 bra 	$L__BB0_83;

	setp.eq.s32 	%p62, %r79, 2;
	add.s32 	%r221, %r90, %r8;
	add.s32 	%r222, %r83, %r221;
	mul.wide.s32 	%rd46, %r222, 4;
	add.s64 	%rd47, %rd1, %rd46;
	ld.global.f32 	%f180, [%rd47];
	ld.shared.f32 	%f181, [%r91+4];
	fma.rn.ftz.f32 	%f201, %f181, %f180, %f201;
	@%p62 bra 	$L__BB0_83;

	add.s32 	%r223, %r89, 2;
	mad.lo.s32 	%r224, %r223, %r8, %r83;
	mul.wide.s32 	%rd48, %r224, 4;
	add.s64 	%rd49, %rd1, %rd48;
	ld.global.f32 	%f182, [%rd49];
	ld.shared.f32 	%f183, [%r91+8];
	fma.rn.ftz.f32 	%f201, %f183, %f182, %f201;

$L__BB0_83:
	add.s32 	%r225, %r249, %r7;
	mul.wide.s32 	%rd50, %r225, 4;
	add.s64 	%rd51, %rd2, %rd50;
	st.global.f32 	[%rd51], %f201;
	add.s32 	%r249, %r249, 256;
	setp.lt.s32 	%p63, %r249, %r98;
	@%p63 bra 	$L__BB0_76;
	bra.uni 	$L__BB0_84;

$L__BB0_69:
	not.b32 	%r194, %r249;
	add.s32 	%r69, %r194, %r98;
	shr.u32 	%r195, %r69, 8;
	add.s32 	%r196, %r195, 1;
	and.b32  	%r248, %r196, 3;
	setp.eq.s32 	%p54, %r248, 0;
	@%p54 bra 	$L__BB0_72;

	add.s32 	%r197, %r249, %r7;
	mul.wide.s32 	%rd37, %r197, 4;
	add.s64 	%rd54, %rd2, %rd37;

$L__BB0_71:
	.pragma "nounroll";
	mov.u32 	%r198, 0;
	st.global.u32 	[%rd54], %r198;
	add.s32 	%r249, %r249, 256;
	add.s64 	%rd54, %rd54, 1024;
	add.s32 	%r248, %r248, -1;
	setp.ne.s32 	%p55, %r248, 0;
	@%p55 bra 	$L__BB0_71;

$L__BB0_72:
	setp.lt.u32 	%p56, %r69, 768;
	@%p56 bra 	$L__BB0_84;

	add.s32 	%r199, %r249, %r7;
	mul.wide.s32 	%rd38, %r199, 4;
	add.s64 	%rd55, %rd2, %rd38;

$L__BB0_74:
	mov.u32 	%r200, 0;
	st.global.u32 	[%rd55], %r200;
	st.global.u32 	[%rd55+1024], %r200;
	st.global.u32 	[%rd55+2048], %r200;
	st.global.u32 	[%rd55+3072], %r200;
	add.s64 	%rd55, %rd55, 4096;
	add.s32 	%r249, %r249, 1024;
	setp.lt.s32 	%p57, %r249, %r98;
	@%p57 bra 	$L__BB0_74;

$L__BB0_84:
	ret;

}

`
