package ptx

// LongAttentionPTX is generated from scripts/kernels/attention_long.cu.
// Regenerate with scripts/generate-long-attention-ptx.sh (CUDA 12.8, sm_86).
const LongAttentionPTX = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	gqa_attention_long
// _ZZ18gqa_attention_longE6reduce has been demoted

.visible .entry gqa_attention_long(
	.param .u64 gqa_attention_long_param_0,
	.param .u64 gqa_attention_long_param_1,
	.param .u64 gqa_attention_long_param_2,
	.param .u64 gqa_attention_long_param_3,
	.param .u64 gqa_attention_long_param_4,
	.param .u64 gqa_attention_long_param_5,
	.param .u64 gqa_attention_long_param_6,
	.param .u64 gqa_attention_long_param_7,
	.param .u64 gqa_attention_long_param_8,
	.param .u64 gqa_attention_long_param_9,
	.param .u32 gqa_attention_long_param_10,
	.param .u32 gqa_attention_long_param_11,
	.param .u32 gqa_attention_long_param_12,
	.param .u32 gqa_attention_long_param_13,
	.param .u32 gqa_attention_long_param_14,
	.param .u32 gqa_attention_long_param_15,
	.param .u32 gqa_attention_long_param_16,
	.param .u32 gqa_attention_long_param_17,
	.param .u32 gqa_attention_long_param_18,
	.param .u32 gqa_attention_long_param_19,
	.param .u32 gqa_attention_long_param_20,
	.param .u32 gqa_attention_long_param_21,
	.param .u32 gqa_attention_long_param_22,
	.param .u32 gqa_attention_long_param_23,
	.param .f32 gqa_attention_long_param_24
)
.maxntid 256, 1, 1
.minnctapersm 1
{
	.reg .pred 	%p<99>;
	.reg .f32 	%f<303>;
	.reg .b32 	%r<372>;
	.reg .b64 	%rd<218>;
	// demoted variable
	.shared .align 4 .b8 _ZZ18gqa_attention_longE6reduce[1024];

	ld.param.u64 	%rd40, [gqa_attention_long_param_0];
	ld.param.u64 	%rd35, [gqa_attention_long_param_1];
	ld.param.u64 	%rd41, [gqa_attention_long_param_2];
	ld.param.u64 	%rd36, [gqa_attention_long_param_3];
	ld.param.u64 	%rd42, [gqa_attention_long_param_4];
	ld.param.u64 	%rd37, [gqa_attention_long_param_5];
	ld.param.u64 	%rd38, [gqa_attention_long_param_6];
	ld.param.u64 	%rd43, [gqa_attention_long_param_7];
	ld.param.u64 	%rd39, [gqa_attention_long_param_8];
	ld.param.u64 	%rd44, [gqa_attention_long_param_9];
	ld.param.u32 	%r129, [gqa_attention_long_param_10];
	ld.param.u32 	%r117, [gqa_attention_long_param_11];
	ld.param.u32 	%r118, [gqa_attention_long_param_12];
	ld.param.u32 	%r119, [gqa_attention_long_param_13];
	ld.param.u32 	%r120, [gqa_attention_long_param_14];
	ld.param.u32 	%r121, [gqa_attention_long_param_15];
	ld.param.u32 	%r122, [gqa_attention_long_param_16];
	ld.param.u32 	%r123, [gqa_attention_long_param_17];
	ld.param.u32 	%r124, [gqa_attention_long_param_18];
	ld.param.u32 	%r340, [gqa_attention_long_param_19];
	ld.param.u32 	%r126, [gqa_attention_long_param_20];
	ld.param.u32 	%r127, [gqa_attention_long_param_21];
	ld.param.u32 	%r130, [gqa_attention_long_param_22];
	ld.param.u32 	%r128, [gqa_attention_long_param_23];
	ld.param.f32 	%f56, [gqa_attention_long_param_24];
	cvta.to.global.u64 	%rd1, %rd40;
	cvta.to.global.u64 	%rd2, %rd42;
	cvta.to.global.u64 	%rd3, %rd41;
	cvta.to.global.u64 	%rd4, %rd44;
	cvta.to.global.u64 	%rd5, %rd43;
	mov.u32 	%r1, %ctaid.y;
	add.s32 	%r2, %r1, %r130;
	setp.ge.s32 	%p1, %r2, %r129;
	mov.u32 	%r3, %ctaid.x;
	setp.ge.s32 	%p2, %r3, %r120;
	or.pred  	%p3, %p2, %p1;
	@%p3 bra 	$L__BB0_124;

	mov.u32 	%r363, %tid.x;
	and.b32  	%r5, %r363, 31;
	shr.s32 	%r131, %r363, 31;
	shr.u32 	%r132, %r131, 27;
	add.s32 	%r133, %r363, %r132;
	shr.s32 	%r342, %r133, 5;
	div.s32 	%r134, %r120, %r121;
	div.s32 	%r7, %r3, %r134;
	mad.lo.s32 	%r135, %r2, %r120, %r3;
	mul.lo.s32 	%r8, %r135, %r122;
	mul.lo.s32 	%r9, %r122, %r121;
	setp.eq.s32 	%p4, %r127, 0;
	@%p4 bra 	$L__BB0_4;

	setp.ne.s32 	%p5, %r127, 1;
	@%p5 bra 	$L__BB0_6;

	mul.wide.s32 	%rd45, %r2, 4;
	add.s64 	%rd46, %rd5, %rd45;
	ld.global.u32 	%r339, [%rd46];
	add.s32 	%r341, %r126, %r340;
	mov.u32 	%r336, 0;
	mov.u32 	%r337, %r336;
	mov.u32 	%r338, %r336;
	bra.uni 	$L__BB0_8;

$L__BB0_4:
	add.s32 	%r144, %r117, %r2;
	add.s32 	%r145, %r144, 1;
	min.s32 	%r341, %r145, %r118;
	setp.lt.s32 	%p6, %r119, 1;
	mov.u32 	%r336, 0;
	mov.u32 	%r337, %r336;
	mov.u32 	%r338, %r336;
	mov.u32 	%r339, %r336;
	mov.u32 	%r340, %r336;
	@%p6 bra 	$L__BB0_8;

	sub.s32 	%r150, %r341, %r119;
	max.s32 	%r340, %r150, 0;
	bra.uni 	$L__BB0_8;

$L__BB0_6:
	mul.lo.s32 	%r153, %r2, 3;
	mul.wide.s32 	%rd47, %r153, 4;
	add.s64 	%rd48, %rd5, %rd47;
	ld.global.u32 	%r337, [%rd48+4];
	add.s32 	%r154, %r123, %r2;
	add.s32 	%r155, %r154, 1;
	ld.global.u32 	%r336, [%rd48];
	sub.s32 	%r156, %r155, %r336;
	ld.global.u32 	%r338, [%rd48+8];
	add.s32 	%r341, %r156, %r338;
	setp.lt.s32 	%p7, %r119, 1;
	mov.u32 	%r339, 0;
	mov.u32 	%r340, %r339;
	@%p7 bra 	$L__BB0_8;

	sub.s32 	%r158, %r341, %r119;
	max.s32 	%r340, %r158, 0;

$L__BB0_8:
	mad.lo.s32 	%r159, %r1, %r120, %r3;
	mul.lo.s32 	%r160, %r159, %r128;
	cvt.u64.u32 	%rd6, %r160;
	sub.s32 	%r25, %r341, %r340;
	setp.ge.s32 	%p8, %r342, %r25;
	@%p8 bra 	$L__BB0_51;

	add.s32 	%r161, %r5, %r8;
	mul.wide.s32 	%rd49, %r161, 4;
	add.s64 	%rd7, %rd1, %rd49;
	@%p4 bra 	$L__BB0_25;

	setp.ne.s32 	%p10, %r127, 1;
	@%p10 bra 	$L__BB0_37;

	not.b32 	%r162, %r5;
	add.s32 	%r163, %r162, %r122;
	shr.u32 	%r164, %r163, 5;
	add.s32 	%r165, %r164, 1;
	and.b32  	%r26, %r165, 3;
	or.b32  	%r27, %r5, 32;
	or.b32  	%r28, %r5, 64;
	or.b32  	%r29, %r5, 96;
	cvta.to.global.u64 	%rd53, %rd37;
	cvta.to.global.u64 	%rd58, %rd36;

$L__BB0_12:
	add.s32 	%r31, %r342, %r340;
	setp.lt.s32 	%p11, %r31, %r123;
	@%p11 bra 	$L__BB0_14;
	bra.uni 	$L__BB0_13;

$L__BB0_14:
	mul.lo.s32 	%r171, %r31, %r9;
	cvt.s64.s32 	%rd55, %r171;
	mul.lo.s32 	%r172, %r7, %r122;
	cvt.s64.s32 	%rd56, %r172;
	add.s64 	%rd57, %rd55, %rd56;
	shl.b64 	%rd59, %rd57, 2;
	add.s64 	%rd213, %rd58, %rd59;
	bra.uni 	$L__BB0_15;

$L__BB0_13:
	mul.lo.s32 	%r166, %r339, %r124;
	sub.s32 	%r167, %r166, %r123;
	add.s32 	%r168, %r167, %r31;
	mul.lo.s32 	%r169, %r168, %r9;
	cvt.s64.s32 	%rd50, %r169;
	mul.lo.s32 	%r170, %r7, %r122;
	cvt.s64.s32 	%rd51, %r170;
	add.s64 	%rd52, %rd50, %rd51;
	shl.b64 	%rd54, %rd52, 2;
	add.s64 	%rd213, %rd53, %rd54;

$L__BB0_15:
	setp.ge.s32 	%p12, %r5, %r122;
	mov.f32 	%f278, 0f00000000;
	@%p12 bra 	$L__BB0_22;

	setp.eq.s32 	%p13, %r26, 0;
	mov.f32 	%f278, 0f00000000;
	mov.u32 	%r343, %r5;
	@%p13 bra 	$L__BB0_20;

	setp.eq.s32 	%p14, %r26, 1;
	shl.b32 	%r173, %r363, 2;
	cvt.u64.u32 	%rd60, %r173;
	and.b64  	%rd61, %rd60, 124;
	add.s64 	%rd62, %rd213, %rd61;
	ld.global.f32 	%f60, [%rd62];
	ld.global.f32 	%f61, [%rd7];
	mov.f32 	%f62, 0f00000000;
	fma.rn.ftz.f32 	%f278, %f61, %f60, %f62;
	mov.u32 	%r343, %r27;
	@%p14 bra 	$L__BB0_20;

	setp.eq.s32 	%p15, %r26, 2;
	ld.global.f32 	%f63, [%rd62+128];
	ld.global.f32 	%f64, [%rd7+128];
	fma.rn.ftz.f32 	%f278, %f64, %f63, %f278;
	mov.u32 	%r343, %r28;
	@%p15 bra 	$L__BB0_20;

	ld.global.f32 	%f65, [%rd62+256];
	ld.global.f32 	%f66, [%rd7+256];
	fma.rn.ftz.f32 	%f278, %f66, %f65, %f278;
	mov.u32 	%r343, %r29;

$L__BB0_20:
	not.b32 	%r176, %r363;
	or.b32  	%r177, %r176, -32;
	add.s32 	%r178, %r177, %r122;
	setp.lt.u32 	%p16, %r178, 96;
	@%p16 bra 	$L__BB0_22;

$L__BB0_21:
	add.s32 	%r179, %r343, %r8;
	mul.wide.s32 	%rd69, %r179, 4;
	add.s64 	%rd70, %rd1, %rd69;
	mul.wide.s32 	%rd71, %r343, 4;
	add.s64 	%rd72, %rd213, %rd71;
	ld.global.f32 	%f67, [%rd72];
	ld.global.f32 	%f68, [%rd70];
	fma.rn.ftz.f32 	%f69, %f68, %f67, %f278;
	ld.global.f32 	%f70, [%rd72+128];
	ld.global.f32 	%f71, [%rd70+128];
	fma.rn.ftz.f32 	%f72, %f71, %f70, %f69;
	ld.global.f32 	%f73, [%rd72+256];
	ld.global.f32 	%f74, [%rd70+256];
	fma.rn.ftz.f32 	%f75, %f74, %f73, %f72;
	ld.global.f32 	%f76, [%rd72+384];
	ld.global.f32 	%f77, [%rd70+384];
	fma.rn.ftz.f32 	%f278, %f77, %f76, %f75;
	add.s32 	%r343, %r343, 128;
	setp.lt.s32 	%p17, %r343, %r122;
	@%p17 bra 	$L__BB0_21;

$L__BB0_22:
	mov.b32 	%r180, %f278;
	mov.u32 	%r181, 2;
	mov.u32 	%r182, 31;
	mov.u32 	%r183, 16;
	mov.u32 	%r184, -1;
	shfl.sync.down.b32 	%r185|%p18, %r180, %r183, %r182, %r184;
	mov.b32 	%f78, %r185;
	add.ftz.f32 	%f79, %f278, %f78;
	mov.b32 	%r186, %f79;
	mov.u32 	%r187, 8;
	shfl.sync.down.b32 	%r188|%p19, %r186, %r187, %r182, %r184;
	mov.b32 	%f80, %r188;
	add.ftz.f32 	%f81, %f79, %f80;
	mov.b32 	%r189, %f81;
	mov.u32 	%r190, 4;
	shfl.sync.down.b32 	%r191|%p20, %r189, %r190, %r182, %r184;
	mov.b32 	%f82, %r191;
	add.ftz.f32 	%f83, %f81, %f82;
	mov.b32 	%r192, %f83;
	shfl.sync.down.b32 	%r193|%p21, %r192, %r181, %r182, %r184;
	mov.b32 	%f84, %r193;
	add.ftz.f32 	%f85, %f83, %f84;
	mov.b32 	%r194, %f85;
	mov.u32 	%r195, 1;
	shfl.sync.down.b32 	%r196|%p22, %r194, %r195, %r182, %r184;
	mov.b32 	%f86, %r196;
	add.ftz.f32 	%f9, %f85, %f86;
	setp.ne.s32 	%p23, %r5, 0;
	@%p23 bra 	$L__BB0_24;

	mul.ftz.f32 	%f87, %f9, %f56;
	cvt.s64.s32 	%rd73, %r342;
	add.s64 	%rd74, %rd73, %rd6;
	shl.b64 	%rd75, %rd74, 2;
	add.s64 	%rd76, %rd4, %rd75;
	st.global.f32 	[%rd76], %f87;

$L__BB0_24:
	add.s32 	%r342, %r342, 8;
	setp.lt.s32 	%p24, %r342, %r25;
	@%p24 bra 	$L__BB0_12;
	bra.uni 	$L__BB0_51;

$L__BB0_25:
	not.b32 	%r197, %r5;
	add.s32 	%r198, %r197, %r122;
	shr.u32 	%r199, %r198, 5;
	add.s32 	%r200, %r199, 1;
	and.b32  	%r36, %r200, 3;
	or.b32  	%r37, %r5, 32;
	or.b32  	%r38, %r5, 64;
	or.b32  	%r39, %r5, 96;
	mul.lo.s32 	%r201, %r7, %r122;
	cvt.s64.s32 	%rd12, %r201;
	cvta.to.global.u64 	%rd81, %rd35;

$L__BB0_26:
	setp.ge.s32 	%p25, %r5, %r122;
	mov.f32 	%f282, 0f00000000;
	@%p25 bra 	$L__BB0_34;

	setp.eq.s32 	%p26, %r36, 0;
	mov.f32 	%f282, 0f00000000;
	mov.u32 	%r346, %r5;
	@%p26 bra 	$L__BB0_31;

	setp.eq.s32 	%p27, %r36, 1;
	and.b32  	%r202, %r363, 31;
	cvt.u64.u32 	%rd77, %r202;
	add.s32 	%r204, %r342, %r340;
	mul.lo.s32 	%r205, %r204, %r9;
	cvt.s64.s32 	%rd78, %r205;
	add.s64 	%rd13, %rd78, %rd12;
	add.s64 	%rd80, %rd13, %rd77;
	shl.b64 	%rd82, %rd80, 2;
	add.s64 	%rd83, %rd81, %rd82;
	ld.global.f32 	%f91, [%rd83];
	ld.global.f32 	%f92, [%rd7];
	mov.f32 	%f93, 0f00000000;
	fma.rn.ftz.f32 	%f282, %f92, %f91, %f93;
	mov.u32 	%r346, %r37;
	@%p27 bra 	$L__BB0_31;

	setp.eq.s32 	%p28, %r36, 2;
	mov.u32 	%r207, %tid.x;
	and.b32  	%r208, %r207, 31;
	cvt.u64.u32 	%rd84, %r208;
	add.s64 	%rd85, %rd13, %rd84;
	shl.b64 	%rd87, %rd85, 2;
	add.s64 	%rd88, %rd81, %rd87;
	ld.global.f32 	%f94, [%rd88+128];
	ld.global.f32 	%f95, [%rd7+128];
	fma.rn.ftz.f32 	%f282, %f95, %f94, %f282;
	mov.u32 	%r346, %r38;
	@%p28 bra 	$L__BB0_31;

	ld.global.f32 	%f96, [%rd83+256];
	ld.global.f32 	%f97, [%rd7+256];
	fma.rn.ftz.f32 	%f282, %f97, %f96, %f282;
	mov.u32 	%r346, %r39;

$L__BB0_31:
	not.b32 	%r214, %r363;
	or.b32  	%r215, %r214, -32;
	add.s32 	%r216, %r215, %r122;
	setp.lt.u32 	%p29, %r216, 96;
	@%p29 bra 	$L__BB0_34;

	add.s32 	%r217, %r342, %r340;
	mul.lo.s32 	%r218, %r217, %r9;
	cvt.s64.s32 	%rd97, %r218;
	add.s64 	%rd16, %rd97, %rd12;

$L__BB0_33:
	add.s32 	%r219, %r346, %r8;
	mul.wide.s32 	%rd98, %r219, 4;
	add.s64 	%rd99, %rd1, %rd98;
	cvt.s64.s32 	%rd100, %r346;
	add.s64 	%rd101, %rd16, %rd100;
	shl.b64 	%rd102, %rd101, 2;
	add.s64 	%rd103, %rd81, %rd102;
	ld.global.f32 	%f98, [%rd103];
	ld.global.f32 	%f99, [%rd99];
	fma.rn.ftz.f32 	%f100, %f99, %f98, %f282;
	ld.global.f32 	%f101, [%rd103+128];
	ld.global.f32 	%f102, [%rd99+128];
	fma.rn.ftz.f32 	%f103, %f102, %f101, %f100;
	ld.global.f32 	%f104, [%rd103+256];
	ld.global.f32 	%f105, [%rd99+256];
	fma.rn.ftz.f32 	%f106, %f105, %f104, %f103;
	ld.global.f32 	%f107, [%rd103+384];
	ld.global.f32 	%f108, [%rd99+384];
	fma.rn.ftz.f32 	%f282, %f108, %f107, %f106;
	add.s32 	%r346, %r346, 128;
	setp.lt.s32 	%p30, %r346, %r122;
	@%p30 bra 	$L__BB0_33;

$L__BB0_34:
	mov.b32 	%r220, %f282;
	mov.u32 	%r221, 2;
	mov.u32 	%r222, 31;
	mov.u32 	%r223, 16;
	mov.u32 	%r224, -1;
	shfl.sync.down.b32 	%r225|%p31, %r220, %r223, %r222, %r224;
	mov.b32 	%f109, %r225;
	add.ftz.f32 	%f110, %f282, %f109;
	mov.b32 	%r226, %f110;
	mov.u32 	%r227, 8;
	shfl.sync.down.b32 	%r228|%p32, %r226, %r227, %r222, %r224;
	mov.b32 	%f111, %r228;
	add.ftz.f32 	%f112, %f110, %f111;
	mov.b32 	%r229, %f112;
	mov.u32 	%r230, 4;
	shfl.sync.down.b32 	%r231|%p33, %r229, %r230, %r222, %r224;
	mov.b32 	%f113, %r231;
	add.ftz.f32 	%f114, %f112, %f113;
	mov.b32 	%r232, %f114;
	shfl.sync.down.b32 	%r233|%p34, %r232, %r221, %r222, %r224;
	mov.b32 	%f115, %r233;
	add.ftz.f32 	%f116, %f114, %f115;
	mov.b32 	%r234, %f116;
	mov.u32 	%r235, 1;
	shfl.sync.down.b32 	%r236|%p35, %r234, %r235, %r222, %r224;
	mov.b32 	%f117, %r236;
	add.ftz.f32 	%f18, %f116, %f117;
	setp.ne.s32 	%p36, %r5, 0;
	@%p36 bra 	$L__BB0_36;

	mul.ftz.f32 	%f118, %f18, %f56;
	cvt.s64.s32 	%rd104, %r342;
	add.s64 	%rd105, %rd104, %rd6;
	shl.b64 	%rd106, %rd105, 2;
	add.s64 	%rd107, %rd4, %rd106;
	st.global.f32 	[%rd107], %f118;

$L__BB0_36:
	add.s32 	%r342, %r342, 8;
	setp.lt.s32 	%p37, %r342, %r25;
	@%p37 bra 	$L__BB0_26;
	bra.uni 	$L__BB0_51;

$L__BB0_37:
	not.b32 	%r237, %r5;
	add.s32 	%r45, %r237, %r122;
	shr.u32 	%r238, %r45, 5;
	add.s32 	%r239, %r238, 1;
	and.b32  	%r46, %r239, 3;
	or.b32  	%r47, %r5, 32;
	or.b32  	%r48, %r5, 64;
	or.b32  	%r49, %r5, 96;
	cvta.to.global.u64 	%rd111, %rd35;
	cvta.to.global.u64 	%rd116, %rd36;

$L__BB0_38:
	add.s32 	%r51, %r342, %r340;
	setp.lt.s32 	%p38, %r51, %r123;
	@%p38 bra 	$L__BB0_40;
	bra.uni 	$L__BB0_39;

$L__BB0_40:
	mul.lo.s32 	%r248, %r51, %r9;
	cvt.s64.s32 	%rd113, %r248;
	mul.lo.s32 	%r249, %r7, %r122;
	cvt.s64.s32 	%rd114, %r249;
	add.s64 	%rd115, %rd113, %rd114;
	shl.b64 	%rd117, %rd115, 2;
	add.s64 	%rd214, %rd116, %rd117;
	bra.uni 	$L__BB0_41;

$L__BB0_39:
	add.s32 	%r240, %r338, %r123;
	setp.lt.s32 	%p39, %r51, %r240;
	sub.s32 	%r241, %r336, %r123;
	sub.s32 	%r242, %r241, %r338;
	sub.s32 	%r243, %r337, %r123;
	selp.b32 	%r244, %r243, %r242, %p39;
	add.s32 	%r245, %r244, %r51;
	mul.lo.s32 	%r246, %r245, %r9;
	cvt.s64.s32 	%rd108, %r246;
	mul.lo.s32 	%r247, %r7, %r122;
	cvt.s64.s32 	%rd109, %r247;
	add.s64 	%rd110, %rd108, %rd109;
	shl.b64 	%rd112, %rd110, 2;
	add.s64 	%rd214, %rd111, %rd112;

$L__BB0_41:
	setp.ge.s32 	%p40, %r5, %r122;
	mov.f32 	%f286, 0f00000000;
	@%p40 bra 	$L__BB0_48;

	setp.eq.s32 	%p41, %r46, 0;
	mov.f32 	%f286, 0f00000000;
	mov.u32 	%r349, %r5;
	@%p41 bra 	$L__BB0_46;

	setp.eq.s32 	%p42, %r46, 1;
	mov.u32 	%r250, %tid.x;
	shl.b32 	%r251, %r250, 2;
	cvt.u64.u32 	%rd118, %r251;
	and.b64  	%rd119, %rd118, 124;
	add.s64 	%rd120, %rd214, %rd119;
	ld.global.f32 	%f122, [%rd120];
	ld.global.f32 	%f123, [%rd7];
	mov.f32 	%f124, 0f00000000;
	fma.rn.ftz.f32 	%f286, %f123, %f122, %f124;
	mov.u32 	%r349, %r47;
	@%p42 bra 	$L__BB0_46;

	setp.eq.s32 	%p43, %r46, 2;
	ld.global.f32 	%f125, [%rd120+128];
	ld.global.f32 	%f126, [%rd7+128];
	fma.rn.ftz.f32 	%f286, %f126, %f125, %f286;
	mov.u32 	%r349, %r48;
	@%p43 bra 	$L__BB0_46;

	ld.global.f32 	%f127, [%rd120+256];
	ld.global.f32 	%f128, [%rd7+256];
	fma.rn.ftz.f32 	%f286, %f128, %f127, %f286;
	mov.u32 	%r349, %r49;

$L__BB0_46:
	setp.lt.u32 	%p44, %r45, 96;
	@%p44 bra 	$L__BB0_48;

$L__BB0_47:
	add.s32 	%r256, %r349, %r8;
	mul.wide.s32 	%rd127, %r256, 4;
	add.s64 	%rd128, %rd1, %rd127;
	mul.wide.s32 	%rd129, %r349, 4;
	add.s64 	%rd130, %rd214, %rd129;
	ld.global.f32 	%f129, [%rd130];
	ld.global.f32 	%f130, [%rd128];
	fma.rn.ftz.f32 	%f131, %f130, %f129, %f286;
	ld.global.f32 	%f132, [%rd130+128];
	ld.global.f32 	%f133, [%rd128+128];
	fma.rn.ftz.f32 	%f134, %f133, %f132, %f131;
	ld.global.f32 	%f135, [%rd130+256];
	ld.global.f32 	%f136, [%rd128+256];
	fma.rn.ftz.f32 	%f137, %f136, %f135, %f134;
	ld.global.f32 	%f138, [%rd130+384];
	ld.global.f32 	%f139, [%rd128+384];
	fma.rn.ftz.f32 	%f286, %f139, %f138, %f137;
	add.s32 	%r349, %r349, 128;
	setp.lt.s32 	%p45, %r349, %r122;
	@%p45 bra 	$L__BB0_47;

$L__BB0_48:
	mov.b32 	%r257, %f286;
	mov.u32 	%r258, 2;
	mov.u32 	%r259, 31;
	mov.u32 	%r260, 16;
	mov.u32 	%r261, -1;
	shfl.sync.down.b32 	%r262|%p46, %r257, %r260, %r259, %r261;
	mov.b32 	%f140, %r262;
	add.ftz.f32 	%f141, %f286, %f140;
	mov.b32 	%r263, %f141;
	mov.u32 	%r264, 8;
	shfl.sync.down.b32 	%r265|%p47, %r263, %r264, %r259, %r261;
	mov.b32 	%f142, %r265;
	add.ftz.f32 	%f143, %f141, %f142;
	mov.b32 	%r266, %f143;
	mov.u32 	%r267, 4;
	shfl.sync.down.b32 	%r268|%p48, %r266, %r267, %r259, %r261;
	mov.b32 	%f144, %r268;
	add.ftz.f32 	%f145, %f143, %f144;
	mov.b32 	%r269, %f145;
	shfl.sync.down.b32 	%r270|%p49, %r269, %r258, %r259, %r261;
	mov.b32 	%f146, %r270;
	add.ftz.f32 	%f147, %f145, %f146;
	mov.b32 	%r271, %f147;
	mov.u32 	%r272, 1;
	shfl.sync.down.b32 	%r273|%p50, %r271, %r272, %r259, %r261;
	mov.b32 	%f148, %r273;
	add.ftz.f32 	%f27, %f147, %f148;
	setp.ne.s32 	%p51, %r5, 0;
	@%p51 bra 	$L__BB0_50;

	mul.ftz.f32 	%f149, %f27, %f56;
	cvt.s64.s32 	%rd131, %r342;
	add.s64 	%rd132, %rd131, %rd6;
	shl.b64 	%rd133, %rd132, 2;
	add.s64 	%rd134, %rd4, %rd133;
	st.global.f32 	[%rd134], %f149;

$L__BB0_50:
	add.s32 	%r342, %r342, 8;
	setp.lt.s32 	%p52, %r342, %r25;
	@%p52 bra 	$L__BB0_38;

$L__BB0_51:
	bar.sync 	0;
	setp.ge.s32 	%p53, %r363, %r25;
	mov.f32 	%f291, 0fFF800000;
	@%p53 bra 	$L__BB0_57;

	mov.u32 	%r353, %tid.x;
	not.b32 	%r275, %r353;
	add.s32 	%r276, %r341, %r275;
	sub.s32 	%r57, %r276, %r340;
	shr.u32 	%r277, %r57, 8;
	add.s32 	%r278, %r277, 1;
	and.b32  	%r352, %r278, 3;
	setp.eq.s32 	%p54, %r352, 0;
	mov.f32 	%f291, 0fFF800000;
	@%p54 bra 	$L__BB0_55;

	mov.f32 	%f291, 0fFF800000;
	mov.u32 	%r353, %tid.x;

$L__BB0_54:
	.pragma "nounroll";
	cvt.s64.s32 	%rd135, %r353;
	add.s64 	%rd136, %rd135, %rd6;
	shl.b64 	%rd137, %rd136, 2;
	add.s64 	%rd138, %rd4, %rd137;
	ld.global.f32 	%f154, [%rd138];
	max.ftz.f32 	%f291, %f291, %f154;
	add.s32 	%r353, %r353, 256;
	add.s32 	%r352, %r352, -1;
	setp.ne.s32 	%p55, %r352, 0;
	@%p55 bra 	$L__BB0_54;

$L__BB0_55:
	setp.lt.u32 	%p56, %r57, 768;
	@%p56 bra 	$L__BB0_57;

$L__BB0_56:
	cvt.s64.s32 	%rd139, %r353;
	add.s64 	%rd140, %rd139, %rd6;
	shl.b64 	%rd141, %rd140, 2;
	add.s64 	%rd142, %rd4, %rd141;
	ld.global.f32 	%f155, [%rd142];
	max.ftz.f32 	%f156, %f291, %f155;
	ld.global.f32 	%f157, [%rd142+1024];
	max.ftz.f32 	%f158, %f156, %f157;
	ld.global.f32 	%f159, [%rd142+2048];
	max.ftz.f32 	%f160, %f158, %f159;
	ld.global.f32 	%f161, [%rd142+3072];
	max.ftz.f32 	%f291, %f160, %f161;
	add.s32 	%r353, %r353, 1024;
	setp.lt.s32 	%p57, %r353, %r25;
	@%p57 bra 	$L__BB0_56;

$L__BB0_57:
	shl.b32 	%r280, %r363, 2;
	mov.u32 	%r281, _ZZ18gqa_attention_longE6reduce;
	add.s32 	%r67, %r281, %r280;
	st.shared.f32 	[%r67], %f291;
	bar.sync 	0;
	setp.gt.s32 	%p58, %r363, 127;
	@%p58 bra 	$L__BB0_59;

	ld.shared.f32 	%f162, [%r67];
	ld.shared.f32 	%f163, [%r67+512];
	max.ftz.f32 	%f164, %f162, %f163;
	st.shared.f32 	[%r67], %f164;

$L__BB0_59:
	bar.sync 	0;
	setp.gt.s32 	%p59, %r363, 63;
	@%p59 bra 	$L__BB0_61;

	ld.shared.f32 	%f165, [%r67];
	ld.shared.f32 	%f166, [%r67+256];
	max.ftz.f32 	%f167, %f165, %f166;
	st.shared.f32 	[%r67], %f167;

$L__BB0_61:
	bar.sync 	0;
	setp.gt.s32 	%p60, %r363, 31;
	@%p60 bra 	$L__BB0_63;

	ld.shared.f32 	%f168, [%r67];
	ld.shared.f32 	%f169, [%r67+128];
	max.ftz.f32 	%f170, %f168, %f169;
	st.shared.f32 	[%r67], %f170;

$L__BB0_63:
	bar.sync 	0;
	setp.gt.s32 	%p61, %r363, 15;
	@%p61 bra 	$L__BB0_65;

	ld.shared.f32 	%f171, [%r67];
	ld.shared.f32 	%f172, [%r67+64];
	max.ftz.f32 	%f173, %f171, %f172;
	st.shared.f32 	[%r67], %f173;

$L__BB0_65:
	bar.sync 	0;
	setp.gt.s32 	%p62, %r363, 7;
	@%p62 bra 	$L__BB0_67;

	ld.shared.f32 	%f174, [%r67];
	ld.shared.f32 	%f175, [%r67+32];
	max.ftz.f32 	%f176, %f174, %f175;
	st.shared.f32 	[%r67], %f176;

$L__BB0_67:
	bar.sync 	0;
	setp.gt.s32 	%p63, %r363, 3;
	@%p63 bra 	$L__BB0_69;

	ld.shared.f32 	%f177, [%r67];
	ld.shared.f32 	%f178, [%r67+16];
	max.ftz.f32 	%f179, %f177, %f178;
	st.shared.f32 	[%r67], %f179;

$L__BB0_69:
	bar.sync 	0;
	setp.gt.s32 	%p64, %r363, 1;
	@%p64 bra 	$L__BB0_71;

	ld.shared.f32 	%f180, [%r67];
	ld.shared.f32 	%f181, [%r67+8];
	max.ftz.f32 	%f182, %f180, %f181;
	st.shared.f32 	[%r67], %f182;

$L__BB0_71:
	bar.sync 	0;
	setp.gt.s32 	%p65, %r363, 0;
	@%p65 bra 	$L__BB0_73;

	ld.shared.f32 	%f183, [%r67];
	ld.shared.f32 	%f184, [%r67+4];
	max.ftz.f32 	%f185, %f183, %f184;
	st.shared.f32 	[%r67], %f185;

$L__BB0_73:
	bar.sync 	0;
	ld.shared.f32 	%f35, [_ZZ18gqa_attention_longE6reduce];
	bar.sync 	0;
	mov.f32 	%f296, 0f00000000;
	@%p53 bra 	$L__BB0_79;

	mov.u32 	%r357, %tid.x;
	not.b32 	%r290, %r357;
	add.s32 	%r291, %r341, %r290;
	sub.s32 	%r69, %r291, %r340;
	shr.u32 	%r292, %r69, 8;
	add.s32 	%r293, %r292, 1;
	and.b32  	%r356, %r293, 3;
	setp.eq.s32 	%p67, %r356, 0;
	mov.f32 	%f296, 0f00000000;
	@%p67 bra 	$L__BB0_77;

	mov.f32 	%f296, 0f00000000;
	mov.u32 	%r357, %tid.x;

$L__BB0_76:
	.pragma "nounroll";
	cvt.s64.s32 	%rd143, %r357;
	add.s64 	%rd144, %rd143, %rd6;
	shl.b64 	%rd145, %rd144, 2;
	add.s64 	%rd146, %rd4, %rd145;
	ld.global.f32 	%f190, [%rd146];
	sub.ftz.f32 	%f191, %f190, %f35;
	mul.ftz.f32 	%f192, %f191, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f193, %f192;
	st.global.f32 	[%rd146], %f193;
	add.ftz.f32 	%f296, %f296, %f193;
	add.s32 	%r357, %r357, 256;
	add.s32 	%r356, %r356, -1;
	setp.ne.s32 	%p68, %r356, 0;
	@%p68 bra 	$L__BB0_76;

$L__BB0_77:
	setp.lt.u32 	%p69, %r69, 768;
	@%p69 bra 	$L__BB0_79;

$L__BB0_78:
	cvt.s64.s32 	%rd147, %r357;
	add.s64 	%rd148, %rd147, %rd6;
	shl.b64 	%rd149, %rd148, 2;
	add.s64 	%rd150, %rd4, %rd149;
	ld.global.f32 	%f194, [%rd150];
	sub.ftz.f32 	%f195, %f194, %f35;
	mul.ftz.f32 	%f196, %f195, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f197, %f196;
	st.global.f32 	[%rd150], %f197;
	add.ftz.f32 	%f198, %f296, %f197;
	ld.global.f32 	%f199, [%rd150+1024];
	sub.ftz.f32 	%f200, %f199, %f35;
	mul.ftz.f32 	%f201, %f200, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f202, %f201;
	st.global.f32 	[%rd150+1024], %f202;
	add.ftz.f32 	%f203, %f198, %f202;
	ld.global.f32 	%f204, [%rd150+2048];
	sub.ftz.f32 	%f205, %f204, %f35;
	mul.ftz.f32 	%f206, %f205, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f207, %f206;
	st.global.f32 	[%rd150+2048], %f207;
	add.ftz.f32 	%f208, %f203, %f207;
	ld.global.f32 	%f209, [%rd150+3072];
	sub.ftz.f32 	%f210, %f209, %f35;
	mul.ftz.f32 	%f211, %f210, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f212, %f211;
	st.global.f32 	[%rd150+3072], %f212;
	add.ftz.f32 	%f296, %f208, %f212;
	add.s32 	%r357, %r357, 1024;
	setp.lt.s32 	%p70, %r357, %r25;
	@%p70 bra 	$L__BB0_78;

$L__BB0_79:
	st.shared.f32 	[%r67], %f296;
	bar.sync 	0;
	@%p58 bra 	$L__BB0_81;

	ld.shared.f32 	%f213, [%r67];
	ld.shared.f32 	%f214, [%r67+512];
	add.ftz.f32 	%f215, %f214, %f213;
	st.shared.f32 	[%r67], %f215;

$L__BB0_81:
	bar.sync 	0;
	@%p59 bra 	$L__BB0_83;

	ld.shared.f32 	%f216, [%r67];
	ld.shared.f32 	%f217, [%r67+256];
	add.ftz.f32 	%f218, %f217, %f216;
	st.shared.f32 	[%r67], %f218;

$L__BB0_83:
	bar.sync 	0;
	@%p60 bra 	$L__BB0_85;

	ld.shared.f32 	%f219, [%r67];
	ld.shared.f32 	%f220, [%r67+128];
	add.ftz.f32 	%f221, %f220, %f219;
	st.shared.f32 	[%r67], %f221;

$L__BB0_85:
	bar.sync 	0;
	@%p61 bra 	$L__BB0_87;

	ld.shared.f32 	%f222, [%r67];
	ld.shared.f32 	%f223, [%r67+64];
	add.ftz.f32 	%f224, %f223, %f222;
	st.shared.f32 	[%r67], %f224;

$L__BB0_87:
	bar.sync 	0;
	@%p62 bra 	$L__BB0_89;

	ld.shared.f32 	%f225, [%r67];
	ld.shared.f32 	%f226, [%r67+32];
	add.ftz.f32 	%f227, %f226, %f225;
	st.shared.f32 	[%r67], %f227;

$L__BB0_89:
	bar.sync 	0;
	@%p63 bra 	$L__BB0_91;

	ld.shared.f32 	%f228, [%r67];
	ld.shared.f32 	%f229, [%r67+16];
	add.ftz.f32 	%f230, %f229, %f228;
	st.shared.f32 	[%r67], %f230;

$L__BB0_91:
	bar.sync 	0;
	@%p64 bra 	$L__BB0_93;

	ld.shared.f32 	%f231, [%r67];
	ld.shared.f32 	%f232, [%r67+8];
	add.ftz.f32 	%f233, %f232, %f231;
	st.shared.f32 	[%r67], %f233;

$L__BB0_93:
	bar.sync 	0;
	@%p65 bra 	$L__BB0_95;

	ld.shared.f32 	%f234, [%r67];
	ld.shared.f32 	%f235, [%r67+4];
	add.ftz.f32 	%f236, %f235, %f234;
	st.shared.f32 	[%r67], %f236;

$L__BB0_95:
	bar.sync 	0;
	ld.shared.f32 	%f237, [_ZZ18gqa_attention_longE6reduce];
	rcp.approx.ftz.f32 	%f43, %f237;
	@%p53 bra 	$L__BB0_101;

	mov.u32 	%r361, %tid.x;
	not.b32 	%r303, %r361;
	add.s32 	%r304, %r341, %r303;
	sub.s32 	%r80, %r304, %r340;
	shr.u32 	%r305, %r80, 8;
	add.s32 	%r306, %r305, 1;
	and.b32  	%r360, %r306, 3;
	setp.eq.s32 	%p80, %r360, 0;
	@%p80 bra 	$L__BB0_99;

	mov.u32 	%r361, %tid.x;

$L__BB0_98:
	.pragma "nounroll";
	cvt.s64.s32 	%rd151, %r361;
	add.s64 	%rd152, %rd151, %rd6;
	shl.b64 	%rd153, %rd152, 2;
	add.s64 	%rd154, %rd4, %rd153;
	ld.global.f32 	%f238, [%rd154];
	mul.ftz.f32 	%f239, %f43, %f238;
	st.global.f32 	[%rd154], %f239;
	add.s32 	%r361, %r361, 256;
	add.s32 	%r360, %r360, -1;
	setp.ne.s32 	%p81, %r360, 0;
	@%p81 bra 	$L__BB0_98;

$L__BB0_99:
	setp.lt.u32 	%p82, %r80, 768;
	@%p82 bra 	$L__BB0_101;

$L__BB0_100:
	cvt.s64.s32 	%rd155, %r361;
	add.s64 	%rd156, %rd155, %rd6;
	shl.b64 	%rd157, %rd156, 2;
	add.s64 	%rd158, %rd4, %rd157;
	ld.global.f32 	%f240, [%rd158];
	mul.ftz.f32 	%f241, %f43, %f240;
	st.global.f32 	[%rd158], %f241;
	ld.global.f32 	%f242, [%rd158+1024];
	mul.ftz.f32 	%f243, %f43, %f242;
	st.global.f32 	[%rd158+1024], %f243;
	ld.global.f32 	%f244, [%rd158+2048];
	mul.ftz.f32 	%f245, %f43, %f244;
	st.global.f32 	[%rd158+2048], %f245;
	ld.global.f32 	%f246, [%rd158+3072];
	mul.ftz.f32 	%f247, %f43, %f246;
	st.global.f32 	[%rd158+3072], %f247;
	add.s32 	%r361, %r361, 1024;
	setp.lt.s32 	%p83, %r361, %r25;
	@%p83 bra 	$L__BB0_100;

$L__BB0_101:
	bar.sync 	0;
	setp.ge.s32 	%p84, %r363, %r122;
	@%p84 bra 	$L__BB0_124;

	ld.param.u32 	%r334, [gqa_attention_long_param_18];
	ld.param.u32 	%r333, [gqa_attention_long_param_15];
	mul.lo.s32 	%r308, %r7, %r122;
	cvt.s64.s32 	%rd21, %r308;
	add.s32 	%r90, %r338, %r123;
	sub.s32 	%r91, %r337, %r123;
	sub.s32 	%r309, %r336, %r123;
	sub.s32 	%r92, %r309, %r338;
	not.b32 	%r310, %r340;
	add.s32 	%r93, %r341, %r310;
	and.b32  	%r94, %r25, 3;
	sub.s32 	%r95, %r25, %r94;
	shl.b64 	%rd159, %rd6, 2;
	add.s64 	%rd22, %rd4, %rd159;
	mul.lo.s32 	%r311, %r340, %r122;
	mul.lo.s32 	%r96, %r311, %r333;
	mad.lo.s32 	%r312, %r339, %r334, %r340;
	sub.s32 	%r313, %r312, %r123;
	mul.lo.s32 	%r97, %r9, %r313;
	mul.wide.s32 	%rd23, %r9, 4;
	cvta.to.global.u64 	%rd24, %rd39;
	cvta.to.global.u64 	%rd162, %rd38;

$L__BB0_103:
	setp.lt.s32 	%p85, %r25, 1;
	mov.f32 	%f302, 0f00000000;
	@%p85 bra 	$L__BB0_123;

	cvt.s64.s32 	%rd25, %r363;
	@%p4 bra 	$L__BB0_111;

	ld.param.u32 	%r335, [gqa_attention_long_param_21];
	mov.f32 	%f302, 0f00000000;
	setp.ne.s32 	%p87, %r335, 1;
	@%p87 bra 	$L__BB0_118;

	mov.u32 	%r367, 0;
	mov.u32 	%r364, %r340;
	mov.u32 	%r365, %r97;
	mov.u32 	%r366, %r96;
	mov.u64 	%rd215, %rd22;

$L__BB0_107:
	setp.lt.s32 	%p88, %r364, %r123;
	@%p88 bra 	$L__BB0_109;
	bra.uni 	$L__BB0_108;

$L__BB0_109:
	cvt.s64.s32 	%rd164, %r366;
	add.s64 	%rd165, %rd164, %rd21;
	shl.b64 	%rd166, %rd165, 2;
	add.s64 	%rd216, %rd2, %rd166;
	bra.uni 	$L__BB0_110;

$L__BB0_108:
	cvt.s64.s32 	%rd160, %r365;
	add.s64 	%rd161, %rd160, %rd21;
	shl.b64 	%rd163, %rd161, 2;
	add.s64 	%rd216, %rd162, %rd163;

$L__BB0_110:
	shl.b64 	%rd167, %rd25, 2;
	add.s64 	%rd168, %rd216, %rd167;
	ld.global.f32 	%f250, [%rd168];
	ld.global.f32 	%f251, [%rd215];
	fma.rn.ftz.f32 	%f302, %f251, %f250, %f302;
	add.s64 	%rd215, %rd215, 4;
	add.s32 	%r366, %r366, %r9;
	add.s32 	%r365, %r365, %r9;
	add.s32 	%r364, %r364, 1;
	add.s32 	%r367, %r367, 1;
	setp.lt.s32 	%p89, %r367, %r25;
	@%p89 bra 	$L__BB0_107;
	bra.uni 	$L__BB0_123;

$L__BB0_111:
	setp.lt.u32 	%p90, %r93, 3;
	mov.f32 	%f302, 0f00000000;
	mov.u32 	%r370, 0;
	@%p90 bra 	$L__BB0_114;

	mov.f32 	%f302, 0f00000000;
	mov.u32 	%r370, 0;
	mov.u32 	%r369, %r95;

$L__BB0_113:
	add.s32 	%r317, %r370, %r340;
	mul.lo.s32 	%r318, %r317, %r9;
	cvt.s64.s32 	%rd169, %r318;
	add.s64 	%rd170, %rd169, %rd21;
	cvt.s64.s32 	%rd171, %r370;
	add.s64 	%rd172, %rd171, %rd6;
	shl.b64 	%rd173, %rd172, 2;
	add.s64 	%rd174, %rd4, %rd173;
	add.s64 	%rd175, %rd170, %rd25;
	shl.b64 	%rd176, %rd175, 2;
	add.s64 	%rd177, %rd3, %rd176;
	ld.global.f32 	%f255, [%rd177];
	ld.global.f32 	%f256, [%rd174];
	fma.rn.ftz.f32 	%f257, %f256, %f255, %f302;
	add.s64 	%rd178, %rd177, %rd23;
	ld.global.f32 	%f258, [%rd178];
	ld.global.f32 	%f259, [%rd174+4];
	fma.rn.ftz.f32 	%f260, %f259, %f258, %f257;
	add.s64 	%rd179, %rd178, %rd23;
	ld.global.f32 	%f261, [%rd179];
	ld.global.f32 	%f262, [%rd174+8];
	fma.rn.ftz.f32 	%f263, %f262, %f261, %f260;
	add.s64 	%rd180, %rd179, %rd23;
	ld.global.f32 	%f264, [%rd180];
	ld.global.f32 	%f265, [%rd174+12];
	fma.rn.ftz.f32 	%f302, %f265, %f264, %f263;
	add.s32 	%r370, %r370, 4;
	add.s32 	%r369, %r369, -4;
	setp.ne.s32 	%p91, %r369, 0;
	@%p91 bra 	$L__BB0_113;

$L__BB0_114:
	setp.eq.s32 	%p92, %r94, 0;
	@%p92 bra 	$L__BB0_123;

	setp.eq.s32 	%p93, %r94, 1;
	add.s32 	%r319, %r370, %r340;
	mul.lo.s32 	%r320, %r319, %r9;
	cvt.s64.s32 	%rd181, %r320;
	add.s64 	%rd182, %rd181, %rd21;
	cvt.s64.s32 	%rd183, %r370;
	add.s64 	%rd184, %rd183, %rd6;
	shl.b64 	%rd185, %rd184, 2;
	add.s64 	%rd31, %rd4, %rd185;
	add.s64 	%rd186, %rd182, %rd25;
	shl.b64 	%rd187, %rd186, 2;
	add.s64 	%rd188, %rd3, %rd187;
	ld.global.f32 	%f266, [%rd188];
	ld.global.f32 	%f267, [%rd31];
	fma.rn.ftz.f32 	%f302, %f267, %f266, %f302;
	@%p93 bra 	$L__BB0_123;

	setp.eq.s32 	%p94, %r94, 2;
	add.s32 	%r322, %r319, 1;
	mul.lo.s32 	%r323, %r322, %r9;
	cvt.s64.s32 	%rd189, %r323;
	add.s64 	%rd190, %rd189, %rd21;
	add.s64 	%rd191, %rd190, %rd25;
	shl.b64 	%rd192, %rd191, 2;
	add.s64 	%rd193, %rd3, %rd192;
	ld.global.f32 	%f268, [%rd193];
	ld.global.f32 	%f269, [%rd31+4];
	fma.rn.ftz.f32 	%f302, %f269, %f268, %f302;
	@%p94 bra 	$L__BB0_123;

	add.s32 	%r325, %r319, 2;
	mul.lo.s32 	%r326, %r325, %r9;
	cvt.s64.s32 	%rd194, %r326;
	add.s64 	%rd195, %rd194, %rd21;
	add.s64 	%rd196, %rd195, %rd25;
	shl.b64 	%rd197, %rd196, 2;
	add.s64 	%rd198, %rd3, %rd197;
	ld.global.f32 	%f270, [%rd198];
	ld.global.f32 	%f271, [%rd31+8];
	fma.rn.ftz.f32 	%f302, %f271, %f270, %f302;
	bra.uni 	$L__BB0_123;

$L__BB0_118:
	mov.u32 	%r371, 0;

$L__BB0_119:
	add.s32 	%r114, %r371, %r340;
	setp.lt.s32 	%p95, %r114, %r123;
	@%p95 bra 	$L__BB0_121;
	bra.uni 	$L__BB0_120;

$L__BB0_121:
	mul.lo.s32 	%r331, %r114, %r9;
	cvt.s64.s32 	%rd202, %r331;
	add.s64 	%rd203, %rd202, %rd21;
	shl.b64 	%rd204, %rd203, 2;
	add.s64 	%rd217, %rd2, %rd204;
	bra.uni 	$L__BB0_122;

$L__BB0_120:
	setp.lt.s32 	%p96, %r114, %r90;
	selp.b32 	%r328, %r91, %r92, %p96;
	add.s32 	%r329, %r328, %r114;
	mul.lo.s32 	%r330, %r329, %r9;
	cvt.s64.s32 	%rd199, %r330;
	add.s64 	%rd200, %rd199, %rd21;
	shl.b64 	%rd201, %rd200, 2;
	add.s64 	%rd217, %rd3, %rd201;

$L__BB0_122:
	cvt.s64.s32 	%rd205, %r371;
	add.s64 	%rd206, %rd205, %rd6;
	shl.b64 	%rd207, %rd206, 2;
	add.s64 	%rd208, %rd4, %rd207;
	shl.b64 	%rd209, %rd25, 2;
	add.s64 	%rd210, %rd217, %rd209;
	ld.global.f32 	%f273, [%rd210];
	ld.global.f32 	%f274, [%rd208];
	fma.rn.ftz.f32 	%f302, %f274, %f273, %f302;
	add.s32 	%r371, %r371, 1;
	setp.lt.s32 	%p97, %r371, %r25;
	@%p97 bra 	$L__BB0_119;

$L__BB0_123:
	add.s32 	%r332, %r363, %r8;
	mul.wide.s32 	%rd211, %r332, 4;
	add.s64 	%rd212, %rd24, %rd211;
	st.global.f32 	[%rd212], %f302;
	add.s32 	%r363, %r363, 256;
	setp.lt.s32 	%p98, %r363, %r122;
	@%p98 bra 	$L__BB0_103;

$L__BB0_124:
	ret;

}

`
