package ptx

// Generated by scripts/generate-packed-ptx.sh; CUDA 12.8, sm_86.
const PackedDecisionPTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	rope_partial_segmented
// _ZZ23gqa_attention_segmentedE6scores has been demoted
// _ZZ23gqa_attention_segmentedE6reduce has been demoted

.visible .entry rope_partial_segmented(
	.param .u64 rope_partial_segmented_param_0,
	.param .u64 rope_partial_segmented_param_1,
	.param .u64 rope_partial_segmented_param_2,
	.param .u32 rope_partial_segmented_param_3,
	.param .u32 rope_partial_segmented_param_4,
	.param .u32 rope_partial_segmented_param_5,
	.param .u32 rope_partial_segmented_param_6,
	.param .u32 rope_partial_segmented_param_7
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<25>;
	.reg .b64 	%rd<15>;


	ld.param.u64 	%rd1, [rope_partial_segmented_param_0];
	ld.param.u64 	%rd2, [rope_partial_segmented_param_1];
	ld.param.u64 	%rd3, [rope_partial_segmented_param_2];
	ld.param.u32 	%r6, [rope_partial_segmented_param_3];
	ld.param.u32 	%r2, [rope_partial_segmented_param_4];
	ld.param.u32 	%r3, [rope_partial_segmented_param_5];
	ld.param.u32 	%r4, [rope_partial_segmented_param_6];
	ld.param.u32 	%r5, [rope_partial_segmented_param_7];
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mul.lo.s32 	%r10, %r3, %r6;
	mul.lo.s32 	%r11, %r10, %r5;
	setp.ge.s32 	%p1, %r1, %r11;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	mul.lo.s32 	%r12, %r5, %r3;
	div.s32 	%r13, %r1, %r12;
	div.s32 	%r14, %r1, %r5;
	rem.s32 	%r15, %r14, %r3;
	add.s32 	%r16, %r13, %r2;
	mul.wide.s32 	%rd5, %r13, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.u32 	%r17, [%rd6];
	sub.s32 	%r18, %r16, %r17;
	mad.lo.s32 	%r19, %r13, %r3, %r15;
	mul.lo.s32 	%r20, %r14, %r5;
	sub.s32 	%r21, %r1, %r20;
	mad.lo.s32 	%r22, %r19, %r4, %r21;
	cvta.to.global.u64 	%rd7, %rd1;
	mul.wide.s32 	%rd8, %r22, 4;
	add.s64 	%rd9, %rd7, %rd8;
	mul.wide.s32 	%rd10, %r5, 4;
	add.s64 	%rd11, %rd9, %rd10;
	mad.lo.s32 	%r23, %r18, %r5, %r21;
	shl.b32 	%r24, %r23, 1;
	cvta.to.global.u64 	%rd12, %rd2;
	mul.wide.s32 	%rd13, %r24, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.f32 	%f1, [%rd14+4];
	ld.global.f32 	%f2, [%rd11];
	mul.ftz.f32 	%f3, %f2, %f1;
	neg.ftz.f32 	%f4, %f3;
	ld.global.f32 	%f5, [%rd14];
	ld.global.f32 	%f6, [%rd9];
	fma.rn.ftz.f32 	%f7, %f6, %f5, %f4;
	st.global.f32 	[%rd9], %f7;
	mul.ftz.f32 	%f8, %f2, %f5;
	fma.rn.ftz.f32 	%f9, %f6, %f1, %f8;
	st.global.f32 	[%rd11], %f9;

$L__BB0_2:
	ret;

}
	// .globl	gqa_attention_segmented
.visible .entry gqa_attention_segmented(
	.param .u64 gqa_attention_segmented_param_0,
	.param .u64 gqa_attention_segmented_param_1,
	.param .u64 gqa_attention_segmented_param_2,
	.param .u64 gqa_attention_segmented_param_3,
	.param .u64 gqa_attention_segmented_param_4,
	.param .u64 gqa_attention_segmented_param_5,
	.param .u64 gqa_attention_segmented_param_6,
	.param .u32 gqa_attention_segmented_param_7,
	.param .u32 gqa_attention_segmented_param_8,
	.param .u32 gqa_attention_segmented_param_9,
	.param .u32 gqa_attention_segmented_param_10,
	.param .u32 gqa_attention_segmented_param_11,
	.param .u32 gqa_attention_segmented_param_12,
	.param .f32 gqa_attention_segmented_param_13
)
.maxntid 256, 1, 1
.minnctapersm 1
{
	.reg .pred 	%p<72>;
	.reg .f32 	%f<202>;
	.reg .b32 	%r<288>;
	.reg .b64 	%rd<158>;
	// demoted variable
	.shared .align 4 .b8 _ZZ23gqa_attention_segmentedE6scores[8192];
	// demoted variable
	.shared .align 4 .b8 _ZZ23gqa_attention_segmentedE6reduce[1024];

	ld.param.u64 	%rd46, [gqa_attention_segmented_param_0];
	ld.param.u64 	%rd47, [gqa_attention_segmented_param_1];
	ld.param.u64 	%rd51, [gqa_attention_segmented_param_2];
	ld.param.u64 	%rd48, [gqa_attention_segmented_param_3];
	ld.param.u64 	%rd52, [gqa_attention_segmented_param_4];
	ld.param.u64 	%rd49, [gqa_attention_segmented_param_5];
	ld.param.u64 	%rd50, [gqa_attention_segmented_param_6];
	ld.param.u32 	%r110, [gqa_attention_segmented_param_7];
	ld.param.u32 	%r105, [gqa_attention_segmented_param_8];
	ld.param.u32 	%r106, [gqa_attention_segmented_param_9];
	ld.param.u32 	%r107, [gqa_attention_segmented_param_10];
	ld.param.u32 	%r108, [gqa_attention_segmented_param_11];
	ld.param.u32 	%r109, [gqa_attention_segmented_param_12];
	ld.param.f32 	%f37, [gqa_attention_segmented_param_13];
	cvta.to.global.u64 	%rd1, %rd51;
	cvta.to.global.u64 	%rd2, %rd52;
	mov.u32 	%r1, %ctaid.x;
	setp.ge.s32 	%p1, %r1, %r107;
	mov.u32 	%r2, %ctaid.y;
	setp.ge.s32 	%p2, %r2, %r110;
	or.pred  	%p3, %p2, %p1;
	@%p3 bra 	$L__BB1_108;

	mov.u32 	%r284, %tid.x;
	cvta.to.global.u64 	%rd53, %rd50;
	and.b32  	%r3, %r284, 31;
	mul.wide.s32 	%rd54, %r2, 4;
	add.s64 	%rd55, %rd53, %rd54;
	add.s32 	%r112, %r2, %r105;
	ld.global.u32 	%r4, [%rd55];
	sub.s32 	%r113, %r112, %r4;
	add.s32 	%r114, %r113, 1;
	setp.ge.s32 	%p4, %r113, %r106;
	setp.gt.s32 	%p5, %r106, 0;
	and.pred  	%p6, %p5, %p4;
	sub.s32 	%r115, %r114, %r106;
	selp.b32 	%r5, %r115, 0, %p6;
	sub.s32 	%r6, %r114, %r5;
	div.s32 	%r116, %r107, %r108;
	div.s32 	%r7, %r1, %r116;
	mul.lo.s32 	%r8, %r109, %r108;
	mad.lo.s32 	%r117, %r2, %r107, %r1;
	mul.lo.s32 	%r118, %r117, %r109;
	cvt.s64.s32 	%rd3, %r118;
	shr.s32 	%r259, %r284, 5;
	setp.ge.s32 	%p7, %r259, %r6;
	@%p7 bra 	$L__BB1_17;

	mul.lo.s32 	%r119, %r7, %r109;
	cvt.s64.s32 	%rd4, %r119;
	not.b32 	%r120, %r3;
	add.s32 	%r121, %r120, %r109;
	shr.u32 	%r122, %r121, 5;
	add.s32 	%r123, %r122, 1;
	and.b32  	%r10, %r123, 3;
	cvt.u64.u32 	%rd56, %r3;
	add.s64 	%rd57, %rd56, %rd3;
	cvta.to.global.u64 	%rd58, %rd46;
	shl.b64 	%rd59, %rd57, 2;
	add.s64 	%rd5, %rd58, %rd59;
	or.b32  	%r11, %r3, 32;
	or.b32  	%r12, %r3, 64;
	or.b32  	%r13, %r3, 96;
	cvta.to.global.u64 	%rd62, %rd47;
	cvta.to.global.u64 	%rd66, %rd48;

$L__BB1_3:
	add.s32 	%r15, %r259, %r5;
	setp.lt.s32 	%p8, %r15, %r105;
	@%p8 bra 	$L__BB1_5;
	bra.uni 	$L__BB1_4;

$L__BB1_5:
	mul.lo.s32 	%r127, %r15, %r8;
	cvt.s64.s32 	%rd64, %r127;
	add.s64 	%rd65, %rd64, %rd4;
	shl.b64 	%rd67, %rd65, 2;
	add.s64 	%rd146, %rd66, %rd67;
	bra.uni 	$L__BB1_6;

$L__BB1_4:
	sub.s32 	%r124, %r4, %r105;
	add.s32 	%r125, %r124, %r15;
	mul.lo.s32 	%r126, %r125, %r8;
	cvt.s64.s32 	%rd60, %r126;
	add.s64 	%rd61, %rd60, %rd4;
	shl.b64 	%rd63, %rd61, 2;
	add.s64 	%rd146, %rd62, %rd63;

$L__BB1_6:
	setp.ge.s32 	%p9, %r3, %r109;
	mov.f32 	%f187, 0f00000000;
	@%p9 bra 	$L__BB1_14;

	setp.eq.s32 	%p10, %r10, 0;
	mov.f32 	%f187, 0f00000000;
	mov.u32 	%r260, %r3;
	@%p10 bra 	$L__BB1_11;

	setp.eq.s32 	%p11, %r10, 1;
	mov.u32 	%r128, %tid.x;
	shl.b32 	%r129, %r128, 2;
	cvt.u64.u32 	%rd68, %r129;
	and.b64  	%rd69, %rd68, 124;
	add.s64 	%rd70, %rd146, %rd69;
	ld.global.f32 	%f41, [%rd70];
	ld.global.f32 	%f42, [%rd5];
	mov.f32 	%f43, 0f00000000;
	fma.rn.ftz.f32 	%f187, %f42, %f41, %f43;
	mov.u32 	%r260, %r11;
	@%p11 bra 	$L__BB1_11;

	setp.eq.s32 	%p12, %r10, 2;
	ld.global.f32 	%f44, [%rd70+128];
	ld.global.f32 	%f45, [%rd5+128];
	fma.rn.ftz.f32 	%f187, %f45, %f44, %f187;
	mov.u32 	%r260, %r12;
	@%p12 bra 	$L__BB1_11;

	ld.global.f32 	%f46, [%rd70+256];
	ld.global.f32 	%f47, [%rd5+256];
	fma.rn.ftz.f32 	%f187, %f47, %f46, %f187;
	mov.u32 	%r260, %r13;

$L__BB1_11:
	mov.u32 	%r134, %tid.x;
	not.b32 	%r135, %r134;
	or.b32  	%r136, %r135, -32;
	add.s32 	%r137, %r136, %r109;
	setp.lt.u32 	%p13, %r137, 96;
	@%p13 bra 	$L__BB1_14;

	mul.wide.u32 	%rd77, %r260, 4;
	add.s64 	%rd78, %rd146, %rd77;
	cvt.u64.u32 	%rd79, %r260;
	add.s64 	%rd148, %rd78, 256;
	add.s64 	%rd80, %rd3, %rd79;
	shl.b64 	%rd82, %rd80, 2;
	add.s64 	%rd83, %rd58, %rd82;
	add.s64 	%rd147, %rd83, 256;

$L__BB1_13:
	ld.global.f32 	%f48, [%rd148+-256];
	ld.global.f32 	%f49, [%rd147+-256];
	fma.rn.ftz.f32 	%f50, %f49, %f48, %f187;
	ld.global.f32 	%f51, [%rd148+-128];
	ld.global.f32 	%f52, [%rd147+-128];
	fma.rn.ftz.f32 	%f53, %f52, %f51, %f50;
	ld.global.f32 	%f54, [%rd148];
	ld.global.f32 	%f55, [%rd147];
	fma.rn.ftz.f32 	%f56, %f55, %f54, %f53;
	ld.global.f32 	%f57, [%rd148+128];
	ld.global.f32 	%f58, [%rd147+128];
	fma.rn.ftz.f32 	%f187, %f58, %f57, %f56;
	add.s64 	%rd148, %rd148, 512;
	add.s64 	%rd147, %rd147, 512;
	add.s32 	%r260, %r260, 128;
	setp.lt.s32 	%p14, %r260, %r109;
	@%p14 bra 	$L__BB1_13;

$L__BB1_14:
	mov.b32 	%r138, %f187;
	mov.u32 	%r139, 2;
	mov.u32 	%r140, 31;
	mov.u32 	%r141, 16;
	mov.u32 	%r142, -1;
	shfl.sync.down.b32 	%r143|%p15, %r138, %r141, %r140, %r142;
	mov.b32 	%f59, %r143;
	add.ftz.f32 	%f60, %f187, %f59;
	mov.b32 	%r144, %f60;
	mov.u32 	%r145, 8;
	shfl.sync.down.b32 	%r146|%p16, %r144, %r145, %r140, %r142;
	mov.b32 	%f61, %r146;
	add.ftz.f32 	%f62, %f60, %f61;
	mov.b32 	%r147, %f62;
	mov.u32 	%r148, 4;
	shfl.sync.down.b32 	%r149|%p17, %r147, %r148, %r140, %r142;
	mov.b32 	%f63, %r149;
	add.ftz.f32 	%f64, %f62, %f63;
	mov.b32 	%r150, %f64;
	shfl.sync.down.b32 	%r151|%p18, %r150, %r139, %r140, %r142;
	mov.b32 	%f65, %r151;
	add.ftz.f32 	%f66, %f64, %f65;
	mov.b32 	%r152, %f66;
	mov.u32 	%r153, 1;
	shfl.sync.down.b32 	%r154|%p19, %r152, %r153, %r140, %r142;
	mov.b32 	%f67, %r154;
	add.ftz.f32 	%f9, %f66, %f67;
	setp.ne.s32 	%p20, %r3, 0;
	@%p20 bra 	$L__BB1_16;

	mul.ftz.f32 	%f68, %f9, %f37;
	shl.b32 	%r155, %r259, 2;
	mov.u32 	%r156, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r157, %r156, %r155;
	st.shared.f32 	[%r157], %f68;

$L__BB1_16:
	add.s32 	%r259, %r259, 8;
	setp.lt.s32 	%p21, %r259, %r6;
	@%p21 bra 	$L__BB1_3;

$L__BB1_17:
	bar.sync 	0;
	setp.ge.s32 	%p22, %r284, %r6;
	mov.f32 	%f192, 0fFF7FFFFF;
	@%p22 bra 	$L__BB1_24;

	sub.s32 	%r161, %r112, %r5;
	mov.u32 	%r265, %tid.x;
	sub.s32 	%r162, %r161, %r265;
	sub.s32 	%r21, %r162, %r4;
	shr.u32 	%r163, %r21, 8;
	add.s32 	%r164, %r163, 1;
	and.b32  	%r264, %r164, 3;
	setp.eq.s32 	%p23, %r264, 0;
	mov.f32 	%f192, 0fFF7FFFFF;
	@%p23 bra 	$L__BB1_21;

	mov.u32 	%r265, %tid.x;
	shl.b32 	%r165, %r265, 2;
	mov.u32 	%r166, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r262, %r166, %r165;
	mov.f32 	%f192, 0fFF7FFFFF;

$L__BB1_20:
	.pragma "nounroll";
	ld.shared.f32 	%f73, [%r262];
	max.ftz.f32 	%f192, %f192, %f73;
	add.s32 	%r265, %r265, 256;
	add.s32 	%r262, %r262, 1024;
	add.s32 	%r264, %r264, -1;
	setp.ne.s32 	%p24, %r264, 0;
	@%p24 bra 	$L__BB1_20;

$L__BB1_21:
	setp.lt.u32 	%p25, %r21, 768;
	@%p25 bra 	$L__BB1_24;

	shl.b32 	%r167, %r265, 2;
	mov.u32 	%r168, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r169, %r168, %r167;
	add.s32 	%r266, %r169, 2048;

$L__BB1_23:
	ld.shared.f32 	%f74, [%r266+-2048];
	max.ftz.f32 	%f75, %f192, %f74;
	ld.shared.f32 	%f76, [%r266+-1024];
	max.ftz.f32 	%f77, %f75, %f76;
	ld.shared.f32 	%f78, [%r266];
	max.ftz.f32 	%f79, %f77, %f78;
	ld.shared.f32 	%f80, [%r266+1024];
	max.ftz.f32 	%f192, %f79, %f80;
	add.s32 	%r266, %r266, 4096;
	add.s32 	%r265, %r265, 1024;
	setp.lt.s32 	%p26, %r265, %r6;
	@%p26 bra 	$L__BB1_23;

$L__BB1_24:
	shl.b32 	%r171, %r284, 2;
	mov.u32 	%r172, _ZZ23gqa_attention_segmentedE6reduce;
	add.s32 	%r37, %r172, %r171;
	st.shared.f32 	[%r37], %f192;
	bar.sync 	0;
	setp.gt.s32 	%p27, %r284, 127;
	@%p27 bra 	$L__BB1_26;

	ld.shared.f32 	%f81, [%r37];
	ld.shared.f32 	%f82, [%r37+512];
	max.ftz.f32 	%f83, %f81, %f82;
	st.shared.f32 	[%r37], %f83;

$L__BB1_26:
	bar.sync 	0;
	setp.gt.s32 	%p28, %r284, 63;
	@%p28 bra 	$L__BB1_28;

	ld.shared.f32 	%f84, [%r37];
	ld.shared.f32 	%f85, [%r37+256];
	max.ftz.f32 	%f86, %f84, %f85;
	st.shared.f32 	[%r37], %f86;

$L__BB1_28:
	bar.sync 	0;
	setp.gt.s32 	%p29, %r284, 31;
	@%p29 bra 	$L__BB1_30;

	ld.shared.f32 	%f87, [%r37];
	ld.shared.f32 	%f88, [%r37+128];
	max.ftz.f32 	%f89, %f87, %f88;
	st.shared.f32 	[%r37], %f89;

$L__BB1_30:
	bar.sync 	0;
	setp.gt.s32 	%p30, %r284, 15;
	@%p30 bra 	$L__BB1_32;

	ld.shared.f32 	%f90, [%r37];
	ld.shared.f32 	%f91, [%r37+64];
	max.ftz.f32 	%f92, %f90, %f91;
	st.shared.f32 	[%r37], %f92;

$L__BB1_32:
	bar.sync 	0;
	setp.gt.s32 	%p31, %r284, 7;
	@%p31 bra 	$L__BB1_34;

	ld.shared.f32 	%f93, [%r37];
	ld.shared.f32 	%f94, [%r37+32];
	max.ftz.f32 	%f95, %f93, %f94;
	st.shared.f32 	[%r37], %f95;

$L__BB1_34:
	bar.sync 	0;
	setp.gt.s32 	%p32, %r284, 3;
	@%p32 bra 	$L__BB1_36;

	ld.shared.f32 	%f96, [%r37];
	ld.shared.f32 	%f97, [%r37+16];
	max.ftz.f32 	%f98, %f96, %f97;
	st.shared.f32 	[%r37], %f98;

$L__BB1_36:
	bar.sync 	0;
	setp.gt.s32 	%p33, %r284, 1;
	@%p33 bra 	$L__BB1_38;

	ld.shared.f32 	%f99, [%r37];
	ld.shared.f32 	%f100, [%r37+8];
	max.ftz.f32 	%f101, %f99, %f100;
	st.shared.f32 	[%r37], %f101;

$L__BB1_38:
	bar.sync 	0;
	setp.gt.s32 	%p34, %r284, 0;
	@%p34 bra 	$L__BB1_40;

	ld.shared.f32 	%f102, [%r37];
	ld.shared.f32 	%f103, [%r37+4];
	max.ftz.f32 	%f104, %f102, %f103;
	st.shared.f32 	[%r37], %f104;

$L__BB1_40:
	bar.sync 	0;
	ld.shared.f32 	%f17, [_ZZ23gqa_attention_segmentedE6reduce];
	bar.sync 	0;
	mov.f32 	%f197, 0f00000000;
	@%p22 bra 	$L__BB1_47;

	sub.s32 	%r183, %r112, %r5;
	mov.u32 	%r271, %tid.x;
	sub.s32 	%r184, %r183, %r271;
	sub.s32 	%r39, %r184, %r4;
	shr.u32 	%r185, %r39, 8;
	add.s32 	%r186, %r185, 1;
	and.b32  	%r270, %r186, 3;
	setp.eq.s32 	%p36, %r270, 0;
	mov.f32 	%f197, 0f00000000;
	@%p36 bra 	$L__BB1_44;

	mov.u32 	%r271, %tid.x;
	shl.b32 	%r187, %r271, 2;
	mov.u32 	%r188, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r268, %r188, %r187;
	mov.f32 	%f197, 0f00000000;

$L__BB1_43:
	.pragma "nounroll";
	ld.shared.f32 	%f109, [%r268];
	sub.ftz.f32 	%f110, %f109, %f17;
	mul.ftz.f32 	%f111, %f110, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f112, %f111;
	st.shared.f32 	[%r268], %f112;
	add.ftz.f32 	%f197, %f197, %f112;
	add.s32 	%r271, %r271, 256;
	add.s32 	%r268, %r268, 1024;
	add.s32 	%r270, %r270, -1;
	setp.ne.s32 	%p37, %r270, 0;
	@%p37 bra 	$L__BB1_43;

$L__BB1_44:
	setp.lt.u32 	%p38, %r39, 768;
	@%p38 bra 	$L__BB1_47;

	shl.b32 	%r189, %r271, 2;
	mov.u32 	%r190, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r191, %r190, %r189;
	add.s32 	%r272, %r191, 2048;

$L__BB1_46:
	ld.shared.f32 	%f113, [%r272+-2048];
	sub.ftz.f32 	%f114, %f113, %f17;
	mul.ftz.f32 	%f115, %f114, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f116, %f115;
	st.shared.f32 	[%r272+-2048], %f116;
	add.ftz.f32 	%f117, %f197, %f116;
	ld.shared.f32 	%f118, [%r272+-1024];
	sub.ftz.f32 	%f119, %f118, %f17;
	mul.ftz.f32 	%f120, %f119, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f121, %f120;
	st.shared.f32 	[%r272+-1024], %f121;
	add.ftz.f32 	%f122, %f117, %f121;
	ld.shared.f32 	%f123, [%r272];
	sub.ftz.f32 	%f124, %f123, %f17;
	mul.ftz.f32 	%f125, %f124, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f126, %f125;
	st.shared.f32 	[%r272], %f126;
	add.ftz.f32 	%f127, %f122, %f126;
	ld.shared.f32 	%f128, [%r272+1024];
	sub.ftz.f32 	%f129, %f128, %f17;
	mul.ftz.f32 	%f130, %f129, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f131, %f130;
	st.shared.f32 	[%r272+1024], %f131;
	add.ftz.f32 	%f197, %f127, %f131;
	add.s32 	%r272, %r272, 4096;
	add.s32 	%r271, %r271, 1024;
	setp.lt.s32 	%p39, %r271, %r6;
	@%p39 bra 	$L__BB1_46;

$L__BB1_47:
	st.shared.f32 	[%r37], %f197;
	bar.sync 	0;
	@%p27 bra 	$L__BB1_49;

	ld.shared.f32 	%f132, [%r37];
	ld.shared.f32 	%f133, [%r37+512];
	add.ftz.f32 	%f134, %f133, %f132;
	st.shared.f32 	[%r37], %f134;

$L__BB1_49:
	bar.sync 	0;
	@%p28 bra 	$L__BB1_51;

	ld.shared.f32 	%f135, [%r37];
	ld.shared.f32 	%f136, [%r37+256];
	add.ftz.f32 	%f137, %f136, %f135;
	st.shared.f32 	[%r37], %f137;

$L__BB1_51:
	bar.sync 	0;
	@%p29 bra 	$L__BB1_53;

	ld.shared.f32 	%f138, [%r37];
	ld.shared.f32 	%f139, [%r37+128];
	add.ftz.f32 	%f140, %f139, %f138;
	st.shared.f32 	[%r37], %f140;

$L__BB1_53:
	bar.sync 	0;
	@%p30 bra 	$L__BB1_55;

	ld.shared.f32 	%f141, [%r37];
	ld.shared.f32 	%f142, [%r37+64];
	add.ftz.f32 	%f143, %f142, %f141;
	st.shared.f32 	[%r37], %f143;

$L__BB1_55:
	bar.sync 	0;
	@%p31 bra 	$L__BB1_57;

	ld.shared.f32 	%f144, [%r37];
	ld.shared.f32 	%f145, [%r37+32];
	add.ftz.f32 	%f146, %f145, %f144;
	st.shared.f32 	[%r37], %f146;

$L__BB1_57:
	bar.sync 	0;
	@%p32 bra 	$L__BB1_59;

	ld.shared.f32 	%f147, [%r37];
	ld.shared.f32 	%f148, [%r37+16];
	add.ftz.f32 	%f149, %f148, %f147;
	st.shared.f32 	[%r37], %f149;

$L__BB1_59:
	bar.sync 	0;
	@%p33 bra 	$L__BB1_61;

	ld.shared.f32 	%f150, [%r37];
	ld.shared.f32 	%f151, [%r37+8];
	add.ftz.f32 	%f152, %f151, %f150;
	st.shared.f32 	[%r37], %f152;

$L__BB1_61:
	bar.sync 	0;
	@%p34 bra 	$L__BB1_63;

	ld.shared.f32 	%f153, [%r37];
	ld.shared.f32 	%f154, [%r37+4];
	add.ftz.f32 	%f155, %f154, %f153;
	st.shared.f32 	[%r37], %f155;

$L__BB1_63:
	bar.sync 	0;
	ld.shared.f32 	%f156, [_ZZ23gqa_attention_segmentedE6reduce];
	rcp.approx.ftz.f32 	%f25, %f156;
	@%p22 bra 	$L__BB1_70;

	sub.s32 	%r203, %r112, %r5;
	mov.u32 	%r277, %tid.x;
	sub.s32 	%r204, %r203, %r277;
	sub.s32 	%r56, %r204, %r4;
	shr.u32 	%r205, %r56, 8;
	add.s32 	%r206, %r205, 1;
	and.b32  	%r276, %r206, 3;
	setp.eq.s32 	%p49, %r276, 0;
	@%p49 bra 	$L__BB1_67;

	mov.u32 	%r277, %tid.x;
	shl.b32 	%r207, %r277, 2;
	mov.u32 	%r208, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r274, %r208, %r207;

$L__BB1_66:
	.pragma "nounroll";
	ld.shared.f32 	%f157, [%r274];
	mul.ftz.f32 	%f158, %f25, %f157;
	st.shared.f32 	[%r274], %f158;
	add.s32 	%r277, %r277, 256;
	add.s32 	%r274, %r274, 1024;
	add.s32 	%r276, %r276, -1;
	setp.ne.s32 	%p50, %r276, 0;
	@%p50 bra 	$L__BB1_66;

$L__BB1_67:
	setp.lt.u32 	%p51, %r56, 768;
	@%p51 bra 	$L__BB1_70;

	shl.b32 	%r209, %r277, 2;
	mov.u32 	%r210, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r211, %r210, %r209;
	add.s32 	%r278, %r211, 2048;

$L__BB1_69:
	ld.shared.f32 	%f159, [%r278+-2048];
	mul.ftz.f32 	%f160, %f25, %f159;
	st.shared.f32 	[%r278+-2048], %f160;
	ld.shared.f32 	%f161, [%r278+-1024];
	mul.ftz.f32 	%f162, %f25, %f161;
	st.shared.f32 	[%r278+-1024], %f162;
	ld.shared.f32 	%f163, [%r278];
	mul.ftz.f32 	%f164, %f25, %f163;
	st.shared.f32 	[%r278], %f164;
	ld.shared.f32 	%f165, [%r278+1024];
	mul.ftz.f32 	%f166, %f25, %f165;
	st.shared.f32 	[%r278+1024], %f166;
	add.s32 	%r278, %r278, 4096;
	add.s32 	%r277, %r277, 1024;
	setp.lt.s32 	%p52, %r277, %r6;
	@%p52 bra 	$L__BB1_69;

$L__BB1_70:
	bar.sync 	0;
	setp.ge.s32 	%p53, %r284, %r109;
	@%p53 bra 	$L__BB1_108;

	setp.gt.s32 	%p54, %r6, 0;
	mul.lo.s32 	%r213, %r7, %r109;
	cvt.s64.s32 	%rd16, %r213;
	sub.s32 	%r72, %r4, %r105;
	@%p54 bra 	$L__BB1_78;
	bra.uni 	$L__BB1_72;

$L__BB1_78:
	add.s32 	%r225, %r112, 1;
	sub.s32 	%r226, %r225, %r5;
	sub.s32 	%r227, %r226, %r4;
	sub.s32 	%r228, %r112, %r5;
	sub.s32 	%r84, %r228, %r4;
	and.b32  	%r85, %r227, 3;
	sub.s32 	%r86, %r227, %r85;
	cvta.to.global.u64 	%rd23, %rd49;

$L__BB1_79:
	cvt.s64.s32 	%rd24, %r284;
	setp.lt.u32 	%p59, %r84, 3;
	mov.f32 	%f201, 0f00000000;
	mov.u32 	%r287, 0;
	@%p59 bra 	$L__BB1_94;

	mov.f32 	%f201, 0f00000000;
	mov.u32 	%r287, 0;
	mov.u32 	%r286, %r86;

$L__BB1_81:
	add.s32 	%r91, %r287, %r5;
	setp.lt.s32 	%p60, %r91, %r105;
	@%p60 bra 	$L__BB1_83;
	bra.uni 	$L__BB1_82;

$L__BB1_83:
	mul.lo.s32 	%r233, %r91, %r8;
	cvt.s64.s32 	%rd91, %r233;
	add.s64 	%rd92, %rd91, %rd16;
	shl.b64 	%rd93, %rd92, 2;
	add.s64 	%rd151, %rd2, %rd93;
	bra.uni 	$L__BB1_84;

$L__BB1_82:
	add.s32 	%r231, %r72, %r91;
	mul.lo.s32 	%r232, %r231, %r8;
	cvt.s64.s32 	%rd88, %r232;
	add.s64 	%rd89, %rd88, %rd16;
	shl.b64 	%rd90, %rd89, 2;
	add.s64 	%rd151, %rd1, %rd90;

$L__BB1_84:
	shl.b64 	%rd94, %rd24, 2;
	add.s64 	%rd95, %rd151, %rd94;
	ld.global.f32 	%f170, [%rd95];
	shl.b32 	%r234, %r287, 2;
	mov.u32 	%r235, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r92, %r235, %r234;
	ld.shared.f32 	%f171, [%r92];
	fma.rn.ftz.f32 	%f27, %f171, %f170, %f201;
	add.s32 	%r93, %r91, 1;
	setp.lt.s32 	%p61, %r93, %r105;
	@%p61 bra 	$L__BB1_86;
	bra.uni 	$L__BB1_85;

$L__BB1_86:
	mul.lo.s32 	%r238, %r93, %r8;
	cvt.s64.s32 	%rd99, %r238;
	add.s64 	%rd100, %rd99, %rd16;
	shl.b64 	%rd101, %rd100, 2;
	add.s64 	%rd152, %rd2, %rd101;
	bra.uni 	$L__BB1_87;

$L__BB1_85:
	add.s32 	%r236, %r72, %r93;
	mul.lo.s32 	%r237, %r236, %r8;
	cvt.s64.s32 	%rd96, %r237;
	add.s64 	%rd97, %rd96, %rd16;
	shl.b64 	%rd98, %rd97, 2;
	add.s64 	%rd152, %rd1, %rd98;

$L__BB1_87:
	add.s64 	%rd103, %rd152, %rd94;
	ld.global.f32 	%f172, [%rd103];
	ld.shared.f32 	%f173, [%r92+4];
	fma.rn.ftz.f32 	%f28, %f173, %f172, %f27;
	add.s32 	%r95, %r91, 2;
	setp.lt.s32 	%p62, %r95, %r105;
	@%p62 bra 	$L__BB1_89;
	bra.uni 	$L__BB1_88;

$L__BB1_89:
	mul.lo.s32 	%r241, %r95, %r8;
	cvt.s64.s32 	%rd107, %r241;
	add.s64 	%rd108, %rd107, %rd16;
	shl.b64 	%rd109, %rd108, 2;
	add.s64 	%rd153, %rd2, %rd109;
	bra.uni 	$L__BB1_90;

$L__BB1_88:
	add.s32 	%r239, %r72, %r95;
	mul.lo.s32 	%r240, %r239, %r8;
	cvt.s64.s32 	%rd104, %r240;
	add.s64 	%rd105, %rd104, %rd16;
	shl.b64 	%rd106, %rd105, 2;
	add.s64 	%rd153, %rd1, %rd106;

$L__BB1_90:
	add.s64 	%rd111, %rd153, %rd94;
	ld.global.f32 	%f174, [%rd111];
	ld.shared.f32 	%f175, [%r92+8];
	fma.rn.ftz.f32 	%f29, %f175, %f174, %f28;
	add.s32 	%r96, %r91, 3;
	setp.lt.s32 	%p63, %r96, %r105;
	@%p63 bra 	$L__BB1_92;
	bra.uni 	$L__BB1_91;

$L__BB1_92:
	mul.lo.s32 	%r244, %r96, %r8;
	cvt.s64.s32 	%rd115, %r244;
	add.s64 	%rd116, %rd115, %rd16;
	shl.b64 	%rd117, %rd116, 2;
	add.s64 	%rd154, %rd2, %rd117;
	bra.uni 	$L__BB1_93;

$L__BB1_91:
	add.s32 	%r242, %r72, %r96;
	mul.lo.s32 	%r243, %r242, %r8;
	cvt.s64.s32 	%rd112, %r243;
	add.s64 	%rd113, %rd112, %rd16;
	shl.b64 	%rd114, %rd113, 2;
	add.s64 	%rd154, %rd1, %rd114;

$L__BB1_93:
	add.s64 	%rd119, %rd154, %rd94;
	ld.global.f32 	%f176, [%rd119];
	ld.shared.f32 	%f177, [%r92+12];
	fma.rn.ftz.f32 	%f201, %f177, %f176, %f29;
	add.s32 	%r287, %r287, 4;
	add.s32 	%r286, %r286, -4;
	setp.ne.s32 	%p64, %r286, 0;
	@%p64 bra 	$L__BB1_81;

$L__BB1_94:
	setp.eq.s32 	%p65, %r85, 0;
	@%p65 bra 	$L__BB1_107;

	add.s32 	%r100, %r287, %r5;
	setp.lt.s32 	%p66, %r100, %r105;
	@%p66 bra 	$L__BB1_97;
	bra.uni 	$L__BB1_96;

$L__BB1_97:
	mul.lo.s32 	%r247, %r100, %r8;
	cvt.s64.s32 	%rd123, %r247;
	add.s64 	%rd124, %rd123, %rd16;
	shl.b64 	%rd125, %rd124, 2;
	add.s64 	%rd155, %rd2, %rd125;
	bra.uni 	$L__BB1_98;

$L__BB1_96:
	add.s32 	%r245, %r72, %r100;
	mul.lo.s32 	%r246, %r245, %r8;
	cvt.s64.s32 	%rd120, %r246;
	add.s64 	%rd121, %rd120, %rd16;
	shl.b64 	%rd122, %rd121, 2;
	add.s64 	%rd155, %rd1, %rd122;

$L__BB1_98:
	shl.b64 	%rd126, %rd24, 2;
	add.s64 	%rd127, %rd155, %rd126;
	ld.global.f32 	%f178, [%rd127];
	shl.b32 	%r248, %r287, 2;
	mov.u32 	%r249, _ZZ23gqa_attention_segmentedE6scores;
	add.s32 	%r101, %r249, %r248;
	ld.shared.f32 	%f179, [%r101];
	fma.rn.ftz.f32 	%f201, %f179, %f178, %f201;
	setp.eq.s32 	%p67, %r85, 1;
	@%p67 bra 	$L__BB1_107;

	add.s32 	%r102, %r100, 1;
	setp.lt.s32 	%p68, %r102, %r105;
	@%p68 bra 	$L__BB1_101;
	bra.uni 	$L__BB1_100;

$L__BB1_101:
	mul.lo.s32 	%r252, %r102, %r8;
	cvt.s64.s32 	%rd131, %r252;
	add.s64 	%rd132, %rd131, %rd16;
	shl.b64 	%rd133, %rd132, 2;
	add.s64 	%rd156, %rd2, %rd133;
	bra.uni 	$L__BB1_102;

$L__BB1_100:
	add.s32 	%r250, %r72, %r102;
	mul.lo.s32 	%r251, %r250, %r8;
	cvt.s64.s32 	%rd128, %r251;
	add.s64 	%rd129, %rd128, %rd16;
	shl.b64 	%rd130, %rd129, 2;
	add.s64 	%rd156, %rd1, %rd130;

$L__BB1_102:
	add.s64 	%rd135, %rd156, %rd126;
	ld.global.f32 	%f180, [%rd135];
	ld.shared.f32 	%f181, [%r101+4];
	fma.rn.ftz.f32 	%f201, %f181, %f180, %f201;
	setp.eq.s32 	%p69, %r85, 2;
	@%p69 bra 	$L__BB1_107;

	add.s32 	%r103, %r100, 2;
	setp.lt.s32 	%p70, %r103, %r105;
	@%p70 bra 	$L__BB1_105;
	bra.uni 	$L__BB1_104;

$L__BB1_105:
	mul.lo.s32 	%r255, %r103, %r8;
	cvt.s64.s32 	%rd139, %r255;
	add.s64 	%rd140, %rd139, %rd16;
	shl.b64 	%rd141, %rd140, 2;
	add.s64 	%rd157, %rd2, %rd141;
	bra.uni 	$L__BB1_106;

$L__BB1_104:
	add.s32 	%r253, %r72, %r103;
	mul.lo.s32 	%r254, %r253, %r8;
	cvt.s64.s32 	%rd136, %r254;
	add.s64 	%rd137, %rd136, %rd16;
	shl.b64 	%rd138, %rd137, 2;
	add.s64 	%rd157, %rd1, %rd138;

$L__BB1_106:
	add.s64 	%rd143, %rd157, %rd126;
	ld.global.f32 	%f182, [%rd143];
	ld.shared.f32 	%f183, [%r101+8];
	fma.rn.ftz.f32 	%f201, %f183, %f182, %f201;

$L__BB1_107:
	cvt.u32.u64 	%r256, %rd24;
	cvt.u32.u64 	%r257, %rd3;
	add.s32 	%r258, %r256, %r257;
	mul.wide.s32 	%rd144, %r258, 4;
	add.s64 	%rd145, %rd23, %rd144;
	st.global.f32 	[%rd145], %f201;
	add.s32 	%r284, %r256, 256;
	setp.lt.s32 	%p71, %r284, %r109;
	@%p71 bra 	$L__BB1_79;
	bra.uni 	$L__BB1_108;

$L__BB1_72:
	mov.u32 	%r282, %tid.x;
	not.b32 	%r214, %r282;
	add.s32 	%r74, %r214, %r109;
	shr.u32 	%r215, %r74, 8;
	add.s32 	%r216, %r215, 1;
	and.b32  	%r281, %r216, 3;
	setp.eq.s32 	%p55, %r281, 0;
	@%p55 bra 	$L__BB1_75;

	cvt.u32.u64 	%r217, %rd3;
	mov.u32 	%r282, %tid.x;
	add.s32 	%r218, %r282, %r217;
	cvta.to.global.u64 	%rd84, %rd49;
	mul.wide.s32 	%rd85, %r218, 4;
	add.s64 	%rd149, %rd84, %rd85;

$L__BB1_74:
	.pragma "nounroll";
	mov.u32 	%r219, 0;
	st.global.u32 	[%rd149], %r219;
	add.s32 	%r282, %r282, 256;
	add.s64 	%rd149, %rd149, 1024;
	add.s32 	%r281, %r281, -1;
	setp.ne.s32 	%p56, %r281, 0;
	@%p56 bra 	$L__BB1_74;

$L__BB1_75:
	setp.lt.u32 	%p57, %r74, 768;
	@%p57 bra 	$L__BB1_108;

	cvt.u32.u64 	%r220, %rd3;
	add.s32 	%r221, %r282, %r220;
	cvta.to.global.u64 	%rd86, %rd49;
	mul.wide.s32 	%rd87, %r221, 4;
	add.s64 	%rd150, %rd86, %rd87;

$L__BB1_77:
	mov.u32 	%r222, 0;
	st.global.u32 	[%rd150], %r222;
	st.global.u32 	[%rd150+1024], %r222;
	st.global.u32 	[%rd150+2048], %r222;
	st.global.u32 	[%rd150+3072], %r222;
	add.s64 	%rd150, %rd150, 4096;
	add.s32 	%r282, %r282, 1024;
	setp.lt.s32 	%p58, %r282, %r109;
	@%p58 bra 	$L__BB1_77;

$L__BB1_108:
	ret;

}
	// .globl	gemv_q5_packed_selected_batch_f32
.visible .entry gemv_q5_packed_selected_batch_f32(
	.param .u64 gemv_q5_packed_selected_batch_f32_param_0,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_1,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_2,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_3,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_4,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_5,
	.param .u64 gemv_q5_packed_selected_batch_f32_param_6,
	.param .u32 gemv_q5_packed_selected_batch_f32_param_7,
	.param .u32 gemv_q5_packed_selected_batch_f32_param_8
)
{
	.reg .pred 	%p<13>;
	.reg .b16 	%rs<6>;
	.reg .f32 	%f<60>;
	.reg .b32 	%r<101>;
	.reg .b64 	%rd<56>;


	ld.param.u64 	%rd9, [gemv_q5_packed_selected_batch_f32_param_0];
	ld.param.u64 	%rd10, [gemv_q5_packed_selected_batch_f32_param_1];
	ld.param.u64 	%rd11, [gemv_q5_packed_selected_batch_f32_param_2];
	ld.param.u64 	%rd12, [gemv_q5_packed_selected_batch_f32_param_3];
	ld.param.u64 	%rd6, [gemv_q5_packed_selected_batch_f32_param_4];
	ld.param.u64 	%rd7, [gemv_q5_packed_selected_batch_f32_param_5];
	ld.param.u64 	%rd8, [gemv_q5_packed_selected_batch_f32_param_6];
	ld.param.u32 	%r29, [gemv_q5_packed_selected_batch_f32_param_7];
	ld.param.u32 	%r30, [gemv_q5_packed_selected_batch_f32_param_8];
	cvta.to.global.u64 	%rd1, %rd9;
	cvta.to.global.u64 	%rd2, %rd12;
	cvta.to.global.u64 	%rd3, %rd10;
	cvta.to.global.u64 	%rd4, %rd11;
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r2, %ctaid.x;
	setp.ge.s32 	%p1, %r2, %r30;
	@%p1 bra 	$L__BB2_10;

	cvt.s64.s32 	%rd5, %r2;
	setp.ge.s32 	%p2, %r1, %r29;
	mov.f32 	%f59, 0f00000000;
	@%p2 bra 	$L__BB2_8;

	cvta.to.global.u64 	%rd13, %rd6;
	shl.b64 	%rd14, %rd5, 2;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.u32 	%r31, [%rd15];
	cvta.to.global.u64 	%rd16, %rd7;
	add.s64 	%rd17, %rd16, %rd14;
	ld.global.u32 	%r32, [%rd17];
	shr.s32 	%r33, %r29, 31;
	shr.u32 	%r34, %r33, 27;
	add.s32 	%r35, %r29, %r34;
	shr.s32 	%r36, %r35, 5;
	mul.lo.s32 	%r3, %r31, %r36;
	mul.lo.s32 	%r4, %r31, %r29;
	mul.lo.s32 	%r5, %r32, %r29;
	not.b32 	%r37, %r1;
	add.s32 	%r6, %r37, %r29;
	shr.u32 	%r38, %r6, 5;
	add.s32 	%r39, %r38, 1;
	and.b32  	%r96, %r39, 3;
	setp.eq.s32 	%p3, %r96, 0;
	mov.f32 	%f59, 0f00000000;
	mov.u32 	%r97, %r1;
	@%p3 bra 	$L__BB2_5;

	add.s32 	%r94, %r1, %r5;
	add.s32 	%r93, %r1, %r4;
	mov.f32 	%f59, 0f00000000;
	mov.u32 	%r97, %r1;

$L__BB2_4:
	.pragma "nounroll";
	shr.s32 	%r40, %r97, 31;
	shr.u32 	%r41, %r40, 27;
	add.s32 	%r42, %r97, %r41;
	shr.s32 	%r43, %r42, 5;
	add.s32 	%r44, %r43, %r3;
	mul.wide.s32 	%rd18, %r44, 4;
	add.s64 	%rd19, %rd4, %rd18;
	cvt.u64.u32 	%rd20, %r93;
	add.s64 	%rd21, %rd3, %rd20;
	ld.global.u8 	%rs1, [%rd21];
	cvt.rn.f32.u16 	%f13, %rs1;
	ld.global.f32 	%f14, [%rd19];
	mul.rn.ftz.f32 	%f15, %f14, %f13;
	add.s64 	%rd22, %rd2, %rd18;
	ld.global.f32 	%f16, [%rd22];
	sub.rn.ftz.f32 	%f17, %f15, %f16;
	mul.wide.u32 	%rd23, %r94, 4;
	add.s64 	%rd24, %rd1, %rd23;
	ld.global.f32 	%f18, [%rd24];
	fma.rn.ftz.f32 	%f59, %f18, %f17, %f59;
	add.s32 	%r97, %r97, 32;
	add.s32 	%r94, %r94, 32;
	add.s32 	%r93, %r93, 32;
	add.s32 	%r96, %r96, -1;
	setp.ne.s32 	%p4, %r96, 0;
	@%p4 bra 	$L__BB2_4;

$L__BB2_5:
	setp.lt.u32 	%p5, %r6, 96;
	@%p5 bra 	$L__BB2_8;

	add.s32 	%r45, %r97, %r5;
	add.s32 	%r99, %r45, 96;
	add.s32 	%r46, %r97, %r4;
	add.s32 	%r98, %r46, 96;
	add.s32 	%r21, %r5, 32;
	add.s32 	%r22, %r4, 32;

$L__BB2_7:
	shr.s32 	%r47, %r97, 31;
	shr.u32 	%r48, %r47, 27;
	add.s32 	%r49, %r97, %r48;
	shr.s32 	%r50, %r49, 5;
	add.s32 	%r51, %r50, %r3;
	mul.wide.s32 	%rd25, %r51, 4;
	add.s64 	%rd26, %rd4, %rd25;
	add.s32 	%r52, %r4, %r97;
	cvt.u64.u32 	%rd27, %r52;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.u8 	%rs2, [%rd28];
	cvt.rn.f32.u16 	%f19, %rs2;
	ld.global.f32 	%f20, [%rd26];
	mul.rn.ftz.f32 	%f21, %f20, %f19;
	add.s64 	%rd29, %rd2, %rd25;
	ld.global.f32 	%f22, [%rd29];
	sub.rn.ftz.f32 	%f23, %f21, %f22;
	add.s32 	%r53, %r5, %r97;
	mul.wide.u32 	%rd30, %r53, 4;
	add.s64 	%rd31, %rd1, %rd30;
	ld.global.f32 	%f24, [%rd31];
	fma.rn.ftz.f32 	%f25, %f24, %f23, %f59;
	add.s32 	%r54, %r97, 32;
	shr.s32 	%r55, %r54, 31;
	shr.u32 	%r56, %r55, 27;
	add.s32 	%r57, %r54, %r56;
	shr.s32 	%r58, %r57, 5;
	add.s32 	%r59, %r58, %r3;
	mul.wide.s32 	%rd32, %r59, 4;
	add.s64 	%rd33, %rd4, %rd32;
	add.s32 	%r60, %r22, %r97;
	cvt.u64.u32 	%rd34, %r60;
	add.s64 	%rd35, %rd3, %rd34;
	ld.global.u8 	%rs3, [%rd35];
	cvt.rn.f32.u16 	%f26, %rs3;
	ld.global.f32 	%f27, [%rd33];
	mul.rn.ftz.f32 	%f28, %f27, %f26;
	add.s64 	%rd36, %rd2, %rd32;
	ld.global.f32 	%f29, [%rd36];
	sub.rn.ftz.f32 	%f30, %f28, %f29;
	add.s32 	%r61, %r21, %r97;
	mul.wide.u32 	%rd37, %r61, 4;
	add.s64 	%rd38, %rd1, %rd37;
	ld.global.f32 	%f31, [%rd38];
	fma.rn.ftz.f32 	%f32, %f31, %f30, %f25;
	add.s32 	%r62, %r97, 64;
	shr.s32 	%r63, %r62, 31;
	shr.u32 	%r64, %r63, 27;
	add.s32 	%r65, %r62, %r64;
	shr.s32 	%r66, %r65, 5;
	add.s32 	%r67, %r66, %r3;
	mul.wide.s32 	%rd39, %r67, 4;
	add.s64 	%rd40, %rd4, %rd39;
	add.s32 	%r68, %r98, -32;
	cvt.u64.u32 	%rd41, %r68;
	add.s64 	%rd42, %rd3, %rd41;
	ld.global.u8 	%rs4, [%rd42];
	cvt.rn.f32.u16 	%f33, %rs4;
	ld.global.f32 	%f34, [%rd40];
	mul.rn.ftz.f32 	%f35, %f34, %f33;
	add.s64 	%rd43, %rd2, %rd39;
	ld.global.f32 	%f36, [%rd43];
	sub.rn.ftz.f32 	%f37, %f35, %f36;
	add.s32 	%r69, %r99, -32;
	mul.wide.u32 	%rd44, %r69, 4;
	add.s64 	%rd45, %rd1, %rd44;
	ld.global.f32 	%f38, [%rd45];
	fma.rn.ftz.f32 	%f39, %f38, %f37, %f32;
	add.s32 	%r70, %r97, 96;
	shr.s32 	%r71, %r70, 31;
	shr.u32 	%r72, %r71, 27;
	add.s32 	%r73, %r70, %r72;
	shr.s32 	%r74, %r73, 5;
	add.s32 	%r75, %r74, %r3;
	mul.wide.s32 	%rd46, %r75, 4;
	add.s64 	%rd47, %rd4, %rd46;
	cvt.u64.u32 	%rd48, %r98;
	add.s64 	%rd49, %rd3, %rd48;
	ld.global.u8 	%rs5, [%rd49];
	cvt.rn.f32.u16 	%f40, %rs5;
	ld.global.f32 	%f41, [%rd47];
	mul.rn.ftz.f32 	%f42, %f41, %f40;
	add.s64 	%rd50, %rd2, %rd46;
	ld.global.f32 	%f43, [%rd50];
	sub.rn.ftz.f32 	%f44, %f42, %f43;
	mul.wide.u32 	%rd51, %r99, 4;
	add.s64 	%rd52, %rd1, %rd51;
	ld.global.f32 	%f45, [%rd52];
	fma.rn.ftz.f32 	%f59, %f45, %f44, %f39;
	add.s32 	%r99, %r99, 128;
	add.s32 	%r98, %r98, 128;
	add.s32 	%r97, %r97, 128;
	setp.lt.s32 	%p6, %r97, %r29;
	@%p6 bra 	$L__BB2_7;

$L__BB2_8:
	mov.b32 	%r76, %f59;
	mov.u32 	%r77, 2;
	mov.u32 	%r78, 31;
	mov.u32 	%r79, 16;
	mov.u32 	%r80, -1;
	shfl.sync.down.b32 	%r81|%p7, %r76, %r79, %r78, %r80;
	mov.b32 	%f46, %r81;
	add.ftz.f32 	%f47, %f59, %f46;
	mov.b32 	%r82, %f47;
	mov.u32 	%r83, 8;
	shfl.sync.down.b32 	%r84|%p8, %r82, %r83, %r78, %r80;
	mov.b32 	%f48, %r84;
	add.ftz.f32 	%f49, %f47, %f48;
	mov.b32 	%r85, %f49;
	mov.u32 	%r86, 4;
	shfl.sync.down.b32 	%r87|%p9, %r85, %r86, %r78, %r80;
	mov.b32 	%f50, %r87;
	add.ftz.f32 	%f51, %f49, %f50;
	mov.b32 	%r88, %f51;
	shfl.sync.down.b32 	%r89|%p10, %r88, %r77, %r78, %r80;
	mov.b32 	%f52, %r89;
	add.ftz.f32 	%f53, %f51, %f52;
	mov.b32 	%r90, %f53;
	mov.u32 	%r91, 1;
	shfl.sync.down.b32 	%r92|%p11, %r90, %r91, %r78, %r80;
	mov.b32 	%f54, %r92;
	add.ftz.f32 	%f8, %f53, %f54;
	setp.ne.s32 	%p12, %r1, 0;
	@%p12 bra 	$L__BB2_10;

	cvta.to.global.u64 	%rd53, %rd8;
	shl.b64 	%rd54, %rd5, 2;
	add.s64 	%rd55, %rd53, %rd54;
	st.global.f32 	[%rd55], %f8;

$L__BB2_10:
	ret;

}

`
