package ptx

// Generated by scripts/generate-qk-staged-ptx.sh; CUDA 12.8, sm_86.
const QKStagedPTX = `
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	q6_staged_j24_o64
// _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X has been demoted
// _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D has been demoted

.visible .entry q6_staged_j24_o64(
	.param .u64 q6_staged_j24_o64_param_0,
	.param .u64 q6_staged_j24_o64_param_1,
	.param .u64 q6_staged_j24_o64_param_2,
	.param .u64 q6_staged_j24_o64_param_3,
	.param .u64 q6_staged_j24_o64_param_4,
	.param .u32 q6_staged_j24_o64_param_5,
	.param .u32 q6_staged_j24_o64_param_6,
	.param .u32 q6_staged_j24_o64_param_7
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<153>;
	.reg .f32 	%f<705>;
	.reg .b32 	%r<2082>;
	.reg .b64 	%rd<118>;
	// demoted variable
	.shared .align 16 .b8 _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X[6144];
	// demoted variable
	.shared .align 4 .b8 _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D[1536];

	ld.param.u64 	%rd6, [q6_staged_j24_o64_param_0];
	ld.param.u64 	%rd7, [q6_staged_j24_o64_param_1];
	ld.param.u64 	%rd3, [q6_staged_j24_o64_param_2];
	ld.param.u64 	%rd4, [q6_staged_j24_o64_param_3];
	ld.param.u64 	%rd5, [q6_staged_j24_o64_param_4];
	ld.param.u32 	%r94, [q6_staged_j24_o64_param_5];
	ld.param.u32 	%r95, [q6_staged_j24_o64_param_6];
	ld.param.u32 	%r96, [q6_staged_j24_o64_param_7];
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd7;
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r97, %ctaid.x;
	shl.b32 	%r98, %r97, 6;
	shr.s32 	%r99, %r1, 31;
	shr.u32 	%r100, %r99, 30;
	add.s32 	%r101, %r1, %r100;
	shr.s32 	%r102, %r101, 2;
	add.s32 	%r2, %r98, %r102;
	mov.u32 	%r103, %ctaid.y;
	mul.lo.s32 	%r3, %r103, 24;
	shr.s32 	%r104, %r94, 31;
	shr.u32 	%r105, %r104, 28;
	add.s32 	%r106, %r94, %r105;
	shr.s32 	%r4, %r106, 4;
	setp.lt.s32 	%p2, %r94, 1;
	mov.f32 	%f657, 0f00000000;
	mov.f32 	%f658, %f657;
	mov.f32 	%f659, %f657;
	mov.f32 	%f660, %f657;
	mov.f32 	%f661, %f657;
	mov.f32 	%f662, %f657;
	mov.f32 	%f663, %f657;
	mov.f32 	%f664, %f657;
	mov.f32 	%f665, %f657;
	mov.f32 	%f666, %f657;
	mov.f32 	%f667, %f657;
	mov.f32 	%f668, %f657;
	mov.f32 	%f669, %f657;
	mov.f32 	%f670, %f657;
	mov.f32 	%f671, %f657;
	mov.f32 	%f672, %f657;
	mov.f32 	%f673, %f657;
	mov.f32 	%f674, %f657;
	mov.f32 	%f675, %f657;
	mov.f32 	%f676, %f657;
	mov.f32 	%f677, %f657;
	mov.f32 	%f678, %f657;
	mov.f32 	%f679, %f657;
	mov.f32 	%f680, %f657;
	@%p2 bra 	$L__BB0_47;

	max.s32 	%r108, %r1, 5888;
	add.s32 	%r109, %r108, 255;
	sub.s32 	%r5, %r109, %r1;
	shr.u32 	%r110, %r5, 8;
	add.s32 	%r111, %r110, 1;
	max.s32 	%r112, %r1, 128;
	add.s32 	%r113, %r112, 255;
	sub.s32 	%r6, %r113, %r1;
	shr.u32 	%r114, %r6, 8;
	add.s32 	%r115, %r114, 1;
	and.b32  	%r7, %r111, 3;
	shr.u32 	%r117, %r99, 24;
	add.s32 	%r118, %r1, %r117;
	and.b32  	%r119, %r118, -256;
	sub.s32 	%r8, %r1, %r119;
	shr.s32 	%r9, %r118, 8;
	and.b32  	%r10, %r115, 3;
	shr.u32 	%r120, %r99, 28;
	add.s32 	%r121, %r1, %r120;
	and.b32  	%r122, %r121, -16;
	sub.s32 	%r11, %r1, %r122;
	shr.s32 	%r12, %r121, 4;
	add.s32 	%r13, %r1, 256;
	shr.s32 	%r123, %r13, 31;
	shr.u32 	%r124, %r123, 24;
	add.s32 	%r125, %r13, %r124;
	shr.s32 	%r14, %r125, 8;
	and.b32  	%r126, %r125, -256;
	sub.s32 	%r15, %r13, %r126;
	shr.u32 	%r127, %r123, 28;
	add.s32 	%r128, %r13, %r127;
	shr.s32 	%r16, %r128, 4;
	and.b32  	%r129, %r128, -16;
	sub.s32 	%r17, %r13, %r129;
	add.s32 	%r18, %r1, 512;
	shr.s32 	%r130, %r18, 31;
	shr.u32 	%r131, %r130, 24;
	add.s32 	%r132, %r18, %r131;
	shr.s32 	%r19, %r132, 8;
	and.b32  	%r133, %r132, -256;
	sub.s32 	%r20, %r18, %r133;
	add.s32 	%r21, %r1, 768;
	shr.u32 	%r134, %r130, 28;
	add.s32 	%r135, %r18, %r134;
	shr.s32 	%r22, %r135, 4;
	and.b32  	%r136, %r135, -16;
	sub.s32 	%r23, %r18, %r136;
	mov.u32 	%r2070, 0;
	mov.f32 	%f657, 0f00000000;
	cvta.to.global.u64 	%rd41, %rd3;
	cvta.to.global.u64 	%rd43, %rd4;

$L__BB0_2:
	setp.gt.s32 	%p3, %r1, 6143;
	@%p3 bra 	$L__BB0_23;

	setp.eq.s32 	%p4, %r7, 0;
	mov.u32 	%r2074, %r1;
	@%p4 bra 	$L__BB0_13;

	add.s32 	%r138, %r9, %r3;
	setp.ge.s32 	%p5, %r138, %r96;
	mov.u32 	%r2071, 0;
	@%p5 bra 	$L__BB0_6;

	add.s32 	%r139, %r8, %r2070;
	mad.lo.s32 	%r141, %r138, %r94, %r139;
	cvt.s64.s32 	%rd8, %r141;
	add.s64 	%rd9, %rd1, %rd8;
	ld.global.s8 	%r2071, [%rd9];

$L__BB0_6:
	shl.b32 	%r142, %r9, 8;
	mov.u32 	%r143, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	add.s32 	%r144, %r143, %r142;
	add.s32 	%r145, %r144, %r8;
	st.shared.u8 	[%r145], %r2071;
	setp.eq.s32 	%p6, %r7, 1;
	mov.u32 	%r2074, %r13;
	@%p6 bra 	$L__BB0_13;

	add.s32 	%r147, %r14, %r3;
	setp.ge.s32 	%p7, %r147, %r96;
	mov.u32 	%r2072, 0;
	@%p7 bra 	$L__BB0_9;

	add.s32 	%r148, %r15, %r2070;
	mad.lo.s32 	%r150, %r147, %r94, %r148;
	cvt.s64.s32 	%rd10, %r150;
	add.s64 	%rd11, %rd1, %rd10;
	ld.global.s8 	%r2072, [%rd11];

$L__BB0_9:
	mov.u32 	%r2060, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	shl.b32 	%r151, %r14, 8;
	add.s32 	%r153, %r2060, %r151;
	add.s32 	%r154, %r153, %r15;
	st.shared.u8 	[%r154], %r2072;
	setp.eq.s32 	%p8, %r7, 2;
	mov.u32 	%r2074, %r18;
	@%p8 bra 	$L__BB0_13;

	add.s32 	%r156, %r19, %r3;
	setp.ge.s32 	%p9, %r156, %r96;
	mov.u32 	%r2073, 0;
	@%p9 bra 	$L__BB0_12;

	add.s32 	%r157, %r20, %r2070;
	mad.lo.s32 	%r159, %r156, %r94, %r157;
	cvt.s64.s32 	%rd12, %r159;
	add.s64 	%rd13, %rd1, %rd12;
	ld.global.s8 	%r2073, [%rd13];

$L__BB0_12:
	mov.u32 	%r2061, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	shl.b32 	%r160, %r19, 8;
	add.s32 	%r162, %r2061, %r160;
	add.s32 	%r163, %r162, %r20;
	st.shared.u8 	[%r163], %r2073;
	mov.u32 	%r2074, %r21;

$L__BB0_13:
	setp.lt.u32 	%p10, %r5, 768;
	@%p10 bra 	$L__BB0_23;

$L__BB0_14:
	shr.s32 	%r165, %r2074, 31;
	shr.u32 	%r166, %r165, 24;
	add.s32 	%r167, %r2074, %r166;
	and.b32  	%r168, %r167, -256;
	sub.s32 	%r33, %r2074, %r168;
	shr.s32 	%r34, %r167, 8;
	add.s32 	%r35, %r34, %r3;
	setp.ge.s32 	%p11, %r35, %r96;
	mov.u32 	%r2077, 0;
	mov.u32 	%r2076, %r2077;
	@%p11 bra 	$L__BB0_16;

	add.s32 	%r169, %r33, %r2070;
	mad.lo.s32 	%r170, %r35, %r94, %r169;
	cvt.s64.s32 	%rd14, %r170;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.s8 	%r2076, [%rd15];

$L__BB0_16:
	shl.b32 	%r172, %r34, 8;
	mov.u32 	%r173, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	add.s32 	%r174, %r173, %r172;
	add.s32 	%r175, %r174, %r33;
	st.shared.u8 	[%r175], %r2076;
	add.s32 	%r176, %r2074, 256;
	shr.s32 	%r177, %r176, 31;
	shr.u32 	%r178, %r177, 24;
	add.s32 	%r179, %r176, %r178;
	shr.s32 	%r38, %r179, 8;
	and.b32  	%r180, %r179, -256;
	sub.s32 	%r39, %r176, %r180;
	add.s32 	%r40, %r38, %r3;
	setp.ge.s32 	%p12, %r40, %r96;
	@%p12 bra 	$L__BB0_18;

	add.s32 	%r181, %r39, %r2070;
	mad.lo.s32 	%r182, %r40, %r94, %r181;
	cvt.s64.s32 	%rd16, %r182;
	add.s64 	%rd17, %rd1, %rd16;
	ld.global.s8 	%r2077, [%rd17];

$L__BB0_18:
	mov.u32 	%r2062, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	shl.b32 	%r184, %r38, 8;
	add.s32 	%r186, %r2062, %r184;
	add.s32 	%r187, %r186, %r39;
	mov.u32 	%r2079, 0;
	st.shared.u8 	[%r187], %r2077;
	add.s32 	%r188, %r2074, 512;
	shr.s32 	%r189, %r188, 31;
	shr.u32 	%r190, %r189, 24;
	add.s32 	%r191, %r188, %r190;
	shr.s32 	%r43, %r191, 8;
	and.b32  	%r192, %r191, -256;
	sub.s32 	%r44, %r188, %r192;
	add.s32 	%r45, %r43, %r3;
	setp.ge.s32 	%p13, %r45, %r96;
	mov.u32 	%r2078, %r2079;
	@%p13 bra 	$L__BB0_20;

	add.s32 	%r193, %r44, %r2070;
	mad.lo.s32 	%r194, %r45, %r94, %r193;
	cvt.s64.s32 	%rd18, %r194;
	add.s64 	%rd19, %rd1, %rd18;
	ld.global.s8 	%r2078, [%rd19];

$L__BB0_20:
	mov.u32 	%r2063, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	shl.b32 	%r196, %r43, 8;
	add.s32 	%r198, %r2063, %r196;
	add.s32 	%r199, %r198, %r44;
	st.shared.u8 	[%r199], %r2078;
	add.s32 	%r200, %r2074, 768;
	shr.s32 	%r201, %r200, 31;
	shr.u32 	%r202, %r201, 24;
	add.s32 	%r203, %r200, %r202;
	shr.s32 	%r48, %r203, 8;
	and.b32  	%r204, %r203, -256;
	sub.s32 	%r49, %r200, %r204;
	add.s32 	%r50, %r48, %r3;
	setp.ge.s32 	%p14, %r50, %r96;
	@%p14 bra 	$L__BB0_22;

	add.s32 	%r205, %r49, %r2070;
	mad.lo.s32 	%r206, %r50, %r94, %r205;
	cvt.s64.s32 	%rd20, %r206;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.s8 	%r2079, [%rd21];

$L__BB0_22:
	mov.u32 	%r2064, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	shl.b32 	%r207, %r48, 8;
	add.s32 	%r209, %r2064, %r207;
	add.s32 	%r210, %r209, %r49;
	st.shared.u8 	[%r210], %r2079;
	add.s32 	%r53, %r2074, 1024;
	setp.lt.s32 	%p15, %r2074, 5120;
	mov.u32 	%r2074, %r53;
	@%p15 bra 	$L__BB0_14;

$L__BB0_23:
	setp.gt.s32 	%p16, %r1, 383;
	@%p16 bra 	$L__BB0_44;

	setp.eq.s32 	%p17, %r10, 0;
	mov.u32 	%r2080, %r1;
	@%p17 bra 	$L__BB0_34;

	add.s32 	%r211, %r12, %r3;
	setp.ge.s32 	%p18, %r211, %r96;
	mov.f32 	%f650, 0f00000000;
	@%p18 bra 	$L__BB0_27;

	shr.u32 	%r2067, %r2070, 4;
	add.s32 	%r212, %r11, %r2067;
	mad.lo.s32 	%r214, %r211, %r4, %r212;
	mul.wide.s32 	%rd22, %r214, 4;
	add.s64 	%rd23, %rd2, %rd22;
	ld.global.f32 	%f650, [%rd23];

$L__BB0_27:
	shl.b32 	%r215, %r12, 6;
	mov.u32 	%r216, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	add.s32 	%r217, %r216, %r215;
	shl.b32 	%r218, %r11, 2;
	add.s32 	%r219, %r217, %r218;
	st.shared.f32 	[%r219], %f650;
	setp.eq.s32 	%p19, %r10, 1;
	mov.u32 	%r2080, %r13;
	@%p19 bra 	$L__BB0_34;

	add.s32 	%r220, %r16, %r3;
	setp.ge.s32 	%p20, %r220, %r96;
	mov.f32 	%f651, 0f00000000;
	@%p20 bra 	$L__BB0_30;

	shr.u32 	%r2066, %r2070, 4;
	add.s32 	%r221, %r17, %r2066;
	mad.lo.s32 	%r223, %r220, %r4, %r221;
	mul.wide.s32 	%rd24, %r223, 4;
	add.s64 	%rd25, %rd2, %rd24;
	ld.global.f32 	%f651, [%rd25];

$L__BB0_30:
	mov.u32 	%r2068, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	shl.b32 	%r224, %r16, 6;
	add.s32 	%r226, %r2068, %r224;
	shl.b32 	%r227, %r17, 2;
	add.s32 	%r228, %r226, %r227;
	st.shared.f32 	[%r228], %f651;
	setp.eq.s32 	%p21, %r10, 2;
	mov.u32 	%r2080, %r18;
	@%p21 bra 	$L__BB0_34;

	add.s32 	%r229, %r22, %r3;
	setp.ge.s32 	%p22, %r229, %r96;
	mov.f32 	%f652, 0f00000000;
	@%p22 bra 	$L__BB0_33;

	shr.u32 	%r2065, %r2070, 4;
	add.s32 	%r230, %r23, %r2065;
	mad.lo.s32 	%r232, %r229, %r4, %r230;
	mul.wide.s32 	%rd26, %r232, 4;
	add.s64 	%rd27, %rd2, %rd26;
	ld.global.f32 	%f652, [%rd27];

$L__BB0_33:
	mov.u32 	%r2069, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	shl.b32 	%r233, %r22, 6;
	add.s32 	%r235, %r2069, %r233;
	shl.b32 	%r236, %r23, 2;
	add.s32 	%r237, %r235, %r236;
	st.shared.f32 	[%r237], %f652;
	mov.u32 	%r2080, %r21;

$L__BB0_34:
	setp.lt.u32 	%p23, %r6, 768;
	@%p23 bra 	$L__BB0_44;

$L__BB0_35:
	shr.s32 	%r238, %r2080, 31;
	shr.u32 	%r239, %r238, 28;
	add.s32 	%r240, %r2080, %r239;
	and.b32  	%r241, %r240, -16;
	sub.s32 	%r57, %r2080, %r241;
	shr.s32 	%r58, %r240, 4;
	add.s32 	%r59, %r58, %r3;
	setp.ge.s32 	%p24, %r59, %r96;
	mov.f32 	%f654, 0f00000000;
	mov.f32 	%f653, %f654;
	@%p24 bra 	$L__BB0_37;

	shr.u32 	%r2057, %r2070, 4;
	add.s32 	%r242, %r57, %r2057;
	mad.lo.s32 	%r243, %r59, %r4, %r242;
	mul.wide.s32 	%rd28, %r243, 4;
	add.s64 	%rd29, %rd2, %rd28;
	ld.global.f32 	%f653, [%rd29];

$L__BB0_37:
	shl.b32 	%r244, %r58, 6;
	mov.u32 	%r245, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	add.s32 	%r246, %r245, %r244;
	shl.b32 	%r247, %r57, 2;
	add.s32 	%r248, %r246, %r247;
	st.shared.f32 	[%r248], %f653;
	add.s32 	%r249, %r2080, 256;
	shr.s32 	%r250, %r249, 31;
	shr.u32 	%r251, %r250, 28;
	add.s32 	%r252, %r249, %r251;
	shr.s32 	%r60, %r252, 4;
	and.b32  	%r253, %r252, -16;
	sub.s32 	%r61, %r249, %r253;
	add.s32 	%r62, %r60, %r3;
	setp.ge.s32 	%p25, %r62, %r96;
	@%p25 bra 	$L__BB0_39;

	shr.u32 	%r2056, %r2070, 4;
	add.s32 	%r254, %r61, %r2056;
	mad.lo.s32 	%r255, %r62, %r4, %r254;
	mul.wide.s32 	%rd30, %r255, 4;
	add.s64 	%rd31, %rd2, %rd30;
	ld.global.f32 	%f654, [%rd31];

$L__BB0_39:
	mov.u32 	%r2055, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	shl.b32 	%r256, %r60, 6;
	add.s32 	%r258, %r2055, %r256;
	shl.b32 	%r259, %r61, 2;
	add.s32 	%r260, %r258, %r259;
	st.shared.f32 	[%r260], %f654;
	add.s32 	%r261, %r2080, 512;
	shr.s32 	%r262, %r261, 31;
	shr.u32 	%r263, %r262, 28;
	add.s32 	%r264, %r261, %r263;
	shr.s32 	%r63, %r264, 4;
	and.b32  	%r265, %r264, -16;
	sub.s32 	%r64, %r261, %r265;
	add.s32 	%r65, %r63, %r3;
	setp.ge.s32 	%p26, %r65, %r96;
	mov.f32 	%f656, 0f00000000;
	mov.f32 	%f655, %f656;
	@%p26 bra 	$L__BB0_41;

	shr.u32 	%r2059, %r2070, 4;
	add.s32 	%r266, %r64, %r2059;
	mad.lo.s32 	%r267, %r65, %r4, %r266;
	mul.wide.s32 	%rd32, %r267, 4;
	add.s64 	%rd33, %rd2, %rd32;
	ld.global.f32 	%f655, [%rd33];

$L__BB0_41:
	mov.u32 	%r2053, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	shl.b32 	%r268, %r63, 6;
	add.s32 	%r270, %r2053, %r268;
	shl.b32 	%r271, %r64, 2;
	add.s32 	%r272, %r270, %r271;
	st.shared.f32 	[%r272], %f655;
	add.s32 	%r273, %r2080, 768;
	shr.s32 	%r274, %r273, 31;
	shr.u32 	%r275, %r274, 28;
	add.s32 	%r276, %r273, %r275;
	shr.s32 	%r66, %r276, 4;
	and.b32  	%r277, %r276, -16;
	sub.s32 	%r67, %r273, %r277;
	add.s32 	%r68, %r66, %r3;
	setp.ge.s32 	%p27, %r68, %r96;
	@%p27 bra 	$L__BB0_43;

	shr.u32 	%r2058, %r2070, 4;
	add.s32 	%r278, %r67, %r2058;
	mad.lo.s32 	%r279, %r68, %r4, %r278;
	mul.wide.s32 	%rd34, %r279, 4;
	add.s64 	%rd35, %rd2, %rd34;
	ld.global.f32 	%f656, [%rd35];

$L__BB0_43:
	mov.u32 	%r2054, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	shl.b32 	%r280, %r66, 6;
	add.s32 	%r282, %r2054, %r280;
	shl.b32 	%r283, %r67, 2;
	add.s32 	%r284, %r282, %r283;
	st.shared.f32 	[%r284], %f656;
	add.s32 	%r69, %r2080, 1024;
	setp.lt.s32 	%p28, %r2080, -640;
	mov.u32 	%r2080, %r69;
	@%p28 bra 	$L__BB0_35;

$L__BB0_44:
	setp.ge.s32 	%p29, %r2, %r95;
	bar.sync 	0;
	@%p29 bra 	$L__BB0_46;

	mov.u32 	%r1821, %tid.x;
	and.b32  	%r1822, %r1821, 3;
	shl.b32 	%r1823, %r1821, 4;
	and.b32  	%r1824, %r1823, 48;
	mov.u32 	%r1825, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1X;
	add.s32 	%r1826, %r1825, %r1824;
	mul.lo.s32 	%r1827, %r2, %r94;
	cvt.s64.s32 	%rd36, %r1827;
	cvt.s64.s32 	%rd37, %r2070;
	add.s64 	%rd38, %rd37, %rd36;
	shr.u32 	%r1828, %r2070, 4;
	mad.lo.s32 	%r1829, %r4, %r2, %r1828;
	cvt.u64.u32 	%rd39, %r1824;
	add.s64 	%rd40, %rd38, %rd39;
	add.s64 	%rd42, %rd41, %rd40;
	ld.global.u32 	%r286, [%rd42];
	ld.global.u32 	%r290, [%rd42+4];
	ld.global.u32 	%r294, [%rd42+8];
	ld.global.u32 	%r298, [%rd42+12];
	add.s32 	%r1830, %r1829, %r1822;
	mul.wide.s32 	%rd44, %r1830, 4;
	add.s64 	%rd45, %rd43, %rd44;
	ld.global.f32 	%f190, [%rd45];
	ld.shared.u32 	%r287, [%r1826];
	mov.u32 	%r1808, 0;
	// begin inline asm
	dp4a.s32.s32 %r285, %r286, %r287, %r1808;
	// end inline asm
	ld.shared.u32 	%r291, [%r1826+4];
	// begin inline asm
	dp4a.s32.s32 %r289, %r290, %r291, %r285;
	// end inline asm
	ld.shared.u32 	%r295, [%r1826+8];
	// begin inline asm
	dp4a.s32.s32 %r293, %r294, %r295, %r289;
	// end inline asm
	ld.shared.u32 	%r299, [%r1826+12];
	// begin inline asm
	dp4a.s32.s32 %r297, %r298, %r299, %r293;
	// end inline asm
	cvt.rn.f32.s32 	%f191, %r297;
	mul.rn.ftz.f32 	%f192, %f190, %f191;
	shl.b32 	%r1831, %r1821, 2;
	and.b32  	%r1832, %r1831, 12;
	mov.u32 	%r1833, _ZZ6stagedILi6ELi24ELi64EEvPKaPKfPKiS1_S3_S3_PfiiiE1D;
	add.s32 	%r1834, %r1833, %r1832;
	ld.shared.f32 	%f193, [%r1834];
	fma.rn.ftz.f32 	%f194, %f193, %f192, %f676;
	ld.shared.u32 	%r303, [%r1826+256];
	// begin inline asm
	dp4a.s32.s32 %r301, %r286, %r303, %r1808;
	// end inline asm
	ld.shared.u32 	%r307, [%r1826+260];
	// begin inline asm
	dp4a.s32.s32 %r305, %r290, %r307, %r301;
	// end inline asm
	ld.shared.u32 	%r311, [%r1826+264];
	// begin inline asm
	dp4a.s32.s32 %r309, %r294, %r311, %r305;
	// end inline asm
	ld.shared.u32 	%r315, [%r1826+268];
	// begin inline asm
	dp4a.s32.s32 %r313, %r298, %r315, %r309;
	// end inline asm
	cvt.rn.f32.s32 	%f195, %r313;
	mul.rn.ftz.f32 	%f196, %f190, %f195;
	ld.shared.f32 	%f197, [%r1834+64];
	fma.rn.ftz.f32 	%f198, %f197, %f196, %f675;
	ld.shared.u32 	%r319, [%r1826+512];
	// begin inline asm
	dp4a.s32.s32 %r317, %r286, %r319, %r1808;
	// end inline asm
	ld.shared.u32 	%r323, [%r1826+516];
	// begin inline asm
	dp4a.s32.s32 %r321, %r290, %r323, %r317;
	// end inline asm
	ld.shared.u32 	%r327, [%r1826+520];
	// begin inline asm
	dp4a.s32.s32 %r325, %r294, %r327, %r321;
	// end inline asm
	ld.shared.u32 	%r331, [%r1826+524];
	// begin inline asm
	dp4a.s32.s32 %r329, %r298, %r331, %r325;
	// end inline asm
	cvt.rn.f32.s32 	%f199, %r329;
	mul.rn.ftz.f32 	%f200, %f190, %f199;
	ld.shared.f32 	%f201, [%r1834+128];
	fma.rn.ftz.f32 	%f202, %f201, %f200, %f674;
	ld.shared.u32 	%r335, [%r1826+768];
	// begin inline asm
	dp4a.s32.s32 %r333, %r286, %r335, %r1808;
	// end inline asm
	ld.shared.u32 	%r339, [%r1826+772];
	// begin inline asm
	dp4a.s32.s32 %r337, %r290, %r339, %r333;
	// end inline asm
	ld.shared.u32 	%r343, [%r1826+776];
	// begin inline asm
	dp4a.s32.s32 %r341, %r294, %r343, %r337;
	// end inline asm
	ld.shared.u32 	%r347, [%r1826+780];
	// begin inline asm
	dp4a.s32.s32 %r345, %r298, %r347, %r341;
	// end inline asm
	cvt.rn.f32.s32 	%f203, %r345;
	mul.rn.ftz.f32 	%f204, %f190, %f203;
	ld.shared.f32 	%f205, [%r1834+192];
	fma.rn.ftz.f32 	%f206, %f205, %f204, %f673;
	ld.shared.u32 	%r351, [%r1826+1024];
	// begin inline asm
	dp4a.s32.s32 %r349, %r286, %r351, %r1808;
	// end inline asm
	ld.shared.u32 	%r355, [%r1826+1028];
	// begin inline asm
	dp4a.s32.s32 %r353, %r290, %r355, %r349;
	// end inline asm
	ld.shared.u32 	%r359, [%r1826+1032];
	// begin inline asm
	dp4a.s32.s32 %r357, %r294, %r359, %r353;
	// end inline asm
	ld.shared.u32 	%r363, [%r1826+1036];
	// begin inline asm
	dp4a.s32.s32 %r361, %r298, %r363, %r357;
	// end inline asm
	cvt.rn.f32.s32 	%f207, %r361;
	mul.rn.ftz.f32 	%f208, %f190, %f207;
	ld.shared.f32 	%f209, [%r1834+256];
	fma.rn.ftz.f32 	%f210, %f209, %f208, %f672;
	ld.shared.u32 	%r367, [%r1826+1280];
	// begin inline asm
	dp4a.s32.s32 %r365, %r286, %r367, %r1808;
	// end inline asm
	ld.shared.u32 	%r371, [%r1826+1284];
	// begin inline asm
	dp4a.s32.s32 %r369, %r290, %r371, %r365;
	// end inline asm
	ld.shared.u32 	%r375, [%r1826+1288];
	// begin inline asm
	dp4a.s32.s32 %r373, %r294, %r375, %r369;
	// end inline asm
	ld.shared.u32 	%r379, [%r1826+1292];
	// begin inline asm
	dp4a.s32.s32 %r377, %r298, %r379, %r373;
	// end inline asm
	cvt.rn.f32.s32 	%f211, %r377;
	mul.rn.ftz.f32 	%f212, %f190, %f211;
	ld.shared.f32 	%f213, [%r1834+320];
	fma.rn.ftz.f32 	%f214, %f213, %f212, %f671;
	ld.shared.u32 	%r383, [%r1826+1536];
	// begin inline asm
	dp4a.s32.s32 %r381, %r286, %r383, %r1808;
	// end inline asm
	ld.shared.u32 	%r387, [%r1826+1540];
	// begin inline asm
	dp4a.s32.s32 %r385, %r290, %r387, %r381;
	// end inline asm
	ld.shared.u32 	%r391, [%r1826+1544];
	// begin inline asm
	dp4a.s32.s32 %r389, %r294, %r391, %r385;
	// end inline asm
	ld.shared.u32 	%r395, [%r1826+1548];
	// begin inline asm
	dp4a.s32.s32 %r393, %r298, %r395, %r389;
	// end inline asm
	cvt.rn.f32.s32 	%f215, %r393;
	mul.rn.ftz.f32 	%f216, %f190, %f215;
	ld.shared.f32 	%f217, [%r1834+384];
	fma.rn.ftz.f32 	%f218, %f217, %f216, %f670;
	ld.shared.u32 	%r399, [%r1826+1792];
	// begin inline asm
	dp4a.s32.s32 %r397, %r286, %r399, %r1808;
	// end inline asm
	ld.shared.u32 	%r403, [%r1826+1796];
	// begin inline asm
	dp4a.s32.s32 %r401, %r290, %r403, %r397;
	// end inline asm
	ld.shared.u32 	%r407, [%r1826+1800];
	// begin inline asm
	dp4a.s32.s32 %r405, %r294, %r407, %r401;
	// end inline asm
	ld.shared.u32 	%r411, [%r1826+1804];
	// begin inline asm
	dp4a.s32.s32 %r409, %r298, %r411, %r405;
	// end inline asm
	cvt.rn.f32.s32 	%f219, %r409;
	mul.rn.ftz.f32 	%f220, %f190, %f219;
	ld.shared.f32 	%f221, [%r1834+448];
	fma.rn.ftz.f32 	%f222, %f221, %f220, %f669;
	ld.shared.u32 	%r415, [%r1826+2048];
	// begin inline asm
	dp4a.s32.s32 %r413, %r286, %r415, %r1808;
	// end inline asm
	ld.shared.u32 	%r419, [%r1826+2052];
	// begin inline asm
	dp4a.s32.s32 %r417, %r290, %r419, %r413;
	// end inline asm
	ld.shared.u32 	%r423, [%r1826+2056];
	// begin inline asm
	dp4a.s32.s32 %r421, %r294, %r423, %r417;
	// end inline asm
	ld.shared.u32 	%r427, [%r1826+2060];
	// begin inline asm
	dp4a.s32.s32 %r425, %r298, %r427, %r421;
	// end inline asm
	cvt.rn.f32.s32 	%f223, %r425;
	mul.rn.ftz.f32 	%f224, %f190, %f223;
	ld.shared.f32 	%f225, [%r1834+512];
	fma.rn.ftz.f32 	%f226, %f225, %f224, %f668;
	ld.shared.u32 	%r431, [%r1826+2304];
	// begin inline asm
	dp4a.s32.s32 %r429, %r286, %r431, %r1808;
	// end inline asm
	ld.shared.u32 	%r435, [%r1826+2308];
	// begin inline asm
	dp4a.s32.s32 %r433, %r290, %r435, %r429;
	// end inline asm
	ld.shared.u32 	%r439, [%r1826+2312];
	// begin inline asm
	dp4a.s32.s32 %r437, %r294, %r439, %r433;
	// end inline asm
	ld.shared.u32 	%r443, [%r1826+2316];
	// begin inline asm
	dp4a.s32.s32 %r441, %r298, %r443, %r437;
	// end inline asm
	cvt.rn.f32.s32 	%f227, %r441;
	mul.rn.ftz.f32 	%f228, %f190, %f227;
	ld.shared.f32 	%f229, [%r1834+576];
	fma.rn.ftz.f32 	%f230, %f229, %f228, %f667;
	ld.shared.u32 	%r447, [%r1826+2560];
	// begin inline asm
	dp4a.s32.s32 %r445, %r286, %r447, %r1808;
	// end inline asm
	ld.shared.u32 	%r451, [%r1826+2564];
	// begin inline asm
	dp4a.s32.s32 %r449, %r290, %r451, %r445;
	// end inline asm
	ld.shared.u32 	%r455, [%r1826+2568];
	// begin inline asm
	dp4a.s32.s32 %r453, %r294, %r455, %r449;
	// end inline asm
	ld.shared.u32 	%r459, [%r1826+2572];
	// begin inline asm
	dp4a.s32.s32 %r457, %r298, %r459, %r453;
	// end inline asm
	cvt.rn.f32.s32 	%f231, %r457;
	mul.rn.ftz.f32 	%f232, %f190, %f231;
	ld.shared.f32 	%f233, [%r1834+640];
	fma.rn.ftz.f32 	%f234, %f233, %f232, %f666;
	ld.shared.u32 	%r463, [%r1826+2816];
	// begin inline asm
	dp4a.s32.s32 %r461, %r286, %r463, %r1808;
	// end inline asm
	ld.shared.u32 	%r467, [%r1826+2820];
	// begin inline asm
	dp4a.s32.s32 %r465, %r290, %r467, %r461;
	// end inline asm
	ld.shared.u32 	%r471, [%r1826+2824];
	// begin inline asm
	dp4a.s32.s32 %r469, %r294, %r471, %r465;
	// end inline asm
	ld.shared.u32 	%r475, [%r1826+2828];
	// begin inline asm
	dp4a.s32.s32 %r473, %r298, %r475, %r469;
	// end inline asm
	cvt.rn.f32.s32 	%f235, %r473;
	mul.rn.ftz.f32 	%f236, %f190, %f235;
	ld.shared.f32 	%f237, [%r1834+704];
	fma.rn.ftz.f32 	%f238, %f237, %f236, %f665;
	ld.shared.u32 	%r479, [%r1826+3072];
	// begin inline asm
	dp4a.s32.s32 %r477, %r286, %r479, %r1808;
	// end inline asm
	ld.shared.u32 	%r483, [%r1826+3076];
	// begin inline asm
	dp4a.s32.s32 %r481, %r290, %r483, %r477;
	// end inline asm
	ld.shared.u32 	%r487, [%r1826+3080];
	// begin inline asm
	dp4a.s32.s32 %r485, %r294, %r487, %r481;
	// end inline asm
	ld.shared.u32 	%r491, [%r1826+3084];
	// begin inline asm
	dp4a.s32.s32 %r489, %r298, %r491, %r485;
	// end inline asm
	cvt.rn.f32.s32 	%f239, %r489;
	mul.rn.ftz.f32 	%f240, %f190, %f239;
	ld.shared.f32 	%f241, [%r1834+768];
	fma.rn.ftz.f32 	%f242, %f241, %f240, %f664;
	ld.shared.u32 	%r495, [%r1826+3328];
	// begin inline asm
	dp4a.s32.s32 %r493, %r286, %r495, %r1808;
	// end inline asm
	ld.shared.u32 	%r499, [%r1826+3332];
	// begin inline asm
	dp4a.s32.s32 %r497, %r290, %r499, %r493;
	// end inline asm
	ld.shared.u32 	%r503, [%r1826+3336];
	// begin inline asm
	dp4a.s32.s32 %r501, %r294, %r503, %r497;
	// end inline asm
	ld.shared.u32 	%r507, [%r1826+3340];
	// begin inline asm
	dp4a.s32.s32 %r505, %r298, %r507, %r501;
	// end inline asm
	cvt.rn.f32.s32 	%f243, %r505;
	mul.rn.ftz.f32 	%f244, %f190, %f243;
	ld.shared.f32 	%f245, [%r1834+832];
	fma.rn.ftz.f32 	%f246, %f245, %f244, %f663;
	ld.shared.u32 	%r511, [%r1826+3584];
	// begin inline asm
	dp4a.s32.s32 %r509, %r286, %r511, %r1808;
	// end inline asm
	ld.shared.u32 	%r515, [%r1826+3588];
	// begin inline asm
	dp4a.s32.s32 %r513, %r290, %r515, %r509;
	// end inline asm
	ld.shared.u32 	%r519, [%r1826+3592];
	// begin inline asm
	dp4a.s32.s32 %r517, %r294, %r519, %r513;
	// end inline asm
	ld.shared.u32 	%r523, [%r1826+3596];
	// begin inline asm
	dp4a.s32.s32 %r521, %r298, %r523, %r517;
	// end inline asm
	cvt.rn.f32.s32 	%f247, %r521;
	mul.rn.ftz.f32 	%f248, %f190, %f247;
	ld.shared.f32 	%f249, [%r1834+896];
	fma.rn.ftz.f32 	%f250, %f249, %f248, %f662;
	ld.shared.u32 	%r527, [%r1826+3840];
	// begin inline asm
	dp4a.s32.s32 %r525, %r286, %r527, %r1808;
	// end inline asm
	ld.shared.u32 	%r531, [%r1826+3844];
	// begin inline asm
	dp4a.s32.s32 %r529, %r290, %r531, %r525;
	// end inline asm
	ld.shared.u32 	%r535, [%r1826+3848];
	// begin inline asm
	dp4a.s32.s32 %r533, %r294, %r535, %r529;
	// end inline asm
	ld.shared.u32 	%r539, [%r1826+3852];
	// begin inline asm
	dp4a.s32.s32 %r537, %r298, %r539, %r533;
	// end inline asm
	cvt.rn.f32.s32 	%f251, %r537;
	mul.rn.ftz.f32 	%f252, %f190, %f251;
	ld.shared.f32 	%f253, [%r1834+960];
	fma.rn.ftz.f32 	%f254, %f253, %f252, %f661;
	ld.shared.u32 	%r543, [%r1826+4096];
	// begin inline asm
	dp4a.s32.s32 %r541, %r286, %r543, %r1808;
	// end inline asm
	ld.shared.u32 	%r547, [%r1826+4100];
	// begin inline asm
	dp4a.s32.s32 %r545, %r290, %r547, %r541;
	// end inline asm
	ld.shared.u32 	%r551, [%r1826+4104];
	// begin inline asm
	dp4a.s32.s32 %r549, %r294, %r551, %r545;
	// end inline asm
	ld.shared.u32 	%r555, [%r1826+4108];
	// begin inline asm
	dp4a.s32.s32 %r553, %r298, %r555, %r549;
	// end inline asm
	cvt.rn.f32.s32 	%f255, %r553;
	mul.rn.ftz.f32 	%f256, %f190, %f255;
	ld.shared.f32 	%f257, [%r1834+1024];
	fma.rn.ftz.f32 	%f258, %f257, %f256, %f660;
	ld.shared.u32 	%r559, [%r1826+4352];
	// begin inline asm
	dp4a.s32.s32 %r557, %r286, %r559, %r1808;
	// end inline asm
	ld.shared.u32 	%r563, [%r1826+4356];
	// begin inline asm
	dp4a.s32.s32 %r561, %r290, %r563, %r557;
	// end inline asm
	ld.shared.u32 	%r567, [%r1826+4360];
	// begin inline asm
	dp4a.s32.s32 %r565, %r294, %r567, %r561;
	// end inline asm
	ld.shared.u32 	%r571, [%r1826+4364];
	// begin inline asm
	dp4a.s32.s32 %r569, %r298, %r571, %r565;
	// end inline asm
	cvt.rn.f32.s32 	%f259, %r569;
	mul.rn.ftz.f32 	%f260, %f190, %f259;
	ld.shared.f32 	%f261, [%r1834+1088];
	fma.rn.ftz.f32 	%f262, %f261, %f260, %f659;
	ld.shared.u32 	%r575, [%r1826+4608];
	// begin inline asm
	dp4a.s32.s32 %r573, %r286, %r575, %r1808;
	// end inline asm
	ld.shared.u32 	%r579, [%r1826+4612];
	// begin inline asm
	dp4a.s32.s32 %r577, %r290, %r579, %r573;
	// end inline asm
	ld.shared.u32 	%r583, [%r1826+4616];
	// begin inline asm
	dp4a.s32.s32 %r581, %r294, %r583, %r577;
	// end inline asm
	ld.shared.u32 	%r587, [%r1826+4620];
	// begin inline asm
	dp4a.s32.s32 %r585, %r298, %r587, %r581;
	// end inline asm
	cvt.rn.f32.s32 	%f263, %r585;
	mul.rn.ftz.f32 	%f264, %f190, %f263;
	ld.shared.f32 	%f265, [%r1834+1152];
	fma.rn.ftz.f32 	%f266, %f265, %f264, %f658;
	ld.shared.u32 	%r591, [%r1826+4864];
	// begin inline asm
	dp4a.s32.s32 %r589, %r286, %r591, %r1808;
	// end inline asm
	ld.shared.u32 	%r595, [%r1826+4868];
	// begin inline asm
	dp4a.s32.s32 %r593, %r290, %r595, %r589;
	// end inline asm
	ld.shared.u32 	%r599, [%r1826+4872];
	// begin inline asm
	dp4a.s32.s32 %r597, %r294, %r599, %r593;
	// end inline asm
	ld.shared.u32 	%r603, [%r1826+4876];
	// begin inline asm
	dp4a.s32.s32 %r601, %r298, %r603, %r597;
	// end inline asm
	cvt.rn.f32.s32 	%f267, %r601;
	mul.rn.ftz.f32 	%f268, %f190, %f267;
	ld.shared.f32 	%f269, [%r1834+1216];
	fma.rn.ftz.f32 	%f270, %f269, %f268, %f657;
	ld.shared.u32 	%r607, [%r1826+5120];
	// begin inline asm
	dp4a.s32.s32 %r605, %r286, %r607, %r1808;
	// end inline asm
	ld.shared.u32 	%r611, [%r1826+5124];
	// begin inline asm
	dp4a.s32.s32 %r609, %r290, %r611, %r605;
	// end inline asm
	ld.shared.u32 	%r615, [%r1826+5128];
	// begin inline asm
	dp4a.s32.s32 %r613, %r294, %r615, %r609;
	// end inline asm
	ld.shared.u32 	%r619, [%r1826+5132];
	// begin inline asm
	dp4a.s32.s32 %r617, %r298, %r619, %r613;
	// end inline asm
	cvt.rn.f32.s32 	%f271, %r617;
	mul.rn.ftz.f32 	%f272, %f190, %f271;
	ld.shared.f32 	%f273, [%r1834+1280];
	fma.rn.ftz.f32 	%f274, %f273, %f272, %f677;
	ld.shared.u32 	%r623, [%r1826+5376];
	// begin inline asm
	dp4a.s32.s32 %r621, %r286, %r623, %r1808;
	// end inline asm
	ld.shared.u32 	%r627, [%r1826+5380];
	// begin inline asm
	dp4a.s32.s32 %r625, %r290, %r627, %r621;
	// end inline asm
	ld.shared.u32 	%r631, [%r1826+5384];
	// begin inline asm
	dp4a.s32.s32 %r629, %r294, %r631, %r625;
	// end inline asm
	ld.shared.u32 	%r635, [%r1826+5388];
	// begin inline asm
	dp4a.s32.s32 %r633, %r298, %r635, %r629;
	// end inline asm
	cvt.rn.f32.s32 	%f275, %r633;
	mul.rn.ftz.f32 	%f276, %f190, %f275;
	ld.shared.f32 	%f277, [%r1834+1344];
	fma.rn.ftz.f32 	%f278, %f277, %f276, %f678;
	ld.shared.u32 	%r639, [%r1826+5632];
	// begin inline asm
	dp4a.s32.s32 %r637, %r286, %r639, %r1808;
	// end inline asm
	ld.shared.u32 	%r643, [%r1826+5636];
	// begin inline asm
	dp4a.s32.s32 %r641, %r290, %r643, %r637;
	// end inline asm
	ld.shared.u32 	%r647, [%r1826+5640];
	// begin inline asm
	dp4a.s32.s32 %r645, %r294, %r647, %r641;
	// end inline asm
	ld.shared.u32 	%r651, [%r1826+5644];
	// begin inline asm
	dp4a.s32.s32 %r649, %r298, %r651, %r645;
	// end inline asm
	cvt.rn.f32.s32 	%f279, %r649;
	mul.rn.ftz.f32 	%f280, %f190, %f279;
	ld.shared.f32 	%f281, [%r1834+1408];
	fma.rn.ftz.f32 	%f282, %f281, %f280, %f679;
	ld.shared.u32 	%r655, [%r1826+5888];
	// begin inline asm
	dp4a.s32.s32 %r653, %r286, %r655, %r1808;
	// end inline asm
	ld.shared.u32 	%r659, [%r1826+5892];
	// begin inline asm
	dp4a.s32.s32 %r657, %r290, %r659, %r653;
	// end inline asm
	ld.shared.u32 	%r663, [%r1826+5896];
	// begin inline asm
	dp4a.s32.s32 %r661, %r294, %r663, %r657;
	// end inline asm
	ld.shared.u32 	%r667, [%r1826+5900];
	// begin inline asm
	dp4a.s32.s32 %r665, %r298, %r667, %r661;
	// end inline asm
	cvt.rn.f32.s32 	%f283, %r665;
	mul.rn.ftz.f32 	%f284, %f190, %f283;
	ld.shared.f32 	%f285, [%r1834+1472];
	fma.rn.ftz.f32 	%f286, %f285, %f284, %f680;
	ld.global.u32 	%r1038, [%rd42+64];
	ld.global.u32 	%r1042, [%rd42+68];
	ld.global.u32 	%r1046, [%rd42+72];
	ld.global.u32 	%r1050, [%rd42+76];
	ld.global.f32 	%f287, [%rd45+16];
	ld.shared.u32 	%r671, [%r1826+64];
	// begin inline asm
	dp4a.s32.s32 %r669, %r1038, %r671, %r1808;
	// end inline asm
	ld.shared.u32 	%r675, [%r1826+68];
	// begin inline asm
	dp4a.s32.s32 %r673, %r1042, %r675, %r669;
	// end inline asm
	ld.shared.u32 	%r679, [%r1826+72];
	// begin inline asm
	dp4a.s32.s32 %r677, %r1046, %r679, %r673;
	// end inline asm
	ld.shared.u32 	%r683, [%r1826+76];
	// begin inline asm
	dp4a.s32.s32 %r681, %r1050, %r683, %r677;
	// end inline asm
	cvt.rn.f32.s32 	%f288, %r681;
	mul.rn.ftz.f32 	%f289, %f287, %f288;
	ld.shared.f32 	%f290, [%r1834+16];
	fma.rn.ftz.f32 	%f291, %f290, %f289, %f194;
	ld.shared.u32 	%r687, [%r1826+320];
	// begin inline asm
	dp4a.s32.s32 %r685, %r1038, %r687, %r1808;
	// end inline asm
	ld.shared.u32 	%r691, [%r1826+324];
	// begin inline asm
	dp4a.s32.s32 %r689, %r1042, %r691, %r685;
	// end inline asm
	ld.shared.u32 	%r695, [%r1826+328];
	// begin inline asm
	dp4a.s32.s32 %r693, %r1046, %r695, %r689;
	// end inline asm
	ld.shared.u32 	%r699, [%r1826+332];
	// begin inline asm
	dp4a.s32.s32 %r697, %r1050, %r699, %r693;
	// end inline asm
	cvt.rn.f32.s32 	%f292, %r697;
	mul.rn.ftz.f32 	%f293, %f287, %f292;
	ld.shared.f32 	%f294, [%r1834+80];
	fma.rn.ftz.f32 	%f295, %f294, %f293, %f198;
	ld.shared.u32 	%r703, [%r1826+576];
	// begin inline asm
	dp4a.s32.s32 %r701, %r1038, %r703, %r1808;
	// end inline asm
	ld.shared.u32 	%r707, [%r1826+580];
	// begin inline asm
	dp4a.s32.s32 %r705, %r1042, %r707, %r701;
	// end inline asm
	ld.shared.u32 	%r711, [%r1826+584];
	// begin inline asm
	dp4a.s32.s32 %r709, %r1046, %r711, %r705;
	// end inline asm
	ld.shared.u32 	%r715, [%r1826+588];
	// begin inline asm
	dp4a.s32.s32 %r713, %r1050, %r715, %r709;
	// end inline asm
	cvt.rn.f32.s32 	%f296, %r713;
	mul.rn.ftz.f32 	%f297, %f287, %f296;
	ld.shared.f32 	%f298, [%r1834+144];
	fma.rn.ftz.f32 	%f299, %f298, %f297, %f202;
	ld.shared.u32 	%r719, [%r1826+832];
	// begin inline asm
	dp4a.s32.s32 %r717, %r1038, %r719, %r1808;
	// end inline asm
	ld.shared.u32 	%r723, [%r1826+836];
	// begin inline asm
	dp4a.s32.s32 %r721, %r1042, %r723, %r717;
	// end inline asm
	ld.shared.u32 	%r727, [%r1826+840];
	// begin inline asm
	dp4a.s32.s32 %r725, %r1046, %r727, %r721;
	// end inline asm
	ld.shared.u32 	%r731, [%r1826+844];
	// begin inline asm
	dp4a.s32.s32 %r729, %r1050, %r731, %r725;
	// end inline asm
	cvt.rn.f32.s32 	%f300, %r729;
	mul.rn.ftz.f32 	%f301, %f287, %f300;
	ld.shared.f32 	%f302, [%r1834+208];
	fma.rn.ftz.f32 	%f303, %f302, %f301, %f206;
	ld.shared.u32 	%r735, [%r1826+1088];
	// begin inline asm
	dp4a.s32.s32 %r733, %r1038, %r735, %r1808;
	// end inline asm
	ld.shared.u32 	%r739, [%r1826+1092];
	// begin inline asm
	dp4a.s32.s32 %r737, %r1042, %r739, %r733;
	// end inline asm
	ld.shared.u32 	%r743, [%r1826+1096];
	// begin inline asm
	dp4a.s32.s32 %r741, %r1046, %r743, %r737;
	// end inline asm
	ld.shared.u32 	%r747, [%r1826+1100];
	// begin inline asm
	dp4a.s32.s32 %r745, %r1050, %r747, %r741;
	// end inline asm
	cvt.rn.f32.s32 	%f304, %r745;
	mul.rn.ftz.f32 	%f305, %f287, %f304;
	ld.shared.f32 	%f306, [%r1834+272];
	fma.rn.ftz.f32 	%f307, %f306, %f305, %f210;
	ld.shared.u32 	%r751, [%r1826+1344];
	// begin inline asm
	dp4a.s32.s32 %r749, %r1038, %r751, %r1808;
	// end inline asm
	ld.shared.u32 	%r755, [%r1826+1348];
	// begin inline asm
	dp4a.s32.s32 %r753, %r1042, %r755, %r749;
	// end inline asm
	ld.shared.u32 	%r759, [%r1826+1352];
	// begin inline asm
	dp4a.s32.s32 %r757, %r1046, %r759, %r753;
	// end inline asm
	ld.shared.u32 	%r763, [%r1826+1356];
	// begin inline asm
	dp4a.s32.s32 %r761, %r1050, %r763, %r757;
	// end inline asm
	cvt.rn.f32.s32 	%f308, %r761;
	mul.rn.ftz.f32 	%f309, %f287, %f308;
	ld.shared.f32 	%f310, [%r1834+336];
	fma.rn.ftz.f32 	%f311, %f310, %f309, %f214;
	ld.shared.u32 	%r767, [%r1826+1600];
	// begin inline asm
	dp4a.s32.s32 %r765, %r1038, %r767, %r1808;
	// end inline asm
	ld.shared.u32 	%r771, [%r1826+1604];
	// begin inline asm
	dp4a.s32.s32 %r769, %r1042, %r771, %r765;
	// end inline asm
	ld.shared.u32 	%r775, [%r1826+1608];
	// begin inline asm
	dp4a.s32.s32 %r773, %r1046, %r775, %r769;
	// end inline asm
	ld.shared.u32 	%r779, [%r1826+1612];
	// begin inline asm
	dp4a.s32.s32 %r777, %r1050, %r779, %r773;
	// end inline asm
	cvt.rn.f32.s32 	%f312, %r777;
	mul.rn.ftz.f32 	%f313, %f287, %f312;
	ld.shared.f32 	%f314, [%r1834+400];
	fma.rn.ftz.f32 	%f315, %f314, %f313, %f218;
	ld.shared.u32 	%r783, [%r1826+1856];
	// begin inline asm
	dp4a.s32.s32 %r781, %r1038, %r783, %r1808;
	// end inline asm
	ld.shared.u32 	%r787, [%r1826+1860];
	// begin inline asm
	dp4a.s32.s32 %r785, %r1042, %r787, %r781;
	// end inline asm
	ld.shared.u32 	%r791, [%r1826+1864];
	// begin inline asm
	dp4a.s32.s32 %r789, %r1046, %r791, %r785;
	// end inline asm
	ld.shared.u32 	%r795, [%r1826+1868];
	// begin inline asm
	dp4a.s32.s32 %r793, %r1050, %r795, %r789;
	// end inline asm
	cvt.rn.f32.s32 	%f316, %r793;
	mul.rn.ftz.f32 	%f317, %f287, %f316;
	ld.shared.f32 	%f318, [%r1834+464];
	fma.rn.ftz.f32 	%f319, %f318, %f317, %f222;
	ld.shared.u32 	%r799, [%r1826+2112];
	// begin inline asm
	dp4a.s32.s32 %r797, %r1038, %r799, %r1808;
	// end inline asm
	ld.shared.u32 	%r803, [%r1826+2116];
	// begin inline asm
	dp4a.s32.s32 %r801, %r1042, %r803, %r797;
	// end inline asm
	ld.shared.u32 	%r807, [%r1826+2120];
	// begin inline asm
	dp4a.s32.s32 %r805, %r1046, %r807, %r801;
	// end inline asm
	ld.shared.u32 	%r811, [%r1826+2124];
	// begin inline asm
	dp4a.s32.s32 %r809, %r1050, %r811, %r805;
	// end inline asm
	cvt.rn.f32.s32 	%f320, %r809;
	mul.rn.ftz.f32 	%f321, %f287, %f320;
	ld.shared.f32 	%f322, [%r1834+528];
	fma.rn.ftz.f32 	%f323, %f322, %f321, %f226;
	ld.shared.u32 	%r815, [%r1826+2368];
	// begin inline asm
	dp4a.s32.s32 %r813, %r1038, %r815, %r1808;
	// end inline asm
	ld.shared.u32 	%r819, [%r1826+2372];
	// begin inline asm
	dp4a.s32.s32 %r817, %r1042, %r819, %r813;
	// end inline asm
	ld.shared.u32 	%r823, [%r1826+2376];
	// begin inline asm
	dp4a.s32.s32 %r821, %r1046, %r823, %r817;
	// end inline asm
	ld.shared.u32 	%r827, [%r1826+2380];
	// begin inline asm
	dp4a.s32.s32 %r825, %r1050, %r827, %r821;
	// end inline asm
	cvt.rn.f32.s32 	%f324, %r825;
	mul.rn.ftz.f32 	%f325, %f287, %f324;
	ld.shared.f32 	%f326, [%r1834+592];
	fma.rn.ftz.f32 	%f327, %f326, %f325, %f230;
	ld.shared.u32 	%r831, [%r1826+2624];
	// begin inline asm
	dp4a.s32.s32 %r829, %r1038, %r831, %r1808;
	// end inline asm
	ld.shared.u32 	%r835, [%r1826+2628];
	// begin inline asm
	dp4a.s32.s32 %r833, %r1042, %r835, %r829;
	// end inline asm
	ld.shared.u32 	%r839, [%r1826+2632];
	// begin inline asm
	dp4a.s32.s32 %r837, %r1046, %r839, %r833;
	// end inline asm
	ld.shared.u32 	%r843, [%r1826+2636];
	// begin inline asm
	dp4a.s32.s32 %r841, %r1050, %r843, %r837;
	// end inline asm
	cvt.rn.f32.s32 	%f328, %r841;
	mul.rn.ftz.f32 	%f329, %f287, %f328;
	ld.shared.f32 	%f330, [%r1834+656];
	fma.rn.ftz.f32 	%f331, %f330, %f329, %f234;
	ld.shared.u32 	%r847, [%r1826+2880];
	// begin inline asm
	dp4a.s32.s32 %r845, %r1038, %r847, %r1808;
	// end inline asm
	ld.shared.u32 	%r851, [%r1826+2884];
	// begin inline asm
	dp4a.s32.s32 %r849, %r1042, %r851, %r845;
	// end inline asm
	ld.shared.u32 	%r855, [%r1826+2888];
	// begin inline asm
	dp4a.s32.s32 %r853, %r1046, %r855, %r849;
	// end inline asm
	ld.shared.u32 	%r859, [%r1826+2892];
	// begin inline asm
	dp4a.s32.s32 %r857, %r1050, %r859, %r853;
	// end inline asm
	cvt.rn.f32.s32 	%f332, %r857;
	mul.rn.ftz.f32 	%f333, %f287, %f332;
	ld.shared.f32 	%f334, [%r1834+720];
	fma.rn.ftz.f32 	%f335, %f334, %f333, %f238;
	ld.shared.u32 	%r863, [%r1826+3136];
	// begin inline asm
	dp4a.s32.s32 %r861, %r1038, %r863, %r1808;
	// end inline asm
	ld.shared.u32 	%r867, [%r1826+3140];
	// begin inline asm
	dp4a.s32.s32 %r865, %r1042, %r867, %r861;
	// end inline asm
	ld.shared.u32 	%r871, [%r1826+3144];
	// begin inline asm
	dp4a.s32.s32 %r869, %r1046, %r871, %r865;
	// end inline asm
	ld.shared.u32 	%r875, [%r1826+3148];
	// begin inline asm
	dp4a.s32.s32 %r873, %r1050, %r875, %r869;
	// end inline asm
	cvt.rn.f32.s32 	%f336, %r873;
	mul.rn.ftz.f32 	%f337, %f287, %f336;
	ld.shared.f32 	%f338, [%r1834+784];
	fma.rn.ftz.f32 	%f339, %f338, %f337, %f242;
	ld.shared.u32 	%r879, [%r1826+3392];
	// begin inline asm
	dp4a.s32.s32 %r877, %r1038, %r879, %r1808;
	// end inline asm
	ld.shared.u32 	%r883, [%r1826+3396];
	// begin inline asm
	dp4a.s32.s32 %r881, %r1042, %r883, %r877;
	// end inline asm
	ld.shared.u32 	%r887, [%r1826+3400];
	// begin inline asm
	dp4a.s32.s32 %r885, %r1046, %r887, %r881;
	// end inline asm
	ld.shared.u32 	%r891, [%r1826+3404];
	// begin inline asm
	dp4a.s32.s32 %r889, %r1050, %r891, %r885;
	// end inline asm
	cvt.rn.f32.s32 	%f340, %r889;
	mul.rn.ftz.f32 	%f341, %f287, %f340;
	ld.shared.f32 	%f342, [%r1834+848];
	fma.rn.ftz.f32 	%f343, %f342, %f341, %f246;
	ld.shared.u32 	%r895, [%r1826+3648];
	// begin inline asm
	dp4a.s32.s32 %r893, %r1038, %r895, %r1808;
	// end inline asm
	ld.shared.u32 	%r899, [%r1826+3652];
	// begin inline asm
	dp4a.s32.s32 %r897, %r1042, %r899, %r893;
	// end inline asm
	ld.shared.u32 	%r903, [%r1826+3656];
	// begin inline asm
	dp4a.s32.s32 %r901, %r1046, %r903, %r897;
	// end inline asm
	ld.shared.u32 	%r907, [%r1826+3660];
	// begin inline asm
	dp4a.s32.s32 %r905, %r1050, %r907, %r901;
	// end inline asm
	cvt.rn.f32.s32 	%f344, %r905;
	mul.rn.ftz.f32 	%f345, %f287, %f344;
	ld.shared.f32 	%f346, [%r1834+912];
	fma.rn.ftz.f32 	%f347, %f346, %f345, %f250;
	ld.shared.u32 	%r911, [%r1826+3904];
	// begin inline asm
	dp4a.s32.s32 %r909, %r1038, %r911, %r1808;
	// end inline asm
	ld.shared.u32 	%r915, [%r1826+3908];
	// begin inline asm
	dp4a.s32.s32 %r913, %r1042, %r915, %r909;
	// end inline asm
	ld.shared.u32 	%r919, [%r1826+3912];
	// begin inline asm
	dp4a.s32.s32 %r917, %r1046, %r919, %r913;
	// end inline asm
	ld.shared.u32 	%r923, [%r1826+3916];
	// begin inline asm
	dp4a.s32.s32 %r921, %r1050, %r923, %r917;
	// end inline asm
	cvt.rn.f32.s32 	%f348, %r921;
	mul.rn.ftz.f32 	%f349, %f287, %f348;
	ld.shared.f32 	%f350, [%r1834+976];
	fma.rn.ftz.f32 	%f351, %f350, %f349, %f254;
	ld.shared.u32 	%r927, [%r1826+4160];
	// begin inline asm
	dp4a.s32.s32 %r925, %r1038, %r927, %r1808;
	// end inline asm
	ld.shared.u32 	%r931, [%r1826+4164];
	// begin inline asm
	dp4a.s32.s32 %r929, %r1042, %r931, %r925;
	// end inline asm
	ld.shared.u32 	%r935, [%r1826+4168];
	// begin inline asm
	dp4a.s32.s32 %r933, %r1046, %r935, %r929;
	// end inline asm
	ld.shared.u32 	%r939, [%r1826+4172];
	// begin inline asm
	dp4a.s32.s32 %r937, %r1050, %r939, %r933;
	// end inline asm
	cvt.rn.f32.s32 	%f352, %r937;
	mul.rn.ftz.f32 	%f353, %f287, %f352;
	ld.shared.f32 	%f354, [%r1834+1040];
	fma.rn.ftz.f32 	%f355, %f354, %f353, %f258;
	ld.shared.u32 	%r943, [%r1826+4416];
	// begin inline asm
	dp4a.s32.s32 %r941, %r1038, %r943, %r1808;
	// end inline asm
	ld.shared.u32 	%r947, [%r1826+4420];
	// begin inline asm
	dp4a.s32.s32 %r945, %r1042, %r947, %r941;
	// end inline asm
	ld.shared.u32 	%r951, [%r1826+4424];
	// begin inline asm
	dp4a.s32.s32 %r949, %r1046, %r951, %r945;
	// end inline asm
	ld.shared.u32 	%r955, [%r1826+4428];
	// begin inline asm
	dp4a.s32.s32 %r953, %r1050, %r955, %r949;
	// end inline asm
	cvt.rn.f32.s32 	%f356, %r953;
	mul.rn.ftz.f32 	%f357, %f287, %f356;
	ld.shared.f32 	%f358, [%r1834+1104];
	fma.rn.ftz.f32 	%f359, %f358, %f357, %f262;
	ld.shared.u32 	%r959, [%r1826+4672];
	// begin inline asm
	dp4a.s32.s32 %r957, %r1038, %r959, %r1808;
	// end inline asm
	ld.shared.u32 	%r963, [%r1826+4676];
	// begin inline asm
	dp4a.s32.s32 %r961, %r1042, %r963, %r957;
	// end inline asm
	ld.shared.u32 	%r967, [%r1826+4680];
	// begin inline asm
	dp4a.s32.s32 %r965, %r1046, %r967, %r961;
	// end inline asm
	ld.shared.u32 	%r971, [%r1826+4684];
	// begin inline asm
	dp4a.s32.s32 %r969, %r1050, %r971, %r965;
	// end inline asm
	cvt.rn.f32.s32 	%f360, %r969;
	mul.rn.ftz.f32 	%f361, %f287, %f360;
	ld.shared.f32 	%f362, [%r1834+1168];
	fma.rn.ftz.f32 	%f363, %f362, %f361, %f266;
	ld.shared.u32 	%r975, [%r1826+4928];
	// begin inline asm
	dp4a.s32.s32 %r973, %r1038, %r975, %r1808;
	// end inline asm
	ld.shared.u32 	%r979, [%r1826+4932];
	// begin inline asm
	dp4a.s32.s32 %r977, %r1042, %r979, %r973;
	// end inline asm
	ld.shared.u32 	%r983, [%r1826+4936];
	// begin inline asm
	dp4a.s32.s32 %r981, %r1046, %r983, %r977;
	// end inline asm
	ld.shared.u32 	%r987, [%r1826+4940];
	// begin inline asm
	dp4a.s32.s32 %r985, %r1050, %r987, %r981;
	// end inline asm
	cvt.rn.f32.s32 	%f364, %r985;
	mul.rn.ftz.f32 	%f365, %f287, %f364;
	ld.shared.f32 	%f366, [%r1834+1232];
	fma.rn.ftz.f32 	%f367, %f366, %f365, %f270;
	ld.shared.u32 	%r991, [%r1826+5184];
	// begin inline asm
	dp4a.s32.s32 %r989, %r1038, %r991, %r1808;
	// end inline asm
	ld.shared.u32 	%r995, [%r1826+5188];
	// begin inline asm
	dp4a.s32.s32 %r993, %r1042, %r995, %r989;
	// end inline asm
	ld.shared.u32 	%r999, [%r1826+5192];
	// begin inline asm
	dp4a.s32.s32 %r997, %r1046, %r999, %r993;
	// end inline asm
	ld.shared.u32 	%r1003, [%r1826+5196];
	// begin inline asm
	dp4a.s32.s32 %r1001, %r1050, %r1003, %r997;
	// end inline asm
	cvt.rn.f32.s32 	%f368, %r1001;
	mul.rn.ftz.f32 	%f369, %f287, %f368;
	ld.shared.f32 	%f370, [%r1834+1296];
	fma.rn.ftz.f32 	%f371, %f370, %f369, %f274;
	ld.shared.u32 	%r1007, [%r1826+5440];
	// begin inline asm
	dp4a.s32.s32 %r1005, %r1038, %r1007, %r1808;
	// end inline asm
	ld.shared.u32 	%r1011, [%r1826+5444];
	// begin inline asm
	dp4a.s32.s32 %r1009, %r1042, %r1011, %r1005;
	// end inline asm
	ld.shared.u32 	%r1015, [%r1826+5448];
	// begin inline asm
	dp4a.s32.s32 %r1013, %r1046, %r1015, %r1009;
	// end inline asm
	ld.shared.u32 	%r1019, [%r1826+5452];
	// begin inline asm
	dp4a.s32.s32 %r1017, %r1050, %r1019, %r1013;
	// end inline asm
	cvt.rn.f32.s32 	%f372, %r1017;
	mul.rn.ftz.f32 	%f373, %f287, %f372;
	ld.shared.f32 	%f374, [%r1834+1360];
	fma.rn.ftz.f32 	%f375, %f374, %f373, %f278;
	ld.shared.u32 	%r1023, [%r1826+5696];
	// begin inline asm
	dp4a.s32.s32 %r1021, %r1038, %r1023, %r1808;
	// end inline asm
	ld.shared.u32 	%r1027, [%r1826+5700];
	// begin inline asm
	dp4a.s32.s32 %r1025, %r1042, %r1027, %r1021;
	// end inline asm
	ld.shared.u32 	%r1031, [%r1826+5704];
	// begin inline asm
	dp4a.s32.s32 %r1029, %r1046, %r1031, %r1025;
	// end inline asm
	ld.shared.u32 	%r1035, [%r1826+5708];
	// begin inline asm
	dp4a.s32.s32 %r1033, %r1050, %r1035, %r1029;
	// end inline asm
	cvt.rn.f32.s32 	%f376, %r1033;
	mul.rn.ftz.f32 	%f377, %f287, %f376;
	ld.shared.f32 	%f378, [%r1834+1424];
	fma.rn.ftz.f32 	%f379, %f378, %f377, %f282;
	ld.shared.u32 	%r1039, [%r1826+5952];
	// begin inline asm
	dp4a.s32.s32 %r1037, %r1038, %r1039, %r1808;
	// end inline asm
	ld.shared.u32 	%r1043, [%r1826+5956];
	// begin inline asm
	dp4a.s32.s32 %r1041, %r1042, %r1043, %r1037;
	// end inline asm
	ld.shared.u32 	%r1047, [%r1826+5960];
	// begin inline asm
	dp4a.s32.s32 %r1045, %r1046, %r1047, %r1041;
	// end inline asm
	ld.shared.u32 	%r1051, [%r1826+5964];
	// begin inline asm
	dp4a.s32.s32 %r1049, %r1050, %r1051, %r1045;
	// end inline asm
	cvt.rn.f32.s32 	%f380, %r1049;
	mul.rn.ftz.f32 	%f381, %f287, %f380;
	ld.shared.f32 	%f382, [%r1834+1488];
	fma.rn.ftz.f32 	%f383, %f382, %f381, %f286;
	ld.global.u32 	%r1422, [%rd42+128];
	ld.global.u32 	%r1426, [%rd42+132];
	ld.global.u32 	%r1430, [%rd42+136];
	ld.global.u32 	%r1434, [%rd42+140];
	ld.global.f32 	%f384, [%rd45+32];
	ld.shared.u32 	%r1055, [%r1826+128];
	// begin inline asm
	dp4a.s32.s32 %r1053, %r1422, %r1055, %r1808;
	// end inline asm
	ld.shared.u32 	%r1059, [%r1826+132];
	// begin inline asm
	dp4a.s32.s32 %r1057, %r1426, %r1059, %r1053;
	// end inline asm
	ld.shared.u32 	%r1063, [%r1826+136];
	// begin inline asm
	dp4a.s32.s32 %r1061, %r1430, %r1063, %r1057;
	// end inline asm
	ld.shared.u32 	%r1067, [%r1826+140];
	// begin inline asm
	dp4a.s32.s32 %r1065, %r1434, %r1067, %r1061;
	// end inline asm
	cvt.rn.f32.s32 	%f385, %r1065;
	mul.rn.ftz.f32 	%f386, %f384, %f385;
	ld.shared.f32 	%f387, [%r1834+32];
	fma.rn.ftz.f32 	%f388, %f387, %f386, %f291;
	ld.shared.u32 	%r1071, [%r1826+384];
	// begin inline asm
	dp4a.s32.s32 %r1069, %r1422, %r1071, %r1808;
	// end inline asm
	ld.shared.u32 	%r1075, [%r1826+388];
	// begin inline asm
	dp4a.s32.s32 %r1073, %r1426, %r1075, %r1069;
	// end inline asm
	ld.shared.u32 	%r1079, [%r1826+392];
	// begin inline asm
	dp4a.s32.s32 %r1077, %r1430, %r1079, %r1073;
	// end inline asm
	ld.shared.u32 	%r1083, [%r1826+396];
	// begin inline asm
	dp4a.s32.s32 %r1081, %r1434, %r1083, %r1077;
	// end inline asm
	cvt.rn.f32.s32 	%f389, %r1081;
	mul.rn.ftz.f32 	%f390, %f384, %f389;
	ld.shared.f32 	%f391, [%r1834+96];
	fma.rn.ftz.f32 	%f392, %f391, %f390, %f295;
	ld.shared.u32 	%r1087, [%r1826+640];
	// begin inline asm
	dp4a.s32.s32 %r1085, %r1422, %r1087, %r1808;
	// end inline asm
	ld.shared.u32 	%r1091, [%r1826+644];
	// begin inline asm
	dp4a.s32.s32 %r1089, %r1426, %r1091, %r1085;
	// end inline asm
	ld.shared.u32 	%r1095, [%r1826+648];
	// begin inline asm
	dp4a.s32.s32 %r1093, %r1430, %r1095, %r1089;
	// end inline asm
	ld.shared.u32 	%r1099, [%r1826+652];
	// begin inline asm
	dp4a.s32.s32 %r1097, %r1434, %r1099, %r1093;
	// end inline asm
	cvt.rn.f32.s32 	%f393, %r1097;
	mul.rn.ftz.f32 	%f394, %f384, %f393;
	ld.shared.f32 	%f395, [%r1834+160];
	fma.rn.ftz.f32 	%f396, %f395, %f394, %f299;
	ld.shared.u32 	%r1103, [%r1826+896];
	// begin inline asm
	dp4a.s32.s32 %r1101, %r1422, %r1103, %r1808;
	// end inline asm
	ld.shared.u32 	%r1107, [%r1826+900];
	// begin inline asm
	dp4a.s32.s32 %r1105, %r1426, %r1107, %r1101;
	// end inline asm
	ld.shared.u32 	%r1111, [%r1826+904];
	// begin inline asm
	dp4a.s32.s32 %r1109, %r1430, %r1111, %r1105;
	// end inline asm
	ld.shared.u32 	%r1115, [%r1826+908];
	// begin inline asm
	dp4a.s32.s32 %r1113, %r1434, %r1115, %r1109;
	// end inline asm
	cvt.rn.f32.s32 	%f397, %r1113;
	mul.rn.ftz.f32 	%f398, %f384, %f397;
	ld.shared.f32 	%f399, [%r1834+224];
	fma.rn.ftz.f32 	%f400, %f399, %f398, %f303;
	ld.shared.u32 	%r1119, [%r1826+1152];
	// begin inline asm
	dp4a.s32.s32 %r1117, %r1422, %r1119, %r1808;
	// end inline asm
	ld.shared.u32 	%r1123, [%r1826+1156];
	// begin inline asm
	dp4a.s32.s32 %r1121, %r1426, %r1123, %r1117;
	// end inline asm
	ld.shared.u32 	%r1127, [%r1826+1160];
	// begin inline asm
	dp4a.s32.s32 %r1125, %r1430, %r1127, %r1121;
	// end inline asm
	ld.shared.u32 	%r1131, [%r1826+1164];
	// begin inline asm
	dp4a.s32.s32 %r1129, %r1434, %r1131, %r1125;
	// end inline asm
	cvt.rn.f32.s32 	%f401, %r1129;
	mul.rn.ftz.f32 	%f402, %f384, %f401;
	ld.shared.f32 	%f403, [%r1834+288];
	fma.rn.ftz.f32 	%f404, %f403, %f402, %f307;
	ld.shared.u32 	%r1135, [%r1826+1408];
	// begin inline asm
	dp4a.s32.s32 %r1133, %r1422, %r1135, %r1808;
	// end inline asm
	ld.shared.u32 	%r1139, [%r1826+1412];
	// begin inline asm
	dp4a.s32.s32 %r1137, %r1426, %r1139, %r1133;
	// end inline asm
	ld.shared.u32 	%r1143, [%r1826+1416];
	// begin inline asm
	dp4a.s32.s32 %r1141, %r1430, %r1143, %r1137;
	// end inline asm
	ld.shared.u32 	%r1147, [%r1826+1420];
	// begin inline asm
	dp4a.s32.s32 %r1145, %r1434, %r1147, %r1141;
	// end inline asm
	cvt.rn.f32.s32 	%f405, %r1145;
	mul.rn.ftz.f32 	%f406, %f384, %f405;
	ld.shared.f32 	%f407, [%r1834+352];
	fma.rn.ftz.f32 	%f408, %f407, %f406, %f311;
	ld.shared.u32 	%r1151, [%r1826+1664];
	// begin inline asm
	dp4a.s32.s32 %r1149, %r1422, %r1151, %r1808;
	// end inline asm
	ld.shared.u32 	%r1155, [%r1826+1668];
	// begin inline asm
	dp4a.s32.s32 %r1153, %r1426, %r1155, %r1149;
	// end inline asm
	ld.shared.u32 	%r1159, [%r1826+1672];
	// begin inline asm
	dp4a.s32.s32 %r1157, %r1430, %r1159, %r1153;
	// end inline asm
	ld.shared.u32 	%r1163, [%r1826+1676];
	// begin inline asm
	dp4a.s32.s32 %r1161, %r1434, %r1163, %r1157;
	// end inline asm
	cvt.rn.f32.s32 	%f409, %r1161;
	mul.rn.ftz.f32 	%f410, %f384, %f409;
	ld.shared.f32 	%f411, [%r1834+416];
	fma.rn.ftz.f32 	%f412, %f411, %f410, %f315;
	ld.shared.u32 	%r1167, [%r1826+1920];
	// begin inline asm
	dp4a.s32.s32 %r1165, %r1422, %r1167, %r1808;
	// end inline asm
	ld.shared.u32 	%r1171, [%r1826+1924];
	// begin inline asm
	dp4a.s32.s32 %r1169, %r1426, %r1171, %r1165;
	// end inline asm
	ld.shared.u32 	%r1175, [%r1826+1928];
	// begin inline asm
	dp4a.s32.s32 %r1173, %r1430, %r1175, %r1169;
	// end inline asm
	ld.shared.u32 	%r1179, [%r1826+1932];
	// begin inline asm
	dp4a.s32.s32 %r1177, %r1434, %r1179, %r1173;
	// end inline asm
	cvt.rn.f32.s32 	%f413, %r1177;
	mul.rn.ftz.f32 	%f414, %f384, %f413;
	ld.shared.f32 	%f415, [%r1834+480];
	fma.rn.ftz.f32 	%f416, %f415, %f414, %f319;
	ld.shared.u32 	%r1183, [%r1826+2176];
	// begin inline asm
	dp4a.s32.s32 %r1181, %r1422, %r1183, %r1808;
	// end inline asm
	ld.shared.u32 	%r1187, [%r1826+2180];
	// begin inline asm
	dp4a.s32.s32 %r1185, %r1426, %r1187, %r1181;
	// end inline asm
	ld.shared.u32 	%r1191, [%r1826+2184];
	// begin inline asm
	dp4a.s32.s32 %r1189, %r1430, %r1191, %r1185;
	// end inline asm
	ld.shared.u32 	%r1195, [%r1826+2188];
	// begin inline asm
	dp4a.s32.s32 %r1193, %r1434, %r1195, %r1189;
	// end inline asm
	cvt.rn.f32.s32 	%f417, %r1193;
	mul.rn.ftz.f32 	%f418, %f384, %f417;
	ld.shared.f32 	%f419, [%r1834+544];
	fma.rn.ftz.f32 	%f420, %f419, %f418, %f323;
	ld.shared.u32 	%r1199, [%r1826+2432];
	// begin inline asm
	dp4a.s32.s32 %r1197, %r1422, %r1199, %r1808;
	// end inline asm
	ld.shared.u32 	%r1203, [%r1826+2436];
	// begin inline asm
	dp4a.s32.s32 %r1201, %r1426, %r1203, %r1197;
	// end inline asm
	ld.shared.u32 	%r1207, [%r1826+2440];
	// begin inline asm
	dp4a.s32.s32 %r1205, %r1430, %r1207, %r1201;
	// end inline asm
	ld.shared.u32 	%r1211, [%r1826+2444];
	// begin inline asm
	dp4a.s32.s32 %r1209, %r1434, %r1211, %r1205;
	// end inline asm
	cvt.rn.f32.s32 	%f421, %r1209;
	mul.rn.ftz.f32 	%f422, %f384, %f421;
	ld.shared.f32 	%f423, [%r1834+608];
	fma.rn.ftz.f32 	%f424, %f423, %f422, %f327;
	ld.shared.u32 	%r1215, [%r1826+2688];
	// begin inline asm
	dp4a.s32.s32 %r1213, %r1422, %r1215, %r1808;
	// end inline asm
	ld.shared.u32 	%r1219, [%r1826+2692];
	// begin inline asm
	dp4a.s32.s32 %r1217, %r1426, %r1219, %r1213;
	// end inline asm
	ld.shared.u32 	%r1223, [%r1826+2696];
	// begin inline asm
	dp4a.s32.s32 %r1221, %r1430, %r1223, %r1217;
	// end inline asm
	ld.shared.u32 	%r1227, [%r1826+2700];
	// begin inline asm
	dp4a.s32.s32 %r1225, %r1434, %r1227, %r1221;
	// end inline asm
	cvt.rn.f32.s32 	%f425, %r1225;
	mul.rn.ftz.f32 	%f426, %f384, %f425;
	ld.shared.f32 	%f427, [%r1834+672];
	fma.rn.ftz.f32 	%f428, %f427, %f426, %f331;
	ld.shared.u32 	%r1231, [%r1826+2944];
	// begin inline asm
	dp4a.s32.s32 %r1229, %r1422, %r1231, %r1808;
	// end inline asm
	ld.shared.u32 	%r1235, [%r1826+2948];
	// begin inline asm
	dp4a.s32.s32 %r1233, %r1426, %r1235, %r1229;
	// end inline asm
	ld.shared.u32 	%r1239, [%r1826+2952];
	// begin inline asm
	dp4a.s32.s32 %r1237, %r1430, %r1239, %r1233;
	// end inline asm
	ld.shared.u32 	%r1243, [%r1826+2956];
	// begin inline asm
	dp4a.s32.s32 %r1241, %r1434, %r1243, %r1237;
	// end inline asm
	cvt.rn.f32.s32 	%f429, %r1241;
	mul.rn.ftz.f32 	%f430, %f384, %f429;
	ld.shared.f32 	%f431, [%r1834+736];
	fma.rn.ftz.f32 	%f432, %f431, %f430, %f335;
	ld.shared.u32 	%r1247, [%r1826+3200];
	// begin inline asm
	dp4a.s32.s32 %r1245, %r1422, %r1247, %r1808;
	// end inline asm
	ld.shared.u32 	%r1251, [%r1826+3204];
	// begin inline asm
	dp4a.s32.s32 %r1249, %r1426, %r1251, %r1245;
	// end inline asm
	ld.shared.u32 	%r1255, [%r1826+3208];
	// begin inline asm
	dp4a.s32.s32 %r1253, %r1430, %r1255, %r1249;
	// end inline asm
	ld.shared.u32 	%r1259, [%r1826+3212];
	// begin inline asm
	dp4a.s32.s32 %r1257, %r1434, %r1259, %r1253;
	// end inline asm
	cvt.rn.f32.s32 	%f433, %r1257;
	mul.rn.ftz.f32 	%f434, %f384, %f433;
	ld.shared.f32 	%f435, [%r1834+800];
	fma.rn.ftz.f32 	%f436, %f435, %f434, %f339;
	ld.shared.u32 	%r1263, [%r1826+3456];
	// begin inline asm
	dp4a.s32.s32 %r1261, %r1422, %r1263, %r1808;
	// end inline asm
	ld.shared.u32 	%r1267, [%r1826+3460];
	// begin inline asm
	dp4a.s32.s32 %r1265, %r1426, %r1267, %r1261;
	// end inline asm
	ld.shared.u32 	%r1271, [%r1826+3464];
	// begin inline asm
	dp4a.s32.s32 %r1269, %r1430, %r1271, %r1265;
	// end inline asm
	ld.shared.u32 	%r1275, [%r1826+3468];
	// begin inline asm
	dp4a.s32.s32 %r1273, %r1434, %r1275, %r1269;
	// end inline asm
	cvt.rn.f32.s32 	%f437, %r1273;
	mul.rn.ftz.f32 	%f438, %f384, %f437;
	ld.shared.f32 	%f439, [%r1834+864];
	fma.rn.ftz.f32 	%f440, %f439, %f438, %f343;
	ld.shared.u32 	%r1279, [%r1826+3712];
	// begin inline asm
	dp4a.s32.s32 %r1277, %r1422, %r1279, %r1808;
	// end inline asm
	ld.shared.u32 	%r1283, [%r1826+3716];
	// begin inline asm
	dp4a.s32.s32 %r1281, %r1426, %r1283, %r1277;
	// end inline asm
	ld.shared.u32 	%r1287, [%r1826+3720];
	// begin inline asm
	dp4a.s32.s32 %r1285, %r1430, %r1287, %r1281;
	// end inline asm
	ld.shared.u32 	%r1291, [%r1826+3724];
	// begin inline asm
	dp4a.s32.s32 %r1289, %r1434, %r1291, %r1285;
	// end inline asm
	cvt.rn.f32.s32 	%f441, %r1289;
	mul.rn.ftz.f32 	%f442, %f384, %f441;
	ld.shared.f32 	%f443, [%r1834+928];
	fma.rn.ftz.f32 	%f444, %f443, %f442, %f347;
	ld.shared.u32 	%r1295, [%r1826+3968];
	// begin inline asm
	dp4a.s32.s32 %r1293, %r1422, %r1295, %r1808;
	// end inline asm
	ld.shared.u32 	%r1299, [%r1826+3972];
	// begin inline asm
	dp4a.s32.s32 %r1297, %r1426, %r1299, %r1293;
	// end inline asm
	ld.shared.u32 	%r1303, [%r1826+3976];
	// begin inline asm
	dp4a.s32.s32 %r1301, %r1430, %r1303, %r1297;
	// end inline asm
	ld.shared.u32 	%r1307, [%r1826+3980];
	// begin inline asm
	dp4a.s32.s32 %r1305, %r1434, %r1307, %r1301;
	// end inline asm
	cvt.rn.f32.s32 	%f445, %r1305;
	mul.rn.ftz.f32 	%f446, %f384, %f445;
	ld.shared.f32 	%f447, [%r1834+992];
	fma.rn.ftz.f32 	%f448, %f447, %f446, %f351;
	ld.shared.u32 	%r1311, [%r1826+4224];
	// begin inline asm
	dp4a.s32.s32 %r1309, %r1422, %r1311, %r1808;
	// end inline asm
	ld.shared.u32 	%r1315, [%r1826+4228];
	// begin inline asm
	dp4a.s32.s32 %r1313, %r1426, %r1315, %r1309;
	// end inline asm
	ld.shared.u32 	%r1319, [%r1826+4232];
	// begin inline asm
	dp4a.s32.s32 %r1317, %r1430, %r1319, %r1313;
	// end inline asm
	ld.shared.u32 	%r1323, [%r1826+4236];
	// begin inline asm
	dp4a.s32.s32 %r1321, %r1434, %r1323, %r1317;
	// end inline asm
	cvt.rn.f32.s32 	%f449, %r1321;
	mul.rn.ftz.f32 	%f450, %f384, %f449;
	ld.shared.f32 	%f451, [%r1834+1056];
	fma.rn.ftz.f32 	%f452, %f451, %f450, %f355;
	ld.shared.u32 	%r1327, [%r1826+4480];
	// begin inline asm
	dp4a.s32.s32 %r1325, %r1422, %r1327, %r1808;
	// end inline asm
	ld.shared.u32 	%r1331, [%r1826+4484];
	// begin inline asm
	dp4a.s32.s32 %r1329, %r1426, %r1331, %r1325;
	// end inline asm
	ld.shared.u32 	%r1335, [%r1826+4488];
	// begin inline asm
	dp4a.s32.s32 %r1333, %r1430, %r1335, %r1329;
	// end inline asm
	ld.shared.u32 	%r1339, [%r1826+4492];
	// begin inline asm
	dp4a.s32.s32 %r1337, %r1434, %r1339, %r1333;
	// end inline asm
	cvt.rn.f32.s32 	%f453, %r1337;
	mul.rn.ftz.f32 	%f454, %f384, %f453;
	ld.shared.f32 	%f455, [%r1834+1120];
	fma.rn.ftz.f32 	%f456, %f455, %f454, %f359;
	ld.shared.u32 	%r1343, [%r1826+4736];
	// begin inline asm
	dp4a.s32.s32 %r1341, %r1422, %r1343, %r1808;
	// end inline asm
	ld.shared.u32 	%r1347, [%r1826+4740];
	// begin inline asm
	dp4a.s32.s32 %r1345, %r1426, %r1347, %r1341;
	// end inline asm
	ld.shared.u32 	%r1351, [%r1826+4744];
	// begin inline asm
	dp4a.s32.s32 %r1349, %r1430, %r1351, %r1345;
	// end inline asm
	ld.shared.u32 	%r1355, [%r1826+4748];
	// begin inline asm
	dp4a.s32.s32 %r1353, %r1434, %r1355, %r1349;
	// end inline asm
	cvt.rn.f32.s32 	%f457, %r1353;
	mul.rn.ftz.f32 	%f458, %f384, %f457;
	ld.shared.f32 	%f459, [%r1834+1184];
	fma.rn.ftz.f32 	%f460, %f459, %f458, %f363;
	ld.shared.u32 	%r1359, [%r1826+4992];
	// begin inline asm
	dp4a.s32.s32 %r1357, %r1422, %r1359, %r1808;
	// end inline asm
	ld.shared.u32 	%r1363, [%r1826+4996];
	// begin inline asm
	dp4a.s32.s32 %r1361, %r1426, %r1363, %r1357;
	// end inline asm
	ld.shared.u32 	%r1367, [%r1826+5000];
	// begin inline asm
	dp4a.s32.s32 %r1365, %r1430, %r1367, %r1361;
	// end inline asm
	ld.shared.u32 	%r1371, [%r1826+5004];
	// begin inline asm
	dp4a.s32.s32 %r1369, %r1434, %r1371, %r1365;
	// end inline asm
	cvt.rn.f32.s32 	%f461, %r1369;
	mul.rn.ftz.f32 	%f462, %f384, %f461;
	ld.shared.f32 	%f463, [%r1834+1248];
	fma.rn.ftz.f32 	%f464, %f463, %f462, %f367;
	ld.shared.u32 	%r1375, [%r1826+5248];
	// begin inline asm
	dp4a.s32.s32 %r1373, %r1422, %r1375, %r1808;
	// end inline asm
	ld.shared.u32 	%r1379, [%r1826+5252];
	// begin inline asm
	dp4a.s32.s32 %r1377, %r1426, %r1379, %r1373;
	// end inline asm
	ld.shared.u32 	%r1383, [%r1826+5256];
	// begin inline asm
	dp4a.s32.s32 %r1381, %r1430, %r1383, %r1377;
	// end inline asm
	ld.shared.u32 	%r1387, [%r1826+5260];
	// begin inline asm
	dp4a.s32.s32 %r1385, %r1434, %r1387, %r1381;
	// end inline asm
	cvt.rn.f32.s32 	%f465, %r1385;
	mul.rn.ftz.f32 	%f466, %f384, %f465;
	ld.shared.f32 	%f467, [%r1834+1312];
	fma.rn.ftz.f32 	%f468, %f467, %f466, %f371;
	ld.shared.u32 	%r1391, [%r1826+5504];
	// begin inline asm
	dp4a.s32.s32 %r1389, %r1422, %r1391, %r1808;
	// end inline asm
	ld.shared.u32 	%r1395, [%r1826+5508];
	// begin inline asm
	dp4a.s32.s32 %r1393, %r1426, %r1395, %r1389;
	// end inline asm
	ld.shared.u32 	%r1399, [%r1826+5512];
	// begin inline asm
	dp4a.s32.s32 %r1397, %r1430, %r1399, %r1393;
	// end inline asm
	ld.shared.u32 	%r1403, [%r1826+5516];
	// begin inline asm
	dp4a.s32.s32 %r1401, %r1434, %r1403, %r1397;
	// end inline asm
	cvt.rn.f32.s32 	%f469, %r1401;
	mul.rn.ftz.f32 	%f470, %f384, %f469;
	ld.shared.f32 	%f471, [%r1834+1376];
	fma.rn.ftz.f32 	%f472, %f471, %f470, %f375;
	ld.shared.u32 	%r1407, [%r1826+5760];
	// begin inline asm
	dp4a.s32.s32 %r1405, %r1422, %r1407, %r1808;
	// end inline asm
	ld.shared.u32 	%r1411, [%r1826+5764];
	// begin inline asm
	dp4a.s32.s32 %r1409, %r1426, %r1411, %r1405;
	// end inline asm
	ld.shared.u32 	%r1415, [%r1826+5768];
	// begin inline asm
	dp4a.s32.s32 %r1413, %r1430, %r1415, %r1409;
	// end inline asm
	ld.shared.u32 	%r1419, [%r1826+5772];
	// begin inline asm
	dp4a.s32.s32 %r1417, %r1434, %r1419, %r1413;
	// end inline asm
	cvt.rn.f32.s32 	%f473, %r1417;
	mul.rn.ftz.f32 	%f474, %f384, %f473;
	ld.shared.f32 	%f475, [%r1834+1440];
	fma.rn.ftz.f32 	%f476, %f475, %f474, %f379;
	ld.shared.u32 	%r1423, [%r1826+6016];
	// begin inline asm
	dp4a.s32.s32 %r1421, %r1422, %r1423, %r1808;
	// end inline asm
	ld.shared.u32 	%r1427, [%r1826+6020];
	// begin inline asm
	dp4a.s32.s32 %r1425, %r1426, %r1427, %r1421;
	// end inline asm
	ld.shared.u32 	%r1431, [%r1826+6024];
	// begin inline asm
	dp4a.s32.s32 %r1429, %r1430, %r1431, %r1425;
	// end inline asm
	ld.shared.u32 	%r1435, [%r1826+6028];
	// begin inline asm
	dp4a.s32.s32 %r1433, %r1434, %r1435, %r1429;
	// end inline asm
	cvt.rn.f32.s32 	%f477, %r1433;
	mul.rn.ftz.f32 	%f478, %f384, %f477;
	ld.shared.f32 	%f479, [%r1834+1504];
	fma.rn.ftz.f32 	%f480, %f479, %f478, %f383;
	ld.global.u32 	%r1806, [%rd42+192];
	ld.global.u32 	%r1810, [%rd42+196];
	ld.global.u32 	%r1814, [%rd42+200];
	ld.global.u32 	%r1818, [%rd42+204];
	ld.global.f32 	%f481, [%rd45+48];
	ld.shared.u32 	%r1439, [%r1826+192];
	// begin inline asm
	dp4a.s32.s32 %r1437, %r1806, %r1439, %r1808;
	// end inline asm
	ld.shared.u32 	%r1443, [%r1826+196];
	// begin inline asm
	dp4a.s32.s32 %r1441, %r1810, %r1443, %r1437;
	// end inline asm
	ld.shared.u32 	%r1447, [%r1826+200];
	// begin inline asm
	dp4a.s32.s32 %r1445, %r1814, %r1447, %r1441;
	// end inline asm
	ld.shared.u32 	%r1451, [%r1826+204];
	// begin inline asm
	dp4a.s32.s32 %r1449, %r1818, %r1451, %r1445;
	// end inline asm
	cvt.rn.f32.s32 	%f482, %r1449;
	mul.rn.ftz.f32 	%f483, %f481, %f482;
	ld.shared.f32 	%f484, [%r1834+48];
	fma.rn.ftz.f32 	%f676, %f484, %f483, %f388;
	ld.shared.u32 	%r1455, [%r1826+448];
	// begin inline asm
	dp4a.s32.s32 %r1453, %r1806, %r1455, %r1808;
	// end inline asm
	ld.shared.u32 	%r1459, [%r1826+452];
	// begin inline asm
	dp4a.s32.s32 %r1457, %r1810, %r1459, %r1453;
	// end inline asm
	ld.shared.u32 	%r1463, [%r1826+456];
	// begin inline asm
	dp4a.s32.s32 %r1461, %r1814, %r1463, %r1457;
	// end inline asm
	ld.shared.u32 	%r1467, [%r1826+460];
	// begin inline asm
	dp4a.s32.s32 %r1465, %r1818, %r1467, %r1461;
	// end inline asm
	cvt.rn.f32.s32 	%f485, %r1465;
	mul.rn.ftz.f32 	%f486, %f481, %f485;
	ld.shared.f32 	%f487, [%r1834+112];
	fma.rn.ftz.f32 	%f675, %f487, %f486, %f392;
	ld.shared.u32 	%r1471, [%r1826+704];
	// begin inline asm
	dp4a.s32.s32 %r1469, %r1806, %r1471, %r1808;
	// end inline asm
	ld.shared.u32 	%r1475, [%r1826+708];
	// begin inline asm
	dp4a.s32.s32 %r1473, %r1810, %r1475, %r1469;
	// end inline asm
	ld.shared.u32 	%r1479, [%r1826+712];
	// begin inline asm
	dp4a.s32.s32 %r1477, %r1814, %r1479, %r1473;
	// end inline asm
	ld.shared.u32 	%r1483, [%r1826+716];
	// begin inline asm
	dp4a.s32.s32 %r1481, %r1818, %r1483, %r1477;
	// end inline asm
	cvt.rn.f32.s32 	%f488, %r1481;
	mul.rn.ftz.f32 	%f489, %f481, %f488;
	ld.shared.f32 	%f490, [%r1834+176];
	fma.rn.ftz.f32 	%f674, %f490, %f489, %f396;
	ld.shared.u32 	%r1487, [%r1826+960];
	// begin inline asm
	dp4a.s32.s32 %r1485, %r1806, %r1487, %r1808;
	// end inline asm
	ld.shared.u32 	%r1491, [%r1826+964];
	// begin inline asm
	dp4a.s32.s32 %r1489, %r1810, %r1491, %r1485;
	// end inline asm
	ld.shared.u32 	%r1495, [%r1826+968];
	// begin inline asm
	dp4a.s32.s32 %r1493, %r1814, %r1495, %r1489;
	// end inline asm
	ld.shared.u32 	%r1499, [%r1826+972];
	// begin inline asm
	dp4a.s32.s32 %r1497, %r1818, %r1499, %r1493;
	// end inline asm
	cvt.rn.f32.s32 	%f491, %r1497;
	mul.rn.ftz.f32 	%f492, %f481, %f491;
	ld.shared.f32 	%f493, [%r1834+240];
	fma.rn.ftz.f32 	%f673, %f493, %f492, %f400;
	ld.shared.u32 	%r1503, [%r1826+1216];
	// begin inline asm
	dp4a.s32.s32 %r1501, %r1806, %r1503, %r1808;
	// end inline asm
	ld.shared.u32 	%r1507, [%r1826+1220];
	// begin inline asm
	dp4a.s32.s32 %r1505, %r1810, %r1507, %r1501;
	// end inline asm
	ld.shared.u32 	%r1511, [%r1826+1224];
	// begin inline asm
	dp4a.s32.s32 %r1509, %r1814, %r1511, %r1505;
	// end inline asm
	ld.shared.u32 	%r1515, [%r1826+1228];
	// begin inline asm
	dp4a.s32.s32 %r1513, %r1818, %r1515, %r1509;
	// end inline asm
	cvt.rn.f32.s32 	%f494, %r1513;
	mul.rn.ftz.f32 	%f495, %f481, %f494;
	ld.shared.f32 	%f496, [%r1834+304];
	fma.rn.ftz.f32 	%f672, %f496, %f495, %f404;
	ld.shared.u32 	%r1519, [%r1826+1472];
	// begin inline asm
	dp4a.s32.s32 %r1517, %r1806, %r1519, %r1808;
	// end inline asm
	ld.shared.u32 	%r1523, [%r1826+1476];
	// begin inline asm
	dp4a.s32.s32 %r1521, %r1810, %r1523, %r1517;
	// end inline asm
	ld.shared.u32 	%r1527, [%r1826+1480];
	// begin inline asm
	dp4a.s32.s32 %r1525, %r1814, %r1527, %r1521;
	// end inline asm
	ld.shared.u32 	%r1531, [%r1826+1484];
	// begin inline asm
	dp4a.s32.s32 %r1529, %r1818, %r1531, %r1525;
	// end inline asm
	cvt.rn.f32.s32 	%f497, %r1529;
	mul.rn.ftz.f32 	%f498, %f481, %f497;
	ld.shared.f32 	%f499, [%r1834+368];
	fma.rn.ftz.f32 	%f671, %f499, %f498, %f408;
	ld.shared.u32 	%r1535, [%r1826+1728];
	// begin inline asm
	dp4a.s32.s32 %r1533, %r1806, %r1535, %r1808;
	// end inline asm
	ld.shared.u32 	%r1539, [%r1826+1732];
	// begin inline asm
	dp4a.s32.s32 %r1537, %r1810, %r1539, %r1533;
	// end inline asm
	ld.shared.u32 	%r1543, [%r1826+1736];
	// begin inline asm
	dp4a.s32.s32 %r1541, %r1814, %r1543, %r1537;
	// end inline asm
	ld.shared.u32 	%r1547, [%r1826+1740];
	// begin inline asm
	dp4a.s32.s32 %r1545, %r1818, %r1547, %r1541;
	// end inline asm
	cvt.rn.f32.s32 	%f500, %r1545;
	mul.rn.ftz.f32 	%f501, %f481, %f500;
	ld.shared.f32 	%f502, [%r1834+432];
	fma.rn.ftz.f32 	%f670, %f502, %f501, %f412;
	ld.shared.u32 	%r1551, [%r1826+1984];
	// begin inline asm
	dp4a.s32.s32 %r1549, %r1806, %r1551, %r1808;
	// end inline asm
	ld.shared.u32 	%r1555, [%r1826+1988];
	// begin inline asm
	dp4a.s32.s32 %r1553, %r1810, %r1555, %r1549;
	// end inline asm
	ld.shared.u32 	%r1559, [%r1826+1992];
	// begin inline asm
	dp4a.s32.s32 %r1557, %r1814, %r1559, %r1553;
	// end inline asm
	ld.shared.u32 	%r1563, [%r1826+1996];
	// begin inline asm
	dp4a.s32.s32 %r1561, %r1818, %r1563, %r1557;
	// end inline asm
	cvt.rn.f32.s32 	%f503, %r1561;
	mul.rn.ftz.f32 	%f504, %f481, %f503;
	ld.shared.f32 	%f505, [%r1834+496];
	fma.rn.ftz.f32 	%f669, %f505, %f504, %f416;
	ld.shared.u32 	%r1567, [%r1826+2240];
	// begin inline asm
	dp4a.s32.s32 %r1565, %r1806, %r1567, %r1808;
	// end inline asm
	ld.shared.u32 	%r1571, [%r1826+2244];
	// begin inline asm
	dp4a.s32.s32 %r1569, %r1810, %r1571, %r1565;
	// end inline asm
	ld.shared.u32 	%r1575, [%r1826+2248];
	// begin inline asm
	dp4a.s32.s32 %r1573, %r1814, %r1575, %r1569;
	// end inline asm
	ld.shared.u32 	%r1579, [%r1826+2252];
	// begin inline asm
	dp4a.s32.s32 %r1577, %r1818, %r1579, %r1573;
	// end inline asm
	cvt.rn.f32.s32 	%f506, %r1577;
	mul.rn.ftz.f32 	%f507, %f481, %f506;
	ld.shared.f32 	%f508, [%r1834+560];
	fma.rn.ftz.f32 	%f668, %f508, %f507, %f420;
	ld.shared.u32 	%r1583, [%r1826+2496];
	// begin inline asm
	dp4a.s32.s32 %r1581, %r1806, %r1583, %r1808;
	// end inline asm
	ld.shared.u32 	%r1587, [%r1826+2500];
	// begin inline asm
	dp4a.s32.s32 %r1585, %r1810, %r1587, %r1581;
	// end inline asm
	ld.shared.u32 	%r1591, [%r1826+2504];
	// begin inline asm
	dp4a.s32.s32 %r1589, %r1814, %r1591, %r1585;
	// end inline asm
	ld.shared.u32 	%r1595, [%r1826+2508];
	// begin inline asm
	dp4a.s32.s32 %r1593, %r1818, %r1595, %r1589;
	// end inline asm
	cvt.rn.f32.s32 	%f509, %r1593;
	mul.rn.ftz.f32 	%f510, %f481, %f509;
	ld.shared.f32 	%f511, [%r1834+624];
	fma.rn.ftz.f32 	%f667, %f511, %f510, %f424;
	ld.shared.u32 	%r1599, [%r1826+2752];
	// begin inline asm
	dp4a.s32.s32 %r1597, %r1806, %r1599, %r1808;
	// end inline asm
	ld.shared.u32 	%r1603, [%r1826+2756];
	// begin inline asm
	dp4a.s32.s32 %r1601, %r1810, %r1603, %r1597;
	// end inline asm
	ld.shared.u32 	%r1607, [%r1826+2760];
	// begin inline asm
	dp4a.s32.s32 %r1605, %r1814, %r1607, %r1601;
	// end inline asm
	ld.shared.u32 	%r1611, [%r1826+2764];
	// begin inline asm
	dp4a.s32.s32 %r1609, %r1818, %r1611, %r1605;
	// end inline asm
	cvt.rn.f32.s32 	%f512, %r1609;
	mul.rn.ftz.f32 	%f513, %f481, %f512;
	ld.shared.f32 	%f514, [%r1834+688];
	fma.rn.ftz.f32 	%f666, %f514, %f513, %f428;
	ld.shared.u32 	%r1615, [%r1826+3008];
	// begin inline asm
	dp4a.s32.s32 %r1613, %r1806, %r1615, %r1808;
	// end inline asm
	ld.shared.u32 	%r1619, [%r1826+3012];
	// begin inline asm
	dp4a.s32.s32 %r1617, %r1810, %r1619, %r1613;
	// end inline asm
	ld.shared.u32 	%r1623, [%r1826+3016];
	// begin inline asm
	dp4a.s32.s32 %r1621, %r1814, %r1623, %r1617;
	// end inline asm
	ld.shared.u32 	%r1627, [%r1826+3020];
	// begin inline asm
	dp4a.s32.s32 %r1625, %r1818, %r1627, %r1621;
	// end inline asm
	cvt.rn.f32.s32 	%f515, %r1625;
	mul.rn.ftz.f32 	%f516, %f481, %f515;
	ld.shared.f32 	%f517, [%r1834+752];
	fma.rn.ftz.f32 	%f665, %f517, %f516, %f432;
	ld.shared.u32 	%r1631, [%r1826+3264];
	// begin inline asm
	dp4a.s32.s32 %r1629, %r1806, %r1631, %r1808;
	// end inline asm
	ld.shared.u32 	%r1635, [%r1826+3268];
	// begin inline asm
	dp4a.s32.s32 %r1633, %r1810, %r1635, %r1629;
	// end inline asm
	ld.shared.u32 	%r1639, [%r1826+3272];
	// begin inline asm
	dp4a.s32.s32 %r1637, %r1814, %r1639, %r1633;
	// end inline asm
	ld.shared.u32 	%r1643, [%r1826+3276];
	// begin inline asm
	dp4a.s32.s32 %r1641, %r1818, %r1643, %r1637;
	// end inline asm
	cvt.rn.f32.s32 	%f518, %r1641;
	mul.rn.ftz.f32 	%f519, %f481, %f518;
	ld.shared.f32 	%f520, [%r1834+816];
	fma.rn.ftz.f32 	%f664, %f520, %f519, %f436;
	ld.shared.u32 	%r1647, [%r1826+3520];
	// begin inline asm
	dp4a.s32.s32 %r1645, %r1806, %r1647, %r1808;
	// end inline asm
	ld.shared.u32 	%r1651, [%r1826+3524];
	// begin inline asm
	dp4a.s32.s32 %r1649, %r1810, %r1651, %r1645;
	// end inline asm
	ld.shared.u32 	%r1655, [%r1826+3528];
	// begin inline asm
	dp4a.s32.s32 %r1653, %r1814, %r1655, %r1649;
	// end inline asm
	ld.shared.u32 	%r1659, [%r1826+3532];
	// begin inline asm
	dp4a.s32.s32 %r1657, %r1818, %r1659, %r1653;
	// end inline asm
	cvt.rn.f32.s32 	%f521, %r1657;
	mul.rn.ftz.f32 	%f522, %f481, %f521;
	ld.shared.f32 	%f523, [%r1834+880];
	fma.rn.ftz.f32 	%f663, %f523, %f522, %f440;
	ld.shared.u32 	%r1663, [%r1826+3776];
	// begin inline asm
	dp4a.s32.s32 %r1661, %r1806, %r1663, %r1808;
	// end inline asm
	ld.shared.u32 	%r1667, [%r1826+3780];
	// begin inline asm
	dp4a.s32.s32 %r1665, %r1810, %r1667, %r1661;
	// end inline asm
	ld.shared.u32 	%r1671, [%r1826+3784];
	// begin inline asm
	dp4a.s32.s32 %r1669, %r1814, %r1671, %r1665;
	// end inline asm
	ld.shared.u32 	%r1675, [%r1826+3788];
	// begin inline asm
	dp4a.s32.s32 %r1673, %r1818, %r1675, %r1669;
	// end inline asm
	cvt.rn.f32.s32 	%f524, %r1673;
	mul.rn.ftz.f32 	%f525, %f481, %f524;
	ld.shared.f32 	%f526, [%r1834+944];
	fma.rn.ftz.f32 	%f662, %f526, %f525, %f444;
	ld.shared.u32 	%r1679, [%r1826+4032];
	// begin inline asm
	dp4a.s32.s32 %r1677, %r1806, %r1679, %r1808;
	// end inline asm
	ld.shared.u32 	%r1683, [%r1826+4036];
	// begin inline asm
	dp4a.s32.s32 %r1681, %r1810, %r1683, %r1677;
	// end inline asm
	ld.shared.u32 	%r1687, [%r1826+4040];
	// begin inline asm
	dp4a.s32.s32 %r1685, %r1814, %r1687, %r1681;
	// end inline asm
	ld.shared.u32 	%r1691, [%r1826+4044];
	// begin inline asm
	dp4a.s32.s32 %r1689, %r1818, %r1691, %r1685;
	// end inline asm
	cvt.rn.f32.s32 	%f527, %r1689;
	mul.rn.ftz.f32 	%f528, %f481, %f527;
	ld.shared.f32 	%f529, [%r1834+1008];
	fma.rn.ftz.f32 	%f661, %f529, %f528, %f448;
	ld.shared.u32 	%r1695, [%r1826+4288];
	// begin inline asm
	dp4a.s32.s32 %r1693, %r1806, %r1695, %r1808;
	// end inline asm
	ld.shared.u32 	%r1699, [%r1826+4292];
	// begin inline asm
	dp4a.s32.s32 %r1697, %r1810, %r1699, %r1693;
	// end inline asm
	ld.shared.u32 	%r1703, [%r1826+4296];
	// begin inline asm
	dp4a.s32.s32 %r1701, %r1814, %r1703, %r1697;
	// end inline asm
	ld.shared.u32 	%r1707, [%r1826+4300];
	// begin inline asm
	dp4a.s32.s32 %r1705, %r1818, %r1707, %r1701;
	// end inline asm
	cvt.rn.f32.s32 	%f530, %r1705;
	mul.rn.ftz.f32 	%f531, %f481, %f530;
	ld.shared.f32 	%f532, [%r1834+1072];
	fma.rn.ftz.f32 	%f660, %f532, %f531, %f452;
	ld.shared.u32 	%r1711, [%r1826+4544];
	// begin inline asm
	dp4a.s32.s32 %r1709, %r1806, %r1711, %r1808;
	// end inline asm
	ld.shared.u32 	%r1715, [%r1826+4548];
	// begin inline asm
	dp4a.s32.s32 %r1713, %r1810, %r1715, %r1709;
	// end inline asm
	ld.shared.u32 	%r1719, [%r1826+4552];
	// begin inline asm
	dp4a.s32.s32 %r1717, %r1814, %r1719, %r1713;
	// end inline asm
	ld.shared.u32 	%r1723, [%r1826+4556];
	// begin inline asm
	dp4a.s32.s32 %r1721, %r1818, %r1723, %r1717;
	// end inline asm
	cvt.rn.f32.s32 	%f533, %r1721;
	mul.rn.ftz.f32 	%f534, %f481, %f533;
	ld.shared.f32 	%f535, [%r1834+1136];
	fma.rn.ftz.f32 	%f659, %f535, %f534, %f456;
	ld.shared.u32 	%r1727, [%r1826+4800];
	// begin inline asm
	dp4a.s32.s32 %r1725, %r1806, %r1727, %r1808;
	// end inline asm
	ld.shared.u32 	%r1731, [%r1826+4804];
	// begin inline asm
	dp4a.s32.s32 %r1729, %r1810, %r1731, %r1725;
	// end inline asm
	ld.shared.u32 	%r1735, [%r1826+4808];
	// begin inline asm
	dp4a.s32.s32 %r1733, %r1814, %r1735, %r1729;
	// end inline asm
	ld.shared.u32 	%r1739, [%r1826+4812];
	// begin inline asm
	dp4a.s32.s32 %r1737, %r1818, %r1739, %r1733;
	// end inline asm
	cvt.rn.f32.s32 	%f536, %r1737;
	mul.rn.ftz.f32 	%f537, %f481, %f536;
	ld.shared.f32 	%f538, [%r1834+1200];
	fma.rn.ftz.f32 	%f658, %f538, %f537, %f460;
	ld.shared.u32 	%r1743, [%r1826+5056];
	// begin inline asm
	dp4a.s32.s32 %r1741, %r1806, %r1743, %r1808;
	// end inline asm
	ld.shared.u32 	%r1747, [%r1826+5060];
	// begin inline asm
	dp4a.s32.s32 %r1745, %r1810, %r1747, %r1741;
	// end inline asm
	ld.shared.u32 	%r1751, [%r1826+5064];
	// begin inline asm
	dp4a.s32.s32 %r1749, %r1814, %r1751, %r1745;
	// end inline asm
	ld.shared.u32 	%r1755, [%r1826+5068];
	// begin inline asm
	dp4a.s32.s32 %r1753, %r1818, %r1755, %r1749;
	// end inline asm
	cvt.rn.f32.s32 	%f539, %r1753;
	mul.rn.ftz.f32 	%f540, %f481, %f539;
	ld.shared.f32 	%f541, [%r1834+1264];
	fma.rn.ftz.f32 	%f657, %f541, %f540, %f464;
	ld.shared.u32 	%r1759, [%r1826+5312];
	// begin inline asm
	dp4a.s32.s32 %r1757, %r1806, %r1759, %r1808;
	// end inline asm
	ld.shared.u32 	%r1763, [%r1826+5316];
	// begin inline asm
	dp4a.s32.s32 %r1761, %r1810, %r1763, %r1757;
	// end inline asm
	ld.shared.u32 	%r1767, [%r1826+5320];
	// begin inline asm
	dp4a.s32.s32 %r1765, %r1814, %r1767, %r1761;
	// end inline asm
	ld.shared.u32 	%r1771, [%r1826+5324];
	// begin inline asm
	dp4a.s32.s32 %r1769, %r1818, %r1771, %r1765;
	// end inline asm
	cvt.rn.f32.s32 	%f542, %r1769;
	mul.rn.ftz.f32 	%f543, %f481, %f542;
	ld.shared.f32 	%f544, [%r1834+1328];
	fma.rn.ftz.f32 	%f677, %f544, %f543, %f468;
	ld.shared.u32 	%r1775, [%r1826+5568];
	// begin inline asm
	dp4a.s32.s32 %r1773, %r1806, %r1775, %r1808;
	// end inline asm
	ld.shared.u32 	%r1779, [%r1826+5572];
	// begin inline asm
	dp4a.s32.s32 %r1777, %r1810, %r1779, %r1773;
	// end inline asm
	ld.shared.u32 	%r1783, [%r1826+5576];
	// begin inline asm
	dp4a.s32.s32 %r1781, %r1814, %r1783, %r1777;
	// end inline asm
	ld.shared.u32 	%r1787, [%r1826+5580];
	// begin inline asm
	dp4a.s32.s32 %r1785, %r1818, %r1787, %r1781;
	// end inline asm
	cvt.rn.f32.s32 	%f545, %r1785;
	mul.rn.ftz.f32 	%f546, %f481, %f545;
	ld.shared.f32 	%f547, [%r1834+1392];
	fma.rn.ftz.f32 	%f678, %f547, %f546, %f472;
	ld.shared.u32 	%r1791, [%r1826+5824];
	// begin inline asm
	dp4a.s32.s32 %r1789, %r1806, %r1791, %r1808;
	// end inline asm
	ld.shared.u32 	%r1795, [%r1826+5828];
	// begin inline asm
	dp4a.s32.s32 %r1793, %r1810, %r1795, %r1789;
	// end inline asm
	ld.shared.u32 	%r1799, [%r1826+5832];
	// begin inline asm
	dp4a.s32.s32 %r1797, %r1814, %r1799, %r1793;
	// end inline asm
	ld.shared.u32 	%r1803, [%r1826+5836];
	// begin inline asm
	dp4a.s32.s32 %r1801, %r1818, %r1803, %r1797;
	// end inline asm
	cvt.rn.f32.s32 	%f548, %r1801;
	mul.rn.ftz.f32 	%f549, %f481, %f548;
	ld.shared.f32 	%f550, [%r1834+1456];
	fma.rn.ftz.f32 	%f679, %f550, %f549, %f476;
	ld.shared.u32 	%r1807, [%r1826+6080];
	// begin inline asm
	dp4a.s32.s32 %r1805, %r1806, %r1807, %r1808;
	// end inline asm
	ld.shared.u32 	%r1811, [%r1826+6084];
	// begin inline asm
	dp4a.s32.s32 %r1809, %r1810, %r1811, %r1805;
	// end inline asm
	ld.shared.u32 	%r1815, [%r1826+6088];
	// begin inline asm
	dp4a.s32.s32 %r1813, %r1814, %r1815, %r1809;
	// end inline asm
	ld.shared.u32 	%r1819, [%r1826+6092];
	// begin inline asm
	dp4a.s32.s32 %r1817, %r1818, %r1819, %r1813;
	// end inline asm
	cvt.rn.f32.s32 	%f551, %r1817;
	mul.rn.ftz.f32 	%f552, %f481, %f551;
	ld.shared.f32 	%f553, [%r1834+1520];
	fma.rn.ftz.f32 	%f680, %f553, %f552, %f480;

$L__BB0_46:
	bar.sync 	0;
	add.s32 	%r2070, %r2070, 256;
	setp.lt.s32 	%p30, %r2070, %r94;
	@%p30 bra 	$L__BB0_2;

$L__BB0_47:
	mov.u32 	%r1835, %tid.x;
	and.b32  	%r1836, %r1835, 3;
	setp.eq.s32 	%p31, %r1836, 0;
	setp.lt.s32 	%p32, %r2, %r95;
	and.pred  	%p1, %p31, %p32;
	not.pred 	%p33, %p1;
	mov.b32 	%r1837, %f676;
	mov.u32 	%r1838, 31;
	mov.u32 	%r1839, 2;
	mov.u32 	%r1840, -1;
	shfl.sync.down.b32 	%r1841|%p34, %r1837, %r1839, %r1838, %r1840;
	mov.b32 	%f554, %r1841;
	add.ftz.f32 	%f555, %f676, %f554;
	mov.b32 	%r1842, %f555;
	mov.u32 	%r1843, 1;
	shfl.sync.down.b32 	%r1844|%p35, %r1842, %r1843, %r1838, %r1840;
	mov.b32 	%f556, %r1844;
	add.ftz.f32 	%f111, %f555, %f556;
	setp.ge.s32 	%p36, %r3, %r96;
	or.pred  	%p37, %p33, %p36;
	@%p37 bra 	$L__BB0_49;

	mad.lo.s32 	%r1845, %r3, %r95, %r2;
	cvta.to.global.u64 	%rd46, %rd5;
	mul.wide.s32 	%rd47, %r1845, 4;
	add.s64 	%rd48, %rd46, %rd47;
	st.global.f32 	[%rd48], %f111;

$L__BB0_49:
	mov.b32 	%r1846, %f675;
	shfl.sync.down.b32 	%r1850|%p38, %r1846, %r1839, %r1838, %r1840;
	mov.b32 	%f557, %r1850;
	add.ftz.f32 	%f558, %f675, %f557;
	mov.b32 	%r1851, %f558;
	shfl.sync.down.b32 	%r1853|%p39, %r1851, %r1843, %r1838, %r1840;
	mov.b32 	%f559, %r1853;
	add.ftz.f32 	%f112, %f558, %f559;
	add.s32 	%r71, %r3, 1;
	setp.ge.s32 	%p40, %r71, %r96;
	or.pred  	%p42, %p33, %p40;
	@%p42 bra 	$L__BB0_51;

	mad.lo.s32 	%r1854, %r71, %r95, %r2;
	cvta.to.global.u64 	%rd49, %rd5;
	mul.wide.s32 	%rd50, %r1854, 4;
	add.s64 	%rd51, %rd49, %rd50;
	st.global.f32 	[%rd51], %f112;

$L__BB0_51:
	mov.b32 	%r1855, %f674;
	mov.u32 	%r1856, 31;
	mov.u32 	%r1857, 2;
	mov.u32 	%r1858, -1;
	shfl.sync.down.b32 	%r1859|%p43, %r1855, %r1857, %r1856, %r1858;
	mov.b32 	%f560, %r1859;
	add.ftz.f32 	%f561, %f674, %f560;
	mov.b32 	%r1860, %f561;
	mov.u32 	%r1861, 1;
	shfl.sync.down.b32 	%r1862|%p44, %r1860, %r1861, %r1856, %r1858;
	mov.b32 	%f562, %r1862;
	add.ftz.f32 	%f113, %f561, %f562;
	add.s32 	%r72, %r3, 2;
	setp.ge.s32 	%p45, %r72, %r96;
	or.pred  	%p47, %p33, %p45;
	@%p47 bra 	$L__BB0_53;

	mad.lo.s32 	%r1863, %r72, %r95, %r2;
	cvta.to.global.u64 	%rd52, %rd5;
	mul.wide.s32 	%rd53, %r1863, 4;
	add.s64 	%rd54, %rd52, %rd53;
	st.global.f32 	[%rd54], %f113;

$L__BB0_53:
	mov.b32 	%r1864, %f673;
	shfl.sync.down.b32 	%r1868|%p48, %r1864, %r1857, %r1856, %r1858;
	mov.b32 	%f563, %r1868;
	add.ftz.f32 	%f564, %f673, %f563;
	mov.b32 	%r1869, %f564;
	shfl.sync.down.b32 	%r1871|%p49, %r1869, %r1861, %r1856, %r1858;
	mov.b32 	%f565, %r1871;
	add.ftz.f32 	%f114, %f564, %f565;
	add.s32 	%r73, %r3, 3;
	setp.ge.s32 	%p50, %r73, %r96;
	or.pred  	%p52, %p33, %p50;
	@%p52 bra 	$L__BB0_55;

	mad.lo.s32 	%r1872, %r73, %r95, %r2;
	cvta.to.global.u64 	%rd55, %rd5;
	mul.wide.s32 	%rd56, %r1872, 4;
	add.s64 	%rd57, %rd55, %rd56;
	st.global.f32 	[%rd57], %f114;

$L__BB0_55:
	mov.b32 	%r1873, %f672;
	mov.u32 	%r1874, 31;
	mov.u32 	%r1875, 2;
	mov.u32 	%r1876, -1;
	shfl.sync.down.b32 	%r1877|%p53, %r1873, %r1875, %r1874, %r1876;
	mov.b32 	%f566, %r1877;
	add.ftz.f32 	%f567, %f672, %f566;
	mov.b32 	%r1878, %f567;
	mov.u32 	%r1879, 1;
	shfl.sync.down.b32 	%r1880|%p54, %r1878, %r1879, %r1874, %r1876;
	mov.b32 	%f568, %r1880;
	add.ftz.f32 	%f115, %f567, %f568;
	add.s32 	%r74, %r3, 4;
	setp.ge.s32 	%p55, %r74, %r96;
	or.pred  	%p57, %p33, %p55;
	@%p57 bra 	$L__BB0_57;

	mad.lo.s32 	%r1881, %r74, %r95, %r2;
	cvta.to.global.u64 	%rd58, %rd5;
	mul.wide.s32 	%rd59, %r1881, 4;
	add.s64 	%rd60, %rd58, %rd59;
	st.global.f32 	[%rd60], %f115;

$L__BB0_57:
	mov.b32 	%r1882, %f671;
	shfl.sync.down.b32 	%r1886|%p58, %r1882, %r1875, %r1874, %r1876;
	mov.b32 	%f569, %r1886;
	add.ftz.f32 	%f570, %f671, %f569;
	mov.b32 	%r1887, %f570;
	shfl.sync.down.b32 	%r1889|%p59, %r1887, %r1879, %r1874, %r1876;
	mov.b32 	%f571, %r1889;
	add.ftz.f32 	%f116, %f570, %f571;
	add.s32 	%r75, %r3, 5;
	setp.ge.s32 	%p60, %r75, %r96;
	or.pred  	%p62, %p33, %p60;
	@%p62 bra 	$L__BB0_59;

	mad.lo.s32 	%r1890, %r75, %r95, %r2;
	cvta.to.global.u64 	%rd61, %rd5;
	mul.wide.s32 	%rd62, %r1890, 4;
	add.s64 	%rd63, %rd61, %rd62;
	st.global.f32 	[%rd63], %f116;

$L__BB0_59:
	mov.b32 	%r1891, %f670;
	mov.u32 	%r1892, 31;
	mov.u32 	%r1893, 2;
	mov.u32 	%r1894, -1;
	shfl.sync.down.b32 	%r1895|%p63, %r1891, %r1893, %r1892, %r1894;
	mov.b32 	%f572, %r1895;
	add.ftz.f32 	%f573, %f670, %f572;
	mov.b32 	%r1896, %f573;
	mov.u32 	%r1897, 1;
	shfl.sync.down.b32 	%r1898|%p64, %r1896, %r1897, %r1892, %r1894;
	mov.b32 	%f574, %r1898;
	add.ftz.f32 	%f117, %f573, %f574;
	add.s32 	%r76, %r3, 6;
	setp.ge.s32 	%p65, %r76, %r96;
	or.pred  	%p67, %p33, %p65;
	@%p67 bra 	$L__BB0_61;

	mad.lo.s32 	%r1899, %r76, %r95, %r2;
	cvta.to.global.u64 	%rd64, %rd5;
	mul.wide.s32 	%rd65, %r1899, 4;
	add.s64 	%rd66, %rd64, %rd65;
	st.global.f32 	[%rd66], %f117;

$L__BB0_61:
	mov.b32 	%r1900, %f669;
	shfl.sync.down.b32 	%r1904|%p68, %r1900, %r1893, %r1892, %r1894;
	mov.b32 	%f575, %r1904;
	add.ftz.f32 	%f576, %f669, %f575;
	mov.b32 	%r1905, %f576;
	shfl.sync.down.b32 	%r1907|%p69, %r1905, %r1897, %r1892, %r1894;
	mov.b32 	%f577, %r1907;
	add.ftz.f32 	%f118, %f576, %f577;
	add.s32 	%r77, %r3, 7;
	setp.ge.s32 	%p70, %r77, %r96;
	or.pred  	%p72, %p33, %p70;
	@%p72 bra 	$L__BB0_63;

	mad.lo.s32 	%r1908, %r77, %r95, %r2;
	cvta.to.global.u64 	%rd67, %rd5;
	mul.wide.s32 	%rd68, %r1908, 4;
	add.s64 	%rd69, %rd67, %rd68;
	st.global.f32 	[%rd69], %f118;

$L__BB0_63:
	mov.b32 	%r1909, %f668;
	mov.u32 	%r1910, 31;
	mov.u32 	%r1911, 2;
	mov.u32 	%r1912, -1;
	shfl.sync.down.b32 	%r1913|%p73, %r1909, %r1911, %r1910, %r1912;
	mov.b32 	%f578, %r1913;
	add.ftz.f32 	%f579, %f668, %f578;
	mov.b32 	%r1914, %f579;
	mov.u32 	%r1915, 1;
	shfl.sync.down.b32 	%r1916|%p74, %r1914, %r1915, %r1910, %r1912;
	mov.b32 	%f580, %r1916;
	add.ftz.f32 	%f119, %f579, %f580;
	add.s32 	%r78, %r3, 8;
	setp.ge.s32 	%p75, %r78, %r96;
	or.pred  	%p77, %p33, %p75;
	@%p77 bra 	$L__BB0_65;

	mad.lo.s32 	%r1917, %r78, %r95, %r2;
	cvta.to.global.u64 	%rd70, %rd5;
	mul.wide.s32 	%rd71, %r1917, 4;
	add.s64 	%rd72, %rd70, %rd71;
	st.global.f32 	[%rd72], %f119;

$L__BB0_65:
	mov.b32 	%r1918, %f667;
	shfl.sync.down.b32 	%r1922|%p78, %r1918, %r1911, %r1910, %r1912;
	mov.b32 	%f581, %r1922;
	add.ftz.f32 	%f582, %f667, %f581;
	mov.b32 	%r1923, %f582;
	shfl.sync.down.b32 	%r1925|%p79, %r1923, %r1915, %r1910, %r1912;
	mov.b32 	%f583, %r1925;
	add.ftz.f32 	%f120, %f582, %f583;
	add.s32 	%r79, %r3, 9;
	setp.ge.s32 	%p80, %r79, %r96;
	or.pred  	%p82, %p33, %p80;
	@%p82 bra 	$L__BB0_67;

	mad.lo.s32 	%r1926, %r79, %r95, %r2;
	cvta.to.global.u64 	%rd73, %rd5;
	mul.wide.s32 	%rd74, %r1926, 4;
	add.s64 	%rd75, %rd73, %rd74;
	st.global.f32 	[%rd75], %f120;

$L__BB0_67:
	mov.b32 	%r1927, %f666;
	mov.u32 	%r1928, 31;
	mov.u32 	%r1929, 2;
	mov.u32 	%r1930, -1;
	shfl.sync.down.b32 	%r1931|%p83, %r1927, %r1929, %r1928, %r1930;
	mov.b32 	%f584, %r1931;
	add.ftz.f32 	%f585, %f666, %f584;
	mov.b32 	%r1932, %f585;
	mov.u32 	%r1933, 1;
	shfl.sync.down.b32 	%r1934|%p84, %r1932, %r1933, %r1928, %r1930;
	mov.b32 	%f586, %r1934;
	add.ftz.f32 	%f121, %f585, %f586;
	add.s32 	%r80, %r3, 10;
	setp.ge.s32 	%p85, %r80, %r96;
	or.pred  	%p87, %p33, %p85;
	@%p87 bra 	$L__BB0_69;

	mad.lo.s32 	%r1935, %r80, %r95, %r2;
	cvta.to.global.u64 	%rd76, %rd5;
	mul.wide.s32 	%rd77, %r1935, 4;
	add.s64 	%rd78, %rd76, %rd77;
	st.global.f32 	[%rd78], %f121;

$L__BB0_69:
	mov.b32 	%r1936, %f665;
	shfl.sync.down.b32 	%r1940|%p88, %r1936, %r1929, %r1928, %r1930;
	mov.b32 	%f587, %r1940;
	add.ftz.f32 	%f588, %f665, %f587;
	mov.b32 	%r1941, %f588;
	shfl.sync.down.b32 	%r1943|%p89, %r1941, %r1933, %r1928, %r1930;
	mov.b32 	%f589, %r1943;
	add.ftz.f32 	%f122, %f588, %f589;
	add.s32 	%r81, %r3, 11;
	setp.ge.s32 	%p90, %r81, %r96;
	or.pred  	%p92, %p33, %p90;
	@%p92 bra 	$L__BB0_71;

	mad.lo.s32 	%r1944, %r81, %r95, %r2;
	cvta.to.global.u64 	%rd79, %rd5;
	mul.wide.s32 	%rd80, %r1944, 4;
	add.s64 	%rd81, %rd79, %rd80;
	st.global.f32 	[%rd81], %f122;

$L__BB0_71:
	mov.b32 	%r1945, %f664;
	mov.u32 	%r1946, 31;
	mov.u32 	%r1947, 2;
	mov.u32 	%r1948, -1;
	shfl.sync.down.b32 	%r1949|%p93, %r1945, %r1947, %r1946, %r1948;
	mov.b32 	%f590, %r1949;
	add.ftz.f32 	%f591, %f664, %f590;
	mov.b32 	%r1950, %f591;
	mov.u32 	%r1951, 1;
	shfl.sync.down.b32 	%r1952|%p94, %r1950, %r1951, %r1946, %r1948;
	mov.b32 	%f592, %r1952;
	add.ftz.f32 	%f123, %f591, %f592;
	add.s32 	%r82, %r3, 12;
	setp.ge.s32 	%p95, %r82, %r96;
	or.pred  	%p97, %p33, %p95;
	@%p97 bra 	$L__BB0_73;

	mad.lo.s32 	%r1953, %r82, %r95, %r2;
	cvta.to.global.u64 	%rd82, %rd5;
	mul.wide.s32 	%rd83, %r1953, 4;
	add.s64 	%rd84, %rd82, %rd83;
	st.global.f32 	[%rd84], %f123;

$L__BB0_73:
	mov.b32 	%r1954, %f663;
	shfl.sync.down.b32 	%r1958|%p98, %r1954, %r1947, %r1946, %r1948;
	mov.b32 	%f593, %r1958;
	add.ftz.f32 	%f594, %f663, %f593;
	mov.b32 	%r1959, %f594;
	shfl.sync.down.b32 	%r1961|%p99, %r1959, %r1951, %r1946, %r1948;
	mov.b32 	%f595, %r1961;
	add.ftz.f32 	%f124, %f594, %f595;
	add.s32 	%r83, %r3, 13;
	setp.ge.s32 	%p100, %r83, %r96;
	or.pred  	%p102, %p33, %p100;
	@%p102 bra 	$L__BB0_75;

	mad.lo.s32 	%r1962, %r83, %r95, %r2;
	cvta.to.global.u64 	%rd85, %rd5;
	mul.wide.s32 	%rd86, %r1962, 4;
	add.s64 	%rd87, %rd85, %rd86;
	st.global.f32 	[%rd87], %f124;

$L__BB0_75:
	mov.b32 	%r1963, %f662;
	mov.u32 	%r1964, 31;
	mov.u32 	%r1965, 2;
	mov.u32 	%r1966, -1;
	shfl.sync.down.b32 	%r1967|%p103, %r1963, %r1965, %r1964, %r1966;
	mov.b32 	%f596, %r1967;
	add.ftz.f32 	%f597, %f662, %f596;
	mov.b32 	%r1968, %f597;
	mov.u32 	%r1969, 1;
	shfl.sync.down.b32 	%r1970|%p104, %r1968, %r1969, %r1964, %r1966;
	mov.b32 	%f598, %r1970;
	add.ftz.f32 	%f125, %f597, %f598;
	add.s32 	%r84, %r3, 14;
	setp.ge.s32 	%p105, %r84, %r96;
	or.pred  	%p107, %p33, %p105;
	@%p107 bra 	$L__BB0_77;

	mad.lo.s32 	%r1971, %r84, %r95, %r2;
	cvta.to.global.u64 	%rd88, %rd5;
	mul.wide.s32 	%rd89, %r1971, 4;
	add.s64 	%rd90, %rd88, %rd89;
	st.global.f32 	[%rd90], %f125;

$L__BB0_77:
	mov.b32 	%r1972, %f661;
	shfl.sync.down.b32 	%r1976|%p108, %r1972, %r1965, %r1964, %r1966;
	mov.b32 	%f599, %r1976;
	add.ftz.f32 	%f600, %f661, %f599;
	mov.b32 	%r1977, %f600;
	shfl.sync.down.b32 	%r1979|%p109, %r1977, %r1969, %r1964, %r1966;
	mov.b32 	%f601, %r1979;
	add.ftz.f32 	%f126, %f600, %f601;
	add.s32 	%r85, %r3, 15;
	setp.ge.s32 	%p110, %r85, %r96;
	or.pred  	%p112, %p33, %p110;
	@%p112 bra 	$L__BB0_79;

	mad.lo.s32 	%r1980, %r85, %r95, %r2;
	cvta.to.global.u64 	%rd91, %rd5;
	mul.wide.s32 	%rd92, %r1980, 4;
	add.s64 	%rd93, %rd91, %rd92;
	st.global.f32 	[%rd93], %f126;

$L__BB0_79:
	mov.b32 	%r1981, %f660;
	mov.u32 	%r1982, 31;
	mov.u32 	%r1983, 2;
	mov.u32 	%r1984, -1;
	shfl.sync.down.b32 	%r1985|%p113, %r1981, %r1983, %r1982, %r1984;
	mov.b32 	%f602, %r1985;
	add.ftz.f32 	%f603, %f660, %f602;
	mov.b32 	%r1986, %f603;
	mov.u32 	%r1987, 1;
	shfl.sync.down.b32 	%r1988|%p114, %r1986, %r1987, %r1982, %r1984;
	mov.b32 	%f604, %r1988;
	add.ftz.f32 	%f127, %f603, %f604;
	add.s32 	%r86, %r3, 16;
	setp.ge.s32 	%p115, %r86, %r96;
	or.pred  	%p117, %p33, %p115;
	@%p117 bra 	$L__BB0_81;

	mad.lo.s32 	%r1989, %r86, %r95, %r2;
	cvta.to.global.u64 	%rd94, %rd5;
	mul.wide.s32 	%rd95, %r1989, 4;
	add.s64 	%rd96, %rd94, %rd95;
	st.global.f32 	[%rd96], %f127;

$L__BB0_81:
	mov.b32 	%r1990, %f659;
	shfl.sync.down.b32 	%r1994|%p118, %r1990, %r1983, %r1982, %r1984;
	mov.b32 	%f605, %r1994;
	add.ftz.f32 	%f606, %f659, %f605;
	mov.b32 	%r1995, %f606;
	shfl.sync.down.b32 	%r1997|%p119, %r1995, %r1987, %r1982, %r1984;
	mov.b32 	%f607, %r1997;
	add.ftz.f32 	%f128, %f606, %f607;
	add.s32 	%r87, %r3, 17;
	setp.ge.s32 	%p120, %r87, %r96;
	or.pred  	%p122, %p33, %p120;
	@%p122 bra 	$L__BB0_83;

	mad.lo.s32 	%r1998, %r87, %r95, %r2;
	cvta.to.global.u64 	%rd97, %rd5;
	mul.wide.s32 	%rd98, %r1998, 4;
	add.s64 	%rd99, %rd97, %rd98;
	st.global.f32 	[%rd99], %f128;

$L__BB0_83:
	mov.b32 	%r1999, %f658;
	mov.u32 	%r2000, 31;
	mov.u32 	%r2001, 2;
	mov.u32 	%r2002, -1;
	shfl.sync.down.b32 	%r2003|%p123, %r1999, %r2001, %r2000, %r2002;
	mov.b32 	%f608, %r2003;
	add.ftz.f32 	%f609, %f658, %f608;
	mov.b32 	%r2004, %f609;
	mov.u32 	%r2005, 1;
	shfl.sync.down.b32 	%r2006|%p124, %r2004, %r2005, %r2000, %r2002;
	mov.b32 	%f610, %r2006;
	add.ftz.f32 	%f129, %f609, %f610;
	add.s32 	%r88, %r3, 18;
	setp.ge.s32 	%p125, %r88, %r96;
	or.pred  	%p127, %p33, %p125;
	@%p127 bra 	$L__BB0_85;

	mad.lo.s32 	%r2007, %r88, %r95, %r2;
	cvta.to.global.u64 	%rd100, %rd5;
	mul.wide.s32 	%rd101, %r2007, 4;
	add.s64 	%rd102, %rd100, %rd101;
	st.global.f32 	[%rd102], %f129;

$L__BB0_85:
	mov.b32 	%r2008, %f657;
	shfl.sync.down.b32 	%r2012|%p128, %r2008, %r2001, %r2000, %r2002;
	mov.b32 	%f611, %r2012;
	add.ftz.f32 	%f612, %f657, %f611;
	mov.b32 	%r2013, %f612;
	shfl.sync.down.b32 	%r2015|%p129, %r2013, %r2005, %r2000, %r2002;
	mov.b32 	%f613, %r2015;
	add.ftz.f32 	%f130, %f612, %f613;
	add.s32 	%r89, %r3, 19;
	setp.ge.s32 	%p130, %r89, %r96;
	or.pred  	%p132, %p33, %p130;
	@%p132 bra 	$L__BB0_87;

	mad.lo.s32 	%r2016, %r89, %r95, %r2;
	cvta.to.global.u64 	%rd103, %rd5;
	mul.wide.s32 	%rd104, %r2016, 4;
	add.s64 	%rd105, %rd103, %rd104;
	st.global.f32 	[%rd105], %f130;

$L__BB0_87:
	mov.b32 	%r2017, %f677;
	mov.u32 	%r2018, 31;
	mov.u32 	%r2019, 2;
	mov.u32 	%r2020, -1;
	shfl.sync.down.b32 	%r2021|%p133, %r2017, %r2019, %r2018, %r2020;
	mov.b32 	%f614, %r2021;
	add.ftz.f32 	%f615, %f677, %f614;
	mov.b32 	%r2022, %f615;
	mov.u32 	%r2023, 1;
	shfl.sync.down.b32 	%r2024|%p134, %r2022, %r2023, %r2018, %r2020;
	mov.b32 	%f616, %r2024;
	add.ftz.f32 	%f131, %f615, %f616;
	add.s32 	%r90, %r3, 20;
	setp.ge.s32 	%p135, %r90, %r96;
	or.pred  	%p137, %p33, %p135;
	@%p137 bra 	$L__BB0_89;

	mad.lo.s32 	%r2025, %r90, %r95, %r2;
	cvta.to.global.u64 	%rd106, %rd5;
	mul.wide.s32 	%rd107, %r2025, 4;
	add.s64 	%rd108, %rd106, %rd107;
	st.global.f32 	[%rd108], %f131;

$L__BB0_89:
	mov.b32 	%r2026, %f678;
	shfl.sync.down.b32 	%r2030|%p138, %r2026, %r2019, %r2018, %r2020;
	mov.b32 	%f617, %r2030;
	add.ftz.f32 	%f618, %f678, %f617;
	mov.b32 	%r2031, %f618;
	shfl.sync.down.b32 	%r2033|%p139, %r2031, %r2023, %r2018, %r2020;
	mov.b32 	%f619, %r2033;
	add.ftz.f32 	%f132, %f618, %f619;
	add.s32 	%r91, %r3, 21;
	setp.ge.s32 	%p140, %r91, %r96;
	or.pred  	%p142, %p33, %p140;
	@%p142 bra 	$L__BB0_91;

	mad.lo.s32 	%r2034, %r91, %r95, %r2;
	cvta.to.global.u64 	%rd109, %rd5;
	mul.wide.s32 	%rd110, %r2034, 4;
	add.s64 	%rd111, %rd109, %rd110;
	st.global.f32 	[%rd111], %f132;

$L__BB0_91:
	mov.b32 	%r2035, %f679;
	mov.u32 	%r2036, 31;
	mov.u32 	%r2037, 2;
	mov.u32 	%r2038, -1;
	shfl.sync.down.b32 	%r2039|%p143, %r2035, %r2037, %r2036, %r2038;
	mov.b32 	%f620, %r2039;
	add.ftz.f32 	%f621, %f679, %f620;
	mov.b32 	%r2040, %f621;
	mov.u32 	%r2041, 1;
	shfl.sync.down.b32 	%r2042|%p144, %r2040, %r2041, %r2036, %r2038;
	mov.b32 	%f622, %r2042;
	add.ftz.f32 	%f133, %f621, %f622;
	add.s32 	%r92, %r3, 22;
	setp.ge.s32 	%p145, %r92, %r96;
	or.pred  	%p147, %p33, %p145;
	@%p147 bra 	$L__BB0_93;

	mad.lo.s32 	%r2043, %r92, %r95, %r2;
	cvta.to.global.u64 	%rd112, %rd5;
	mul.wide.s32 	%rd113, %r2043, 4;
	add.s64 	%rd114, %rd112, %rd113;
	st.global.f32 	[%rd114], %f133;

$L__BB0_93:
	mov.b32 	%r2044, %f680;
	shfl.sync.down.b32 	%r2048|%p148, %r2044, %r2037, %r2036, %r2038;
	mov.b32 	%f623, %r2048;
	add.ftz.f32 	%f624, %f680, %f623;
	mov.b32 	%r2049, %f624;
	shfl.sync.down.b32 	%r2051|%p149, %r2049, %r2041, %r2036, %r2038;
	mov.b32 	%f625, %r2051;
	add.ftz.f32 	%f134, %f624, %f625;
	add.s32 	%r93, %r3, 23;
	setp.ge.s32 	%p150, %r93, %r96;
	or.pred  	%p152, %p33, %p150;
	@%p152 bra 	$L__BB0_95;

	mad.lo.s32 	%r2052, %r93, %r95, %r2;
	cvta.to.global.u64 	%rd115, %rd5;
	mul.wide.s32 	%rd116, %r2052, 4;
	add.s64 	%rd117, %rd115, %rd116;
	st.global.f32 	[%rd117], %f134;

$L__BB0_95:
	ret;

}

`
