//go:build amd64

#include "textflag.h"

// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_go_llama_q4_0_q8_0_8x4(SB), $0-32

    MOVQ q4+0(FP), DI
    MOVQ q8+8(FP), SI
    MOVQ blocks+16(FP), DX
    MOVQ out+24(FP), CX
    LEAQ ·kernelCompilerConsts<>(SB), R15

    WORD $0xd285                                                 // test    edx, edx
	JLE LBB0_1
    LONG $0x48ec8148; WORD $0x0002; BYTE $0x00                   // sub    rsp, 584
    LONG $0xf657c8c5                                             // vxorps    xmm6, xmm6, xmm6
    LONG $0xed57d0c5                                             // vxorps    xmm5, xmm5, xmm5
    LONG $0xd257e8c5                                             // vxorps    xmm2, xmm2, xmm2
    LONG $0xc057f8c5                                             // vxorps    xmm0, xmm0, xmm0
LBB0_4:
    LONG $0x4411fcc5; WORD $0x2024                               // vmovups    yword [rsp + 32], ymm0
    LONG $0x5411fcc5; WORD $0x4024                               // vmovups    yword [rsp + 64], ymm2
    QUAD $0x00020024ac11fcc5; BYTE $0x00                         // vmovups    yword [rsp + 512], ymm5
    QUAD $0x00022024b411fcc5; BYTE $0x00                         // vmovups    yword [rsp + 544], ymm6
    LONG $0x476ffec5; BYTE $0x10                                 // vmovdqu    ymm0, yword [rdi + 16]
    LONG $0x4f6ffec5; BYTE $0x30                                 // vmovdqu    ymm1, yword [rdi + 48]
    LONG $0x576ffec5; BYTE $0x50                                 // vmovdqu    ymm2, yword [rdi + 80]
    LONG $0x5f6ffec5; BYTE $0x70                                 // vmovdqu    ymm3, yword [rdi + 112]
    LONG $0x467d63c4; WORD $0x20d1                               // vperm2i128    ymm10, ymm0, ymm1, 32
    LONG $0x467d63c4; WORD $0x31e1                               // vperm2i128    ymm12, ymm0, ymm1, 49
    LONG $0x466de3c4; WORD $0x20eb                               // vperm2i128    ymm5, ymm2, ymm3, 32
    LONG $0x466d63c4; WORD $0x31db                               // vperm2i128    ymm11, ymm2, ymm3, 49
    LONG $0x717dc1c4; WORD $0x04d2                               // vpsrlw    ymm0, ymm10, 4
    LONG $0x787d42c4; WORD $0x2077                               // vpbroadcastb    ymm14, byte [r15 + 32]
    LONG $0xc0db8dc5                                             // vpand    ymm0, ymm14, ymm0
    LONG $0x6f7d41c4; BYTE $0x2f                                 // vmovdqa    ymm13, yword [r15]
    LONG $0x001562c4; BYTE $0xc8                                 // vpshufb    ymm9, ymm13, ymm0
    LONG $0x0c7f7ec5; BYTE $0x24                                 // vmovdqu    yword [rsp], ymm9
    LONG $0xd571fdc5; BYTE $0x04                                 // vpsrlw    ymm0, ymm5, 4
    LONG $0xc0db8dc5                                             // vpand    ymm0, ymm14, ymm0
    LONG $0x0015e2c4; BYTE $0xe0                                 // vpshufb    ymm4, ymm13, ymm0
    QUAD $0x0001c024a47ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 448], ymm4
    LONG $0x717dc1c4; WORD $0x04d3                               // vpsrlw    ymm0, ymm11, 4
    LONG $0xc0db8dc5                                             // vpand    ymm0, ymm14, ymm0
    LONG $0x0015e2c4; BYTE $0xf8                                 // vpshufb    ymm7, ymm13, ymm0
    QUAD $0x0001a024bc7ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 416], ymm7
    LONG $0x5e6ffec5; BYTE $0x48                                 // vmovdqu    ymm3, yword [rsi + 72]
    QUAD $0x0000c0249c7ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 192], ymm3
    LONG $0x466ffec5; BYTE $0x68                                 // vmovdqu    ymm0, yword [rsi + 104]
    QUAD $0x0000a024847ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 160], ymm0
    LONG $0xc070f9c5; BYTE $0xa0                                 // vpshufd    xmm0, xmm0, 160
    LONG $0x00fde3c4; WORD $0x44d0                               // vpermq    ymm2, ymm0, 68
    LONG $0x086de2c4; BYTE $0xca                                 // vpsignb    ymm1, ymm2, ymm2
    LONG $0xfc707dc5; BYTE $0x88                                 // vpshufd    ymm15, ymm4, 136
    LONG $0x0805e2c4; BYTE $0xc2                                 // vpsignb    ymm0, ymm15, ymm2
    LONG $0xe4efd9c5                                             // vpxor    xmm4, xmm4, xmm4
    LONG $0x5075e2c4; BYTE $0xe0                                 // {vex}    vpdpbusd    ymm4, ymm1, ymm0
    LONG $0xf46ffdc5                                             // vmovdqa    ymm6, ymm4
    LONG $0xc370f9c5; BYTE $0xa0                                 // vpshufd    xmm0, xmm3, 160
    LONG $0x00fde3c4; WORD $0x44c0                               // vpermq    ymm0, ymm0, 68
    LONG $0xe770fdc5; BYTE $0x88                                 // vpshufd    ymm4, ymm7, 136
    LONG $0x085de2c4; BYTE $0xd2                                 // vpsignb    ymm2, ymm4, ymm2
    LONG $0xef3941c4; BYTE $0xc0                                 // vpxor    xmm8, xmm8, xmm8
    LONG $0x507562c4; BYTE $0xc2                                 // {vex}    vpdpbusd    ymm8, ymm1, ymm2
    LONG $0x087de2c4; BYTE $0xc8                                 // vpsignb    ymm1, ymm0, ymm0
    LONG $0x707dc1c4; WORD $0x88f9                               // vpshufd    ymm7, ymm9, 136
    LONG $0x0845e2c4; BYTE $0xd0                                 // vpsignb    ymm2, ymm7, ymm0
    LONG $0x5075e2c4; BYTE $0xf2                                 // {vex}    vpdpbusd    ymm6, ymm1, ymm2
    LONG $0x716dc1c4; WORD $0x04d4                               // vpsrlw    ymm2, ymm12, 4
    LONG $0xd2db8dc5                                             // vpand    ymm2, ymm14, ymm2
    LONG $0x0015e2c4; BYTE $0xd2                                 // vpshufb    ymm2, ymm13, ymm2
    QUAD $0x00018024947ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 384], ymm2
    LONG $0xd270fdc5; BYTE $0x88                                 // vpshufd    ymm2, ymm2, 136
    QUAD $0x0000e024947ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 224], ymm2
    LONG $0x086de2c4; BYTE $0xc0                                 // vpsignb    ymm0, ymm2, ymm0
    LONG $0x507562c4; BYTE $0xc0                                 // {vex}    vpdpbusd    ymm8, ymm1, ymm0
    LONG $0xc5db8dc5                                             // vpand    ymm0, ymm14, ymm5
    LONG $0x0015e2c4; BYTE $0xd0                                 // vpshufb    ymm2, ymm13, ymm0
    QUAD $0x00016024947ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 352], ymm2
    LONG $0x466ffec5; BYTE $0x28                                 // vmovdqu    ymm0, yword [rsi + 40]
    QUAD $0x00008024847ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 128], ymm0
    LONG $0xc070f9c5; BYTE $0xa0                                 // vpshufd    xmm0, xmm0, 160
    LONG $0x00fde3c4; WORD $0x44e8                               // vpermq    ymm5, ymm0, 68
    LONG $0x085562c4; BYTE $0xcd                                 // vpsignb    ymm9, ymm5, ymm5
    LONG $0xda70fdc5; BYTE $0x88                                 // vpshufd    ymm3, ymm2, 136
    LONG $0x0865e2c4; BYTE $0xc5                                 // vpsignb    ymm0, ymm3, ymm5
    LONG $0x5035e2c4; BYTE $0xf0                                 // {vex}    vpdpbusd    ymm6, ymm9, ymm0
    LONG $0xdb25c1c4; BYTE $0xc6                                 // vpand    ymm0, ymm11, ymm14
    LONG $0x0015e2c4; BYTE $0xc0                                 // vpshufb    ymm0, ymm13, ymm0
    QUAD $0x00014024847ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 320], ymm0
    LONG $0xc870fdc5; BYTE $0x88                                 // vpshufd    ymm1, ymm0, 136
    LONG $0x0875e2c4; BYTE $0xed                                 // vpsignb    ymm5, ymm1, ymm5
    LONG $0x503562c4; BYTE $0xc5                                 // {vex}    vpdpbusd    ymm8, ymm9, ymm5
    LONG $0xdb2dc1c4; BYTE $0xee                                 // vpand    ymm5, ymm10, ymm14
    LONG $0x0015e2c4; BYTE $0xd5                                 // vpshufb    ymm2, ymm13, ymm5
    QUAD $0x00012024947ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 288], ymm2
    LONG $0x466ffec5; BYTE $0x08                                 // vmovdqu    ymm0, yword [rsi + 8]
    LONG $0x447ffec5; WORD $0x6024                               // vmovdqu    yword [rsp + 96], ymm0
    LONG $0xe870f9c5; BYTE $0xa0                                 // vpshufd    xmm5, xmm0, 160
    LONG $0x00fd63c4; WORD $0x44d5                               // vpermq    ymm10, ymm5, 68
    LONG $0x082d42c4; BYTE $0xda                                 // vpsignb    ymm11, ymm10, ymm10
    LONG $0xea70fdc5; BYTE $0x88                                 // vpshufd    ymm5, ymm2, 136
    LONG $0x085542c4; BYTE $0xca                                 // vpsignb    ymm9, ymm5, ymm10
    LONG $0x5025c2c4; BYTE $0xf1                                 // {vex}    vpdpbusd    ymm6, ymm11, ymm9
    QUAD $0x0001e024b47ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 480], ymm6
    LONG $0xdb1d41c4; BYTE $0xce                                 // vpand    ymm9, ymm12, ymm14
    LONG $0x0015c2c4; BYTE $0xc1                                 // vpshufb    ymm0, ymm13, ymm9
    QUAD $0x00010024847ffec5; BYTE $0x00                         // vmovdqu    yword [rsp + 256], ymm0
    LONG $0xc8707dc5; BYTE $0x88                                 // vpshufd    ymm9, ymm0, 136
    LONG $0x083542c4; BYTE $0xd2                                 // vpsignb    ymm10, ymm9, ymm10
    LONG $0x502542c4; BYTE $0xc2                                 // {vex}    vpdpbusd    ymm8, ymm11, ymm10
    QUAD $0x0000a024ac6f7ec5; BYTE $0x00                         // vmovdqu    ymm13, yword [rsp + 160]
    LONG $0x707d41c4; WORD $0xa0d5                               // vpshufd    ymm10, ymm13, 160
    LONG $0x00fd43c4; WORD $0xeed2                               // vpermq    ymm10, ymm10, 238
    LONG $0x080542c4; BYTE $0xda                                 // vpsignb    ymm11, ymm15, ymm10
    LONG $0x082dc2c4; BYTE $0xc2                                 // vpsignb    ymm0, ymm10, ymm10
    LONG $0xef1941c4; BYTE $0xe4                                 // vpxor    xmm12, xmm12, xmm12
    LONG $0x507d42c4; BYTE $0xe3                                 // {vex}    vpdpbusd    ymm12, ymm0, ymm11
    LONG $0x085dc2c4; BYTE $0xe2                                 // vpsignb    ymm4, ymm4, ymm10
    LONG $0xef0141c4; BYTE $0xff                                 // vpxor    xmm15, xmm15, xmm15
    LONG $0x507d62c4; BYTE $0xfc                                 // {vex}    vpdpbusd    ymm15, ymm0, ymm4
    QUAD $0x0000c024946f7ec5; BYTE $0x00                         // vmovdqu    ymm10, yword [rsp + 192]
    LONG $0x707dc1c4; WORD $0xa0c2                               // vpshufd    ymm0, ymm10, 160
    LONG $0x00fde3c4; WORD $0xeec0                               // vpermq    ymm0, ymm0, 238
    LONG $0x0845e2c4; BYTE $0xe0                                 // vpsignb    ymm4, ymm7, ymm0
    LONG $0x087de2c4; BYTE $0xf8                                 // vpsignb    ymm7, ymm0, ymm0
    LONG $0x504562c4; BYTE $0xe4                                 // {vex}    vpdpbusd    ymm12, ymm7, ymm4
    QUAD $0x0000e024946ffec5; BYTE $0x00                         // vmovdqu    ymm2, yword [rsp + 224]
    LONG $0x086de2c4; BYTE $0xc0                                 // vpsignb    ymm0, ymm2, ymm0
    LONG $0x504562c4; BYTE $0xf8                                 // {vex}    vpdpbusd    ymm15, ymm7, ymm0
    QUAD $0x00008024bc6ffec5; BYTE $0x00                         // vmovdqu    ymm7, yword [rsp + 128]
    LONG $0xc770fdc5; BYTE $0xa0                                 // vpshufd    ymm0, ymm7, 160
    LONG $0x00fde3c4; WORD $0xeec0                               // vpermq    ymm0, ymm0, 238
    LONG $0x0865e2c4; BYTE $0xd0                                 // vpsignb    ymm2, ymm3, ymm0
    LONG $0x087de2c4; BYTE $0xd8                                 // vpsignb    ymm3, ymm0, ymm0
    LONG $0x506562c4; BYTE $0xe2                                 // {vex}    vpdpbusd    ymm12, ymm3, ymm2
    LONG $0x0875e2c4; BYTE $0xc0                                 // vpsignb    ymm0, ymm1, ymm0
    LONG $0x506562c4; BYTE $0xf8                                 // {vex}    vpdpbusd    ymm15, ymm3, ymm0
    LONG $0x746ffec5; WORD $0x6024                               // vmovdqu    ymm6, yword [rsp + 96]
    LONG $0xc670fdc5; BYTE $0xa0                                 // vpshufd    ymm0, ymm6, 160
    LONG $0x00fde3c4; WORD $0xeec0                               // vpermq    ymm0, ymm0, 238
    LONG $0x0855e2c4; BYTE $0xc8                                 // vpsignb    ymm1, ymm5, ymm0
    LONG $0x087de2c4; BYTE $0xd0                                 // vpsignb    ymm2, ymm0, ymm0
    LONG $0x506d62c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm12, ymm2, ymm1
    LONG $0x0835e2c4; BYTE $0xc0                                 // vpsignb    ymm0, ymm9, ymm0
    LONG $0x506d62c4; BYTE $0xf8                                 // {vex}    vpdpbusd    ymm15, ymm2, ymm0
    LONG $0x7079c1c4; WORD $0xf5c5                               // vpshufd    xmm0, xmm13, 245
    LONG $0x00fde3c4; WORD $0x44c8                               // vpermq    ymm1, ymm0, 68
    QUAD $0x0001c024b4707dc5; WORD $0xdd00                       // vpshufd    ymm14, yword [rsp + 448], 221
    LONG $0x0875e2c4; BYTE $0xd9                                 // vpsignb    ymm3, ymm1, ymm1
    LONG $0x080de2c4; BYTE $0xd1                                 // vpsignb    ymm2, ymm14, ymm1
    LONG $0xe4efd9c5                                             // vpxor    xmm4, xmm4, xmm4
    LONG $0x5065e2c4; BYTE $0xe2                                 // {vex}    vpdpbusd    ymm4, ymm3, ymm2
    QUAD $0x0001a0249c707dc5; WORD $0xdd00                       // vpshufd    ymm11, yword [rsp + 416], 221
    LONG $0x0825e2c4; BYTE $0xc9                                 // vpsignb    ymm1, ymm11, ymm1
    LONG $0xd2efe9c5                                             // vpxor    xmm2, xmm2, xmm2
    LONG $0x5065e2c4; BYTE $0xd1                                 // {vex}    vpdpbusd    ymm2, ymm3, ymm1
    LONG $0x7079c1c4; WORD $0xf5ca                               // vpshufd    xmm1, xmm10, 245
    LONG $0x00fde3c4; WORD $0x44c9                               // vpermq    ymm1, ymm1, 68
    LONG $0x0470fdc5; WORD $0xdd24                               // vpshufd    ymm0, yword [rsp], 221
    LONG $0x047ffec5; BYTE $0x24                                 // vmovdqu    yword [rsp], ymm0
    LONG $0x0875e2c4; BYTE $0xd9                                 // vpsignb    ymm3, ymm1, ymm1
    LONG $0x087de2c4; BYTE $0xe9                                 // vpsignb    ymm5, ymm0, ymm1
    LONG $0x5065e2c4; BYTE $0xe5                                 // {vex}    vpdpbusd    ymm4, ymm3, ymm5
    QUAD $0x000180248c707dc5; WORD $0xdd00                       // vpshufd    ymm9, yword [rsp + 384], 221
    LONG $0x0835e2c4; BYTE $0xc9                                 // vpsignb    ymm1, ymm9, ymm1
    LONG $0x5065e2c4; BYTE $0xd1                                 // {vex}    vpdpbusd    ymm2, ymm3, ymm1
    LONG $0xcf70f9c5; BYTE $0xf5                                 // vpshufd    xmm1, xmm7, 245
    LONG $0x00fde3c4; WORD $0x44d9                               // vpermq    ymm3, ymm1, 68
    QUAD $0x0001602494707dc5; WORD $0xdd00                       // vpshufd    ymm10, yword [rsp + 352], 221
    LONG $0x0865e2c4; BYTE $0xfb                                 // vpsignb    ymm7, ymm3, ymm3
    LONG $0x082de2c4; BYTE $0xcb                                 // vpsignb    ymm1, ymm10, ymm3
    LONG $0x5045e2c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm4, ymm7, ymm1
    QUAD $0x00014024ac70fdc5; WORD $0xdd00                       // vpshufd    ymm5, yword [rsp + 320], 221
    LONG $0x0855e2c4; BYTE $0xdb                                 // vpsignb    ymm3, ymm5, ymm3
    LONG $0x5045e2c4; BYTE $0xd3                                 // {vex}    vpdpbusd    ymm2, ymm7, ymm3
    LONG $0xde70f9c5; BYTE $0xf5                                 // vpshufd    xmm3, xmm6, 245
    LONG $0x00fde3c4; WORD $0x44c3                               // vpermq    ymm0, ymm3, 68
    QUAD $0x00012024ac707dc5; WORD $0xdd00                       // vpshufd    ymm13, yword [rsp + 288], 221
    LONG $0x087de2c4; BYTE $0xc8                                 // vpsignb    ymm1, ymm0, ymm0
    LONG $0x0815e2c4; BYTE $0xd8                                 // vpsignb    ymm3, ymm13, ymm0
    LONG $0x5075e2c4; BYTE $0xe3                                 // {vex}    vpdpbusd    ymm4, ymm1, ymm3
    QUAD $0x00010024bc70fdc5; WORD $0xdd00                       // vpshufd    ymm7, yword [rsp + 256], 221
    LONG $0x0845e2c4; BYTE $0xc0                                 // vpsignb    ymm0, ymm7, ymm0
    LONG $0x5075e2c4; BYTE $0xd0                                 // {vex}    vpdpbusd    ymm2, ymm1, ymm0
    QUAD $0x0000a0248470fdc5; WORD $0xf500                       // vpshufd    ymm0, yword [rsp + 160], 245
    LONG $0x00fde3c4; WORD $0xeec8                               // vpermq    ymm1, ymm0, 238
    LONG $0x080d62c4; BYTE $0xf1                                 // vpsignb    ymm14, ymm14, ymm1
    LONG $0x0875e2c4; BYTE $0xd9                                 // vpsignb    ymm3, ymm1, ymm1
    LONG $0xc0eff9c5                                             // vpxor    xmm0, xmm0, xmm0
    LONG $0x5065c2c4; BYTE $0xc6                                 // {vex}    vpdpbusd    ymm0, ymm3, ymm14
    LONG $0x0825e2c4; BYTE $0xc9                                 // vpsignb    ymm1, ymm11, ymm1
    LONG $0xef2141c4; BYTE $0xdb                                 // vpxor    xmm11, xmm11, xmm11
    LONG $0x506562c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm3, ymm1
    QUAD $0x0000c0248c70fdc5; WORD $0xf500                       // vpshufd    ymm1, yword [rsp + 192], 245
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x1c6ffec5; BYTE $0x24                                 // vmovdqu    ymm3, yword [rsp]
    LONG $0x0865e2c4; BYTE $0xd9                                 // vpsignb    ymm3, ymm3, ymm1
    LONG $0x087562c4; BYTE $0xf1                                 // vpsignb    ymm14, ymm1, ymm1
    LONG $0x500de2c4; BYTE $0xc3                                 // {vex}    vpdpbusd    ymm0, ymm14, ymm3
    LONG $0x0835e2c4; BYTE $0xc9                                 // vpsignb    ymm1, ymm9, ymm1
    LONG $0x500d62c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm14, ymm1
    QUAD $0x000080248c70fdc5; WORD $0xf500                       // vpshufd    ymm1, yword [rsp + 128], 245
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x0875e2c4; BYTE $0xd9                                 // vpsignb    ymm3, ymm1, ymm1
    LONG $0x082d62c4; BYTE $0xc9                                 // vpsignb    ymm9, ymm10, ymm1
    LONG $0x5065c2c4; BYTE $0xc1                                 // {vex}    vpdpbusd    ymm0, ymm3, ymm9
    LONG $0x0855e2c4; BYTE $0xc9                                 // vpsignb    ymm1, ymm5, ymm1
    LONG $0x506562c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm3, ymm1
    QUAD $0x0001e0248cfeddc5; BYTE $0x00                         // vpaddd    ymm1, ymm4, yword [rsp + 480]
    QUAD $0x00022024b410fcc5; BYTE $0x00                         // vmovups    ymm6, yword [rsp + 544]
    LONG $0xd2febdc5                                             // vpaddd    ymm2, ymm8, ymm2
    LONG $0x5c70fdc5; WORD $0x6024; BYTE $0xf5                   // vpshufd    ymm3, yword [rsp + 96], 245
    LONG $0x00fde3c4; WORD $0xeedb                               // vpermq    ymm3, ymm3, 238
    LONG $0x0865e2c4; BYTE $0xe3                                 // vpsignb    ymm4, ymm3, ymm3
    LONG $0x0815e2c4; BYTE $0xeb                                 // vpsignb    ymm5, ymm13, ymm3
    LONG $0x505de2c4; BYTE $0xc5                                 // {vex}    vpdpbusd    ymm0, ymm4, ymm5
    LONG $0x0845e2c4; BYTE $0xdb                                 // vpsignb    ymm3, ymm7, ymm3
    LONG $0x505d62c4; BYTE $0xdb                                 // {vex}    vpdpbusd    ymm11, ymm4, ymm3
    LONG $0xda6cf5c5                                             // vpunpcklqdq    ymm3, ymm1, ymm2
    LONG $0x137de2c4; BYTE $0x27                                 // vcvtph2ps    ymm4, oword [rdi]
    LONG $0x2ec4f9c5; BYTE $0x00                                 // vpinsrw    xmm5, xmm0, word [rsi], 0
    LONG $0x1379e2c4; BYTE $0xed                                 // vcvtph2ps    xmm5, xmm5
    LONG $0x187de2c4; BYTE $0xed                                 // vbroadcastss    ymm5, xmm5
    LONG $0xec59d4c5                                             // vmulps    ymm5, ymm5, ymm4
    LONG $0xdb5bfcc5                                             // vcvtdq2ps    ymm3, ymm3
    LONG $0xb855e2c4; BYTE $0xf3                                 // vfmadd231ps    ymm6, ymm5, ymm3
    LONG $0xc0fe9dc5                                             // vpaddd    ymm0, ymm12, ymm0
    LONG $0xfe25c1c4; BYTE $0xdf                                 // vpaddd    ymm3, ymm11, ymm15
    LONG $0x6ec4f9c5; WORD $0x0002                               // vpinsrw    xmm5, xmm0, word [rsi + 2], 0
    LONG $0xca6df5c5                                             // vpunpckhqdq    ymm1, ymm1, ymm2
    LONG $0x1379e2c4; BYTE $0xd5                                 // vcvtph2ps    xmm2, xmm5
    QUAD $0x00020024ac10fcc5; BYTE $0x00                         // vmovups    ymm5, yword [rsp + 512]
    LONG $0x187de2c4; BYTE $0xd2                                 // vbroadcastss    ymm2, xmm2
    LONG $0xd459ecc5                                             // vmulps    ymm2, ymm2, ymm4
    LONG $0xc95bfcc5                                             // vcvtdq2ps    ymm1, ymm1
    LONG $0xb86de2c4; BYTE $0xe9                                 // vfmadd231ps    ymm5, ymm2, ymm1
    LONG $0xcb6cfdc5                                             // vpunpcklqdq    ymm1, ymm0, ymm3
    LONG $0x56c4f9c5; WORD $0x0004                               // vpinsrw    xmm2, xmm0, word [rsi + 4], 0
    LONG $0x1379e2c4; BYTE $0xd2                                 // vcvtph2ps    xmm2, xmm2
    LONG $0x187de2c4; BYTE $0xd2                                 // vbroadcastss    ymm2, xmm2
    LONG $0xd459ecc5                                             // vmulps    ymm2, ymm2, ymm4
    LONG $0xc95bfcc5                                             // vcvtdq2ps    ymm1, ymm1
    LONG $0x7c10fcc5; WORD $0x4024                               // vmovups    ymm7, yword [rsp + 64]
    LONG $0xb86de2c4; BYTE $0xf9                                 // vfmadd231ps    ymm7, ymm2, ymm1
    LONG $0x7c11fcc5; WORD $0x4024                               // vmovups    yword [rsp + 64], ymm7
    LONG $0x5410fcc5; WORD $0x4024                               // vmovups    ymm2, yword [rsp + 64]
    LONG $0x4ec4f9c5; WORD $0x0006                               // vpinsrw    xmm1, xmm0, word [rsi + 6], 0
    LONG $0x1379e2c4; BYTE $0xc9                                 // vcvtph2ps    xmm1, xmm1
    LONG $0xc36dfdc5                                             // vpunpckhqdq    ymm0, ymm0, ymm3
    LONG $0x187de2c4; BYTE $0xc9                                 // vbroadcastss    ymm1, xmm1
    LONG $0xcc59f4c5                                             // vmulps    ymm1, ymm1, ymm4
    LONG $0xc05bfcc5                                             // vcvtdq2ps    ymm0, ymm0
    LONG $0x5c10fcc5; WORD $0x2024                               // vmovups    ymm3, yword [rsp + 32]
    LONG $0xb875e2c4; BYTE $0xd8                                 // vfmadd231ps    ymm3, ymm1, ymm0
    LONG $0x5c11fcc5; WORD $0x2024                               // vmovups    yword [rsp + 32], ymm3
    LONG $0x4410fcc5; WORD $0x2024                               // vmovups    ymm0, yword [rsp + 32]
    LONG $0x90c78148; WORD $0x0000; BYTE $0x00                   // add    rdi, 144
    LONG $0x88c68148; WORD $0x0000; BYTE $0x00                   // add    rsi, 136
    WORD $0xcaff                                                 // dec    edx
	JNE LBB0_4
    LONG $0x48c48148; WORD $0x0002; BYTE $0x00                   // add    rsp, 584
	JMP LBB0_2
LBB0_1:
    LONG $0xf657c8c5                                             // vxorps    xmm6, xmm6, xmm6
    LONG $0xed57d0c5                                             // vxorps    xmm5, xmm5, xmm5
    LONG $0xd257e8c5                                             // vxorps    xmm2, xmm2, xmm2
    LONG $0xc057f8c5                                             // vxorps    xmm0, xmm0, xmm0
LBB0_2:
    LONG $0x3111fcc5                                             // vmovups    yword [rcx], ymm6
    LONG $0x6911fcc5; BYTE $0x20                                 // vmovups    yword [rcx + 32], ymm5
    LONG $0x5111fcc5; BYTE $0x40                                 // vmovups    yword [rcx + 64], ymm2
    LONG $0x4111fcc5; BYTE $0x60                                 // vmovups    yword [rcx + 96], ymm0
    VZEROUPPER
    RET




DATA LCDATA2<>+0x000(SB)/8, $0x0f0f0f0f88888888
DATA LCDATA2<>+0x008(SB)/8, $0x0000000000000000
DATA LCDATA2<>+0x010(SB)/8, $0x0000000000000000
DATA LCDATA2<>+0x018(SB)/8, $0x0000000000000000
DATA LCDATA2<>+0x020(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA2<>+0x028(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA2<>+0x030(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA2<>+0x038(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA2<>+0x040(SB)/8, $0x0101010101010101
DATA LCDATA2<>+0x048(SB)/8, $0x0101010101010101
DATA LCDATA2<>+0x050(SB)/8, $0x0101010101010101
DATA LCDATA2<>+0x058(SB)/8, $0x0101010101010101
DATA LCDATA2<>+0x060(SB)/8, $0x000000000000010f
GLOBL LCDATA2<>(SB), 8, $104

TEXT ·_go_llama_q4_0_q8_0_8x16(SB), $72-32

    MOVQ q4+0(FP), DI
    MOVQ q8+8(FP), SI
    MOVQ blocks+16(FP), DX
    MOVQ out+24(FP), CX
    LEAQ ·kernelCompilerConsts<>(SB), R15
    ADDQ $72, SP
    LEAQ LCDATA2<>(SB), BP

    BYTE $0x55                                                   // push    rbp
    WORD $0x8948; BYTE $0xe5                                     // mov    rbp, rsp
    LONG $0xe0e48348                                             // and    rsp, -32
    LONG $0x20ec8148; WORD $0x0005; BYTE $0x00                   // sub    rsp, 1312
    LONG $0xc057f8c5                                             // vxorps    xmm0, xmm0, xmm0
    QUAD $0x0004e0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1248], ymm0
    QUAD $0x0004c0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1216], ymm0
    QUAD $0x0004a0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1184], ymm0
    QUAD $0x000480248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1152], ymm0
    QUAD $0x000460248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1120], ymm0
    QUAD $0x000440248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1088], ymm0
    QUAD $0x000420248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1056], ymm0
    QUAD $0x000400248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 1024], ymm0
    QUAD $0x0003e0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 992], ymm0
    QUAD $0x0003c0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 960], ymm0
    QUAD $0x0003a0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 928], ymm0
    QUAD $0x000380248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 896], ymm0
    QUAD $0x000360248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 864], ymm0
    QUAD $0x000340248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 832], ymm0
    QUAD $0x000320248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 800], ymm0
    QUAD $0x000300248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 768], ymm0
    WORD $0xd285                                                 // test    edx, edx
	JLE LBB1_5
    WORD $0xd089                                                 // mov    eax, edx
    WORD $0x8948; BYTE $0xc2                                     // mov    rdx, rax
    LONG $0x07e2c148                                             // shl    rdx, 7
    LONG $0xc2148d48                                             // lea    rdx, [rdx + 8*rax]
    WORD $0x3145; BYTE $0xc0                                     // xor    r8d, r8d
    LONG $0x187dc2c4; WORD $0x2447                               // vbroadcastss    ymm0, dword [r15 + 36]
    QUAD $0x0000a0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 160], ymm0
    LONG $0x187dc2c4; WORD $0x2847                               // vbroadcastss    ymm0, dword [r15 + 40]
    QUAD $0x000080248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 128], ymm0
LBB1_2:
    QUAD $0x0000a024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 160]
    LONG $0x47efddc5; BYTE $0x10                                 // vpxor    ymm0, ymm4, yword [rdi + 16]
    LONG $0x4fefddc5; BYTE $0x30                                 // vpxor    ymm1, ymm4, yword [rdi + 48]
    LONG $0x387de3c4; WORD $0x01d1                               // vinserti128    ymm2, ymm0, xmm1, 1
    LONG $0x5fefddc5; BYTE $0x50                                 // vpxor    ymm3, ymm4, yword [rdi + 80]
    LONG $0x67efddc5; BYTE $0x70                                 // vpxor    ymm4, ymm4, yword [rdi + 112]
    LONG $0x467de3c4; WORD $0x31c1                               // vperm2i128    ymm0, ymm0, ymm1, 49
    LONG $0x3865e3c4; WORD $0x01cc                               // vinserti128    ymm1, ymm3, xmm4, 1
    LONG $0x4665e3c4; WORD $0x31dc                               // vperm2i128    ymm3, ymm3, ymm4, 49
    LONG $0xd271ddc5; BYTE $0x04                                 // vpsrlw    ymm4, ymm2, 4
    LONG $0xd071d5c5; BYTE $0x04                                 // vpsrlw    ymm5, ymm0, 4
    LONG $0xd171cdc5; BYTE $0x04                                 // vpsrlw    ymm6, ymm1, 4
    LONG $0xd371c5c5; BYTE $0x04                                 // vpsrlw    ymm7, ymm3, 4
    QUAD $0x00008024846f7dc5; BYTE $0x00                         // vmovdqa    ymm8, yword [rsp + 128]
    LONG $0xd2dbbdc5                                             // vpand    ymm2, ymm8, ymm2
    LONG $0xc9dbbdc5                                             // vpand    ymm1, ymm8, ymm1
    LONG $0x787d42c4; WORD $0x204f                               // vpbroadcastb    ymm9, byte [r15 + 32]
    LONG $0xe4dbb5c5                                             // vpand    ymm4, ymm9, ymm4
    LONG $0xf6dbb5c5                                             // vpand    ymm6, ymm9, ymm6
    LONG $0xc0dbbdc5                                             // vpand    ymm0, ymm8, ymm0
    LONG $0xdbdbbdc5                                             // vpand    ymm3, ymm8, ymm3
    LONG $0xeddbb5c5                                             // vpand    ymm5, ymm9, ymm5
    LONG $0xffdbb5c5                                             // vpand    ymm7, ymm9, ymm7
    LONG $0xc6707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm6, 136
    QUAD $0x00028024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 640], ymm8
    LONG $0xc4707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm4, 136
    QUAD $0x00026024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 608], ymm8
    LONG $0xc1707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm1, 136
    QUAD $0x00024024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 576], ymm8
    LONG $0xc2707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm2, 136
    QUAD $0x00022024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 544], ymm8
    LONG $0xc7707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm7, 136
    QUAD $0x00020024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 512], ymm8
    LONG $0xc5707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm5, 136
    QUAD $0x0001e024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 480], ymm8
    LONG $0xc3707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm3, 136
    QUAD $0x0001c024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 448], ymm8
    LONG $0xc0707dc5; BYTE $0x88                                 // vpshufd    ymm8, ymm0, 136
    QUAD $0x0001a024847f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 416], ymm8
    LONG $0xf670fdc5; BYTE $0xdd                                 // vpshufd    ymm6, ymm6, 221
    LONG $0x747ffdc5; WORD $0x4024                               // vmovdqa    yword [rsp + 64], ymm6
    LONG $0xe470fdc5; BYTE $0xdd                                 // vpshufd    ymm4, ymm4, 221
    QUAD $0x00018024a47ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 384], ymm4
    LONG $0xc970fdc5; BYTE $0xdd                                 // vpshufd    ymm1, ymm1, 221
    QUAD $0x000160248c7ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 352], ymm1
    LONG $0xca70fdc5; BYTE $0xdd                                 // vpshufd    ymm1, ymm2, 221
    QUAD $0x000140248c7ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 320], ymm1
    LONG $0xcf70fdc5; BYTE $0xdd                                 // vpshufd    ymm1, ymm7, 221
    LONG $0x4c7ffdc5; WORD $0x2024                               // vmovdqa    yword [rsp + 32], ymm1
    LONG $0xcd70fdc5; BYTE $0xdd                                 // vpshufd    ymm1, ymm5, 221
    QUAD $0x000120248c7ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 288], ymm1
    LONG $0xcb70fdc5; BYTE $0xdd                                 // vpshufd    ymm1, ymm3, 221
    QUAD $0x000100248c7ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 256], ymm1
    LONG $0xc070fdc5; BYTE $0xdd                                 // vpshufd    ymm0, ymm0, 221
    QUAD $0x0000e024847ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 224], ymm0
    WORD $0x3145; BYTE $0xc9                                     // xor    r9d, r9d
    WORD $0x8949; BYTE $0xf2                                     // mov    r10, rsi
    LONG $0x137de2c4; BYTE $0x07                                 // vcvtph2ps    ymm0, oword [rdi]
    QUAD $0x0000c0248429fcc5; BYTE $0x00                         // vmovaps    yword [rsp + 192], ymm0
LBB1_3:
    LONG $0x6f7e41c4; WORD $0x2862                               // vmovdqu    ymm12, yword [r10 + 40]
    QUAD $0x0002e024a47f7dc5; BYTE $0x00                         // vmovdqa    yword [rsp + 736], ymm12
    LONG $0x6f7ec1c4; WORD $0x487a                               // vmovdqu    ymm7, yword [r10 + 72]
    QUAD $0x0002c024bc7ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 704], ymm7
    LONG $0x6f7ec1c4; WORD $0x684a                               // vmovdqu    ymm1, yword [r10 + 104]
    LONG $0x4c7ffdc5; WORD $0x6024                               // vmovdqa    yword [rsp + 96], ymm1
    LONG $0x6f7ac1c4; WORD $0x0852                               // vmovdqu    xmm2, oword [r10 + 8]
    LONG $0x147ff9c5; BYTE $0x24                                 // vmovdqa    oword [rsp], xmm2
    LONG $0x6f7ac1c4; WORD $0x285a                               // vmovdqu    xmm3, oword [r10 + 40]
    LONG $0x5c7ff9c5; WORD $0x1024                               // vmovdqa    oword [rsp + 16], xmm3
    LONG $0x6f7a41c4; WORD $0x4872                               // vmovdqu    xmm14, oword [r10 + 72]
    LONG $0x6f7a41c4; WORD $0x686a                               // vmovdqu    xmm13, oword [r10 + 104]
    LONG $0x7079c1c4; WORD $0xa0c5                               // vpshufd    xmm0, xmm13, 160
    LONG $0xef3941c4; BYTE $0xc0                                 // vpxor    xmm8, xmm8, xmm8
    LONG $0x707941c4; WORD $0xa0ce                               // vpshufd    xmm9, xmm14, 160
    LONG $0x00fd63c4; WORD $0x44d8                               // vpermq    ymm11, ymm0, 68
    LONG $0x00fd43c4; WORD $0x44c9                               // vpermq    ymm9, ymm9, 68
    LONG $0xc370f9c5; BYTE $0xa0                                 // vpshufd    xmm0, xmm3, 160
    LONG $0x00fd63c4; WORD $0x44f8                               // vpermq    ymm15, ymm0, 68
    QUAD $0x00028024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 640]
    LONG $0x505d42c4; BYTE $0xc3                                 // {vex}    vpdpbusd    ymm8, ymm4, ymm11
    LONG $0xc270f9c5; BYTE $0xa0                                 // vpshufd    xmm0, xmm2, 160
    LONG $0x00fde3c4; WORD $0x44f0                               // vpermq    ymm6, ymm0, 68
    LONG $0xef2941c4; BYTE $0xd2                                 // vpxor    xmm10, xmm10, xmm10
    QUAD $0x00026024ac6ffdc5; BYTE $0x00                         // vmovdqa    ymm5, yword [rsp + 608]
    LONG $0x505542c4; BYTE $0xc1                                 // {vex}    vpdpbusd    ymm8, ymm5, ymm9
    QUAD $0x00020024946ffdc5; BYTE $0x00                         // vmovdqa    ymm2, yword [rsp + 512]
    LONG $0x506d42c4; BYTE $0xd3                                 // {vex}    vpdpbusd    ymm10, ymm2, ymm11
    QUAD $0x0001e0249c6ffdc5; BYTE $0x00                         // vmovdqa    ymm3, yword [rsp + 480]
    LONG $0x506542c4; BYTE $0xd1                                 // {vex}    vpdpbusd    ymm10, ymm3, ymm9
    LONG $0xc9707dc5; BYTE $0xa0                                 // vpshufd    ymm9, ymm1, 160
    QUAD $0x00024024846ffdc5; BYTE $0x00                         // vmovdqa    ymm0, yword [rsp + 576]
    LONG $0x507d42c4; BYTE $0xc7                                 // {vex}    vpdpbusd    ymm8, ymm0, ymm15
    LONG $0x00fdc3c4; WORD $0xeec9                               // vpermq    ymm1, ymm9, 238
    LONG $0xef2141c4; BYTE $0xdb                                 // vpxor    xmm11, xmm11, xmm11
    LONG $0x505d62c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm4, ymm1
    QUAD $0x0001c024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 448]
    LONG $0x505d42c4; BYTE $0xd7                                 // {vex}    vpdpbusd    ymm10, ymm4, ymm15
    LONG $0xef3141c4; BYTE $0xc9                                 // vpxor    xmm9, xmm9, xmm9
    LONG $0x506d62c4; BYTE $0xc9                                 // {vex}    vpdpbusd    ymm9, ymm2, ymm1
    LONG $0xcf70fdc5; BYTE $0xa0                                 // vpshufd    ymm1, ymm7, 160
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x505562c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm5, ymm1
    LONG $0x506562c4; BYTE $0xc9                                 // {vex}    vpdpbusd    ymm9, ymm3, ymm1
    LONG $0x707dc1c4; WORD $0xa0cc                               // vpshufd    ymm1, ymm12, 160
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x507d62c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm0, ymm1
    LONG $0x505d62c4; BYTE $0xc9                                 // {vex}    vpdpbusd    ymm9, ymm4, ymm1
    LONG $0x7079c1c4; WORD $0xf5cd                               // vpshufd    xmm1, xmm13, 245
    QUAD $0x00022024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 544]
    LONG $0x505d62c4; BYTE $0xc6                                 // {vex}    vpdpbusd    ymm8, ymm4, ymm6
    LONG $0x00fde3c4; WORD $0x44c9                               // vpermq    ymm1, ymm1, 68
    LONG $0xef0141c4; BYTE $0xff                                 // vpxor    xmm15, xmm15, xmm15
    LONG $0x446ffdc5; WORD $0x4024                               // vmovdqa    ymm0, yword [rsp + 64]
    LONG $0x507d62c4; BYTE $0xf9                                 // {vex}    vpdpbusd    ymm15, ymm0, ymm1
    QUAD $0x0001a024ac6ffdc5; BYTE $0x00                         // vmovdqa    ymm5, yword [rsp + 416]
    LONG $0x505562c4; BYTE $0xd6                                 // {vex}    vpdpbusd    ymm10, ymm5, ymm6
    LONG $0xd2efe9c5                                             // vpxor    xmm2, xmm2, xmm2
    LONG $0x446ffdc5; WORD $0x2024                               // vmovdqa    ymm0, yword [rsp + 32]
    LONG $0x507de2c4; BYTE $0xd1                                 // {vex}    vpdpbusd    ymm2, ymm0, ymm1
    LONG $0x6f7ec1c4; WORD $0x0842                               // vmovdqu    ymm0, yword [r10 + 8]
    QUAD $0x0002a024847ffdc5; BYTE $0x00                         // vmovdqa    yword [rsp + 672], ymm0
    LONG $0x7079c1c4; WORD $0xf5ce                               // vpshufd    xmm1, xmm14, 245
    LONG $0x00fde3c4; WORD $0x44c9                               // vpermq    ymm1, ymm1, 68
    QUAD $0x00018024b46ffdc5; BYTE $0x00                         // vmovdqa    ymm6, yword [rsp + 384]
    LONG $0x504d62c4; BYTE $0xf9                                 // {vex}    vpdpbusd    ymm15, ymm6, ymm1
    QUAD $0x000120249c6ffdc5; BYTE $0x00                         // vmovdqa    ymm3, yword [rsp + 288]
    LONG $0x5065e2c4; BYTE $0xd1                                 // {vex}    vpdpbusd    ymm2, ymm3, ymm1
    LONG $0xc870fdc5; BYTE $0xa0                                 // vpshufd    ymm1, ymm0, 160
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x6c7079c5; WORD $0x1024; BYTE $0xf5                   // vpshufd    xmm13, oword [rsp + 16], 245
    LONG $0x00fd43c4; WORD $0x44ed                               // vpermq    ymm13, ymm13, 68
    QUAD $0x00016024b46f7dc5; BYTE $0x00                         // vmovdqa    ymm14, yword [rsp + 352]
    LONG $0x500d42c4; BYTE $0xfd                                 // {vex}    vpdpbusd    ymm15, ymm14, ymm13
    LONG $0x247079c5; WORD $0xf524                               // vpshufd    xmm12, oword [rsp], 245
    LONG $0x00fd43c4; WORD $0x44e4                               // vpermq    ymm12, ymm12, 68
    QUAD $0x00014024bc6ffdc5; BYTE $0x00                         // vmovdqa    ymm7, yword [rsp + 320]
    LONG $0x504542c4; BYTE $0xfc                                 // {vex}    vpdpbusd    ymm15, ymm7, ymm12
    LONG $0x505d62c4; BYTE $0xd9                                 // {vex}    vpdpbusd    ymm11, ymm4, ymm1
    QUAD $0x00010024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 256]
    LONG $0x505dc2c4; BYTE $0xd5                                 // {vex}    vpdpbusd    ymm2, ymm4, ymm13
    QUAD $0x0000e024846ffdc5; BYTE $0x00                         // vmovdqa    ymm0, yword [rsp + 224]
    LONG $0x507dc2c4; BYTE $0xd4                                 // {vex}    vpdpbusd    ymm2, ymm0, ymm12
    LONG $0x64707dc5; WORD $0x6024; BYTE $0xf5                   // vpshufd    ymm12, yword [rsp + 96], 245
    LONG $0x505562c4; BYTE $0xc9                                 // {vex}    vpdpbusd    ymm9, ymm5, ymm1
    LONG $0x00fdc3c4; WORD $0xeecc                               // vpermq    ymm1, ymm12, 238
    LONG $0xef1141c4; BYTE $0xed                                 // vpxor    xmm13, xmm13, xmm13
    LONG $0xef1941c4; BYTE $0xe4                                 // vpxor    xmm12, xmm12, xmm12
    LONG $0x6c6ffdc5; WORD $0x4024                               // vmovdqa    ymm5, yword [rsp + 64]
    LONG $0x505562c4; BYTE $0xe9                                 // {vex}    vpdpbusd    ymm13, ymm5, ymm1
    LONG $0x6c6ffdc5; WORD $0x2024                               // vmovdqa    ymm5, yword [rsp + 32]
    LONG $0x505562c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm12, ymm5, ymm1
    QUAD $0x0002c024ac6ffdc5; BYTE $0x00                         // vmovdqa    ymm5, yword [rsp + 704]
    LONG $0xcd70fdc5; BYTE $0xf5                                 // vpshufd    ymm1, ymm5, 245
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x504d62c4; BYTE $0xe9                                 // {vex}    vpdpbusd    ymm13, ymm6, ymm1
    LONG $0x506562c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm12, ymm3, ymm1
    QUAD $0x0002e0249c6ffdc5; BYTE $0x00                         // vmovdqa    ymm3, yword [rsp + 736]
    LONG $0xcb70fdc5; BYTE $0xf5                                 // vpshufd    ymm1, ymm3, 245
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x500d62c4; BYTE $0xe9                                 // {vex}    vpdpbusd    ymm13, ymm14, ymm1
    LONG $0x505d62c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm12, ymm4, ymm1
    QUAD $0x0002a024a46ffdc5; BYTE $0x00                         // vmovdqa    ymm4, yword [rsp + 672]
    LONG $0xcc70fdc5; BYTE $0xf5                                 // vpshufd    ymm1, ymm4, 245
    LONG $0x00fde3c4; WORD $0xeec9                               // vpermq    ymm1, ymm1, 238
    LONG $0x504562c4; BYTE $0xe9                                 // {vex}    vpdpbusd    ymm13, ymm7, ymm1
    LONG $0x507d62c4; BYTE $0xe1                                 // {vex}    vpdpbusd    ymm12, ymm0, ymm1
    LONG $0xc9eff1c5                                             // vpxor    xmm1, xmm1, xmm1
    LONG $0x787dc2c4; WORD $0x2c47                               // vpbroadcastb    ymm0, byte [r15 + 44]
    LONG $0x507de2c4; BYTE $0xcc                                 // {vex}    vpdpbusd    ymm1, ymm0, ymm4
    LONG $0xfe0541c4; BYTE $0xc0                                 // vpaddd    ymm8, ymm15, ymm8
    LONG $0x507de2c4; BYTE $0xcb                                 // {vex}    vpdpbusd    ymm1, ymm0, ymm3
    LONG $0x507de2c4; BYTE $0xcd                                 // {vex}    vpdpbusd    ymm1, ymm0, ymm5
    LONG $0x507de2c4; WORD $0x244c; BYTE $0x60                   // {vex}    vpdpbusd    ymm1, ymm0, yword [rsp + 96]
    LONG $0xd2feadc5                                             // vpaddd    ymm2, ymm10, ymm2
    LONG $0x0275e2c4; BYTE $0xc9                                 // vphaddd    ymm1, ymm1, ymm1
    LONG $0xfe15c1c4; BYTE $0xc3                                 // vpaddd    ymm0, ymm13, ymm11
    LONG $0xea6cbdc5                                             // vpunpcklqdq    ymm5, ymm8, ymm2
    LONG $0xc479c1c4; WORD $0x0032                               // vpinsrw    xmm6, xmm0, word [r10], 0
    LONG $0xfa6dbdc5                                             // vpunpckhqdq    ymm7, ymm8, ymm2
    LONG $0xf172edc5; BYTE $0x03                                 // vpslld    ymm2, ymm1, 3
    LONG $0x1379e2c4; BYTE $0xce                                 // vcvtph2ps    xmm1, xmm6
    LONG $0x587de2c4; BYTE $0xf2                                 // vpbroadcastd    ymm6, xmm2
    LONG $0xeefad5c5                                             // vpsubd    ymm5, ymm5, ymm6
    LONG $0x187de2c4; BYTE $0xc9                                 // vbroadcastss    ymm1, xmm1
    QUAD $0x0000c0249c28fcc5; BYTE $0x00                         // vmovaps    ymm3, yword [rsp + 192]
    LONG $0xcb59f4c5                                             // vmulps    ymm1, ymm1, ymm3
    LONG $0xed5bfcc5                                             // vcvtdq2ps    ymm5, ymm5
    QUAD $0x03000caca875a2c4; WORD $0x0000                       // vfmadd213ps    ymm5, ymm1, yword [rsp + r9 + 768]
    QUAD $0x03000cac297ca1c4; WORD $0x0000                       // vmovaps    yword [rsp + r9 + 768], ymm5
    LONG $0xca70f9c5; BYTE $0x55                                 // vpshufd    xmm1, xmm2, 85
    LONG $0x587de2c4; BYTE $0xc9                                 // vpbroadcastd    ymm1, xmm1
    LONG $0xc9fac5c5                                             // vpsubd    ymm1, ymm7, ymm1
    LONG $0xc479c1c4; WORD $0x026a; BYTE $0x00                   // vpinsrw    xmm5, xmm0, word [r10 + 2], 0
    LONG $0x1379e2c4; BYTE $0xed                                 // vcvtph2ps    xmm5, xmm5
    LONG $0x187de2c4; BYTE $0xed                                 // vbroadcastss    ymm5, xmm5
    LONG $0xeb59d4c5                                             // vmulps    ymm5, ymm5, ymm3
    LONG $0xc95bfcc5                                             // vcvtdq2ps    ymm1, ymm1
    QUAD $0x03200c8ca855a2c4; WORD $0x0000                       // vfmadd213ps    ymm1, ymm5, yword [rsp + r9 + 800]
    LONG $0xfe1dc1c4; BYTE $0xe9                                 // vpaddd    ymm5, ymm12, ymm9
    QUAD $0x03200c8c297ca1c4; WORD $0x0000                       // vmovaps    yword [rsp + r9 + 800], ymm1
    LONG $0xc479c1c4; WORD $0x044a; BYTE $0x00                   // vpinsrw    xmm1, xmm0, word [r10 + 4], 0
    LONG $0xf56cfdc5                                             // vpunpcklqdq    ymm6, ymm0, ymm5
    LONG $0x397de3c4; WORD $0x01d7                               // vextracti128    xmm7, ymm2, 1
    LONG $0x1379e2c4; BYTE $0xc9                                 // vcvtph2ps    xmm1, xmm1
    LONG $0x587de2c4; BYTE $0xff                                 // vpbroadcastd    ymm7, xmm7
    LONG $0xf7facdc5                                             // vpsubd    ymm6, ymm6, ymm7
    LONG $0x187de2c4; BYTE $0xc9                                 // vbroadcastss    ymm1, xmm1
    LONG $0xf65bfcc5                                             // vcvtdq2ps    ymm6, ymm6
    LONG $0xcb59f4c5                                             // vmulps    ymm1, ymm1, ymm3
    QUAD $0x03400cb4a875a2c4; WORD $0x0000                       // vfmadd213ps    ymm6, ymm1, yword [rsp + r9 + 832]
    QUAD $0x03400cb4297ca1c4; WORD $0x0000                       // vmovaps    yword [rsp + r9 + 832], ymm6
    LONG $0xc56dfdc5                                             // vpunpckhqdq    ymm0, ymm0, ymm5
    LONG $0xca70fdc5; BYTE $0x55                                 // vpshufd    ymm1, ymm2, 85
    LONG $0xc479c1c4; WORD $0x0652; BYTE $0x00                   // vpinsrw    xmm2, xmm0, word [r10 + 6], 0
    LONG $0x00fde3c4; WORD $0xaac9                               // vpermq    ymm1, ymm1, 170
    LONG $0xc1fafdc5                                             // vpsubd    ymm0, ymm0, ymm1
    LONG $0x1379e2c4; BYTE $0xca                                 // vcvtph2ps    xmm1, xmm2
    LONG $0x187de2c4; BYTE $0xc9                                 // vbroadcastss    ymm1, xmm1
    LONG $0xcb59f4c5                                             // vmulps    ymm1, ymm1, ymm3
    LONG $0xc05bfcc5                                             // vcvtdq2ps    ymm0, ymm0
    QUAD $0x03600c84a875a2c4; WORD $0x0000                       // vfmadd213ps    ymm0, ymm1, yword [rsp + r9 + 864]
    QUAD $0x03600c84297ca1c4; WORD $0x0000                       // vmovaps    yword [rsp + r9 + 864], ymm0
    WORD $0x0149; BYTE $0xd2                                     // add    r10, rdx
    LONG $0x80e98349                                             // sub    r9, -128
    LONG $0x00f98149; WORD $0x0002; BYTE $0x00                   // cmp    r9, 512
	JNE LBB1_3
    WORD $0xff49; BYTE $0xc0                                     // inc    r8
    LONG $0x90c78148; WORD $0x0000; BYTE $0x00                   // add    rdi, 144
    LONG $0x88c68148; WORD $0x0000; BYTE $0x00                   // add    rsi, 136
    WORD $0x3949; BYTE $0xc0                                     // cmp    r8, rax
	JNE LBB1_2
LBB1_5:
	LEAQ 768(SP), SI
	MOVQ CX, DI
	MOVQ $16, R8
plan9_copy_8x16:
	VMOVUPS 0(SI), Y0
	VMOVUPS Y0, 0(DI)
	ADDQ $32, SI
	ADDQ $32, DI
	DECQ R8
	JNZ plan9_copy_8x16
	VZEROUPPER
    WORD $0x8948; BYTE $0xec                                     // mov    rsp, rbp
    BYTE $0x5d                                                   // pop    rbp
    SUBQ $72, SP
    RET
DATA ·kernelCompilerConsts<>+0(SB)/8, $0x0706050403020100
DATA ·kernelCompilerConsts<>+8(SB)/8, $0xfffefdfcfbfaf9f8
DATA ·kernelCompilerConsts<>+16(SB)/8, $0x0706050403020100
DATA ·kernelCompilerConsts<>+24(SB)/8, $0xfffefdfcfbfaf9f8
DATA ·kernelCompilerConsts<>+32(SB)/4, $0x0f0f0f0f
DATA ·kernelCompilerConsts<>+36(SB)/4, $0x88888888
DATA ·kernelCompilerConsts<>+40(SB)/4, $0x0f0f0f0f
DATA ·kernelCompilerConsts<>+44(SB)/4, $0x01010101
GLOBL ·kernelCompilerConsts<>(SB), RODATA|NOPTR, $48
